### ISSUE TITLE
Homematic: lots of warnings from NanoHTTPD on Windows 10

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1036]
In my Windows 10 test environment I get lots of warnings from NanoHTTPD:
```
2016-06-19 13:36:49.660 [INFO ] [smarthome.event.ItemStateEvent:43   ] - homematic_HM_CC_RT_DN_ccu_MEQ0798753_4_SET_TEMPERATURE updated to 4.50
Jun 19, 2016 1:36:49 PM fi.iki.elonen.NanoHTTPD$DefaultTempFileManager clear
WARNUNG: could not delete file 
java.lang.Exception: could not delete temporary file
	at fi.iki.elonen.NanoHTTPD$DefaultTempFile.delete(NanoHTTPD.java:403)
	at fi.iki.elonen.NanoHTTPD$DefaultTempFileManager.clear(NanoHTTPD.java:446)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:964)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:745)
```
On the Raspberry I do not get these messages. I suppose that it is a Windows-specific problem.

This bug has already been reported to NanoHTTPD and there seems to be a bypass in the [nanoHTTP repository](https://github.com/NanoHttpd/nanohttpd/issues/279).

**Comment by MHerbst** [comment]
Typo in title corrected
