### ISSUE TITLE
[YamahReceiver] RefreshCommand not handled

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1064]
The YamahaReceiver binding does not handle RefreshCommand. This leads to an exception:
```
2016-06-26 11:15:12.719 [ERROR] [.c.thing.link.ThingLinkManager:192  ] - Exception occured while informing handler:org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.OnOffTypejava.lang.ClassCastException: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.OnOffType
	at org.openhab.binding.yamahareceiver.handler.YamahaReceiverHandler.handleCommand(YamahaReceiverHandler.java:224)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:198)
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:190)
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.access$1(ThingLinkManager.java:186)
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:104)
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager$1.added(ThingLinkManager.java:1)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:142)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:161)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:165)
	at org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:102)
	at org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:1)
```

**Comment by kaikreuzer** [comment]
@davidgraeff, could you fix that?

**Comment by davidgraeff** [comment]
Sure
