### ISSUE TITLE
Provider marytts.voice.CmuSltHsmm.Config not a subtype

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2-addons#1076]
With the latest ESH snapshot, the following is thrown when marytts is configured:

```
2016-06-28 18:07:50.707 [ERROR] [rg.openhab.io.multimedia.tts.marytts] - [org.openhab.io.multimedia.tts.marytts(203)] The activate method has thrown an exception
java.util.ServiceConfigurationError: marytts.config.MaryConfig: Provider marytts.voice.CmuSltHsmm.Config not a subtype
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)[:1.8.0_66]
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)[:1.8.0_66]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)[:1.8.0_66]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)[:1.8.0_66]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)[:1.8.0_66]
        at marytts.server.MaryProperties.getProperty(MaryProperties.java:89)
        at marytts.util.MaryRuntimeUtils.<clinit>(MaryRuntimeUtils.java:296)
        at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:63)
        at org.openhab.io.multimedia.internal.tts.TTSServiceMaryTTS.activate(TTSServiceMaryTTS.java:43)
2016-06-28 18:07:50.796 [ERROR] [rg.openhab.io.multimedia.tts.marytts] - [org.openhab.io.multimedia.tts.marytts(203)] Failed creating the component instance; see log for reason
2016-06-28 18:07:50.797 [WARN ] [rg.openhab.io.multimedia.tts.marytts] - FrameworkEvent WARNING - org.openhab.io.multimedia.tts.marytts
org.osgi.framework.ServiceException: org.apache.felix.scr.impl.manager.SingleComponentManager.getService() returned a null service object
2016-06-28 18:07:50.873 [ERROR] [rg.openhab.io.multimedia.tts.marytts] - [org.openhab.io.multimedia.tts.marytts(203)] The activate method has thrown an exception
java.lang.NoClassDefFoundError: Could not initialize class marytts.util.MaryRuntimeUtils
```

**Comment by kaikreuzer** [comment]
Note that MaryTTS is maintained at https://github.com/openhab/openhab (although I will probably soon have it ported to OH2).

**Comment by cosinelabs** [comment]
What is the fix for this ?
