### ISSUE TITLE
Z-Wave: NPE on inclusion on SecurityCommandClass#438

### ISSUE THREAD

**Issue by sja** [openhab/openhab2-addons#1080]
While trying to include a Fibaro Universal Binary Sensor:

```
2016-06-30 20:21:06.813 [WARN ] [tocol.commandclass.ZWaveCommandClass] - NODE 21: Unsupported command class MULTI_INSTANCE_ASSOCIATION
2016-06-30 20:21:09.049 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:155a0a17a2b:node21' to inbox.
2016-06-30 20:21:09.072 [WARN ] [rialmessage.IdentifyNodeMessageClass] - Got IdentifyNodeMessage without request, ignoring. Last message was SendData.
2016-06-30 20:21:14.111 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 21: Timeout while sending message. Requeueing - 2 attempts left!
2016-06-30 20:21:14.117 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 21: Got an error while sending data. Resending message.
2016-06-30 20:21:19.251 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 21: Timeout while sending message. Requeueing - 1 attempts left!
2016-06-30 20:21:19.260 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 21: Got an error while sending data. Resending message.
2016-06-30 20:21:22.833 [ERROR] [age.AssignSucReturnRouteMessageClass] - NODE 21: AssignSucReturnRoute command failed.
2016-06-30 20:21:24.783 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 21: Sent Data was not placed on stack due to error 0.
2016-06-30 20:21:29.801 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 21: Timeout while sending message. Requeueing - 2 attempts left!
2016-06-30 20:21:29.805 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 21: Got an error while sending data. Resending message.
2016-06-30 20:22:04.252 [ERROR] [ve.internal.protocol.ZWaveController] - Exception during ZWave thread: Input 2. {}
java.lang.NullPointerException
	at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveSecurityCommandClass.sendNonceReport(ZWaveSecurityCommandClass.java:432)[205:org.openhab.binding.zwave:2.0.0.201606150102]
	at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveSecurityCommandClass.handleApplicationCommandRequest(ZWaveSecurityCommandClass.java:387)[205:org.openhab.binding.zwave:2.0.0.201606150102]
	at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveSecurityCommandClassWithInitialization.handleApplicationCommandRequest(ZWaveSecurityCommandClassWithInitialization.java:269)[205:org.openhab.binding.zwave:2.0.0.201606150102]
	at org.openhab.binding.zwave.internal.protocol.serialmessage.ApplicationCommandMessageClass.handleRequest(ApplicationCommandMessageClass.java:119)[205:org.openhab.binding.zwave:2.0.0.201606150102]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:241)[205:org.openhab.binding.zwave:2.0.0.201606150102]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:207)[205:org.openhab.binding.zwave:2.0.0.201606150102]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$7(ZWaveController.java:201)[205:org.openhab.binding.zwave:2.0.0.201606150102]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1278)[205:org.openhab.binding.zwave:2.0.0.201606150102]
2016-06-30 20:22:11.981 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE 21: Initialising Thing Node...
2016-06-30 20:23:36.349 [WARN ] [veClimateControlScheduleCommandClass] - NODE 20: Unsupported Command 8 for command class CLIMATE_CONTROL_SCHEDULE (0x46).
2016-06-30 20:23:36.354 [WARN ] [.commandclass.ZWaveClockCommandClass] - NODE 20: Unsupported Command 5 for command class CLOCK (0x81).
2016-06-30 20:23:36.359 [WARN ] [veClimateControlScheduleCommandClass] - NODE 20: Unsupported Command 4 for command class CLIMATE_CONTROL_SCHEDULE (0x46).
```

**Comment by cdjackson** [comment]
The security classes are not supported in OH2 yet. I would recommend disabling it (in network settings in the controller I believe) until this is ready. This will cause the device to work in non-secure mode.

**Comment by sja** [comment]
Wasn't aware of that. Thanks for fast response.
