### ISSUE TITLE
RFXCOM binding: NPE at initialization

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1128]
I have a bridge and 3 things.
A null pointer exception occured for each thing at startup with recent snapshots (is OK in beta 3)::
```
21:23:17.774 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured during notification of thing 'rfxcom:temperaturehumidity:rfx:Chambre' about bridge initialization at 'org.openhab.binding.rfxcom.handler.RFXComHandler@18658a1': null
java.lang.NullPointerException
        at org.openhab.binding.rfxcom.handler.RFXComHandler.initializeBridge(RFXComHandler.java:125)[199:org.openhab.binding.rfxcom:2.0.0.201607140102]
        at org.openhab.binding.rfxcom.handler.RFXComHandler.bridgeHandlerInitialized(RFXComHandler.java:114)[199:org.openhab.binding.rfxcom:2.0.0.201607140102]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$9.run(ThingManager.java:801)[102:org.eclipse.smarthome.core.thing:0.9.0.201607131940]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
        at java.lang.Thread.run(Thread.java:744)[:1.8.0]
21:23:17.777 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured during notification of thing 'rfxcom:temperaturehumidity:rfx:Veranda' about bridge initialization at 'org.openhab.binding.rfxcom.handler.RFXComHandler@1ac71a': null
java.lang.NullPointerException
        at org.openhab.binding.rfxcom.handler.RFXComHandler.initializeBridge(RFXComHandler.java:125)[199:org.openhab.binding.rfxcom:2.0.0.201607140102]
        at org.openhab.binding.rfxcom.handler.RFXComHandler.bridgeHandlerInitialized(RFXComHandler.java:114)[199:org.openhab.binding.rfxcom:2.0.0.201607140102]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$9.run(ThingManager.java:801)[102:org.eclipse.smarthome.core.thing:0.9.0.201607131940]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
        at java.lang.Thread.run(Thread.java:744)[:1.8.0]
21:23:17.776 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured during notification of thing 'rfxcom:temperaturehumidity:rfx:Bureau' about bridge initialization at 'org.openhab.binding.rfxcom.handler.RFXComHandler@1083d86': null
java.lang.NullPointerException
        at org.openhab.binding.rfxcom.handler.RFXComHandler.initializeBridge(RFXComHandler.java:125)[199:org.openhab.binding.rfxcom:2.0.0.201607140102]
        at org.openhab.binding.rfxcom.handler.RFXComHandler.bridgeHandlerInitialized(RFXComHandler.java:114)[199:org.openhab.binding.rfxcom:2.0.0.201607140102]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$9.run(ThingManager.java:801)[102:org.eclipse.smarthome.core.thing:0.9.0.201607131940]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
        at java.lang.Thread.run(Thread.java:744)[:1.8.0]
```

**Comment by lolodomo** [comment]
Fixed by PR #1129
