### ISSUE TITLE
PaperUI: Invalid operation on a fragment

### ISSUE THREAD

**Issue by sja** [openhab/openhab2-addons#1152]
I try to change my launcher to start PaperUI and it's OH2-Fragment from my workspace instead of the targetplatform.

But while startup, I get `Invalid operation on a fragment.`-Bundle Exception:

```
!SESSION 2016-07-24 16:35:54.046 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  -application org.eclipse.ui.ide.workbench
Command-line arguments:  -application org.eclipse.ui.ide.workbench -data /Volumes/ESH/eclipse-neon/ws/../runtime-org.openhab.runtime.product.product -dev file:/Volumes/ESH/eclipse-neon/ws/.metadata/.plugins/org.eclipse.pde.core/openHAB_Runtime/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -console

!ENTRY org.eclipse.osgi 4 0 2016-07-24 16:35:54.770
!MESSAGE Error starting bundle: initial@reference:file:plugins/org.openhab.ui.paperui_2.0.0.201607210102.jar
!STACK 0
org.osgi.framework.BundleException: Invalid operation on a fragment.
	at org.eclipse.osgi.container.Module.checkFragment(Module.java:510)
	at org.eclipse.osgi.container.Module.start(Module.java:397)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startBundle(EclipseStarter.java:1047)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startBundles(EclipseStarter.java:1040)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.loadBasicBundles(EclipseStarter.java:584)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:311)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
2016-07-24 16:35:55.564 [DEBUG] [.i.PersistenceRuntimeActivator:21   ] - Registered 'persistence' configuration parser
2016-07-24 16:35:56.379 [DEBUG] [s.m.r.r.i.RuleRuntimeActivator:27   ] - Registered 'rule' configuration parser
...
```

If I just not check the OH2-Fragment, PaperUI only, it seems to be started but is not accessible. The OSGi-Console marks it as _ACTIVE_, but neither a Tile nor `/ui/index.html` is accessible (404). The log:

```
2016-07-24 16:39:31.365 [INFO ] [rg.eclipse.jetty.server.Server:379  ] - Started @4687ms
2016-07-24 16:39:31.367 [INFO ] [.DefaultJettyAtJettyHomeHelper:180  ] - Default jetty server configured
2016-07-24 16:39:31.447 [DEBUG] [ui.internal.chart.ChartServlet:119  ] - Starting up chart servlet at /chart
2016-07-24 16:39:31.449 [INFO ] [s.ui.paper.internal.PaperUIApp:31   ] - Started Paper UI at /ui
2016-07-24 16:39:31.452 [INFO ] [.u.d.internal.DashboardService:55   ] - Started dashboard at /start
2016-07-24 16:39:31.507 [DEBUG] [s.c.d.AbstractDiscoveryService:349  ] - Background discovery for discovery service 'org.eclipse.smarthome.config.discovery.internal.UpnpDiscoveryService' enabled.
```

**Comment by kaikreuzer** [comment]
Not that neither the Paper UI nor its fragment is maintained in this repo.
It is better to discuss issues about your IDE setup in [our community](https://community.openhab.org/).
Tip: For the Paper UI to work from the workspace, you need to have executed the Maven build on it first.

**Comment by sja** [comment]
Ok, sorry, I thought the fragment is hosted here. 

Von meinem Toaster gesendet
