### ISSUE TITLE
OpenHab 2 startup Could not resolved module ui.paper

### ISSUE THREAD

**Issue by bsutton** [openhab/openhab2-addons#1181]
Could not resolve module org.eclipse.smarthome.ui.paper.

See the following error. The system appears to start just fine. Error makes me wonder if there are two separate singletons both trying to load the same module.
`
cat  userdata/logs/openhab.log  
2016-08-07 18:05:04.944 [ERROR] [.glassfish.hk2.osgi-resource-locator] - FrameworkEvent ERROR - org.glassfish.hk2.osgi-resource-locator
org.osgi.framework.BundleException: Exception in org.apache.karaf.features.internal.service.FeaturesServiceImpl$3.end()
    at org.eclipse.osgi.internal.framework.OSGiFrameworkHooks$CoreResolverHookFactory.handleHookException(OSGiFrameworkHooks.java:164)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.framework.OSGiFrameworkHooks$CoreResolverHookFactory$CoreResolverHook.end(OSGiFrameworkHooks.java:340)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.container.ModuleResolver$ResolveProcess.resolve(ModuleResolver.java:901)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.container.ModuleResolver.resolveDelta(ModuleResolver.java:111)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:479)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:437)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:427)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.container.Module.start(Module.java:416)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1498)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
2016-08-07 18:06:09.369 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2016-08-07 18:06:09.536 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2016-08-07 18:06:09.574 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
2016-08-07 18:06:09.574 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2016-08-07 18:06:09.578 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-package-standard': Error restarting bundles
2016-08-07 18:06:09.608 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-package-standard': Error restarting bundles
2016-08-07 18:09:28.215 [INFO ] [.dashboard.internal.DashboardService] - Stopped dashboard
2016-08-07 18:09:28.232 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Stopped Paper UI
2016-08-07 18:09:28.239 [INFO ] [assic.internal.servlet.WebAppServlet] - Stopped Classic UI
2016-08-07 18:09:37.302 [INFO ] [basic.internal.servlet.WebAppServlet] - Stopped Basic UI
2016-08-07 18:09:38.988 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2016-08-07 18:09:39.037 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2016-08-07 18:09:39.101 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2016-08-07 18:09:39.364 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
2016-08-07 18:09:39.691 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Stopped Paper UI
2016-08-07 18:09:39.703 [ERROR] [org.eclipse.smarthome.ui.paper      ] - FrameworkEvent ERROR - org.eclipse.smarthome.ui.paper
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.smarthome.ui.paper [180]
  Another singleton bundle selected: osgi.identity; osgi.identity="org.eclipse.smarthome.ui.paper"; type="osgi.bundle"; version:Version="0.9.0.201608031951"; singleton:="true"

```
at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
at org.eclipse.osgi.container.ModuleContainer.update(ModuleContainer.java:354)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
at org.eclipse.osgi.storage.Storage.update(Storage.java:713)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
at org.eclipse.osgi.internal.framework.EquinoxBundle.update(EquinoxBundle.java:439)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.updateBundle(FeaturesServiceImpl.java:1185)[9:org.apache.karaf.features.core:4.0.4]
at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:688)[9:org.apache.karaf.features.core:4.0.4]
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1089)[9:org.apache.karaf.features.core:4.0.4]
at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:985)[9:org.apache.karaf.features.core:4.0.4]
at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_66]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_66]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_66]
at java.lang.Thread.run(Thread.java:745)[:1.8.0_66]
```

2016-08-07 18:09:39.707 [INFO ] [.dashboard.internal.DashboardService] - Stopped dashboard
2016-08-07 18:09:39.750 [INFO ] [assic.internal.servlet.WebAppServlet] - Stopped Classic UI
2016-08-07 18:09:39.796 [INFO ] [basic.internal.servlet.WebAppServlet] - Stopped Basic UI
2016-08-07 18:09:46.549 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2016-08-07 18:09:46.736 [INFO ] [basic.internal.servlet.WebAppServlet] - Stopped Basic UI
2016-08-07 18:09:46.792 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2016-08-07 18:09:47.835 [INFO ] [basic.internal.servlet.WebAppServlet] - Stopped Basic UI
2016-08-07 18:09:47.980 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2016-08-07 18:09:47.996 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2016-08-07 18:09:48.057 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2016-08-07 18:09:48.098 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
2016-08-07 18:09:48.111 [ERROR] [st.core.extensions.ExtensionResource] - Exception while installing extension: org.apache.karaf.features.internal.util.MultiException: Error restarting bundles
2016-08-07 18:09:48.111 [ERROR] [st.core.extensions.ExtensionResource] - Exception while installing extension: org.apache.karaf.features.internal.util.MultiException: Error restarting bundles
2016-08-07 18:09:48.159 [INFO ] [.dashboard.internal.DashboardService] - Stopped dashboard
2016-08-07 18:09:48.174 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2016-08-07 18:09:48.377 [INFO ] [assic.internal.servlet.WebAppServlet] - Stopped Classic UI
2016-08-07 18:09:48.424 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2016-08-07 18:09:48.884 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Stopped Paper UI
2016-08-07 18:09:48.908 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
2016-08-07 18:09:48.914 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Stopped Paper UI
2016-08-07 18:09:48.918 [INFO ] [.dashboard.internal.DashboardService] - Stopped dashboard
2016-08-07 18:09:48.930 [INFO ] [assic.internal.servlet.WebAppServlet] - Stopped Classic UI
2016-08-07 18:09:56.958 [INFO ] [basic.internal.servlet.WebAppServlet] - Stopped Basic UI
2016-08-07 18:09:57.153 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2016-08-07 18:09:57.181 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2016-08-07 18:09:57.220 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
2016-08-07 18:09:57.246 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2016-08-07 18:09:57.254 [ERROR] [st.core.extensions.ExtensionResource] - Exception while installing extension: org.apache.karaf.features.internal.util.MultiException: Error restarting bundles
2016-08-07 18:11:17.320 [ERROR] [st.core.extensions.ExtensionResource] - Exception while installing extension: org.apache.karaf.features.internal.util.MultiException: Error restarting bundles
2016-08-07 18:11:22.161 [ERROR] [st.core.extensions.ExtensionResource] - Exception while installing extension: org.apache.karaf.features.internal.util.MultiException: Error restarting bundles
2016-08-07 18:11:46.457 [WARN ] [sql.internal.MysqlPersistenceService] - The SQL database URL is missing - please configure the sql:url parameter in openhab.cfg
2016-08-07 18:16:31.492 [ERROR] [st.core.extensions.ExtensionResource] - Exception while installing extension: org.apache.karaf.features.internal.util.MultiException: Error restarting bundles

`
##

**Comment by hmerk** [comment]
@martinvw I guess this issue can be closed, as it is older than 1 year an we stepped forward....

**Comment by martinvw** [comment]
> @martinvw I guess this issue can be closed, as it is older than 1 year an we stepped forward....

@hmerk Thanks for checking out some of those old issues!
