### ISSUE TITLE
Freebox binding: NPE in the jobs run by the phone thing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1210]
I discovered in my logs the jobs (maybe one particular job) run by the phone thing are sometimes triggering a NPE..
The exception is catched so the job scheduling is not suspended and the problem has no real consequence in practice.
Unfortunately due to the exception catching, I have no hint of what could lead to this NPE.

**Comment by lolodomo** [comment]
I finally catched the NPE:
```
2016-09-07 12:22:33.881 [ERROR] [.freebox.handler.FreeboxThingHandler] - Phone calls job - Exception: java.lang.NullPointerException
2016-09-07 12:22:33.885 [ERROR] [.freebox.handler.FreeboxThingHandler] - java.lang.RuntimeException: java.lang.NullPointerException
        at org.matmaul.freeboxos.login.LoginManager.hmacSha1(LoginManager.java:122)
        at org.matmaul.freeboxos.login.LoginManager.openSession(LoginManager.java:96)
        at org.matmaul.freeboxos.internal.RestManager.execute(RestManager.java:168)
        at org.matmaul.freeboxos.internal.RestManager.get(RestManager.java:112)
        at org.matmaul.freeboxos.internal.RestManager.get(RestManager.java:107)
        at org.matmaul.freeboxos.call.CallManager.getCallEntries(CallManager.java:17)
        at org.openhab.binding.freebox.handler.FreeboxThingHandler.fetchNewCalls(FreeboxThingHandler.java:229)
        at org.openhab.binding.freebox.handler.FreeboxThingHandler.access$4(FreeboxThingHandler.java:228)
        at org.openhab.binding.freebox.handler.FreeboxThingHandler$2.run(FreeboxThingHandler.java:178)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
        at org.matmaul.freeboxos.login.LoginManager.hmacSha1(LoginManager.java:114)
        ... 15 more
```
The NPE is not in the binding itself but in the used library, probably when trying to opening a new session.
It occured around 6 times per day. Always the same job.
Will try to find a solution.
