### ISSUE TITLE
Hue Emulation + Harmony Elite = exception with ZWave Switch

### ISSUE THREAD

**Issue by ertanden** [openhab/openhab2-addons#1261]
I'm trying to use Hue Emulation paired with my Logitech Harmony Elite.

I have a Z-Wave switch and the item is defined as:

```
Switch ZW_TVPriz "TV Priz" <poweroutlet> (Group_ZWave) ["Switchable"] {channel="zwave:device:0b96edd1:node46:switch_binary"}
```

Looks like switching "OFF" works, however, when I try to switch "ON" the device I get the following exception. 

```java
20:39:48.166 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /api/bcb4cd60-0032-478c-ab44-141182c2fdc2/lights/ZW_TVPriz/state
java.lang.IllegalArgumentException: The argument 'command' must not be null or empty.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)[14:com.google.guava:18.0.0]
	at org.eclipse.smarthome.core.items.events.ItemEventFactory.assertValidArguments(ItemEventFactory.java:344)[97:org.eclipse.smarthome.core:0.9.0.201609151119]
	at org.eclipse.smarthome.core.items.events.ItemEventFactory.createCommandEvent(ItemEventFactory.java:186)[97:org.eclipse.smarthome.core:0.9.0.201609151119]
	at org.eclipse.smarthome.core.items.events.ItemEventFactory.createCommandEvent(ItemEventFactory.java:204)[97:org.eclipse.smarthome.core:0.9.0.201609151119]
	at org.openhab.io.hueemulation.internal.HueEmulationServlet.apiState(HueEmulationServlet.java:269)[218:org.openhab.io.hueemulation:2.0.0.201609212035]
	at org.openhab.io.hueemulation.internal.HueEmulationServlet.service(HueEmulationServlet.java:221)[218:org.openhab.io.hueemulation:2.0.0.201609212035]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)[21:javax.servlet-api:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[80:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[80:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[166:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[78:org.eclipse.jetty.security:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[166:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[80:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[166:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.Server.handle(Server.java:499)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[79:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[71:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[82:org.eclipse.jetty.util:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[82:org.eclipse.jetty.util:9.2.14.v20151106]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
`

**Comment by digitaldan** [comment]
Can you enable debug logging?  it should print out what it thinks the state should be, my guess is that for some reason it is sending a value that is between 0-255, thinking that the bulb is dimmable, where a Switch only accepts on and off (0 or 255 from the hue bridge).  I should probably do a check on the item type and correct for this however.

**Comment by digitaldan** [comment]
I have a fix here https://github.com/digitaldan/openhab2-addons/commit/80365f530caa962f90397e278ede02dfec924129 , I just need to test thisover the weekend when I'm back in town
