### ISSUE TITLE
[RFXCOM] Unclear / stripped error messages

### ISSUE THREAD

**Issue by gersilex** [openhab/openhab2-addons#1265]
I am debugging a problem where I can't send LIGHTING4 Commands. So I do this on the Karaf shell:

```
openhab> log:set DEBUG org.openhab.binding.rfxcom
openhab> log:tail
```

I get the DEBUG messages from the binding just fine:

```
19:36:47.401 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
19:36:47.765 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 085001B20C0100B949, Packet type = TEMPERATURE, Seq number = 178, Sub type = TEMP1, Device Id = 3073, Temperature = 18.5, Signal level = 4, Battery level = 9
19:36:47.768 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:rfxcom message: Raw data = 085001B20C0100B949, Packet type = TEMPERATURE, Seq number = 178, Sub type = TEMP1, Device Id = 3073, Temperature = 18.5, Signal level = 4, Battery level = 9
```

Unfortunately, as soon as something goes wrong, an error message is fired to the [ERROR] stream:

```
19:40:01.076 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'rfxcom_lighting4_rfxcom_5571845_command' received command OFF
19:40:01.081 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received channel: rfxcom:lighting4:rfxcom:5571845:command, command: OFF
19:40:01.082 [ERROR] [binding.rfxcom.handler.RFXComHandler] - Transmitting error
19:40:01.088 [INFO ] [marthome.event.ItemStateChangedEvent] - rfxcom_lighting4_rfxcom_5571845_command changed from ON to OFF
```

This is all of the output. Not even the Command that failed sending is logged.

Is there something wrong? I would expect something like this (taken from the Pioneer AVR Binding):

```
19:28:26.726 [WARN ] [nternal.protocol.StreamAvrConnection] - The AVR @192.168.1.139:8102 is disconnected.
java.net.SocketException: Keine Route zum Zielrechner
        at java.net.SocketInputStream.socketRead0(Native Method)[:1.8.0]
        at java.net.SocketInputStream.read(SocketInputStream.java:150)[:1.8.0]
[...]
```

Thank you for any thoughts, ideas or fixes!
##

**Comment by martinvw** [comment]
@gersilex can you attempt with a more recent snapshot whether this behavior has improved?

Looking at the current code it should!

**Comment by gersilex** [comment]
Thank you. I will try do get to it this week.

**Comment by paulianttila** [comment]
Lightning4 message support is broken on OH2. There is a fundamental problem with pulse length which should be somehow solved. 

See discussion:
https://community.openhab.org/t/rfxcom-cheap-pir-sensor-binding-in-openhab2/13607/24
