### ISSUE TITLE
Hue emulation: Can't set light to off

### ISSUE THREAD

**Issue by ertanden** [openhab/openhab2-addons#1285]
I can't set my Hue lights off with my Harmony Elite. Using latest snapshot openhab 2.0 distribution.

Light defined as an item:

```
Color Light_Salon "Salon Isigi" (Group_Lights) [Lighting] {channel="hue:0210:0017882a70b4:3:color"}
```

The error I get is as following with debug logs enabled. Looks like brightness is -1, but it shouldn't cause an error, as on = false.

```java
19:51:35.159 [DEBUG] [ulation.internal.HueEmulationServlet] - 192.168.11.52: PUT /api/6de763b5-b2c9-43ef-80be-6caa9bdb4846/lights/Light_Salon/state
19:51:35.161 [DEBUG] [ulation.internal.HueEmulationServlet] - State [on: false bri: -1 hue: 0 sat: 0 xy: {0.0 0.0 } ct: 500 alert: none effect: none colormode: ct reachable: true
19:51:35.162 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /api/6de763b5-b2c9-43ef-80be-6caa9bdb4846/lights/Light_Salon/state
java.lang.IllegalArgumentException: Value must be between 0 and 100
	at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:46)[99:org.eclipse.smarthome.core:0.9.0.201609302115]
	at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:41)[99:org.eclipse.smarthome.core:0.9.0.201609302115]
	at org.eclipse.smarthome.core.library.types.HSBType.getBrightness(HSBType.java:135)[99:org.eclipse.smarthome.core:0.9.0.201609302115]
	at org.eclipse.smarthome.core.library.types.HSBType.toString(HSBType.java:165)[99:org.eclipse.smarthome.core:0.9.0.201609302115]
	at org.eclipse.smarthome.core.items.events.ItemEventFactory.createCommandEvent(ItemEventFactory.java:188)[99:org.eclipse.smarthome.core:0.9.0.201609302115]
	at org.eclipse.smarthome.core.items.events.ItemEventFactory.createCommandEvent(ItemEventFactory.java:204)[99:org.eclipse.smarthome.core:0.9.0.201609302115]
	at org.openhab.io.hueemulation.internal.HueEmulationServlet.apiState(HueEmulationServlet.java:297)[225:org.openhab.io.hueemulation:2.0.0.201610021150]
	at org.openhab.io.hueemulation.internal.HueEmulationServlet.service(HueEmulationServlet.java:235)[225:org.openhab.io.hueemulation:2.0.0.201610021150]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)[21:javax.servlet-api:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[82:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[82:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[171:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[80:org.eclipse.jetty.security:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[171:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[82:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[171:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.Server.handle(Server.java:499)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[81:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[73:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[84:org.eclipse.jetty.util:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[84:org.eclipse.jetty.util:9.2.14.v20151106]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
```

**Comment by ertanden** [comment]
Also, I can't set the brightness.

From the error, it looks like the validation for "bri" is checked between 0 and 100, however actually that value is something between 0 and 254.

http://www.developers.meethue.com/documentation/core-concepts

**Comment by digitaldan** [comment]
Yes, I did not convert to our HSBType correctly (it was doing this for non HSB types), I'll push something soon.

**Comment by ertanden** [comment]
I guess this fix is not merged yet?

**Comment by digitaldan** [comment]
I was just testing new changes this am, I think my latest PR should do the trick.
