### ISSUE TITLE
mios Binding not working

### ISSUE THREAD

**Issue by jpete7683** [openhab/openhab2-addons#1304]
Updated to the new transformation files and now receiving the following stack trace..

2016-10-07 23:49:00.927 [ERROR] [ab.binding.mios.internal.MiosBinding] - Error handling command
org.openhab.core.transform.TransformationException: An error occured while opening file.
	at org.openhab.core.transform.TransformationHelper$TransformationServiceDelegate.transform(TransformationHelper.java:63)[196:org.openhab.core.compat1x:2.0.0.201610072017]
	at org.openhab.binding.mios.internal.config.DeviceBindingConfig.transformCommand(DeviceBindingConfig.java:442)[195:org.openhab.binding.mios:1.9.0.201610070111]
	at org.openhab.binding.mios.internal.MiosUnitConnector.callDevice(MiosUnitConnector.java:192)[195:org.openhab.binding.mios:1.9.0.201610070111]
	at org.openhab.binding.mios.internal.MiosUnitConnector.invokeCommand(MiosUnitConnector.java:378)[195:org.openhab.binding.mios:1.9.0.201610070111]
	at org.openhab.binding.mios.internal.MiosBinding.internalReceiveCommand(MiosBinding.java:271)[195:org.openhab.binding.mios:1.9.0.201610070111]
	at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:97)[196:org.openhab.core.compat1x:2.0.0.201610072017]
	at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:42)[196:org.openhab.core.compat1x:2.0.0.201610072017]
	at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415)[3:org.apache.karaf.services.eventadmin:4.0.4]
	at org.apache.felix.eventadmin.impl.tasks.HandlerTask.run(HandlerTask.java:90)[3:org.apache.karaf.services.eventadmin:4.0.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]

**Comment by jpete7683** [comment]
This is only for thermostat.  All switches work fine and dimmers, but nothing with thermostat is working.

**Comment by kaikreuzer** [comment]
Afaik, mios is a 1.x binding and thus its sourcecode is not here. Please enter the issue at https://github.com/openhab/openhab/issues instead.
