### ISSUE TITLE
Running openHAB-runtime configuration fails

### ISSUE THREAD

**Issue by Lukas84** [openhab/openhab2-addons#1308]
Hi,
I made a fresh Installation of the openHAB 2 development by using the Eclipse installer. When I want to run the openHAB_runtime I always get the following eror message:

An error has occurred.  See the log file
C:\Users\Lukas\openhab2-master\ws.metadata.plugins\org.eclipse.pde.core\openHAB_Runtime\1476026965966.log

The log file Content is:

```
!SESSION Sun Oct 09 17:29:25 CEST 2016 -----------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2016-10-09 17:29:26.025
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:670)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

How to solve the issue?
##

**Comment by kaikreuzer** [comment]
Please ask for support in our community at https://community.openhab.org/
