### ISSUE TITLE
MiLight Exception while toggling the state to off

### ISSUE THREAD

**Issue by patrickse** [openhab/openhab2-addons#1322]
Hi,

I´ve currently facing some problems with my HomeKit and Milight integration.

My item is defined as the following.

```
Dimmer BDROOM_LED "Bett Beleuchtung" <light> (bedRoom) [ "Lighting" ] { channel="milight:rgbLed:ACCF23284AA0:7:ledbrightness" }
```

On my iPhone the light appears and can be used. Up to now I was able to push on the bulb on my phone to activate or deactivate the light. Touch-hold enabled the dimmer. 

After my last upgrade of openhab I can´t turn the light off with simply touching the bulp on my phone.

Here´s the error log.

```
16:25:34.136 [INFO ] [marthome.event.ItemStateChangedEvent] - BDROOM_LED changed from 100 to 0
16:25:34.139 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling handler: java.lang.ClassCastException: org.eclipse.smarthome.core.library.types.OnOffType cannot be cast to org.eclipse.smarthome.core.library.types.DecimalType
java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.eclipse.smarthome.core.library.types.OnOffType cannot be cast to org.eclipse.smarthome.core.library.types.DecimalType
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_101]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)[96:org.eclipse.smarthome.core:0.9.0.201610101820]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)[96:org.eclipse.smarthome.core:0.9.0.201610101820]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)[96:org.eclipse.smarthome.core:0.9.0.201610101820]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:411)[102:org.eclipse.smarthome.core.thing:0.9.0.201610101820]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)[96:org.eclipse.smarthome.core:0.9.0.201610101820]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201610101820]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201610101820]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[96:org.eclipse.smarthome.core:0.9.0.201610101820]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
Caused by: java.lang.ClassCastException: org.eclipse.smarthome.core.library.types.OnOffType cannot be cast to org.eclipse.smarthome.core.library.types.DecimalType
	at org.openhab.binding.milight.handler.MilightLedHandler.handleCommand(MilightLedHandler.java:75)[168:org.openhab.binding.milight:2.0.0.201610121647]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:414)[102:org.eclipse.smarthome.core.thing:0.9.0.201610101820]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:1)[102:org.eclipse.smarthome.core.thing:0.9.0.201610101820]
	... 5 more
```

Up to now I was not able to find any related changes in the homekit addon, so I guess it is related to openhab/esh itself.

**Comment by kaikreuzer** [comment]
This exception comes from the Milight binding, I doubt that it has anything to do with the HomeKit bundle. So better update your title to get the correct people's attention!

**Comment by patrickse** [comment]
@kaikreuzer you´re right. Thanks...

**Comment by patrickse** [comment]
I've checked the stacktrace and it looks like only the color itemtype supports on/off commands. So I've changed the channel to ledcolor and Color item and the error is gone.

**Comment by kaikreuzer** [comment]
No, this is a false assumption. Any Dimmer item can receive ON/OFF commands and every binding has to handle that case correctly.

**Comment by patrickse** [comment]
Ok. If that´s the case, the handler needs to implement the OnOff command, right?

[MlightLedHandler.java L74-L77](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/handler/MilightLedHandler.java#L74-L77)

What I can see, the Brightness Control just accepts DecimalType at the moment.

**Comment by kaikreuzer** [comment]
Yes, it needs to handle OnOffType and PercentType (DecimalType is actually wrong).

Likewise, the Color channel is missing the handling of PercentTypes (which should dim the color light).

**Comment by patrickse** [comment]
Hi Kai.. I´ve tried to implement the missing Command Handling. It´s working quite decent in my environment. Could you please review..
