### ISSUE TITLE
Systeminfo 2.0 binding - OpenHAB 2 on Windows 7

### ISSUE THREAD

**Issue by davorf** [openhab/openhab2-addons#1396]
After discovering Local machine in Systeminfo 2.0 binding via Paper UI and adding it as a thing, the thing displays an error message: 

> OFFLINE - HANDLER_INITIALIZING_ERROR Thing can not be initialized! 

I've enabled DEBUG level of logging and this is a part of the log with Systeminfo binding information and error message: 

```
2016-11-08 10:52:42.630 [DEBUG] [discovery.SysteminfoDiscoveryService] - Starting system information discovery !
2016-11-08 10:52:42.827 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'systeminfo:computer:MEDIABEAST' to inbox.
2016-11-08 10:52:51.994 [DEBUG] [org.openhab.binding.systeminfo      ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandler}={thing.type=systeminfo:computer, thing.id=systeminfo:computer:MEDIABEAST, service.id=414, service.bundleid=209, service.scope=singleton} - org.openhab.binding.systeminfo
2016-11-08 10:52:51.998 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Start initializing!
2016-11-08 10:52:51.998 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Thing configuration updated!
2016-11-08 10:52:51.999 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Channel configuration updated!
2016-11-08 10:52:52.771 [ERROR] [systeminfo.handler.SysteminfoHandler] - Can not instantate Systeminfo object!
java.lang.NullPointerException
	at com.sun.jna.platform.win32.Variant$VARIANT.stringValue(Variant.java:539)[209:org.openhab.binding.systeminfo:2.0.0.201610221219]
	at oshi.util.platform.windows.WmiUtil.enumerateProperties(WmiUtil.java:459)[209:org.openhab.binding.systeminfo:2.0.0.201610221219]
	at oshi.util.platform.windows.WmiUtil.queryWMI(WmiUtil.java:324)[209:org.openhab.binding.systeminfo:2.0.0.201610221219]
	at oshi.util.platform.windows.WmiUtil.selectObjectsFrom(WmiUtil.java:242)[209:org.openhab.binding.systeminfo:2.0.0.201610221219]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.getProcesses(WindowsCentralProcessor.java:397)[209:org.openhab.binding.systeminfo:2.0.0.201610221219]
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.<init>(OshiSysteminfo.java:72)[209:org.openhab.binding.systeminfo:2.0.0.201610221219]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.instantiateSysteminfoLibrary(SysteminfoHandler.java:121)[209:org.openhab.binding.systeminfo:2.0.0.201610221219]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.initialize(SysteminfoHandler.java:107)[209:org.openhab.binding.systeminfo:2.0.0.201610221219]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:758)[106:org.eclipse.smarthome.core.thing:0.9.0.201610220816]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.201610220816]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[99:org.eclipse.smarthome.core:0.9.0.201610220816]
	at java.util.concurrent.FutureTask.run(Unknown Source)[:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)[:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)[:1.8.0_111]
	at java.lang.Thread.run(Unknown Source)[:1.8.0_111]
```

**Comment by svilenvul** [comment]
@davorf 
Thanks for reporting this issue. I am the initial contributor of the Systeminfo 2.0 binding. 

From the log I see, the problem is most probably caused from the underlying library([oshi](https://github.com/oshi/oshi)). I can not open a bug before updating to the latest version (the version used in the Systeminfo 2.0 binding is 2.5 and the latest stable is 3.2 ), because the problem might be already solved. 

I will try update the binding to the latest version. It will be really helpful, if you test it after the change.

**Comment by davorf** [comment]
Hello!

I have OpenHAB 2 offline installed/extracted from the .zip file. Will it be enough to uninstall and then reinstall binding from the Paper UI, or there is some other procedure to install updated binding? I have Access remote repositories and Include Legacy 1.x bindings turned on, and Include experimental extensions turned off in System settings.

Best regards,
Davor

**Comment by svilenvul** [comment]
When it is merged, I guess it will be possible.

You can try now with this jar file: 
[org.openhab.binding.systeminfo-2.0.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/592389/org.openhab.binding.systeminfo-2.0.0-SNAPSHOT.jar.zip). Simply replace the file in your addons folder.

**Comment by davorf** [comment]
Hello! 

I've just tried a new binding jar, but it still reports thing as uninitialized. The message I get in log is:

```
11:52:28.749 [WARN ] [ore.thing.internal.ThingRegistryImpl] - Cannot create thin
g. No binding found that supports creating a thing of type systeminfo:computer.
```

Best regards,
Davor

**Comment by svilenvul** [comment]
Hmm, strange, maybe I missed to export something. 
Anyway the PR with the update is merged, so it will be available in two or three days.

**Comment by bboser** [comment]
Not sure if this is related: 
I'm using the OH2 system info binding on a raspberry pi 3. I've copied the configuration from the readme (I'm using text file configuration, not GUI).
Per the log (see below), the binging reaches the ONLINE state. However, none of the channels are being updated and the Paper UI reports the thing as "initializing" (even after waiting overnight).
I ran apt-get update/upgrade yesterday, so should have the latest version.

`11:48:48.373 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Process_name-systeminfo:computer:SvilenV-L540:process#name' has been added.
11:48:48.374 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Process_threads-systeminfo:computer:SvilenV-L540:process#threads' has been added.
11:48:48.376 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Process_path-systeminfo:computer:SvilenV-L540:process#path' has been added.
11:48:50.634 [DEBUG] [org.openhab.binding.systeminfo      ] - BundleEvent STARTING - org.openhab.binding.systeminfo
11:48:50.636 [DEBUG] [org.openhab.binding.systeminfo      ] - BundleEvent STARTED - org.openhab.binding.systeminfo
11:48:50.656 [DEBUG] [org.openhab.binding.systeminfo      ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={component.name=org.openhab.binding.systeminfo.discovery, component.id=133, service.id=253, service.bundleid=177, service.scope=bundle} - org.openhab.binding.systeminfo
11:48:50.670 [DEBUG] [org.openhab.binding.systeminfo      ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={component.name=binding.systeminfo, component.id=134, service.id=254, service.bundleid=177, service.scope=bundle} - org.openhab.binding.systeminfo
11:48:50.688 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'systeminfo:computer:work' has been added.
11:48:51.412 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Start initializing!
11:48:51.413 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Thing configuration updated!
11:48:51.414 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Channel configuration updated!
11:48:51.433 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'systeminfo:computer:work' changed from UNINITIALIZED to INITIALIZING
11:48:53.275 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'systeminfo:computer:work' has been updated.
11:48:54.950 [DEBUG] [systeminfo.handler.SysteminfoHandler] - OSHI Systeminfo library is instatiated!
11:48:54.952 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Start reading Thing configuration.
11:48:54.953 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Refresh time for medium priority channels set to 60 s
11:48:54.954 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Refresh time for high priority channels set to 3 s
11:48:54.958 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Properties updated!
11:48:54.959 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Schedule high priority tasks at fixed rate 3 s.
11:48:54.961 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Schedule medium priority tasks at fixed rate 60 s.
11:48:54.964 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Schedule one time update for low priority tasks.
11:48:54.966 [DEBUG] [systeminfo.handler.SysteminfoHandler] - Thing is successfully initialized!
11:48:54.979 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'systeminfo:computer:work' changed from INITIALIZING to ONLINE
`

**Comment by davorf** [comment]
Hello!

Any news regarding this issue?

Best regards,
Davor

**Comment by bboser** [comment]
I’m waiting until the flurry of updates to openhab subsides before trying
again.

Bernhard

**Comment by svilenvul** [comment]
@bboser  this seems to be related to this  [bug in the Eclipse SmartHome ](https://github.com/eclipse/smarthome/pull/3088)

**Comment by svilenvul** [comment]
@davorf, have you tried with the latest version of the binding ?
I will update it again (with the newest stable version of oshi), so if you haven't, you might want to wait until it is ready.

**Comment by davorf** [comment]
Hello @svilenvul 

I've tried it few days ago, but it wasn't working. I'll try it again when you say it's ready and included in regular nightly build. 

Best regards,
Davor

**Comment by davorf** [comment]
Hello! 

I've just installed latest nightly and tried Systeminfo binding 2.0 and it works, so, I will close this issue. 

Best regards,
Davor
