### ISSUE TITLE
system info NullPointerException

### ISSUE THREAD

**Issue by bboser** [openhab/openhab2-addons#1450]
In a brand-new installation based on openhabian (on an rpi 3), the OH2 system info binding throws a null pointer exception on startup and does not update any channels.

Config: (no cfg file)
`Thing systeminfo:computer:raspberrypi [interval_high=15, interval_medium=120] 

Group gSystem
Number cpuMemTotal     "Memory total [%.0f MBytes]"      (gSystem) { channel="systeminfo:computer:raspberrypi:memory#total" }
Number cpuMemUsed      "Memory used  [%.0f MBytes]"      (gSystem) { channel="systeminfo:computer:raspberrypi:memory#used" }
Number cpuMemAvailable "Memory available [%.0f MBytes]"  (gSystem) { channel="systeminfo:computer:raspberrypi:memory#available" }
Number cpuMemPercent   "Memory available [%.0f %%]"      (gSystem) { channel="systeminfo:computer:raspberrypi:memory#availablePercent" }

Number diskTotal       "Disk total [%.0f MBytes]"        (gSystem) { channel="systeminfo:computer:raspberrypi:storage#total" }
Number diskPercent     "Disk available [%.0f %%]"        (gSystem) { channel="systeminfo:computer:raspberrypi:storage#availablePercent" }
Number diskAvailable   "Disk available [%.0f MBytes]"    (gSystem) { channel="systeminfo:computer:raspberrypi:storage#available" }
Number cpuLoad         "CPU load [%.0f %%]"              (gSystem) { channel="systeminfo:computer:raspberrypi:cpu#load" }
`

Log:

`12:50:27.296 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'systeminfo:computer:raspberrypi' changed from UNINITIALIZED to INITIALIZING
12:50:27.452 [ERROR] [platform.linux.LinuxCentralProcessor] - Couldn't find physical processor count. Assuming 1.
12:50:27.842 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'systeminfo:computer:raspberrypi' changed from INITIALIZING to ONLINE
12:50:28.351 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling thing updated at ThingHandler 'org.openhab.binding.systeminfo.handler.SysteminfoHandler@12d0bb1: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_111]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)[96:org.eclipse.smarthome.core:0.9.0.201611181452]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)[96:org.eclipse.smarthome.core:0.9.0.201611181452]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)[96:org.eclipse.smarthome.core:0.9.0.201611181452]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:498)[103:org.eclipse.smarthome.core.thing:0.9.0.201611181452]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:226)[103:org.eclipse.smarthome.core.thing:0.9.0.201611181452]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:149)[103:org.eclipse.smarthome.core.thing:0.9.0.201611181452]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201611181452]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:167)[96:org.eclipse.smarthome.core:0.9.0.201611181452]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[96:org.eclipse.smarthome.core:0.9.0.201611181452]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[96:org.eclipse.smarthome.core:0.9.0.201611181452]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$3(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201611181452]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$2.apply(GenericThingProvider.java:985)[131:org.eclipse.smarthome.model.thing:0.9.0.201611181452]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$2.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201611181452]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.run(GenericThingProvider.java:994)[131:org.eclipse.smarthome.model.thing:0.9.0.201611181452]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
Caused by: java.lang.NullPointerException
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.handleChannelConfigurationChange(SysteminfoHandler.java:568)[194:org.openhab.binding.systeminfo:2.0.0.201611181914]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.thingUpdated(SysteminfoHandler.java:547)[194:org.openhab.binding.systeminfo:2.0.0.201611181914]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$6.call(ThingManager.java:502)[103:org.eclipse.smarthome.core.thing:0.9.0.201611181452]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$6.call(ThingManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201611181452]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[96:org.eclipse.smarthome.core:0.9.0.201611181452]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
	... 1 more
`

**Comment by kaikreuzer** [comment]
@svilenvul Could you please have a look?

**Comment by svilenvul** [comment]
Yes, I will open a PR for this one.

**Comment by bboser** [comment]
Since my first report, I've observed the following:

1. The null-pointer exception is not reliably reproducible. It sometimes occurs on startup, but not always.
2. Although the binding claims it's online (per log), it won't report any updates and in the paper UI it shows as "initializing".
3. I found the following workaround for the problem in (2): 
     a) remove the thing declaration of the binding from the textual configuration.
     b) use the computer name in the all channel definitions, like so: { channel="systeminfo:computer:habian_creston:cpu#load" }
     c) import the binding with the paper UI.
With the above steps the binding works correctly. But I have not found a path to entirely configure the binding with configuration files alone.

Thanks for looking into this. No longer a significant issue from my perspective, but others (who use configuration files) may run into similar issues.

**Comment by svilenvul** [comment]
@bboser 

Thanks for the information. 

From what I have seen, the NPE could occur if you change the configuration of  channel while the thing has been modified ( somehow, maybe through Paper UI or textual, I can only assume). 
Anyway I have found other things that can be improved as well, so I will fix this as well to make it more robust.
