### ISSUE TITLE
Maven build faild

### ISSUE THREAD

**Issue by MichaelGottschlich** [openhab/openhab2-addons#1478]
Hallo

i want to build openhab2-addons on my own computer. To update knx binding. 

I have an problem with download of p2-openhab-core from location https://dl.bintray.com/openhab/p2/openhab-core/2.0.0.x . Can fix download server, please.

Java version: 1.8.0_92(win)
maven version: 3.2.1

[INFO] Computing target platform for MavenProject: org.openhab.binding:org.openhab.binding.amazondashbutton:2.0.0-SNAPSHOT @ C:\Temp\openhab2-addons\addons\binding\org.openhab.binding.amazondashbutton\pom.xml
[INFO] Adding repository http://download.eclipse.org/smarthome/updates-stable
[INFO] Adding repository https://dl.bintray.com/openhab/p2/openhab-core/2.0.0.x
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-openhab-core' from location https://dl.bintray.com/openhab/p2/openhab-core/2.0.0.x: Unable to connect to repository https://dl.bintray.com/openhab/p2/openhab-core/2.0.0.x/content.xml: Connection timed out: connect -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-openhab-core' from location https://dl.bintray.com/openhab/p2/openhab-core/2.0.0.x
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-openhab-core' from location https://dl.bintray.com/openhab/p2/openhab-core/2.0.0.x

.
.
.
.

[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

Process finished with exit code 1

**Comment by kaikreuzer** [comment]
Server is ok as you can check on https://dl.bintray.com/openhab/p2/openhab-core/2.0.0.x/ with your browser yourself.
