### ISSUE TITLE
[avmfritz] Invalid Request 403

### ISSUE THREAD

**Issue by janKG** [openhab/openhab2-addons#1479]
I'm getting lots of avmfritz info log entries about invalid requests.
System is OH2 on the latest nightly snapshot.

I'm only using the binding to switch DECT 200 outlets, which still is working fine.

`2016-11-25 12:09:45.314 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403`

**Comment by kaikreuzer** [comment]
403 Forbidden: "The request was a valid request, but the server is refusing to respond to it. The user might be logged in but does not have the necessary permissions for the resource."

Did you check that you use a correct user that has AHA rights?

**Comment by janKG** [comment]
I had another look and also enabled debug logging. I'm getting the feeling it is some kind of initialization problem. The message is only displayed a few times after the startup of OH2, after that everything works fine.

I also rechecked the username, password and rights - all are correct.

Here are the relevant log entries:
```
2016-11-30 15:54:31.834 [ERROR] [org.openhab.binding.avmfritz        ] - FrameworkEvent ERROR - org.openhab.binding.avmfritz
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.avmfritz [11]
  Another singleton bundle selected: osgi.identity; osgi.identity="org.openhab.binding.avmfritz"; type="osgi.bundle"; version:Version="2.0.0.201611241944"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]

2016-11-30 15:54:51.533 [DEBUG] [org.openhab.binding.avmfritz        ] - BundleEvent STARTING - org.openhab.binding.avmfritz
2016-11-30 15:54:51.641 [DEBUG] [org.openhab.binding.avmfritz        ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.UpnpDiscoveryParticipant}={component.name=org.openhab.binding.avmfritz.discovery.bridge, component.id=133, service.id=253, service.bundleid=178, service.scope=bundle} - org.openhab.binding.avmfritz
2016-11-30 15:54:51.705 [DEBUG] [org.openhab.binding.avmfritz        ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={component.name=org.openhab.binding.avmfritz.internal.HandlerFactory, component.id=134, service.id=255, service.bundleid=178, service.scope=bundle} - org.openhab.binding.avmfritz
2016-11-30 15:54:51.878 [DEBUG] [ternal.discovery.AvmDiscoveryService] - initialize discovery service
2016-11-30 15:54:51.890 [DEBUG] [ternal.discovery.AvmDiscoveryService] - start background scanning job
2016-11-30 15:54:51.946 [DEBUG] [org.openhab.binding.avmfritz        ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=256, service.bundleid=178, service.scope=singleton} - org.openhab.binding.avmfritz
2016-11-30 15:54:51.975 [DEBUG] [org.openhab.binding.avmfritz        ] - BundleEvent STARTED - org.openhab.binding.avmfritz
2016-11-30 15:54:52.249 [DEBUG] [.binding.avmfritz.handler.BoxHandler] - About to initialize bridge fritzbox
2016-11-30 15:54:52.262 [DEBUG] [.binding.avmfritz.handler.BoxHandler] - discovered fritzaha bridge initialized: org.openhab.binding.avmfritz.config.AvmFritzConfiguration@cd0863[IP=192.168.1.1,port=<null>,proto=http,user=openhab,password=mypassword,pollingInterval=15,asyncTimeout=10000,syncTimeout=2000]
2016-11-30 15:54:53.626 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered on /192.168.1.253
2016-11-30 15:54:53.628 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered: AVM Berlin FRITZ!Box 7490 (UI) at 192.168.1.1
2016-11-30 15:54:53.642 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered on /192.168.1.253
2016-11-30 15:54:53.647 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered on /192.168.1.253
2016-11-30 15:54:53.647 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered: AVM Berlin FRITZ!Box Fon WLAN 7390 (UI) at 192.168.1.254
2016-11-30 15:54:53.647 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered: AVM Berlin FRITZ!Box 7490 (UI) at 192.168.1.1
2016-11-30 15:54:54.050 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered on /192.168.1.253
2016-11-30 15:54:54.059 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered: AVM Berlin FRITZ!Box 7490 (UI) at 192.168.1.1
2016-11-30 15:54:54.259 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered on /192.168.1.253
2016-11-30 15:54:54.260 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered: AVM Berlin FRITZ!Box Fon WLAN 7390 (UI) at 192.168.1.254
2016-11-30 15:54:54.413 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered on /192.168.1.253
2016-11-30 15:54:54.413 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered: AVM Berlin FRITZ!Box 7490 (UI) at 192.168.1.1
2016-11-30 15:54:54.475 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered on /192.168.1.253
2016-11-30 15:54:54.476 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered: AVM Berlin FRITZ!Box Fon WLAN 7390 (UI) at 192.168.1.254
2016-11-30 15:54:54.533 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered on /192.168.1.253
2016-11-30 15:54:54.534 [DEBUG] [iscovery.AvmUpnpDiscoveryParticipant] - discovered: AVM Berlin FRITZ!Box 7490 (UI) at 192.168.1.1

2016-11-30 15:54:54.728 [DEBUG] [ternal.hardware.FritzahaWebInterface] - Starting with SID 0000000000000000
2016-11-30 15:54:54.729 [DEBUG] [.binding.avmfritz.handler.BoxHandler] - start polling job at intervall 15

2016-11-30 15:54:55.731 [DEBUG] [g.avmfritz.handler.DeviceListPolling] - polling fritzbox org.openhab.binding.avmfritz.config.AvmFritzConfiguration@cd0863[IP=192.168.1.1,port=<null>,proto=http,user=openhab,password=mypassword,pollingInterval=15,asyncTimeout=10000,syncTimeout=2000]
2016-11-30 15:54:55.748 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:54:55.938 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:54:55.939 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:54:55.942 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:54:56.300 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:54:56.301 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403
2016-11-30 15:54:56.558 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:54:56.559 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:54:56.559 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:54:56.560 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403

2016-11-30 15:54:56.892 [DEBUG] [ternal.discovery.AvmDiscoveryService] - starting scan on bridge avmfritz:fritzbox:192_168_1_1
2016-11-30 15:54:56.924 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:54:57.108 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:54:57.109 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:54:57.110 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:54:57.414 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:54:57.583 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:54:57.583 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:54:57.584 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 

2016-11-30 15:55:10.757 [DEBUG] [g.avmfritz.handler.DeviceListPolling] - polling fritzbox org.openhab.binding.avmfritz.config.AvmFritzConfiguration@cd0863[IP=192.168.1.1,port=<null>,proto=http,user=openhab,password=mypassword,pollingInterval=15,asyncTimeout=10000,syncTimeout=2000]
2016-11-30 15:55:10.760 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:55:10.923 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:10.924 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:10.925 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:55:11.231 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:55:11.233 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403
2016-11-30 15:55:11.396 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:11.397 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:11.398 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:55:11.399 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403

2016-11-30 15:55:25.761 [DEBUG] [g.avmfritz.handler.DeviceListPolling] - polling fritzbox org.openhab.binding.avmfritz.config.AvmFritzConfiguration@cd0863[IP=192.168.1.1,port=<null>,proto=http,user=openhab,password=mypassword,pollingInterval=15,asyncTimeout=10000,syncTimeout=2000]
2016-11-30 15:55:25.765 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:55:25.931 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:25.932 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:25.933 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:55:26.237 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:55:26.238 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403
2016-11-30 15:55:26.400 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:26.400 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:26.401 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:55:26.402 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403

2016-11-30 15:55:40.766 [DEBUG] [g.avmfritz.handler.DeviceListPolling] - polling fritzbox org.openhab.binding.avmfritz.config.AvmFritzConfiguration@cd0863[IP=192.168.1.1,port=<null>,proto=http,user=openhab,password=mypassword,pollingInterval=15,asyncTimeout=10000,syncTimeout=2000]
2016-11-30 15:55:40.769 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:55:40.935 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:40.936 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:40.937 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:55:41.238 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:55:41.239 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403
2016-11-30 15:55:41.401 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:41.402 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:41.403 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:55:41.403 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403

2016-11-30 15:55:55.771 [DEBUG] [g.avmfritz.handler.DeviceListPolling] - polling fritzbox org.openhab.binding.avmfritz.config.AvmFritzConfiguration@cd0863[IP=192.168.1.1,port=<null>,proto=http,user=openhab,password=mypassword,pollingInterval=15,asyncTimeout=10000,syncTimeout=2000]
2016-11-30 15:55:55.774 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=0000000000000000
2016-11-30 15:55:55.947 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:55.948 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 403
2016-11-30 15:55:55.949 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: 
2016-11-30 15:55:56.251 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.1.1/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=3953027d0ad99136
2016-11-30 15:55:56.251 [INFO ] [.callbacks.FritzAhaUpdateXmlCallback] - request is invalid: 403
2016-11-30 15:55:56.486 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 200
2016-11-30 15:55:56.487 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 200
2016-11-30 15:55:56.488 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: <devicelist version="1"><device identifier="REMOVED" id="18" functionbitmask="896" fwversion="03.59" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><name>SD01</name><switch><state>0</state><mode>manuell</mode><lock>0</lock></switch><powermeter><power>0</power><energy>18345</energy></powermeter><temperature><celsius>200</celsius><offset>0</offset></temperature></device><device identifier="08761 0231987" id="19" functionbitmask="896" fwversion="03.59" manufacturer="AVM" productname="FRITZ!DECT 200"><present>1</present><name>SD02</name><switch><state>0</state><mode>manuell</mode><lock>0</lock></switch><powermeter><power>0</power><energy>2742</energy></powermeter><temperature><celsius>195</celsius><offset>0</offset></temperature></device></devicelist>

```

**Comment by cweitkamp** [comment]
@janKG Does this till happen in your system? Or can we maybe close this issue?

**Comment by cweitkamp** [comment]
@martinvw @wborn Let's close this issue. WDYT?

**Comment by janKG** [comment]
I don't think I've seen thr issue in a while, so yes, let's consider it closed.
