### ISSUE TITLE
harmony binding bug

### ISSUE THREAD

**Issue by tratho** [openhab/openhab2-addons#1480]
I trying since days to setup the harmony binding, and i'm unable to manage it. But now i think it is a bug.
I'm not really sure if it is a bug in the harmony bindung but in the core framework.
Nervertheless i found it here, so i thought it would be the right way to post it here.

All Things were found correctly the hub, and the devices. Nevertheless the the device does not have a pointer the bridge (hub). I tried it with paperUI and with HABmin. There is no way to select the bridge (hub). This leads to a nullpointerException

`2016-11-20 23:48:15.523 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling handler: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_65]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_65]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)[96:org.eclipse.smarthome.core:0.9.0.201611191809]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)[96:org.eclipse.smarthome.core:0.9.0.201611191809]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)[96:org.eclipse.smarthome.core:0.9.0.201611191809]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:349)[103:org.eclipse.smarthome.core.thing:0.9.0.201611191809]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)[96:org.eclipse.smarthome.core:0.9.0.201611191809]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201611191809]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201611191809]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[96:org.eclipse.smarthome.core:0.9.0.201611191809]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
Caused by: java.lang.NullPointerException
	at org.openhab.binding.harmonyhub.handler.HarmonyDeviceHandler.handleCommand(HarmonyDeviceHandler.java:90)[196:org.openhab.binding.harmonyhub:2.0.0.201611201812]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:352)[103:org.eclipse.smarthome.core.thing:0.9.0.201611191809]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201611191809]
	... 5 more`

So i started it in the debugger and found out that the harmonyHub is not initialised in the device.

I'm talking about `HarmonyHubHandler bridge` in `HarmonyDeviceHandler.java`

But as ` <supported-bridge-type-refs>` is a core function i'm not really sure, if it is a bug in the binding or somewhere else.

**Comment by kungfoolfighting** [comment]
I am experiencing the exact same problem with today's OH2 snapshot.
I wanted to move to a newer snapshot of OH2 to get the HarmonyHub plugin for OH2 since the 1.x version stopped working recently. But it turns out that the OH2 version doesn't work either.
I also recently (3 days ago or so) did a firmware update on the HarmonyHub.

**Comment by tratho** [comment]
I have done new observations.
It is definitly a bug in the binding. The bridge is not pointed to the device.
I have done a very dirty hack in the binding.

In `HarmonyHubHandlerFactory.java` a member 
` public HarmonyHubHandler harmonyHubHandler;`

and changed 

` @Override
    protected ThingHandler createHandler(Thing thing) {

        ThingTypeUID thingTypeUID = thing.getThingTypeUID();

        if (thingTypeUID.equals(HarmonyHubBindingConstants.HARMONY_HUB_THING_TYPE)) {
            HarmonyHubHandler harmonyHubHandler = new HarmonyHubHandler((Bridge) thing, this);
            registerHarmonyDeviceDiscoveryService(harmonyHubHandler);
            return harmonyHubHandler;
        }

        if (thingTypeUID.equals(HarmonyHubBindingConstants.HARMONY_DEVICE_THING_TYPE)) {
            return new HarmonyDeviceHandler(thing, this);
        }

        return null;
    }`

to

` @Override
    protected ThingHandler createHandler(Thing thing) {

        ThingTypeUID thingTypeUID = thing.getThingTypeUID();

        if (thingTypeUID.equals(HarmonyHubBindingConstants.HARMONY_HUB_THING_TYPE)) {
            HarmonyHubHandler harmonyHubHandler = new HarmonyHubHandler((Bridge) thing, this);
            registerHarmonyDeviceDiscoveryService(harmonyHubHandler);
            this.harmonyHubHandler = harmonyHubHandler;
            return harmonyHubHandler;
        }

        if (thingTypeUID.equals(HarmonyHubBindingConstants.HARMONY_DEVICE_THING_TYPE)) {
            return new HarmonyDeviceHandler(thing, this);
        }

        return null;
    }`

In `HarmonyDeviceHandler.java` i changed the constructor from

`public HarmonyDeviceHandler(Thing thing, HarmonyHubHandlerFactory factory) {
        super(thing);
        this.factory = factory;
    }`

to

`public HarmonyDeviceHandler(Thing thing, HarmonyHubHandlerFactory factory) {
        super(thing);
        this.factory = factory;
        bridge = factory.harmonyHubHandler;
    }`

And now it seems to work. Nevertheless i am not able to to select a bridge in the paperUI

**Comment by kungfoolfighting** [comment]
Hi tratho,
thanks for looking into this.
I managed to compile the bundle with your changes, but now I don't know how to get OpenHAB to use it.
I have used the karaf console to load the bundle and start it, after I uninstalled the old HarmonyHub extension in the paperUI. 
But I still get the nullpointer exception when using an item that is bound to a harmony thing.
Any help?

**Comment by digitaldan** [comment]
Hi all, I have a fix I am testing today, I'll post a updated jar here soon

**Comment by tratho** [comment]
@digitaldan that sounds great, cause my fix is no fix but a bad hack.

@kungfoolfighting just copy the compiled *.jar in the addon folder.
But probalby it would be the best, you just wait, for a real fix, and not this dirty hack

**Comment by digitaldan** [comment]
I have a PR open, in the mean time you can find a pre compiled jar at https://github.com/digitaldan/openhab2-addons/releases/tag/harmony-bridge-fix

**Comment by kungfoolfighting** [comment]
@digitaldan Thanks for the quick fix.
It seems to be working now, however, I got a lot of exceptions during boot and I keep getting this sort of message after pressing a harmony button:

```
2016-11-26 19:19:34.702 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@5ee37556' takes more than 5000ms.
2016-11-26 19:19:34.878 [WARN ] [ome.core.thing.internal.ThingManager] - Handler for thing 'harmonyhub:device:HarmonyHub:33163673' takes more than 5000ms for processing event

```
