### ISSUE TITLE
[amazondashbutton] NoSuchMethodError

### ISSUE THREAD

**Issue by SuperOok** [openhab/openhab2-addons#1512]
I successfully installed latest snapshot build (624) for the whole distro, including the amazondashbutton version 2.0.0.201611291735.
I connected 4 Dash Buttons successfully (recently bought, so german new generation buttons).
However, when triggering the button I get this exception in the logs:

```
20:41:01.187 [ERROR] [org.pcap4j.core.PcapHandle          ] - The executor has thrown an exception.
java.lang.NoSuchMethodError: org.openhab.binding.amazondashbutton.handler.AmazonDashButtonHandler.triggerChannel(Lorg/eclipse/smarthome/core/thing/ChannelUID;)V
        at org.openhab.binding.amazondashbutton.handler.AmazonDashButtonHandler.access$1(AmazonDashButtonHandler.java:1)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.openhab.binding.amazondashbutton.handler.AmazonDashButtonHandler$1.packetCaptured(AmazonDashButtonHandler.java:76)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.openhab.binding.amazondashbutton.internal.capturing.PacketCapturingService$1$1.gotPacket(PacketCapturingService.java:112)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor$1.run(PcapHandle.java:1451)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle$SimpleExecutor.execute(PcapHandle.java:1417)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.got_packet(PcapHandle.java:1445)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.NativeMappings.pcap_loop(Native Method)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle.doLoop(PcapHandle.java:895)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:819)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:782)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.openhab.binding.amazondashbutton.internal.capturing.PacketCapturingService$1.call(PacketCapturingService.java:102)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.openhab.binding.amazondashbutton.internal.capturing.PacketCapturingService$1.call(PacketCapturingService.java:1)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
20:41:01.199 [ERROR] [org.pcap4j.core.PcapHandle          ] - The executor has thrown an exception.
java.lang.NoSuchMethodError: org.openhab.binding.amazondashbutton.handler.AmazonDashButtonHandler.triggerChannel(Lorg/eclipse/smarthome/core/thing/ChannelUID;)V
        at org.openhab.binding.amazondashbutton.handler.AmazonDashButtonHandler.access$1(AmazonDashButtonHandler.java:1)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.openhab.binding.amazondashbutton.handler.AmazonDashButtonHandler$1.packetCaptured(AmazonDashButtonHandler.java:76)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.openhab.binding.amazondashbutton.internal.capturing.PacketCapturingService$1$1.gotPacket(PacketCapturingService.java:112)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor$1.run(PcapHandle.java:1451)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle$SimpleExecutor.execute(PcapHandle.java:1417)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.got_packet(PcapHandle.java:1445)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.NativeMappings.pcap_loop(Native Method)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle.doLoop(PcapHandle.java:895)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:819)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:782)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.openhab.binding.amazondashbutton.internal.capturing.PacketCapturingService$1.call(PacketCapturingService.java:102)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at org.openhab.binding.amazondashbutton.internal.capturing.PacketCapturingService$1.call(PacketCapturingService.java:1)[212:org.openhab.binding.amazondashbutton:2.0.0.201611291735]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

None of the corresponding rules get triggered

```
rule "Dash Ariel"
    when
        Channel "amazondashbutton:dashbutton:50-f5-da-xx-xx-xx:press" triggered
    then
        Licht_Zimmer2.sendCommand(ON)
end
```
Removing the rules does not make a change.

**Comment by SuperOok** [comment]
Any way I can assign this directly to @OLibutzki ?

**Comment by kaikreuzer** [comment]
You can mention him as you just did to get his attention :-)

**Comment by OLibutzki** [comment]
> You can mention him as you just did to get his attention :-)
That worked ;-)

@SuperOok  Looks like you do not have the latest of [BaseThingHandler](https://github.com/eclipse/smarthome/blob/9bf9cacf187c1b46a7f0ca840678ecb7cb440b38/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java)  in your classpath. The triggerChannel method has been added with commit https://github.com/eclipse/smarthome/commit/fb42a5d109fc12888dbd25e4130b9e3a6ebdbd2d#diff-87efa14fe4d7f7992108b2deedd0401e.

**Comment by SuperOok** [comment]
Aha, that's strange. Yesterday I just updated my OH2-b4 to the latest Snapshot version from cloudbees via the official apt-get repository from yesterday's built.
I will check which versions I have. And check why I don't have the latest version you mentioned.

**Comment by SuperOok** [comment]
Ok, upgrading helped. So I just did an upgrade
```
sudo apt-get update
sudo apt-get upgrade
```
It upgraded to the latest snapshot version, build 627 from today. That seems to work.
Before that I had build 624 from start-of-week. I assumed that should also work.

a wild guess is that there is some issue with the linux apt-packages if you switch from beta to latest snapshot...

However, I think it is no issue with the binding, might be another problem...
