### ISSUE TITLE
Netatmo binding: NPE (getNAThingProperty)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1517]
Using snapshot 627:
```
2016-12-02 00:16:55.984 [WARN ] [ome.core.thing.internal.ThingManager] - Initializing handler for thing 'netatmo:netatmoapi:maison' takes more than 5000ms.
2016-12-02 00:16:56.104 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
        at org.openhab.binding.netatmo.handler.station.NAModule1Handler.getNAThingProperty(NAModule1Handler.java:36)[184:org.openhab.binding.netatmo:2.0.0.201612010742]
        at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[184:org.openhab.binding.netatmo:2.0.0.201612010742]
        at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[184:org.openhab.binding.netatmo:2.0.0.201612010742]
        at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[184:org.openhab.binding.netatmo:2.0.0.201612010742]
        at org.openhab.binding.netatmo.handler.station.NAModule1Handler.handleCommand(NAModule1Handler.java:1)[184:org.openhab.binding.netatmo:2.0.0.201612010742]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[184:org.openhab.binding.netatmo:2.0.0.201612010742]
        at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[184:org.openhab.binding.netatmo:2.0.0.201612010742]
        at org.openhab.binding.netatmo.handler.station.NAModule1Handler.channelLinked(NAModule1Handler.java:1)[184:org.openhab.binding.netatmo:2.0.0.201612010742]
        at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:305)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

**Comment by planbnet** [comment]
Same here - for station and thermostat. Only happens when the Thing is defined in .thing file - confuguring from the UI works.

```
08:42:33.221 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
        at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[189:org.openhab.binding.netatmo:2.0.0.201611281907]
        at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:111)[189:org.openhab.binding.netatmo:2.0.0.201611281907]
        at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:157)[189:org.openhab.binding.netatmo:2.0.0.201611281907]
        at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[189:org.openhab.binding.netatmo:2.0.0.201611281907]
        at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[189:org.openhab.binding.netatmo:2.0.0.201611281907]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[105:org.eclipse.smarthome.core.thing:0.9.0.201611272028]
        at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:126)[189:org.openhab.binding.netatmo:2.0.0.201611281907]
        at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[189:org.openhab.binding.netatmo:2.0.0.201611281907]
        at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[189:org.openhab.binding.netatmo:2.0.0.201611281907]
        at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[105:org.eclipse.smarthome.core.thing:0.9.0.201611272028]
        at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:305)[105:org.eclipse.smarthome.core.thing:0.9.0.201611272028]
        at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[105:org.eclipse.smarthome.core.thing:0.9.0.201611272028]
        at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[98:org.eclipse.smarthome.core:0.9.0.201611272028]
        at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[98:org.eclipse.smarthome.core:0.9.0.201611272028]
        at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[98:org.eclipse.smarthome.core:0.9.0.201611272028]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[98:org.eclipse.smarthome.core:0.9.0.201611272028]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
08:42:34.170 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
08:42:34.180 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
```

**Comment by lolodomo** [comment]
My things are defined in a .things file.
