### ISSUE TITLE
Harmony not starting in OH online release 632

### ISSUE THREAD

**Issue by Royw51** [openhab/openhab2-addons#1549]
OS  windows 10
Java JDK1.8.0_65
OH online release 632

When starting openhab I get the following error and HarmonyHUB does not start.
06:57:57.076 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while initializing handler of thing 'harmonyhub:hub:Mediaroom': java.lang.IllegalArgumentException: Illegal status INITIALIZING. Bindings only may set UNKNOWN, ONLINE, OFFLINE or REMOVED.
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Illegal status INITIALIZING. Bindings only may set UNKNOWN, ONLINE, OFFLINE or REMOVED.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_111]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:188)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:81)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:65)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$9.run(ThingManager.java:743)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Illegal status INITIALIZING. Bindings only may set UNKNOWN, ONLINE, OFFLINE or REMOVED.
        at org.eclipse.smarthome.core.thing.internal.ThingManager$1.ensureValidStatus(ThingManager.java:185)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$1.statusUpdated(ThingManager.java:150)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:386)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.updateStatus(HarmonyHubHandler.java:144)[175:org.openhab.binding.harmonyhub:2.0.0.201612091044]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:415)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.connect(HarmonyHubHandler.java:205)[175:org.openhab.binding.harmonyhub:2.0.0.201612091044]
        at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.initialize(HarmonyHubHandler.java:132)[175:org.openhab.binding.harmonyhub:2.0.0.201612091044]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:746)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
        ... 3 more
06:57:57.076 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'harmonyhub:hub:Mediaroom' changed from UNINITIALIZED to INITIALIZING
06:57:57.092 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'harmonyhub:hub:Mediaroom' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): Illegal status INITIALIZING. Bindings only may set UNKNOWN, ONLINE, OFFLINE or REMOVED.

**Comment by kaikreuzer** [comment]
Interesting, this seems to be a bug in the binding, which is now popping up by a more strict check in the framework. I'll have a look, thanks for reporting!

**Comment by kaikreuzer** [comment]
should work with the next distro again!
