### ISSUE TITLE
[openHABCloud] several IOException messages after add-on installation

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1585]
This is not a sever problem but I wanted to document it.

I have installed the latest openHAB version on my Raspberry 3. Not via apt-get but by unzipping the ...-online zip file from Cloudbees. 
After the first start I selected "install" for the openHab Cloud and the Rest documentation add-on.
Now I got several error messages on the console.
```
21:35:49.067 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'misc-openhabcloud' has been installed.
21:35:49.227 [ERROR] [io.openhabcloud.internal.CloudClient] - Socket.IO error: not authorized
```
This Socket.IO error is understandable because I did not configure the correct uuid and secret at this time. 
What I am missing is some feedback in Paper UI when the connection to myopenhab can't be established.

More interestingly are the following messages. Unfortunately they can't be reproduced at any time. But I have the feeling that error messages like these happen if two add-ons are installed at the same. Mabe its because of slow file access on the Raspberry. 
There are several "java.io.IOException: Exception in opening zip file" for different files but after configuring the correct secret and uuid and configuring the items that should be exposed everything worked fine. 
````
21:36:01.162 [ERROR] [org.apache.felix.scr                ] - Error while disposing components of bundle org.openhab.io.openhabcloud/181
java.lang.IllegalStateException: BundleContext is no longer valid
        at org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:983)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.ungetService(BundleContextImpl.java:659)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.osgi.util.tracker.ServiceTracker.removedService(ServiceTracker.java:459)[org.osgi.core-6.0.0.jar:]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:967)[org.osgi.core-6.0.0.jar:]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:870)[org.osgi.core-6.0.0.jar:]
        at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)[org.osgi.core-6.0.0.jar:]
        at org.osgi.util.tracker.ServiceTracker.close(ServiceTracker.java:377)[org.osgi.core-6.0.0.jar:]
        at org.apache.felix.scr.impl.BundleComponentActivator.dispose(BundleComponentActivator.java:549)[33:org.apache.felix.scr:2.0.2]
        at org.apache.felix.scr.impl.Activator.disposeComponents(Activator.java:414)[33:org.apache.felix.scr:2.0.2]
        at org.apache.felix.scr.impl.Activator.access$300(Activator.java:53)[33:org.apache.felix.scr:2.0.2]
        at org.apache.felix.scr.impl.Activator$ScrExtension.destroy(Activator.java:273)[33:org.apache.felix.scr:2.0.2]
        at org.apache.felix.utils.extender.AbstractExtender$2.run(AbstractExtender.java:290)[33:org.apache.felix.scr:2.0.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
        at org.apache.felix.utils.extender.AbstractExtender.destroyExtension(AbstractExtender.java:312)[33:org.apache.felix.scr:2.0.2]
        at org.apache.felix.utils.extender.AbstractExtender.bundleChanged(AbstractExtender.java:186)[33:org.apache.felix.scr:2.0.2]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:902)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer.update(ModuleContainer.java:342)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.storage.Storage.update(Storage.java:713)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.update(EquinoxBundle.java:439)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.updateBundle(FeaturesServiceImpl.java:1185)[9:org.apache.karaf.features.core:4.0.4]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:688)[9:org.apache.karaf.features.core:4.0.4]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1089)[9:org.apache.karaf.features.core:4.0.4]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:985)[9:org.apache.karaf.features.core:4.0.4]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
21:36:04.317 [INFO ] [core.karaf.internal.FeatureInstaller] - Installed 'openhab-misc-restdocs'
21:36:04.320 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'misc-restdocs' has been installed.
21:36:04.608 [ERROR] [io.openhabcloud.internal.CloudClient] - Socket.IO error: not authorized
21:36:14.163 [ERROR] [org.openhab.io.openhabcloud         ] - FrameworkEvent ERROR - org.openhab.io.openhabcloud
java.io.IOException: Exception in opening zip file: /opt/openhab2/userdata/cache/org.eclipse.osgi/181/0/bundleFile
        at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:305)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.basicOpen(ZipBundleFile.java:85)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getZipFile(ZipBundleFile.java:98)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.checkedOpen(ZipBundleFile.java:65)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getEntry(ZipBundleFile.java:232)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:562)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:540)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:527)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:320)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:395)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_111]
        at io.socket.engineio.client.Socket$15.run(Socket.java:568)[181:org.openhab.io.openhabcloud:2.0.0.201612180944]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
Caused by: java.io.FileNotFoundException: /opt/openhab2/userdata/cache/org.eclipse.osgi/181/0/bundleFile (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)[:1.8.0_111]
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)[:1.8.0_111]
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)[:1.8.0_111]
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)[:1.8.0_111]
        at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:288)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        ... 22 more
```

**Comment by Marty56** [comment]
Same here. 
When I have to do an update of OH2 and using the online version and starting the new installation the first time, my log is full of error messages which seems to root from timing issues installing and accessing for example the persistence service.
Normally after 15 Minutes I have to stop OH2 again and then do another restart which is then working normally.
But also in this case I still get sometimes xslt or also persistence errors.

I have the impression that the start of  rule execution and service installation are not really synchronized and this behavior is more or less happening randomly.

**Comment by kaikreuzer** [comment]
@MHerbst I also see these messages after a first start after having upgraded to a more recent snapshot. This is imho not related to openhabcloud nor to any other specific add-on.

If you can confirm this is the same for you, I'd suggest to continue on https://github.com/openhab/openhab-distro/issues/299, which isn't yet solved (i.e. we do not really have a working upgrade mechanism in place yet).

**Comment by MHerbst** [comment]
@kaikreuzer You are most likely right that it is not specific to openhabcloud, but with the installation of openhablcloud it was possible to reproduce it easier then with other addons.

It is different from https://github.com/openhab/openhab-distro/issues/299 because I did a complete fresh installation. I completely removed an old instalallation, unzipped the online version zip of the latest build and started openHAB. After the initialization of Paper UI I went to the add-ons section and selected openhabcloud and the REST API documentation addons and both were installed at the same time. As far as I can see this problem occurs if two or more installations are done at the same time (especially on a slow machine like the Raspberry).

**Comment by kaikreuzer** [comment]
Thanks for your analysis @MHerbst! This sounds indeed as if the Karaf feature installer is not thread safe.

I actually have [this work](https://github.com/openhab/openhab-core/commit/2c80b88a82fadcc789b7d762050412a85400800b) pending since September - it is a new feature in Karaf that allows to install several features in one go, I would hope that this helps for this issue. Unfortunately all past Karaf versions were broken and only today Karaf 4.0.8 has been released, where this can be finally used. So I might have a try with that.

**Comment by MHerbst** [comment]
Sounds good. I can then test it again.

**Comment by kaikreuzer** [comment]
Please test with the next distro - I have upgraded to Karaf 4.0.8. The new bulk feature installation seems to be much, much faster as well :-)

**Comment by MHerbst** [comment]
@kaikreuzer I tried it with a fresh installation on my Raspi and on Windows 10 and I could no longer reproduce the problems with parallel installation. :-)

Only one thing in the logs looks a bit strange (but does not really seem to be problem). Each time a new add-on is installed the messages about the installation of "ui-habpanel" and "ui-paper" (or "ui-basic" are repeated:
``` 
15:31:16.163 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-basic' has been installed.
15:31:16.165 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-habpanel' has been installed.
15:31:16.167 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-paper' has been installed.
15:32:08.942 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-basic' has been installed.
15:32:08.944 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'misc-openhabcloud' has been installed.
15:32:08.945 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-habpanel' has been installed.
15:32:08.987 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-paper' has been installed.
15:32:09.587 [ERROR] [io.openhabcloud.internal.CloudClient] - Socket.IO error: not authorized
15:32:26.549 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-basic' has been installed.
15:32:26.552 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'misc-openhabcloud' has been installed.
15:32:26.555 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'misc-restdocs' has been installed.
15:32:26.559 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-habpanel' has been installed.
15:32:26.561 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-paper' has been installed.
15:32:56.889 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-basic' has been installed.
15:32:56.892 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'misc-openhabcloud' has been installed.
15:32:56.894 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'misc-restdocs' has been installed.
15:32:56.897 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'binding-homematic' has been installed.
15:32:56.900 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-habpanel' has been installed.
15:32:56.903 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-paper' has been installed.
15:33:10.259 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'binding-yahooweather' has been installed.
15:33:10.262 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-basic' has been installed.
15:33:10.263 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'misc-openhabcloud' has been installed.
15:33:10.265 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'misc-restdocs' has been installed.
15:33:10.275 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'binding-homematic' has been installed.
15:33:10.277 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-habpanel' has been installed.
15:33:10.280 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-paper' has been installed.
```

**Comment by kaikreuzer** [comment]
Thanks for testing @MHerbst - glad it seems to be solved.

Regarding the "installed messages": Funny, I was just fixing it in this minute: https://github.com/openhab/openhab-core/pull/100

**Comment by MHerbst** [comment]
With the latest build (672) I no longer see the duplicate messages and everything works fine (tested on Raspi and Windows). So I close this issue.

**Comment by papadi** [comment]
So the solution to this problem is to upgrade Karaf to 4.0.8? How can I do that on Synology?

**Comment by kaikreuzer** [comment]
@papadi Use the official 2.0.0 release for Synology, this uses Karaf 4.0.8.

**Comment by papadi** [comment]
Well, that's what I'm using already.
