### ISSUE TITLE
XBMC 1.9.0.b4 -  Unexpected problem updating configuration org.openhab.xbmc

### ISSUE THREAD

**Issue by littlej956** [openhab/openhab2-addons#1607]
This binding used to work on my Kodi 16 - Libreelec box, but now i get this error : 

`19:24:46.105 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=364, bundle=200/mvn:org.openhab.binding/org.openhab.binding.xbmc/1.9.0.b4]: Unexpected problem updating configuration org.openhab.xbmc
java.lang.ArrayIndexOutOfBoundsException: 1
        at org.openhab.binding.xbmc.internal.XbmcActiveBinding.updated(XbmcActiveBinding.java:410)[200:org.openhab.binding.xbmc:1.9.0.b4]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
`

this is my service config :

`livingRoom.host=192.168.1.171

# Port number for the json rpc service (optional, defaults to 8080)
livingRoom.rsPort=8080

# Port number for the web socket service (optional, defaults to 9090)
livingRoom.wsPort=9090

# Username to connect to XBMC. (optional, defaults to xbmc)
livingRoom.username=xbmc

# Password to connect to XBMC. (optional, defaults to xbmc)
livingRoom.password=password

#(ONLY FROM V1.9 onwards)
# Refresh interval. Global setting. (optional, defaults to 60000ms = 1 minute)
refreshInterval=60000
`

 i can confirm controlling kodi via json-rpc api works :
check this forum post also : https://community.openhab.org/t/xbmc-binding-error-no-xbmc-connector-found/16904/3

**Comment by watou** [comment]
Sorry to have to direct you to the openhab/openhab repo where this binding exists.  Please open this issue there and thank you.
