### ISSUE TITLE
[Homematic] Initialization problems after fresh install (Build 674)

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#1613]
I have installed the online version of openHAB on Windows 10. Then I installed the Homematic add-on and wanted to start a discovery. But no things were discovered and this error message appeared on the console:

```
13:36:23.767 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'homematic:bridge:hm' changed from INITIALIZING to ONLINE
13:36:54.363 [ERROR] [very.HomematicDeviceDiscoveryService] - Could not initialize class org.openhab.binding.homematic.type.MetadataUtils
java.lang.NoClassDefFoundError: Could not initialize class org.openhab.binding.homematic.type.MetadataUtils
        at org.openhab.binding.homematic.type.HomematicTypeGeneratorImpl.createChannelType(HomematicTypeGeneratorImpl.java:232)[180:org.openhab.binding.homematic:2.0.0.201612251526]
        at org.openhab.binding.homematic.type.HomematicTypeGeneratorImpl.generate(HomematicTypeGeneratorImpl.java:129)[180:org.openhab.binding.homematic:2.0.0.201612251526]
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.onDeviceLoaded(HomematicBridgeHandler.java:285)[180:org.openhab.binding.homematic:2.0.0.201612251526]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadAllDeviceMetadata(AbstractHomematicGateway.java:400)[180:org.openhab.binding.homematic:2.0.0.201612251526]
        at org.openhab.binding.homematic.discovery.HomematicDeviceDiscoveryService$1.run(HomematicDeviceDiscoveryService.java:108)[180:org.openhab.binding.homematic:2.0.0.201612251526]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_102]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_102]
```
After a restart of openHAB everything worked fine.

I can remember that I have already seen this problem sometimes in the past but I was never able to reproduce it reliably. Because this problem only occurs directly after the installation of the Homematic add-on I assume that it is some kind of timing issue and that the static initializer in MetadataUtils fails while trying to read the bundles.

**Comment by Alex-Witkowski** [comment]
Same here.. 
Fresh openHABian installation. 
```
21:57:21.487 [ERROR] [very.HomematicDeviceDiscoveryService] - Could not initialize class org.openhab.binding.homematic.type.MetadataUtils
java.lang.NoClassDefFoundError: Could not initialize class org.openhab.binding.homematic.type.MetadataUtils
        at org.openhab.binding.homematic.type.HomematicTypeGeneratorImpl.createChannelType(HomematicTypeGeneratorImpl.java:232)[180:org.openhab.binding.homematic:2.0.0.201701021217]
        at org.openhab.binding.homematic.type.HomematicTypeGeneratorImpl.generate(HomematicTypeGeneratorImpl.java:129)[180:org.openhab.binding.homematic:2.0.0.201701021217]
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.onDeviceLoaded(HomematicBridgeHandler.java:285)[180:org.openhab.binding.homematic:2.0.0.201701021217]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadAllDeviceMetadata(AbstractHomematicGateway.java:400)[180:org.openhab.binding.homematic:2.0.0.201701021217]
        at org.openhab.binding.homematic.discovery.HomematicDeviceDiscoveryService$1.run(HomematicDeviceDiscoveryService.java:108)[180:org.openhab.binding.homematic:2.0.0.201701021217]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

**Comment by MHerbst** [comment]
Ping @gerrieg

**Comment by Alex-Witkowski** [comment]
After reboot a lot of things came in. Will observe it.

**Comment by gerrieg** [comment]
I think this is a issue of the core framework not properly loading the binding. What exact version do you use?

**Comment by MHerbst** [comment]
I retestet it with build 699 and the problem did not appear. Maybe it is solved somehow now. But because I was not able to reproduce it reliably I am not sure. Maybe @Alex-Witkowski  can do a retest with a newer openHABian version.

**Comment by MHerbst** [comment]
@gerrieg Unfortunately the problem is not gone. I made a test with the OH 2 release version and the same error occured. Maybe a timing issue because I only could see it on my (rather fast) Windows 10 PC and not on the Raspberry.

**Comment by gerrieg** [comment]
@kaikreuzer any idea?

**Comment by kaikreuzer** [comment]
Asking [Stackoverflow](http://stackoverflow.com/a/7325829):

There is most likely an exception being thrown in the static{} section of MetadataUtils.

**Comment by kaikreuzer** [comment]
Btw, looking at the code, it seems the InputStream of loadStandardDatapoints() is never closed - you might want to use a try-with-resources there.

**Comment by gerrieg** [comment]
Changed resource file loading with https://github.com/openhab/openhab2-addons/pull/1622, hope it helps

**Comment by MHerbst** [comment]
I have tried with #1622 to reproduce it, but until now without success :-). Therefore closed. Will reopen it if necessary.
