### ISSUE TITLE
[RFXCOM] binding error when reloading things file

### ISSUE THREAD

**Issue by rtvb** [openhab/openhab2-addons#1650]
Running latest snapshot on RPi, with apt-get install

On startup of service, things file loads perfectly. When I edit the file and save it, I get an error (see below)

demo.things
```
Bridge rfxcom:bridge:1 [ serialPort="/dev/ttyUSB1" ] {
	Thing lighting2 remote1_1 [deviceId="12260194.1", subType="AC"]
	Thing lighting2 remote1_2 [deviceId="12260194.2", subType="AC"]
	Thing lighting2 remote1_3 [deviceId="12260194.3", subType="AC"]
	Thing lighting2 remote1_0 [deviceId="12260194.0", subType="AC"]
}
```

openhab.log
```
2017-01-03 11:00:18.413 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'demo.things'
2017-01-03 11:00:23.551 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling thing updated at ThingHandler 'org.openhab.binding.rfxcom.handler.RFXComBridgeHandler@afa67c': null
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)[:1.8.0_111]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:188)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:81)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:65)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:518)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:227)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:150)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:167)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$4(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:923)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModelForThingHandlerFactory(GenericThingProvider.java:933)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$1(GenericThingProvider.java:887)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:228)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:231)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.config.core.BundleProcessorVetoManager.applyActionFor(BundleProcessorVetoManager.java:121)[92:org.eclipse.smarthome.config.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:302)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModel(GenericThingProvider.java:305)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.modelChanged(GenericThingProvider.java:825)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:120)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:270)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.access$1(FolderObserver.java:264)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$WatchQueueReader.processWatchEvent(FolderObserver.java:145)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(AbstractWatchQueueReader.java:122)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
2017-01-03 11:00:23.585 [ERROR] [ore.thing.internal.ThingRegistryImpl] - Could not inform the ThingTracker 'org.eclipse.smarthome.core.thing.internal.ThingManager@19c0d3f' about the 'THING_UPDATED' event!
java.lang.NullPointerException
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:542)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:227)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:150)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:167)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$4(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:923)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModelForThingHandlerFactory(GenericThingProvider.java:933)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$1(GenericThingProvider.java:887)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:228)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:231)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.config.core.BundleProcessorVetoManager.applyActionFor(BundleProcessorVetoManager.java:121)[92:org.eclipse.smarthome.config.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:302)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModel(GenericThingProvider.java:305)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.modelChanged(GenericThingProvider.java:825)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:120)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:270)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.access$1(FolderObserver.java:264)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$WatchQueueReader.processWatchEvent(FolderObserver.java:145)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(AbstractWatchQueueReader.java:122)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
2017-01-03 11:00:23.610 [ERROR] [ore.thing.internal.ThingRegistryImpl] - Could not inform the ThingTracker 'org.eclipse.smarthome.core.thing.internal.ThingManager@19c0d3f' about the 'THING_UPDATED' event!
java.lang.NullPointerException
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:542)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:227)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:150)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:167)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$4(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:923)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModelForThingHandlerFactory(GenericThingProvider.java:933)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$1(GenericThingProvider.java:887)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:228)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:231)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.config.core.BundleProcessorVetoManager.applyActionFor(BundleProcessorVetoManager.java:121)[92:org.eclipse.smarthome.config.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:302)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModel(GenericThingProvider.java:305)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.modelChanged(GenericThingProvider.java:825)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:120)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:270)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.access$1(FolderObserver.java:264)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$WatchQueueReader.processWatchEvent(FolderObserver.java:145)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(AbstractWatchQueueReader.java:122)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
2017-01-03 11:00:24.652 [ERROR] [ore.thing.internal.ThingRegistryImpl] - Could not inform the ThingTracker 'org.eclipse.smarthome.core.thing.internal.ThingManager@19c0d3f' about the 'THING_UPDATED' event!
java.lang.NullPointerException
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:542)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:227)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:150)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:167)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$4(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:923)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModelForThingHandlerFactory(GenericThingProvider.java:933)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$1(GenericThingProvider.java:887)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:228)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:231)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.config.core.BundleProcessorVetoManager.applyActionFor(BundleProcessorVetoManager.java:121)[92:org.eclipse.smarthome.config.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:302)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModel(GenericThingProvider.java:305)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.modelChanged(GenericThingProvider.java:825)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:120)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:270)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.access$1(FolderObserver.java:264)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$WatchQueueReader.processWatchEvent(FolderObserver.java:145)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(AbstractWatchQueueReader.java:122)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
2017-01-03 11:00:24.697 [ERROR] [ore.thing.internal.ThingRegistryImpl] - Could not inform the ThingTracker 'org.eclipse.smarthome.core.thing.internal.ThingManager@19c0d3f' about the 'THING_UPDATED' event!
java.lang.NullPointerException
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:542)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:227)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:150)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:167)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$4(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:923)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModelForThingHandlerFactory(GenericThingProvider.java:933)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$1(GenericThingProvider.java:887)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:228)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:231)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.config.core.BundleProcessorVetoManager.applyActionFor(BundleProcessorVetoManager.java:121)[92:org.eclipse.smarthome.config.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:302)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$6.apply(GenericThingProvider.java:1)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[144:org.eclipse.xtext.xbase.lib:2.9.2]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModel(GenericThingProvider.java:305)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.modelChanged(GenericThingProvider.java:825)[131:org.eclipse.smarthome.model.thing:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:120)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:270)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.access$1(FolderObserver.java:264)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$WatchQueueReader.processWatchEvent(FolderObserver.java:145)[120:org.eclipse.smarthome.model.core:0.9.0.201612221226]
	at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(AbstractWatchQueueReader.java:122)[96:org.eclipse.smarthome.core:0.9.0.201612221226]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
```

**Comment by kaikreuzer** [comment]
As the stacktrace is not at all about RFXCOM, I suspect that is a bug in the framework itself.
May I ask you to enter this issue at https://github.com/eclipse/smarthome/issues? Thanks!
