### ISSUE TITLE
[HomeKit] breaks when tagging Color item for milight rgbw bulb

### ISSUE THREAD

**Issue by buzink** [openhab/openhab2-addons#1651]
Homekit works fine for most of my lights and switches, but whenever I add the lighting tag to a color item, the homekit app reports that the openhab bridge is unavailable. When I remove the tag, the bridge becomes available again.

This is the item that breaks the homekit binding:

`Color Light_GF_Living_Ceiling_ColorPick "Living Ceiling Color" (gMilight,All,gLight_GF_Living_Ceiling) [ "Lighting" ] { milight="living;7;rgb" }`

These items are for the same bulb and work fine with homekit (when I tag one at a time):

```
Switch Light_GF_Living_Ceiling "Living Ceiling" (gSwitches,gLights_GF_Living,All,gLight_GF_Living_Ceiling) { milight="living;7" }
Dimmer Light_GF_Living_Ceiling_Brightness "Living Ceiling Brightness" (gMilight,All,gLight_GF_Living_Ceiling) { milight="living;7;brightness" }
```

@beowulfe

**Comment by beowulfe** [comment]
@planbnet added the support for Color Items - he may have some idea

**Comment by planbnet** [comment]
There probably is an error and/or stacktrace in the logs. Can you please paste this here?

**Comment by buzink** [comment]
Thanks for looking in to this. About 20 seconds after tagging the color item instead of the brightness item, I get this:

```
14:38:34.627 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
	at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
14:38:56.635 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
	at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
```

After trying to turn on a light in the Home app, it starts saying 'No Response' and the log says:

```
14:39:49.667 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
	at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
14:39:51.919 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
	at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
14:39:54.014 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:bridge:ACCF239E343C' changed from ONLINE to OFFLINE
14:39:54.024 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:8' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
14:39:54.025 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:9' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
14:39:54.033 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:10' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
14:39:54.039 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:6' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
14:39:54.046 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:7' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
14:41:51.289 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:bridge:ACCF239E343C' changed from OFFLINE to ONLINE
14:41:51.295 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:10' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
14:41:51.300 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:8' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
14:41:51.301 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:9' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
14:41:51.306 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:7' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
14:41:51.308 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'milight:rgbLed:ACCF239E343C:6' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
14:42:48.965 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
	at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
14:42:53.410 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
	at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
14:42:58.644 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
	at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
14:45:14.313 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
	at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[218:org.openhab.io.homekit:2.0.0.201612291742]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
```

**Comment by semaf** [comment]
Any news about this bug?

**Comment by curryking1607** [comment]
Having the same issue, any news?

**Comment by planbnet** [comment]
From what I can see, this seems to be caused by a bug in the HAP-Java library that was fixed a long time ago: https://github.com/beowulfe/HAP-Java/commit/4e05b2574221f6c7dc4148e6cb8d7441dc5c4115 (see FloatCharacteristic.java, Line 72)
Maybe the HomeKit Binding just needs to be updated to use a newer version?

**Comment by dsundberg** [comment]
Stumbled upon this same bug trying to add a color lightbulb. I think the problem lies in that the value of the color is not set the first time HomeKit reads it. Setting a value in the openhab console e.g. smarthome:send MyColorItem 1, seems to resolve it. I also believe that the cause of the crash is that getHue and getSaturation in the ColorfulLightbulb returns a raw null instead of a CompletableFuture of null. Might be an easy fix but my system is not setup for development at the moment so I can't test it. Will try to sort it by the weekend unless @planbnet beats me to it =)

**Comment by planbnet** [comment]
Great - thank you for solving this @dsundberg !

**Comment by fundix** [comment]
same problem ... implementation of homekit in OpenHab have possible only 1 subscription. Maybe this is problem?
