### ISSUE TITLE
MQTT binding install gives error and breaks system

### ISSUE THREAD

**Issue by basovink** [openhab/openhab2-addons#1725]
I installed the MQTT add on through the paper UI. The terminal showed errors (see below) and after restart the paper UI doesn't come up anymore. Deep links to some of the other UI's still work.

```
Exception in thread "nioEventLoopGroup-2-1" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.DefaultPromise$2 cannot be found by org.openhab.io.homekit_2.0.0.201612251526
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
Exception in thread "nioEventLoopGroup-3-11" Exception in thread "nioEventLoopGroup-2-16" Exception in thread "nioEventLoopGroup-3-12" Exception in thread "nioEventLoopGroup-2-2" Exception in thread "nioEventLoopGroup-3-13" Exception in thread "nioEventLoopGroup-3-9" Exception in thread "nioEventLoopGroup-3-6" Exception in thread "nioEventLoopGroup-3-14" Exception in thread "nioEventLoopGroup-3-8" Exception in thread "nioEventLoopGroup-3-7" Exception in thread "nioEventLoopGroup-3-5" Exception in thread "nioEventLoopGroup-3-10" Exception in thread "nioEventLoopGroup-3-4" Exception in thread "nioEventLoopGroup-3-15" Exception in thread "nioEventLoopGroup-2-12" Exception in thread "nioEventLoopGroup-2-13" Exception in thread "nioEventLoopGroup-2-10" Exception in thread "nioEventLoopGroup-2-14" Exception in thread "nioEventLoopGroup-2-11" Exception in thread "nioEventLoopGroup-2-7" Exception in thread "nioEventLoopGroup-2-8" Exception in thread "nioEventLoopGroup-2-9" Exception in thread "nioEventLoopGroup-2-4" Exception in thread "nioEventLoopGroup-2-6" Exception in thread "nioEventLoopGroup-3-16" Exception in thread "nioEventLoopGroup-3-1" Exception in thread "nioEventLoopGroup-2-5" Exception in thread "nioEventLoopGroup-3-2" Exception in thread "nioEventLoopGroup-3-3" Exception in thread "nioEventLoopGroup-2-3" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
Exception in thread "nioEventLoopGroup-2-15" 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

@martinvw *edit*: put exception in code block

**Comment by wborn** [comment]
If this is still an issue please report this in the openhab1-addons [issue tracker](https://github.com/openhab/openhab1-addons/issues). You could also give the new MQTT addon a try that was released with openHAB 2.4.0 last monday. There's also a nice [blog post](https://www.openhab.org/blog/2018-12-16-mqtt-arrives-in-the-modern-openhab-2-x-architecture.html) about the new MQTT addon.
