### ISSUE TITLE
Startup error on ARM (karaf)

### ISSUE THREAD

**Issue by fivetide** [openhab/openhab2-addons#1793]
I am trying to run OpenHAB2 from the Syno-package (2.1.0.001-SNAPSHOT-DSM6 currently, but the same issue for other 2.* packages exists) on my DS214.
I followed the guide on (http://docs.openhab.org/installation/synology.html), then set the whole userdata folder read and writeable. 
```
2017-01-29 12:03:42.787 [SEVERE] [org.apache.karaf.main.Main] - Could not launch framework
java.lang.ArrayIndexOutOfBoundsException: 0
	at sun.nio.cs.UTF_8$Decoder.decode(UTF_8.java:441)
	at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:153)
	at java.lang.StringCoding.decode(StringCoding.java:193)
	at java.lang.String.<init>(String.java:426)
	at java.lang.String.<init>(String.java:491)
	at sun.security.x509.AVA.toRFC2253CanonicalString(AVA.java:909)
	at sun.security.x509.RDN.toRFC2253StringInternal(RDN.java:443)
	at sun.security.x509.RDN.toRFC2253String(RDN.java:423)
	at sun.security.x509.X500Name.getRFC2253CanonicalName(X500Name.java:729)
	at sun.security.x509.X500Name.equals(X500Name.java:415)
	at sun.security.pkcs.SignerInfo.getCertificateChain(SignerInfo.java:274)
	at sun.security.pkcs.SignerInfo.getTimestamp(SignerInfo.java:557)
	at sun.security.util.SignatureFileVerifier.getSigners(SignatureFileVerifier.java:559)
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:300)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:162)
	at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:238)
	at org.apache.karaf.main.Main.loadFrameworkFactory(Main.java:425)
	at org.apache.karaf.main.Main.launch(Main.java:252)
	at org.apache.karaf.main.Main.main(Main.java:177)
```

``` 
cat /proc/cpuinfo 
Processor	: Marvell PJ4Bv7 Processor rev 2 (v7l)

java -version
java version "1.8.0_121"
Java(TM) SE Embedded Runtime Environment (build 1.8.0_121-b13, headless)
Java HotSpot(TM) Embedded Client VM (build 25.121-b13, mixed mode)

```

**Comment by fivetide** [comment]
Sorry, wrong repo, will reopen in the appropiate one.
