### ISSUE TITLE
After upgrading to 2.0.0 Realease no new Add-ons can be installed

### ISSUE THREAD

**Issue by Pirx99** [openhab/openhab2-addons#1804]
I'm using MacOS X 10.11.6 and the newest OH2 release.

When trying to install in Paper UI additional packeges like EXEC-Biding or Mail-Action or Telgram-Action the following massage appears in the log:
`12:58:04.566 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-action-telegram, openhab-binding-exec, openhab-action-mail': Error`

Here is more prices warning when installing Exec-Binding:
```
12:58:04.554 [WARN ] [url.mvn.internal.AetherBasedResolver] - Error resolving artifact org.openhab.binding:org.openhab.binding.exec:jar:2.0.0-SNAPSHOT: [Could not find artifact org.openhab.binding:org.openhab.binding.exec:jar:2.0.0-SNAPSHOT in openhab (https://dl.bintray.com/openhab/mvn/online-repo/2.0/)]
java.io.IOException: Error resolving artifact org.openhab.binding:org.openhab.binding.exec:jar:2.0.0-SNAPSHOT: [Could not find artifact org.openhab.binding:org.openhab.binding.exec:jar:2.0.0-SNAPSHOT in openhab (https://dl.bintray.com/openhab/mvn/online-repo/2.0/)]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:720)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567)[7:org.ops4j.pax.url.mvn:2.5.2]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:36)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)[8:org.apache.karaf.features.core:4.0.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_112]
Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.openhab.binding:org.openhab.binding.exec:jar:2.0.0-SNAPSHOT
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705)[7:org.ops4j.pax.url.mvn:2.5.2]
	... 12 more
```

It seams that I need to upgrade a file which contains correct binding information. I.e. the process is trying to download "2.0.0-SNAPSHOT" which doesnt exist anymore. Instead "2.0.0" should be used.
Can you tell which file is it?

**Comment by kaikreuzer** [comment]
This is not an issue about any openHAB 2 add-on (and that's what the issue tracker is for).
It looks to me like a messed up installation after upgrading. Please ask for help in our forum at https://community.openhab.org/.
