### ISSUE TITLE
[Astro] Unable to store Job

### ISSUE THREAD

**Issue by sjka** [openhab/openhab2-addons#1808]
On a clean OH2 2.1.0-SNAPSHOT startup, the astro binding logged some trouble scheduling jobs:

```
2017-01-30 17:33:05.914 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2017-01-30 17:33:09.931 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'sjka.sitemap'
2017-01-30 17:33:10.766 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'sjka.things'
2017-01-30 17:33:11.180 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'sjka.items'
2017-01-30 17:33:11.478 [ERROR] [arthome.core.items.dto.ItemDTOMapper] - Group function 'AND' requires two arguments. Using Equality instead.
2017-01-30 17:33:11.483 [ERROR] [arthome.core.items.dto.ItemDTOMapper] - Group function 'AND' requires two arguments. Using Equality instead.
2017-01-30 17:33:12.175 [ERROR] [arthome.core.items.dto.ItemDTOMapper] - Group function 'AND' requires two arguments. Using Equality instead.
2017-01-30 17:33:12.176 [ERROR] [arthome.core.items.dto.ItemDTOMapper] - Group function 'AND' requires two arguments. Using Equality instead.
2017-01-30 17:33:18.721 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-01-30 17:33:18.974 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2017-01-30 17:33:22.074 [INFO ] [ding.astro.handler.AstroThingHandler] - Scheduled astro job-daily-sun at midnight for thing astro:sun:gdhsn
2017-01-30 17:33:22.080 [INFO ] [ding.astro.handler.AstroThingHandler] - Scheduled astro job-positional with interval of 10 seconds for thing astro:sun:gdhsn
2017-01-30 17:33:22.085 [INFO ] [ding.astro.handler.AstroThingHandler] - Scheduled astro job-daily-sun at midnight for thing astro:sun:gdhsn
2017-01-30 17:33:22.086 [INFO ] [ding.astro.handler.AstroThingHandler] - Scheduled astro job-positional with interval of 10 seconds for thing astro:sun:gdhsn
2017-01-30 17:33:22.087 [INFO ] [ding.astro.handler.AstroThingHandler] - Scheduled astro job-daily-moon at midnight for thing astro:moon:gdhsn
2017-01-30 17:33:22.215 [ERROR] [.astro.internal.job.AbstractDailyJob] - Unable to store Job : 'astro:sun:gdhsn.job-event-start-night#event', because one already exists with this identification.
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'astro:sun:gdhsn.job-event-start-night#event', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:886)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.schedule(AbstractDailyJob.java:92)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleEvent(AbstractDailyJob.java:69)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleRange(AbstractDailyJob.java:57)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.DailyJobSun.schedulePlanetEvents(DailyJobSun.java:34)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.executeJob(AbstractDailyJob.java:46)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
2017-01-30 17:33:22.245 [ERROR] [.astro.internal.job.AbstractDailyJob] - Unable to store Job : 'astro:sun:gdhsn.job-event-start-astroDusk#event', because one already exists with this identification.
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'astro:sun:gdhsn.job-event-start-astroDusk#event', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:886)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.schedule(AbstractDailyJob.java:92)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleEvent(AbstractDailyJob.java:69)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleRange(AbstractDailyJob.java:57)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.DailyJobSun.schedulePlanetEvents(DailyJobSun.java:39)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.executeJob(AbstractDailyJob.java:46)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
2017-01-30 17:33:22.251 [INFO ] [.astro.internal.job.AbstractDailyJob] - Scheduled astro event-jobs for thing astro:sun:gdhsn
2017-01-30 17:33:22.253 [ERROR] [.astro.internal.job.AbstractDailyJob] - Unable to store Job : 'astro:sun:gdhsn.job-event-end-astroDusk#event', because one already exists with this identification.
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'astro:sun:gdhsn.job-event-end-astroDusk#event', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:886)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.schedule(AbstractDailyJob.java:92)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleEvent(AbstractDailyJob.java:69)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleRange(AbstractDailyJob.java:58)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.DailyJobSun.schedulePlanetEvents(DailyJobSun.java:39)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.executeJob(AbstractDailyJob.java:46)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
2017-01-30 17:33:22.256 [ERROR] [.astro.internal.job.AbstractDailyJob] - Unable to store Job : 'astro:sun:gdhsn.job-event-start-nauticDusk#event', because one already exists with this identification.
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'astro:sun:gdhsn.job-event-start-nauticDusk#event', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:886)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.schedule(AbstractDailyJob.java:92)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleEvent(AbstractDailyJob.java:69)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleRange(AbstractDailyJob.java:57)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.DailyJobSun.schedulePlanetEvents(DailyJobSun.java:40)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.executeJob(AbstractDailyJob.java:46)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
2017-01-30 17:33:22.261 [ERROR] [.astro.internal.job.AbstractDailyJob] - Unable to store Job : 'astro:sun:gdhsn.job-event-end-nauticDusk#event', because one already exists with this identification.
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'astro:sun:gdhsn.job-event-end-nauticDusk#event', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:886)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.schedule(AbstractDailyJob.java:92)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleEvent(AbstractDailyJob.java:69)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleRange(AbstractDailyJob.java:58)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.DailyJobSun.schedulePlanetEvents(DailyJobSun.java:40)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.executeJob(AbstractDailyJob.java:46)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
2017-01-30 17:33:22.262 [ERROR] [.astro.internal.job.AbstractDailyJob] - Unable to store Job : 'astro:sun:gdhsn.job-event-end-civilDusk#event', because one already exists with this identification.
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'astro:sun:gdhsn.job-event-end-civilDusk#event', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:886)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.schedule(AbstractDailyJob.java:92)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleEvent(AbstractDailyJob.java:69)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleRange(AbstractDailyJob.java:58)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.DailyJobSun.schedulePlanetEvents(DailyJobSun.java:41)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.executeJob(AbstractDailyJob.java:46)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
2017-01-30 17:33:22.263 [ERROR] [.astro.internal.job.AbstractDailyJob] - Unable to store Job : 'astro:sun:gdhsn.job-event-start-eveningNight#event', because one already exists with this identification.
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'astro:sun:gdhsn.job-event-start-eveningNight#event', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:886)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.schedule(AbstractDailyJob.java:92)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleEvent(AbstractDailyJob.java:69)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.scheduleRange(AbstractDailyJob.java:57)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.DailyJobSun.schedulePlanetEvents(DailyJobSun.java:42)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractDailyJob.executeJob(AbstractDailyJob.java:46)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:39)[191:org.openhab.binding.astro:2.1.0.201701292153]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201701192225]
2017-01-30 17:33:22.267 [INFO ] [.astro.internal.job.AbstractDailyJob] - Scheduled astro event-jobs for thing astro:sun:gdhsn
2017-01-30 17:33:22.278 [INFO ] [.astro.internal.job.AbstractDailyJob] - Scheduled astro event-jobs for thing astro:moon:gdhsn
```

Eclipse SmartHome build 0.9.0.201701192225
openHAB2 Add-On build 2.1.0.201701292153

I'm aware of the fact that quartz will be replaced anyway soon, so I'd be okay to immediately close this again as "won't fix". However, I wanted to document it here so you may have a look if you think it makes sense.

**Comment by gnalbandian** [comment]
I am facing this issue as well in build #858

**Comment by martinvw** [comment]
The astro binding is now moved to Eclipse Smarthome, if needed please (re)open an issue there.

**Comment by wenchen123456** [comment]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scheduler' defined in class path resource [com/cloud/mihui/quartzConfig/QuartzConfig.class]: Invocation of init method failed; nested exception is org.quartz.ObjectAlreadyExistsException: Unable to store Trigger with name: 'sendBuySuceessMsgTrigger' and group: 'SendMsg', because one already exists with this identification.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
