### ISSUE TITLE
HomeMatic NullPointerException

### ISSUE THREAD

**Issue by solars** [openhab/openhab2-addons#1820]
Hi there,

I successfully used homegear with HM-LAN-CFG and Thermostate in openhab1 as a test. Then switched to openhab2. The bridge is recognized as a thing, the thermostate as well. All the configuration seems to be read correctly also.

However, I cannot seem to get any data out of it, and I noticed in the logs:

```
2017-02-02 07:49:03.725 [ERROR] [ternal.communicator.HomematicGateway] -
java.lang.NullPointerException
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.updateThing(HomematicBridgeHandler.java:221)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.onNewDevice(HomematicBridgeHandler.java:243)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.newDevices(AbstractHomematicGateway.java:609)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.internal.communicator.server.BinRpcCallbackHandler.handleNewDevice(BinRpcCallbackHandler.java:143)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.internal.communicator.server.BinRpcCallbackHandler.handleMethodCall(BinRpcCallbackHandler.java:90)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.internal.communicator.server.BinRpcCallbackHandler.run(BinRpcCallbackHandler.java:62)[184:org.openhab.binding.homematic:2.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
2017-02-02 07:51:05.808 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:0#RSSI_DEVICE'
2017-02-02 07:51:05.816 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#ACTUAL_TEMPERATURE'
2017-02-02 07:51:05.819 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BATTERY_STATE'
2017-02-02 07:51:05.822 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BOOST_STATE'
2017-02-02 07:51:05.825 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#CONTROL_MODE'
2017-02-02 07:51:05.827 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#FAULT_REPORTING'
2017-02-02 07:51:05.830 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#PARTY_START_TIME'
2017-02-02 07:51:05.833 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#SET_TEMPERATURE'
2017-02-02 07:51:05.835 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#VALVE_STATE'
2017-02-02 07:53:30.304 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:0#RSSI_DEVICE'
2017-02-02 07:53:30.310 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#ACTUAL_TEMPERATURE'
2017-02-02 07:53:30.313 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BATTERY_STATE'
2017-02-02 07:53:30.316 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BOOST_STATE'
2017-02-02 07:53:30.319 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#CONTROL_MODE'
2017-02-02 07:53:30.321 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#FAULT_REPORTING'
2017-02-02 07:53:30.324 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#PARTY_START_TIME'
2017-02-02 07:53:30.327 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#SET_TEMPERATURE'
2017-02-02 07:53:30.329 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#VALVE_STATE'
2017-02-02 07:55:40.305 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:0#RSSI_DEVICE'
2017-02-02 07:55:40.312 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#ACTUAL_TEMPERATURE'
2017-02-02 07:55:40.315 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BATTERY_STATE'
2017-02-02 07:55:40.323 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BOOST_STATE'
2017-02-02 07:55:40.329 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#CONTROL_MODE'
2017-02-02 07:55:40.335 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#FAULT_REPORTING'
2017-02-02 07:55:40.341 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#PARTY_START_TIME'
2017-02-02 07:55:40.347 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#SET_TEMPERATURE'
2017-02-02 07:55:40.350 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#VALVE_STATE'

```

Can anyone tell me what causes this or how I can debug it?

**Comment by MHerbst** [comment]
@solars This one looks similar to #1825 that you already closed. Can this also be closed?

**Comment by solars** [comment]
@MHerbst sorry I think I added it twice by mistake, it can be closed as well! Thanks for your reply!
