### ISSUE TITLE
Homematic: NullPointer and Channel not found for datapoint?

### ISSUE THREAD

**Issue by solars** [openhab/openhab2-addons#1825]
Hi there,

I successfully used homegear with HM-LAN-CFG and Thermostate in openhab1 as a test. Then switched to openhab2. The bridge is recognized as a thing, the thermostate as well. All the configuration seems to be read correctly also.

However, I cannot seem to get any data out of it, and I noticed in the logs:

```
2017-02-02 07:49:03.725 [ERROR] [ternal.communicator.HomematicGateway] -
java.lang.NullPointerException
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.updateThing(HomematicBridgeHandler.java:221)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.onNewDevice(HomematicBridgeHandler.java:243)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.newDevices(AbstractHomematicGateway.java:609)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.internal.communicator.server.BinRpcCallbackHandler.handleNewDevice(BinRpcCallbackHandler.java:143)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.internal.communicator.server.BinRpcCallbackHandler.handleMethodCall(BinRpcCallbackHandler.java:90)[184:org.openhab.binding.homematic:2.0.0]
        at org.openhab.binding.homematic.internal.communicator.server.BinRpcCallbackHandler.run(BinRpcCallbackHandler.java:62)[184:org.openhab.binding.homematic:2.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
2017-02-02 07:51:05.808 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:0#RSSI_DEVICE'
2017-02-02 07:51:05.816 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#ACTUAL_TEMPERATURE'
2017-02-02 07:51:05.819 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BATTERY_STATE'
2017-02-02 07:51:05.822 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BOOST_STATE'
2017-02-02 07:51:05.825 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#CONTROL_MODE'
2017-02-02 07:51:05.827 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#FAULT_REPORTING'
2017-02-02 07:51:05.830 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#PARTY_START_TIME'
2017-02-02 07:51:05.833 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#SET_TEMPERATURE'
2017-02-02 07:51:05.835 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#VALVE_STATE'
2017-02-02 07:53:30.304 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:0#RSSI_DEVICE'
2017-02-02 07:53:30.310 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#ACTUAL_TEMPERATURE'
2017-02-02 07:53:30.313 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BATTERY_STATE'
2017-02-02 07:53:30.316 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BOOST_STATE'
2017-02-02 07:53:30.319 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#CONTROL_MODE'
2017-02-02 07:53:30.321 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#FAULT_REPORTING'
2017-02-02 07:53:30.324 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#PARTY_START_TIME'
2017-02-02 07:53:30.327 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#SET_TEMPERATURE'
2017-02-02 07:53:30.329 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#VALVE_STATE'
2017-02-02 07:55:40.305 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:0#RSSI_DEVICE'
2017-02-02 07:55:40.312 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#ACTUAL_TEMPERATURE'
2017-02-02 07:55:40.315 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BATTERY_STATE'
2017-02-02 07:55:40.323 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#BOOST_STATE'
2017-02-02 07:55:40.329 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#CONTROL_MODE'
2017-02-02 07:55:40.335 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#FAULT_REPORTING'
2017-02-02 07:55:40.341 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#PARTY_START_TIME'
2017-02-02 07:55:40.347 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#SET_TEMPERATURE'
2017-02-02 07:55:40.350 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint 'LEQ0782160:4#VALVE_STATE'

```

Can anyone tell me what causes this or how I can debug it?

**Comment by solars** [comment]
Here is the complete log with debug: https://dl.dropboxusercontent.com/u/311345/openhab.log

**Comment by solars** [comment]
I've deleted the Thermostate (Thing) and re-added it - now the channels are there... weird.

**Comment by kohlsalem** [comment]
It looks like i have similar problem form my HMIP devices on CCU2 since the laste update of OH2 and CCU2 FW.

i get 

````
21:39:36.055 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000313C98CBC67:0#RSSI_DEVICE'
```
for all of my devices, HMIP-SWDO, HMIP-eTRV and HMIP-WTH.

Is the recommendation really to remove/rediscover, ot is there a fix to come?

Best
Michael

**Comment by awittenburg** [comment]
I have a similar problem with a HMIP-eTRV and deleting things+binding did not fix my problem. I use openhabian and a raspberrymatic. My non-IP homematic roller shutters are working.

`2017-02-20 13:10:19.655 [ERROR] [ternal.communicator.HomematicGateway] - 
java.lang.NullPointerException
	at org.openhab.binding.homematic.handler.HomematicBridgeHandler.updateThing(HomematicBridgeHandler.java:221)[197:org.openhab.binding.homematic:2.0.0]
	at org.openhab.binding.homematic.handler.HomematicBridgeHandler.onNewDevice(HomematicBridgeHandler.java:243)[197:org.openhab.binding.homematic:2.0.0]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.newDevices(AbstractHomematicGateway.java:609)[197:org.openhab.binding.homematic:2.0.0]
	at org.openhab.binding.homematic.internal.communicator.server.XmlRpcServer$ResponseHandler.handleNewDevice(XmlRpcServer.java:193)[197:org.openhab.binding.homematic:2.0.0]
	at org.openhab.binding.homematic.internal.communicator.server.XmlRpcServer$ResponseHandler.handleMethodCall(XmlRpcServer.java:140)[197:org.openhab.binding.homematic:2.0.0]
	at org.openhab.binding.homematic.internal.communicator.server.XmlRpcServer$ResponseHandler.handle(XmlRpcServer.java:116)[197:org.openhab.binding.homematic:2.0.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.Server.handle(Server.java:499)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[80:org.eclipse.jetty.server:9.2.19.v20160908]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[72:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[83:org.eclipse.jetty.util:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[83:org.eclipse.jetty.util:9.2.19.v20160908]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
`
and
`2017-02-20 13:19:15.672 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:0#UNREACH'
2017-02-20 13:19:15.673 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:0#RSSI_DEVICE'
2017-02-20 13:19:15.674 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:0#OPERATING_VOLTAGE'
2017-02-20 13:19:15.714 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#VALVE_STATE'
2017-02-20 13:19:15.714 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#SET_POINT_TEMPERATURE'
2017-02-20 13:19:15.716 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#PARTY_MODE'
2017-02-20 13:19:15.716 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#ACTIVE_PROFILE'
2017-02-20 13:19:15.717 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#WINDOW_STATE'
2017-02-20 13:19:15.718 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#FROST_PROTECTION'
2017-02-20 13:19:15.718 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#ACTUAL_TEMPERATURE'
2017-02-20 13:19:15.719 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#SET_POINT_MODE'
2017-02-20 13:19:15.720 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#BOOST_MODE'
2017-02-20 13:19:15.721 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#LEVEL'
2017-02-20 13:19:15.721 [WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint '000393C994DF30:1#SWITCH_POINT_OCCURED'
`
Before deleting I had the following message in my logfile:

Full log is attached.

t
[openhap.txt](https://github.com/openhab/openhab2-addons/files/787404/openhap.txt)

hx, andré
