### ISSUE TITLE
OH2 - RC1 - FrameworkEvent ERROR - org.openhab.binding.avmfritz

### ISSUE THREAD

**Issue by JoeRu** [openhab/openhab2-addons#1837]
Hi all,

i switched to RC1 and as @kaikreuzer said to post issues arround - i figure this one needs to be checked at least.

I am not really sure weather it is Binding related or core - But it's only comming with avmfritz-binding

```
2017-02-05 06:14:41.414 [ERROR] [org.openhab.binding.avmfritz        ] - FrameworkEvent ERROR - org.openhab.binding.avmfritz
java.io.IOException: Exception in opening zip file: /var/lib/openhab2/cache/org.eclipse.osgi/203/0/bundleFile
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:305)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.basicOpen(ZipBundleFile.java:85)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getZipFile(ZipBundleFile.java:98)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.checkedOpen(ZipBundleFile.java:65)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getEntry(ZipBundleFile.java:232)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.storage.bundlefile.BundleFile.getResourceURL(BundleFile.java:136)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findResourceImpl(ClasspathManager.java:420)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalResources(ClasspathManager.java:397)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalResources(ModuleClassLoader.java:320)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalResources(BundleLoader.java:813)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.internal.loader.BundleLoader.findResources(BundleLoader.java:674)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.getResources(ModuleClassLoader.java:230)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.internal.framework.ContextFinder.findResources(ContextFinder.java:165)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at java.lang.ClassLoader.getResources(ClassLoader.java:1139)[:1.8.0_65]
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)[:1.8.0_65]
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)[:1.8.0_65]
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)[:1.8.0_65]
	at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)[:1.8.0_65]
	at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_65]
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)[:1.8.0_65]
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)[:1.8.0_65]
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)[:1.8.0_65]
	at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:116)[:1.8.0_65]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139)[:1.8.0_65]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)[:1.8.0_65]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)[:1.8.0_65]
	at org.openhab.binding.avmfritz.internal.hardware.callbacks.FritzAhaDiscoveryCallback.execute(FritzAhaDiscoveryCallback.java:59)[203:org.openhab.binding.avmfritz:2.0.0.RC1]
	at org.openhab.binding.avmfritz.internal.hardware.FritzahaContentExchange.onComplete(FritzahaContentExchange.java:71)[203:org.openhab.binding.avmfritz:2.0.0.RC1]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:453)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:400)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:266)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1487)[71:org.eclipse.jetty.http:9.2.19.v20160908]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1245)[71:org.eclipse.jetty.http:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:156)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:117)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:89)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:123)[69:org.eclipse.jetty.client:9.2.19.v20160908]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[72:org.eclipse.jetty.io:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[83:org.eclipse.jetty.util:9.2.19.v20160908]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[83:org.eclipse.jetty.util:9.2.19.v20160908]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
Caused by: java.io.FileNotFoundException: /var/lib/openhab2/cache/org.eclipse.osgi/203/0/bundleFile (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)[:1.8.0_65]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)[:1.8.0_65]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)[:1.8.0_65]
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)[:1.8.0_65]
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:288)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	... 43 more
```

So just for checking.

**Comment by JoeRu** [comment]
ok. I think i found the problem. There were Things left - while i did remove the binding... still not really "intuitive" - the message.

**Comment by kaikreuzer** [comment]
This is likely a message that comes from upgrading your runtime as it is thrown from the depth of the OSGi framework - so definitely not related to any binding specifically.
