### ISSUE TITLE
[systeminfo] Throws ArrayIndexOutOfBoundsException during initialization

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#1884]
I see the below exception during initialization of the systeminfo binding.  This error prevents the binding from initializing.  This occurs on some versions of Ubuntu 16.04 (I see it on one system, but not on two other systems, probably due to config differences between those systems).

Running this version of the binding:

> 186 | Active    |  80 | 2.1.0.201702102300    | Systeminfo Binding                                     | org.openhab.binding.systeminfo

It looks like this issue was fixed in version 3.3 of the oshi library.  The systeminfo binding currently includes version 3.2.
https://github.com/oshi/oshi/commit/ae7529bd66dea4f7e8b8b011c9090e80f039c3cf

```

2017-02-11 17:39:43.920 [ERROR] [systeminfo.handler.SysteminfoHandler] - Can not instantate Systeminfo object!
java.lang.ArrayIndexOutOfBoundsException: 11
        at oshi.hardware.platform.linux.LinuxBlockDevStats.<init>(LinuxBlockDevStats.java:78)[186:org.openhab.binding.systeminfo:2.1.0.201702102300]
        at oshi.hardware.platform.linux.LinuxDisks.computeDiskStats(LinuxDisks.java:145)[186:org.openhab.binding.systeminfo:2.1.0.201702102300]
        at oshi.hardware.platform.linux.LinuxDisks.getDisks(LinuxDisks.java:93)[186:org.openhab.binding.systeminfo:2.1.0.201702102300]
        at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDiskStores(LinuxHardwareAbstractionLayer.java:70)[186:org.openhab.binding.systeminfo:2.1.0.201702102300]
        at org.openhab.binding.systeminfo.model.OshiSysteminfo.<init>(OshiSysteminfo.java:69)[186:org.openhab.binding.systeminfo:2.1.0.201702102300]
        at org.openhab.binding.systeminfo.handler.SysteminfoHandler.instantiateSysteminfoLibrary(SysteminfoHandler.java:112)[186:org.openhab.binding.systeminfo:2.1.0.201702102300]
        at org.openhab.binding.systeminfo.handler.SysteminfoHandler.initialize(SysteminfoHandler.java:98)[186:org.openhab.binding.systeminfo:2.1.0.201702102300]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:701)[105:org.eclipse.smarthome.core.thing:0.9.0.201702100936]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:1)[105:org.eclipse.smarthome.core.thing:0.9.0.201702100936]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[98:org.eclipse.smarthome.core:0.9.0.201702100936]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]


```

**Comment by mhilbush** [comment]
Wanted to confirm that this issue is resolved in build 858.  Thanks @svilenvul

**Comment by svilenvul** [comment]
Great news ! Sorry that it took too long.
