### ISSUE TITLE
[homekit] NPE in HomekitRegistry.getCharacteristics

### ISSUE THREAD

**Issue by Spybyte** [openhab/openhab2-addons#1950]
Hi,

I'm new to openhab, so maybe I have the wrong idea. I try to sync the variable from a ccu2 to openhab. To do it I defined a cron rule which sends a REFRESH to a ccu2 variable:

Excerpt from my items file:

```
String CCU_Reload    "CCU Reload Vars"  { channel="homematic:GATEWAY-EXTRAS-CCU:ccu:GWE00000000:1#ReloadEventVar" }
Switch Test          "Test"             { channel="homematic:GATEWAY-EXTRAS-CCU:ccu:GWE00000000:1#TestVar" }
```

Excerpt from my rules file:
```
rule "Test"
when 
	/* Seconds, Minutes, Hours, Day-of-Month, Month, Day-of-Week, Year (optional field)*/
	Time cron "0 * * ? * * *"
then
	logInfo("Test", "Rule executed...")
	CCU_Reload.send(RefreshType.REFRESH)
end
```

If I modify TestVar on the ccu2 and everything works, Test in openhab is update as expected. But unfortunately in most case I get a concurrent modification exception while running the cron job:
```
java.lang.NullPointerException
	at java.util.Collections$UnmodifiableMap.<init>(Collections.java:1446)[:1.8.0_112]
	at java.util.Collections.unmodifiableMap(Collections.java:1433)[:1.8.0_112]
	at com.beowulfe.hap.impl.HomekitRegistry.getCharacteristics(HomekitRegistry.java:75)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at com.beowulfe.hap.impl.json.CharacteristicsController.put(CharacteristicsController.java:70)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:75)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[186:org.openhab.io.homekit:2.1.0.201702121957]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_112]
```

What am I doing wrong?

Thanks,
Björn

**Comment by MHerbst** [comment]
The exeception occurs in a Homekit class so I suspect that it is a problem of the Homekit binding.

**Comment by martinvw** [comment]
Thanks, relabeled

**Comment by J-N-K** [comment]
Should be fixed with latest changes.
