### ISSUE TITLE
[Homekit] NPE wwhen pairing with iOS10

### ISSUE THREAD

**Issue by codefalk** [openhab/openhab2-addons#2002]
System is openHAB2 distro. Installed homekit via PaperUI and see "Extension 'misc-homekit' has been installed." in logfile. When pairing with iOS10 (iPhone) the following exception is been thrown:

`12:37:17.378 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
        at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[206:org.openhab.io.homekit:2
        at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[206:org.openhab.io.homekit:
        at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[206:org.openhab.io.homeki
        at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[206:org.openhab.io.homekit:2.0.0
        at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[206:org.openhab.io.homekit:2.0.0]
        at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[206:org.openhab.io.homekit:2.0.0]
        at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[206:org.openhab.io.homeki
        at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[206:org.openhab.io.homekit:2.0
        at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[206:org.openhab.io.homekit:2.0.0
        at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[206:org.openhab.io.homekit:2.0.
        at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[206:org.openhab.io.homekit:2.0.
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[206:org.openhab.io.homek
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[206:org.openha
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[206:org.openhab.io.hom
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[206:org.openhab.io.homekit
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[206:org.openhab.io.homekit:2.0.0]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[206:org.openhab.io.homekit
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[206:org.openh
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
`

homekit.cfg configured as following:
`org.openhab.homekit:port=9124
org.openhab.homekit:pin=031-45-154
org.openhab.homekit:useFahrenheitTemperature=false
org.openhab.homekit:thermostatCoolMode=CoolOn
org.openhab.homekit:thermostatHeatMode=HeatOn
org.openhab.homekit:thermostatAutoMode=Auto
org.openhab.homekit:thermostatOffMode=Off
org.openhab.homekit:networkInterface=192.168.17.3`

More than 50 items with Tag ["Lighting"] are configured in *.items file.

**Comment by codefalk** [comment]
Just found that this is a duplicate to [Issue #1810](https://github.com/openhab/openhab2-addons/issues/1810). Therefore this is closed.
