### ISSUE TITLE
homematic device (HG-HM-ES-PMSw1-Pl) reacts very slow - up to not reacting at all

### ISSUE THREAD

**Issue by jipp** [openhab/openhab2-addons#2010]
Hi

I have some Homematic devices running. For some I see that it reacts very slowly on commands (for one device it looks like permanently being so) - sometimes there are delays of several 10's sec, sometimes its not reacting at all, it also could be that switching 'on' is ok, but switching 'off' is not working.

Is this already a known issue?

The Log is shown at the end.

thanks
Jipp

2017-02-18 19:06:17.755 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@4eceac' takes more than 5000ms.
2017-02-18 19:06:17.764 [WARN ] [ome.core.thing.internal.ThingManager] - Handler for thing 'homematic:HG-HM-ES-PMSw1-Pl:scc:MEQ0272739' takes more than 5000ms for processing event
2017-02-18 19:06:17.887 [ERROR] [ematic.handler.HomematicThingHandler] - -100 No answer from device. (sending setValue()
MEQ0272739:1
STATE
false
)
java.io.IOException: -100 No answer from device. (sending setValue()
MEQ0272739:1
STATE
false
)
    at org.openhab.binding.homematic.internal.communicator.parser.RpcResponseParser.parse(RpcResponseParser.java:47)[183:org.openhab.binding.homematic:2.0.0]
    at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:91)[183:org.openhab.binding.homematic:2.0.0]
    at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:103)[183:org.openhab.binding.homematic:2.0.0]
    at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:79)[183:org.openhab.binding.homematic:2.0.0]
    at org.openhab.binding.homematic.internal.communicator.client.RpcClient.setDatapointValue(RpcClient.java:273)[183:org.openhab.binding.homematic:2.0.0]
    at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:539)[183:org.openhab.binding.homematic:2.0.0]
    at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:61)[183:org.openhab.binding.homematic:2.0.0]
    at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:518)[183:org.openhab.binding.homematic:2.0.0]
    at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:493)[183:org.openhab.binding.homematic:2.0.0]
    at org.openhab.binding.homematic.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:175)[183:org.openhab.binding.homematic:2.0.0]
    at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:372)[105:org.eclipse.smarthome.core.thing:0.9.0.b4]
    at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[105:org.eclipse.smarthome.core.thing:0.9.0.b4]
    at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[98:org.eclipse.smarthome.core:0.9.0.b4]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]

**Comment by MHerbst** [comment]
Did you try to restart the CCU? And did it help? I don't have exactly the same problem but it seems that that the CCU (or maybe only the WebUI) does not work correctly after about a week without restart.

**Comment by jipp** [comment]
I have a SCC from busware stacked on the gpio ports with external antenna.

In the meantime I did some more analysis:

I assume that "-100 No answer from device. " is referring to the signal strength. Got this idea after adding the RSSI info from the homematic devices into my config of the items and sitemap.

The RSSI is fluctuating and some times below -100 dBm.
It looks like that I got massive problems in reaction when the RSSI < -100 dBm.

To validate if the "java.io.IOException" is a known issue I upgraded to the latest snapshot. I think I did not see the exception anymore but still observed the problem in reaction and in addition I saw more "[WARN ] [ematic.handler.HomematicThingHandler] - Channel not found for datapoint" after some reboots. The general feeling of running a more unstable release made me downgrading to the 2.0.0 again. 

So to my opinion is that the problem is related to the RSSI < -100.
the java exception seems to be a different issue and hopefully fixed in the next release - when will it be released?

That the switch 'on' seems to work and the switch 'off' not - maybe its related that power 'on' generates more interferences which has a bigger impact when RSSI is already weak.

To further debug the problem I'm now playing around with the position of the antenna (antenna in the cellar, receiver on 1st floor) and thinking about adding a lan-gateway.

**Comment by jipp** [comment]
is there a description of how to replace a single binding with a snapshot and not the whole release?

**Comment by MHerbst** [comment]
There is a small chapter in the installation doc: http://docs.openhab.org/installation/linux.html#installing-add-ons

Another rather new option is the new IoT marketplace: https://community.openhab.org/t/distributing-bindings-through-the-iot-marketplace/24491 . But you won't find the Homematic add-on there yet.

**Comment by jipp** [comment]
including a small typo:
> Simply download the kar files

I will give it a try

thanks a lot for the hint

**Comment by jipp** [comment]
I found the following folders on Jessi - none in '/opt/openhab2/addons':

# find / -name addons
/usr/share/openhab2/addons
/usr/share/openhab2/runtime/system/org/openhab/distro/addons


copied the snapshot of the homematic in to the /usr/share/openhab2/addons folder.

'/usr/share/openhab2/runtime/system/org/openhab/distro/addons' shows a subfolder '2.0.0':
ls /usr/share/openhab2/runtime/system/org/openhab/distro/addons/2.0.0/
addons-2.0.0-features.xml


after a restart I saw the messages below and still using 2.0.0:

2017-03-12 12:36:23.464 [ERROR] [org.openhab.binding.homematic       ] - FrameworkEvent ERROR - org.openhab.binding.homematic
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.homematic [197]
  Another singleton bundle selected: osgi.identity; osgi.identity="org.openhab.binding.homematic"; type="osgi.bundle"; version:Version="2.0.0"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]

**Comment by MHerbst** [comment]
You can solve it by uninstalling the add-on in Paper UI. This will remove the default version. The add-ons stored in the addons folder are always automatically loaded.

**Comment by MHerbst** [comment]
> including a small typo:
> 
> Simply download the kar files

This is not really a typo. There is a kar file here https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ that contains all add-ons. The section describing the add-on folder is a bit short ...

**Comment by jipp** [comment]
I followed the following:

-download the latest snapshot:
wget https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.homematic/2.1.0-SNAPSHOT/org.openhab.binding.homematic-2.1.0-SNAPSHOT.jar

-deleted the installed add-on using paper UI
-restarting the openhab

during startup I saw the followin message:
2017-03-12 16:07:32.520 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-homematic': Error restarting bundles

as a result the 2.0.0 was installed again and snapshot was not activated.

**Comment by MHerbst** [comment]
Probably the 2.0 version is cached and therefore loaded instead of the downloaded version. I had a similar problem with another add-on. Need to check it on my Raspi tomorrow.

**Comment by MHerbst** [comment]
You can try it as follows:

1. Uninstall the add-on in Paper UI
1. Stop openHAB
1. Clean content of ./userdata/cache (don't know where it is exactly located in your environment, because I installed it manually).
1. Copy latest version of the add-on to userdata/addons
1. Restart openHAB

**Comment by jipp** [comment]
As an intermediate feedback:
-I placed a repeater in the network and this solved the reaction problems quite good so far.
-for replacing the 2.0.0 with the current snapshot I did not yet succeed and have to follow this up
