### ISSUE TITLE
[homekit] Pairing failed

### ISSUE THREAD

**Issue by baakoo** [openhab/openhab2-addons#2056]
Hi guys 

i try to get openHAB working. In PaperUI everything is fine and i also managed to create an items and sitemap config file. This works fine in Basic UI.

But i have Problems to pair openHAB with homekit. I managed once but no devices shown up and after i remove openhab an try to pair it again pairing failed. 

I hope I get the right part of the log file - what is marked as error is here:

```
13:23:29.045 [ERROR] [lfe.hap.impl.connections.HttpSession] - Excepton encountered while verifying pairing
java.lang.Exception: Unknown user: 067A750D-BC7E-44B1-9107-6828E428A31A
	at com.beowulfe.hap.impl.pairing.PairVerificationManager.stage2(PairVerificationManager.java:107)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.pairing.PairVerificationManager.handle(PairVerificationManager.java:51)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.connections.HttpSession.handlePairVerify(HttpSession.java:123)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.connections.HttpSession.handleRequest(HttpSession.java:54)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[183:org.openhab.io.homekit:2.0.0]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_112]
13:23:49.026 [ERROR] [lfe.hap.impl.connections.HttpSession] - Excepton encountered while verifying pairing
java.lang.Exception: Unknown user: 067A750D-BC7E-44B1-9107-6828E428A31A
	at com.beowulfe.hap.impl.pairing.PairVerificationManager.stage2(PairVerificationManager.java:107)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.pairing.PairVerificationManager.handle(PairVerificationManager.java:51)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.connections.HttpSession.handlePairVerify(HttpSession.java:123)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.connections.HttpSession.handleRequest(HttpSession.java:54)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[183:org.openhab.io.homekit:2.0.0]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[183:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[183:org.openhab.io.homekit:2.0.0]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_112]
```

its really hard to find all information as newbie so i hope someone can help

Cheers

**Comment by aotd1** [comment]
So you successfully pair openHab2 homekit. Then remove hub from iOS and try to pair again?
Try to ssh into OpenHab2 console with default password 'habopen'
```
sh -p8101 openhab@localhost
```
apply command
```
smarthome:homekit clearPairings
```
And try to pair again

**Comment by baakoo** [comment]
I tried "clearPairings" but this does not work. I did a fresh installation and that worked for me. Since then it is working .... Thanks für reply!
