### ISSUE TITLE
[Homematic binding] Issue with latest CCU2 firmware 2.27.7

### ISSUE THREAD

**Issue by thefox73** [openhab/openhab2-addons#2078]
I updated my CCU2 to the latest FW 2.27.7 a couple of days ago and I recognised no issues in OH2.
Today I saw, that the gateway extras thing was offline. I removed the thing and started the discovery, but unfortunately the gateway extra was not found.  After the discovery all Homematic items were offline in OH2, except the bridge, whichj was online. I uninstalled the binding, removed all things etc... without success.
My final step was to downgrade the CCU firmware to 2.25.5 and this resolved the issue. Auto discovery found all items and everything is working fine again.
Is this a known issue?

**Comment by MHerbst** [comment]
I have also updated to 2.27.7 and until now I did not have any problems. Neither with OH 2 release nor with one of the latest snapshots.
In the community forum is a post regarding NPEs that may be related to 2.27.7 (https://community.openhab.org/t/openhabe-2-homematic-cant-find-things/25512).

Does your openhab log contain any error messages or exceptions related to the Homematic binding?

**Comment by thefox73** [comment]
`2017-03-24 20:02:09.186 [DEBUG] [very.HomematicDeviceDiscoveryService] - Starting Homematic discovery scan
2017-03-24 20:02:09.780 [ERROR] [very.HomematicDeviceDiscoveryService] - 
java.lang.NullPointerException
	at org.openhab.binding.homematic.internal.misc.MiscUtils.validateCharacters(MiscUtils.java:26)[213:org.openhab.binding.homematic:2.0.0.b5]
	at org.openhab.binding.homematic.internal.model.HmDevice.setType(HmDevice.java:94)[213:org.openhab.binding.homematic:2.0.0.b5]
	at org.openhab.binding.homematic.internal.communicator.parser.ListDevicesParser.parse(ListDevicesParser.java:52)[213:org.openhab.binding.homematic:2.0.0.b5]
	at org.openhab.binding.homematic.internal.communicator.client.RpcClient.listDevices(RpcClient.java:137)[213:org.openhab.binding.homematic:2.0.0.b5]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.getDeviceDescriptions(AbstractHomematicGateway.java:418)[213:org.openhab.binding.homematic:2.0.0.b5]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadAllDeviceMetadata(AbstractHomematicGateway.java:358)[213:org.openhab.binding.homematic:2.0.0.b5]
	at org.openhab.binding.homematic.discovery.HomematicDeviceDiscoveryService$1.run(HomematicDeviceDiscoveryService.java:108)[213:org.openhab.binding.homematic:2.0.0.b5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]`

**Comment by MHerbst** [comment]
This seems to be the same problem as described in the forum posting. @gerrieg has solved it already and it was already merged yesterday. It should be contained in the latest snapshot or you can download the jar file only from the PR build.

**Comment by thefox73** [comment]
Ok, thank you for your quick response and help.
As I'm not very familliar with GitHub, I don't know how to download jar files from the PR build ;-) and where to add it in OH :-)
So it would be maybe easier to use the snapshot distro for me.
Would you mind telling me, how to access the snapshot repo?
Thank you

**Comment by thefox73** [comment]
Guess I found it
https://community.openhab.org/t/the-linux-snapshot-installation-repo-has-moved/22915

**Comment by thefox73** [comment]
@MHerbst Where can I download the jar file?

**Comment by MHerbst** [comment]
@thefox73 You can download it from here: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.homematic/2.1.0-SNAPSHOT/

**Comment by thefox73** [comment]
@MHerbst Thank you very much and have a nice weekend
