### ISSUE TITLE
Stacktraces are not always properly logged

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#2093]
A lot places where an Exception (or even worst a Throwable is caught) only the exception message is logged which will not be very useful if you are actually catching a NullPointerException or an OutOfMemoryError. While reviewing the following PR I found some of them.

https://github.com/openhab/openhab2-addons/pull/2088

Maybe we could include the resolving of:

```
logger.error("", e);
logger.error("{}", someVar);
```

And I would prefer to stop catching Throwable and catch RuntimeExceptions instead of maybe some specific check Exceptions.

So the following list of issues should imho be picked up:
- log exceptions with stacktrace if RuntimeExceptions (might) be caught
- do not log empty messages or only a single placeholder (see: no-check & https://github.com/KengoTODA/findbugs-slf4j#slf4j_sign_only_format)
- Do not log Throwable (see http://pmd.sourceforge.net/pmd-4.3.0/rules/strictexception.html)

**Comment by ThomDietrich** [comment]
* Differentiate between different log levels

`error`, `warn` and `info` should contain interpreted unambiguous messages only while `debug` or `trace` may contain a full stack trace. For critical sections I'd ideally log an error message to logger.error and additionally the stack trace to logger.debug/trace

**Comment by martinvw** [comment]
> error, warn and info should contain interpreted unambiguous messages only while debug or trace may contain a full stack trace. For critical sections I'd ideally log an error message to logger.error and additionally the stack trace to logger.debug/trace

If that is how we feel about it, we should also update http://docs.openhab.org/developers/development/guidelines.html

However it feels quite contradictory to how I have worked with logging in professional environments over the last 5-10 years, although mostly server-side. If something is really wrong (thus an error condition) I would like a stacktrace straight in the logging and not having to hope that the error occurs again after I enabled the debug logging.

Otherwise we always have to redirect every error report on the community forum to let them configure debug logging and wait for the error to re-appear.

**Comment by ThomDietrich** [comment]
That was just my opinion, maybe @kaikreuzer can comment on the matter.

On server-side stack traces in the log might be helpful but they are *imho* inappropriate in an end user environment. Dozens of stacktrace lines will just confuse the en duser.
Instead of dumping the stack trace in hope of a hint for the error, I'd expect better exception handling and clear error reporting (as suggested by pointing out the `logger.error("", e);` lines). 

> Where ever unchecked exceptions are caught and logged, the exception should be added as a last parameter to the logging. For checked exceptions, this is normally not recommended, unless it can be considered an error situation and the stacktrace would hold additional important information for the analysis.

I see no problem here.

> Otherwise we always have to redirect every error report on the community forum to let them configure debug logging and wait for the error to re-appear.

I actually see that from time to time https://community.openhab.org/t/homematic-communication-error/16040/5

**Comment by martinvw** [comment]
Looking at https://logback.qos.ch/manual/layouts.html#ex I would just promote users to either use 

```
%ex{short} 
%ex{full}
```
or to get rid of them completely put you might also lose the message and exception class, so I would advice against it:
```
%nopex
```

**Comment by martinvw** [comment]
I just did a quick test with a spring boot application slf4j & logback

Log layout:
> %-5level %message %nopex%n

Message:
> WARN  Name should be longer than 4 characters.

**Comment by martinvw** [comment]
Log layout:

> %-5level %message %ex%n

Message:
```
WARN  Name should be longer than 4 characters. java.lang.IllegalArgumentException: Name should be longer than 4 characters.
	at nl.mtin.demo.rest.backend.GreetingController.test(GreetingController.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Log layout:

> %-5level %message %ex{short}%n

Message:
```
WARN  Name should be longer than 4 characters. java.lang.IllegalArgumentException: Name should be longer than 4 characters.
	at nl.mtin.demo.rest.backend.GreetingController.test(GreetingController.java:22)
```

Log layout:

> %-5level %message %ex{short}%n

Message:
```
WARN  Name should be longer than 4 characters. java.lang.IllegalArgumentException: Name should be longer than 4 characters.
	at nl.mtin.demo.rest.backend.GreetingController.test(GreetingController.java:22)
```

We could also look into the https://logback.qos.ch/manual/layouts.html#Evaluators

**Comment by martinvw** [comment]
And even greater:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <evaluator name="DISPLAY_EX_EVAL">
        <expression>throwable != null &amp;&amp; !(throwable instanceof java.lang.RuntimeException)</expression>
    </evaluator>

    <include resource="org/springframework/boot/logging/logback/base.xml"/>
    <logger name="org.springframework.web" level="WARN"/>
</configuration>
```

Log layout:
> =%-5level %message %ex{full, DISPLAY_EX_EVAL}%n

```java
         IllegalArgumentException e = new IllegalArgumentException("Name should be longer than 4 characters.");
        logger.warn("{}", e.getMessage(), e);
        Exception e2 = new Exception("Name should be longer than 4 characters.");
        logger.warn("{}", e2.getMessage(), e2);
```

Output:

```
WARN  Name should be longer than 4 characters. java.lang.IllegalArgumentException: Name should be longer than 4 characters.
	at nl.mtin.demo.rest.backend.GreetingController.test(GreetingController.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

WARN  Name should be longer than 4 characters. 
``` 

So automatically showing stacktraces (length is configurable) for RuntimeExeptions while supressing check exceptions. Note that this requires the (maybe) ugly pattern of `logger.warn("{}", e.getMessage(), e);` for all checked ones.

**Comment by kaikreuzer** [comment]
Note that we are sharing the coding guidelines with Eclipse SmartHome and the ones for logging have been recently discussed and documented with https://github.com/eclipse/smarthome/pull/2996.

So ideally, any change to these guidelines should be discussed at ESH as well.
In general, the guideline is:
- Always log a meaningful message (i.e. never do "")
- Also include a stacktrace in case of any unexpected (and thus likely to be a bug) issues; it is then up to the solution's logger configuration, whether it logs these stacktraces or not.

**Comment by martinvw** [comment]
So you do agree that for every RuntimeException the stacktrace should be included?

Do you also agree that we should get rid of catching Throwable's, because logging and ignore an OutOfMemmoryError will not help in stability.

Note that the guidelines does not state something about meaningful messages but imho it could be assumed to be common sense.

**Comment by kaikreuzer** [comment]
I'd suggest to close this issue and open one at ESH instead, where we can continue the discussion.

I so far wasn't aware of https://github.com/KengoTODA/findbugs-slf4j#slf4j_sign_only_format, so I'll have to look again into it in more depth myself.

**Comment by lolodomo** [comment]
Concerning throwable catching, there is something to consider. If you have a job scheduled to run every X, if there is an exception in the run() method that is not catched, the schedule of the job is just stopped silently.
It takes me a very long time to understand why the Freebox binding suddenly stopped to run the job after several hours or even few days. It was because the third-party library called in the run() method was throwing sometimes an exception that was not catched by the binding. I don't remember now what was this exception but I can try to find the issue where it was discussed. Catching throwable was a way to be sure that the job will continue to be scheduled as expected.
I don't know if in this case, catching RuntimeExceptions instead of Throwable would have the same result but this solution was not proposed to me.

**Comment by davidgraeff** [comment]
There is now also the community forum with the development section for this. Closing now.
