### ISSUE TITLE
[boschindego] The login credentials are wrong or another client connected to your Indego account

### ISSUE THREAD

**Issue by bloodybeet** [openhab/openhab2-addons#2168]
After adding a Bosch Indego succesfully as a thing, using the correct password, the thing shows up as Online. Using another password won't show it as Online, and I can succesfully read out e.g. the progress percentage, which aligns with the percentage I can read from the Android app.

When trying to get the Bosch Indego to mow, nothing happens and I see the following in the logs:

```
2017-04-17 14:28:43.924 [WARN ] [schindego.handler.BoschIndegoHandler] - The login credentials are wrong or another client connected to your Indego account
de.zazaz.iot.bosch.indego.IndegoAuthenticationException: The request failed with error: HTTP/1.1 504 
	at de.zazaz.iot.bosch.indego.IndegoController.doPutRequest(IndegoController.java:312)[212:org.openhab.binding.boschindego:2.1.0.201704170008]
	at de.zazaz.iot.bosch.indego.IndegoController.sendCommand(IndegoController.java:190)[212:org.openhab.binding.boschindego:2.1.0.201704170008]
	at org.openhab.binding.boschindego.handler.BoschIndegoHandler.poll(BoschIndegoHandler.java:129)[212:org.openhab.binding.boschindego:2.1.0.201704170008]
	at org.openhab.binding.boschindego.handler.BoschIndegoHandler.access$1(BoschIndegoHandler.java:101)[212:org.openhab.binding.boschindego:2.1.0.201704170008]
	at org.openhab.binding.boschindego.handler.BoschIndegoHandler$1.run(BoschIndegoHandler.java:240)[212:org.openhab.binding.boschindego:2.1.0.201704170008]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

Item declaration:
`Number Indego_State "Indego" { channel="boschindego:indego:83371535:state" }`

Sitemap declaration:
`Switch item=Indego_State mappings=[ 1="Mow", 2="Return",3="Pause" ]`

The event trace shows the following:
```
2017-04-17 14:27:53.282 [ItemCommandEvent          ] - Item 'Indego_State' received command 1
2017-04-17 14:27:53.295 [ItemStateChangedEvent     ] - Indego_State changed from 2 to 1
2017-04-17 14:28:43.935 [hingStatusInfoChangedEvent] - 'boschindego:indego:83371535' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): The login credentials are wrong or another client connected to your Indego account
2017-04-17 14:29:44.714 [hingStatusInfoChangedEvent] - 'boschindego:indego:83371535' changed from OFFLINE (COMMUNICATION_ERROR): The login credentials are wrong or another client connected to your Indego account to ONLINE
2017-04-17 14:29:44.723 [ItemStateChangedEvent     ] - Indego_State changed from 1 to 2
```

It looks like there is succesful communication with the Bosch Indego (otherwise I wouldn't be able to read out states (?)), but when actually sending a command I receive this error. I am also logged out of the Android App and have waited 2 hours in between, to make sure it isn't a token issue or related at Bosch's servers.
![indego](https://cloud.githubusercontent.com/assets/12112860/25089088/6b43ed68-237b-11e7-8711-1dc68e47f48b.PNG)

**Comment by jofleck** [comment]
Mhhh which Indego are you using? I couldn't reproduce the problem with our connect 1200. I noticed that the library throws an IndegoAuthenticationException when the mower reports an error after sending a command too. Maybe the temperature is out of range? Its really cold outside this week.

**Comment by bartverstrynge** [comment]
Hi Jonas,

It's an Indego 1000. The mower runs fine when I command it through the
proprietary app. Can you confirm that it works if you are logged into the
app simultaneously with sending a command through OpenHab?

Is there anything else I could try? Again, I would expect the reads to use
the same authentication mechanism as sending commands (is this correct?) so
I hope it's not something I configured incorrectly for the commanding of
the state.

**Comment by bartverstrynge** [comment]
Hi,

It suddenly started working since today (I've been trying every day), so I do think it has something to do with a token invalidation on Bosch's end. 

Something to note, the documentation shows a lot of supported channels:

![image](https://cloud.githubusercontent.com/assets/12112860/25292381/266a7c1c-26d6-11e7-81e4-6b7588d7fe9b.png)

While the actual binding only shows 4:

![image](https://cloud.githubusercontent.com/assets/12112860/25292400/3b971212-26d6-11e7-9f2f-31dd6cc97116.png)

**Comment by jofleck** [comment]
Really strange behaviour...I hope this problem occours  not again. 

These are advanced channels. They are not shown in the paper UI but you can use them as usual in your items file.

**Comment by jofleck** [comment]
Its no problem to keep logged in in the Indego App. Bosch allows only one connection at the same time. So its possible that you will Receive an error message in the app which says that another user is logged in when your OpenHAB is refreshing the state.

**Comment by davidgraeff** [comment]
Please reopen if the issue still persists and the given solution does not suffice. Thanks for the report.
