### ISSUE TITLE
IKEA Trådfri binding

### ISSUE THREAD

**Issue by dsundberg** [openhab/openhab2-addons#2187]
The newly released IKEA Trådfri Lighting products do not have a binding for openHAB. I've started to write a binding and will submit a PR as soon as the basic functionality is implemented.

**Comment by tstewen** [comment]
Great work! Looking forward to this binding,

**Comment by tstewen** [comment]
Did some quick testing with overall good results:

- Setup worked with no issues in openhab2
- Control of on/off, brightness and color worked as expected.
- Not working: The state of the different values do not get an update when changed in the IKEA andriod app or IKEA remote.

Keep up the good work!

**Comment by DavidBoman** [comment]
I'm happy go help out - do you have fork I can fork :)

**Comment by dsundberg** [comment]
Here is the fork, https://github.com/dsundberg/openhab2-addons/tree/ikeatradfri/addons/binding/org.openhab.binding.ikeatradfri

States should now be reflected when changed from the app or one of the remotes. Warm white and White Spectrum bulbs are now separated. Looking into groups now.

**Comment by cweitkamp** [comment]
Here are some test results - mostly for setup and discovery. I use Paper UI for all steps:

- setup worked fine, my gateway poped up immediately in the Inbox of Paper UI.
- adding it as a thing results in thing status UNINITIALIZED because of my missing security token.
- configuring the security token results in thing status OFFLINE and nothing happened after that - I commented on your initial commit. I needed a restart of my openhab service to get it run - maybe a handleConfigurationUpdate helps.
- after restarting my two bulbs poped up immediately in the Inbox of Paper UI.

I spent some more time on testing the bulbs during the week.

Thank you and keep going.

**Comment by tstewen** [comment]
Can confirm that state updates work now. Nice work!

**Comment by kaikreuzer** [comment]
Hey @dsundberg, you could directly create a PR from your fork and mark it with [WIP] in the title - this would trigger our PR builder so that the binding jar becomes directly available at https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/ for people for testing.

**Comment by dsundberg** [comment]
@kaikreuzer Thanks, will do that.

**Comment by dsundberg** [comment]
Find PR here:  #2200 and binding jar [here](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.ikeatradfri/).

**Comment by DerGute** [comment]
Great work! Does this mean, that with #2200 it is possible to set color of the light without the restrictions, that are given by the ikea app?

**Comment by dsundberg** [comment]
@DerGute Yes, you can now use a dimmer do set any "temperature" value between the the warm and cold endpoints.

**Comment by DerGute** [comment]
@dsundberg sounds great! One more question:
Does the Binding communicate With the Gateway Or directly with each bulb ? If the Binding speaks With the Gateway, Can Sensor Data Like Motion be read?

**Comment by dsundberg** [comment]
@DerGute Binding talks to the gateway. I am looking into if there is a possibility to get events from the controllers, dimmers and motion sensor. The expected way of "observing" the controller and dimmer devices on COAP does not give any event data, I only see changes on the bulbs at the moment.

**Comment by tstewen** [comment]
Any progress catching events on controllers or motion sensors? Maybe controllers send signal to the bulb with without us using the gateway? Can you catch an event on a group with a controller assigned?

**Comment by cweitkamp** [comment]
I am getting these NPEs from time to time. Any ideas?

You are calling the `completeExceptionally();` method with argument `null` in those lines. Is that a valid way to go?
```
2017-05-11 08:16:38.128 [DEBUG] [adfri.handler.IkeaTradfriBulbHandler] - Sending to: 65537 payload: {"3311":[{"5850":0}]}
2017-05-11 08:16:38.137 [DEBUG] [ri.handler.IkeaTradfriGatewayHandler] - COAP PUT {"3311":[{"5850":0}]} to 15001/65537
2017-05-11 08:17:56.605 [DEBUG] [ri.handler.IkeaTradfriGatewayHandler] - COAP PUT Error
2017-05-11 08:17:56.622 [ERROR] [.core.network.stack.ReliabilityLayer] - Exception in MessageObserver: null
java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1975)[:1.8.0_65]
	at org.openhab.binding.ikeatradfri.handler.IkeaTradfriGatewayHandler$2.onError(IkeaTradfriGatewayHandler.java:186)[341:org.openhab.binding.ikeatradfri:2.1.0.201704282000]
	at org.eclipse.californium.core.CoapClient$MessageObserverImpl.failed(CoapClient.java:999)[341:org.openhab.binding.ikeatradfri:2.1.0.201704282000]
	at org.eclipse.californium.core.CoapClient$MessageObserverImpl.onTimeout(CoapClient.java:960)[341:org.openhab.binding.ikeatradfri:2.1.0.201704282000]
	at org.eclipse.californium.core.coap.Message.setTimedOut(Message.java:512)[341:org.openhab.binding.ikeatradfri:2.1.0.201704282000]
	at org.eclipse.californium.core.coap.Request.setTimedOut(Request.java:485)[341:org.openhab.binding.ikeatradfri:2.1.0.201704282000]
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.run(ReliabilityLayer.java:368)[341:org.openhab.binding.ikeatradfri:2.1.0.201704282000]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

**Comment by Mtwbs** [comment]
Hello @dsundberg 

I am a new use for openhab2
Develop a new binding has problem
Can you talk to you?
mail=z12385200@gmail.com

Thx,
tony

**Comment by cweitkamp** [comment]
Could this be closed as it is superseded by [eclipse/smarthome#3653](https://github.com/eclipse/smarthome/pull/3653).

**Comment by martinvw** [comment]
Ye
