### ISSUE TITLE
[systeminfo] Avoid DeviceNotFoundException for channel group process on sending a refresh command

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab2-addons#2222]
The channel group `process` can be used to tracked a process at runtime. The process can be configured with a parameter `pid` (see [Systeminfo Binding - Channels](http://docs.openhab.org/addons/bindings/systeminfo/readme.html#channels)). If a refresh command is send to one channel of the channel group a default pid will be used which is `0`. A process with `pid = 0` will never be valid.

Avoid DeviceNotFoundException for channel group `process` on sending a refresh command, which results in the following ERROR in the log:
```
2017-04-30 13:40:45.341 [ERROR] [systeminfo.handler.SysteminfoHandler] - No information for channel process#load with device intex 0 :
org.openhab.binding.systeminfo.model.DeviceNotFoundException: Error while getting information for process with PID 0
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcess(OshiSysteminfo.java:97)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcessCpuUsage(OshiSysteminfo.java:571)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.getInfoForChannel(SysteminfoHandler.java:419)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.publishDataForChannel(SysteminfoHandler.java:253)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.handleChannelConfigurationChange(SysteminfoHandler.java:574)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.thingUpdated(SysteminfoHandler.java:556)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:522)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2017-04-30 13:40:45.378 [ERROR] [systeminfo.handler.SysteminfoHandler] - No information for channel process#used with device intex 0 :
org.openhab.binding.systeminfo.model.DeviceNotFoundException: Error while getting information for process with PID 0
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcess(OshiSysteminfo.java:97)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcessMemoryUsage(OshiSysteminfo.java:579)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.getInfoForChannel(SysteminfoHandler.java:422)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.publishDataForChannel(SysteminfoHandler.java:253)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.handleChannelConfigurationChange(SysteminfoHandler.java:574)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.thingUpdated(SysteminfoHandler.java:556)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:522)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2017-04-30 13:40:45.392 [ERROR] [systeminfo.handler.SysteminfoHandler] - No information for channel process#name with device intex 0 :
org.openhab.binding.systeminfo.model.DeviceNotFoundException: Error while getting information for process with PID 0
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcess(OshiSysteminfo.java:97)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcessName(OshiSysteminfo.java:564)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.getInfoForChannel(SysteminfoHandler.java:425)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.publishDataForChannel(SysteminfoHandler.java:253)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.handleChannelConfigurationChange(SysteminfoHandler.java:574)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.thingUpdated(SysteminfoHandler.java:556)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:522)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2017-04-30 13:40:45.418 [ERROR] [systeminfo.handler.SysteminfoHandler] - No information for channel process#threads with device intex 0 :
org.openhab.binding.systeminfo.model.DeviceNotFoundException: Error while getting information for process with PID 0
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcess(OshiSysteminfo.java:97)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcessThreads(OshiSysteminfo.java:594)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.getInfoForChannel(SysteminfoHandler.java:431)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.publishDataForChannel(SysteminfoHandler.java:253)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.handleChannelConfigurationChange(SysteminfoHandler.java:574)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.thingUpdated(SysteminfoHandler.java:556)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:522)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2017-04-30 13:40:45.436 [ERROR] [systeminfo.handler.SysteminfoHandler] - No information for channel process#path with device intex 0 :
org.openhab.binding.systeminfo.model.DeviceNotFoundException: Error while getting information for process with PID 0
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcess(OshiSysteminfo.java:97)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.model.OshiSysteminfo.getProcessPath(OshiSysteminfo.java:587)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.getInfoForChannel(SysteminfoHandler.java:428)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.publishDataForChannel(SysteminfoHandler.java:253)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.handleChannelConfigurationChange(SysteminfoHandler.java:574)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.openhab.binding.systeminfo.handler.SysteminfoHandler.thingUpdated(SysteminfoHandler.java:556)[344:org.openhab.binding.systeminfo:2.1.0.201704270651]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:522)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.b4]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[99:org.eclipse.smarthome.core:0.9.0.b4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

**Comment by cweitkamp** [comment]
Find PR here: #2230
