### ISSUE TITLE
[Homematic] Initial setup problems with build 20170506

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab2-addons#2247]
I have installed the Snapshot build on my Windows 10 machine with a fresh configuration. 
On the PC VirtualBox is installed and that means that there is more than one IP address. This now leads to following problems.

In the first step, I only set the IP address of the CCU (192.168.2.93). The log file shows the following messages (I have mixed openhab.log and events.log):
```
2017-05-07 18:51:34.936 [WARN ] [g.eclipse.smarthome.core.net.NetUtil] - Found multiple local interfaces - ignoring 192.168.2.119
2017-05-07 18:51:36.113 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'WIRED' on gateway '0967692e' not available, disabling support
2017-05-07 18:51:37.154 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'CUXD' on gateway '0967692e' not available, disabling support
2017-05-07 18:51:37.261 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=2.27.8,address=MEQ0226766,wired=false,hmip=true,cuxd=false,group=true]
2017-05-07 18:52:07.300 [WARN ] [ommunicator.AbstractHomematicGateway] - Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)[:1.8.0_121]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)[:1.8.0_121]
...
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2017-05-07 18:52:17.428 [WARN ] [g.eclipse.smarthome.core.net.NetUtil] - Found multiple local interfaces - ignoring 192.168.2.119
2017-05-07 18:52:23.029 [ThingUpdatedEvent         ] - Thing 'homematic:bridge:0967692e' has been updated.
2017-05-07 18:52:47.455 [hingStatusInfoChangedEvent] - 'homematic:bridge:0967692e' changed from OFFLINE (COMMUNICATION_ERROR): Read timed out to OFFLINE (COMMUNICATION_ERROR)
2017-05-07 18:54:05.138 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'WIRED' on gateway '0967692e' not available, disabling support
2017-05-07 18:54:05.143 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'WIRED' on gateway '0967692e' not available, disabling support
2017-05-07 18:54:06.182 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'CUXD' on gateway '0967692e' not available, disabling support
2017-05-07 18:54:06.205 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'CUXD' on gateway '0967692e' not available, disabling support
2017-05-07 18:54:06.208 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=2.27.8,address=MEQ0226766,wired=false,hmip=true,cuxd=false,group=true]
2017-05-07 18:54:06.259 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=2.27.8,address=MEQ0226766,wired=false,hmip=true,cuxd=false,group=true]
2017-05-07 18:54:39.194 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'WIRED' on gateway '0967692e' not available, disabling support
2017-05-07 18:54:40.239 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'CUXD' on gateway '0967692e' not available, disabling support
2017-05-07 18:54:40.271 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=2.27.8,address=MEQ0226766,wired=false,hmip=true,cuxd=false,group=true]
2017-05-07 18:54:53.106 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:HM-Sec-SCo:0967692e:MEQ1407665' to inbox.
```
Unfortunately the binding ignores the real IP address of the PC (192.168.2.119) and uses the VirtualBox network address (192.68.56.1). As far as I remember in older version the correct address was used. Maybe this was just by accident. 

I have then changed the bridge configuration and set a callback address (timestamp 18:52:23). 24s later there is another timeout message and 2min later a new scan starts automatically.

I would have expected that the update of the bridge configuration would immediately trigger a new connection attempt and scan for things.

Accidentially I entered a wrong callback address and then this happens (events.log): 
```
2017-05-07 19:19:07.938 [hingStatusInfoChangedEvent] - 'homematic:bridge:9982543f' changed from OFFLINE (COMMUNICATION_ERROR) to OFFLINE (COMMUNICATION_ERROR): Address already in use: JVM_Bind
2017-05-07 19:19:12.842 [InboxAddedEvent           ] - Discovery Result with UID 'homematic:HM-Sec-SCo:9982543f:MEQ1407665' has been added.
2017-05-07 19:19:12.888 [InboxAddedEvent           ] - Discovery Result with UID 'homematic:HM-Sec-SD-2-Team:9982543f:T-NEQ0002819' has been added.
...
2017-05-07 19:19:23.312 [hingStatusInfoChangedEvent] - 'homematic:bridge:9982543f' changed from OFFLINE (COMMUNICATION_ERROR): Address already in use: JVM_Bind to ONLINE
```
And openhab.log shows:
```
2017-05-07 19:19:12.841 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:HM-Sec-SCo:9982543f:MEQ1407665' to inbox.
2017-05-07 19:19:12.887 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:HM-Sec-SD-2-Team:9982543f:T-NEQ0002819' to inbox.
...
2017-05-07 19:19:23.273 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Ventil:Arbeitszimmer' contains invalid characters, new Datapoint name 'Ventil_Arbeitszimmer'
2017-05-07 19:19:23.273 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name 'Ventil:Bad' contains invalid characters, new Datapoint name 'Ventil_Bad'
2017-05-07 19:19:23.303 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name '${ruleTmpProgramName}' contains invalid characters, new Datapoint name '__ruleTmpProgramName_'
2017-05-07 19:19:23.303 [INFO ] [ng.homematic.internal.misc.MiscUtils] - Datapoint name '${ruleTmpProgramName} 1' contains invalid characters, new Datapoint name '__ruleTmpProgramName__1'
2017-05-07 19:19:23.307 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:GATEWAY-EXTRAS-9982543F:9982543f:GWE00000000' to inbox.
2017-05-07 19:19:24.991 [WARN ] [ommunicator.AbstractHomematicGateway] - Can't load device with address 'MEQ1407665' from gateway '9982543f': RPC client for interface RF not available
2017-05-07 19:19:24.992 [WARN ] [ommunicator.AbstractHomematicGateway] - Can't load device with address 'T-NEQ0002819' from gateway '9982543f': RPC client for interface RF not available
...
2017-05-07 19:19:24.999 [ERROR] [very.HomematicDeviceDiscoveryService] - null
java.lang.NullPointerException
	at org.openhab.binding.homematic.internal.communicator.CcuGateway.sendScriptByName(CcuGateway.java:221)[183:org.openhab.binding.homematic:2.1.0.201705061030]
	at org.openhab.binding.homematic.internal.communicator.CcuGateway.sendScriptByName(CcuGateway.java:213)[183:org.openhab.binding.homematic:2.1.0.201705061030]
	at org.openhab.binding.homematic.internal.communicator.CcuGateway.loadVariables(CcuGateway.java:108)[183:org.openhab.binding.homematic:2.1.0.201705061030]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadChannelValues(AbstractHomematicGateway.java:479)[183:org.openhab.binding.homematic:2.1.0.201705061030]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadAllDeviceMetadata(AbstractHomematicGateway.java:387)[183:org.openhab.binding.homematic:2.1.0.201705061030]
	at org.openhab.binding.homematic.discovery.HomematicDeviceDiscoveryService$1.run(HomematicDeviceDiscoveryService.java:108)[183:org.openhab.binding.homematic:2.1.0.201705061030]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2017-05-07 19:19:36.231 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'WIRED' on gateway '9982543f' not available, disabling support
```

**Comment by MarcusWolschon** [comment]
I get the same NPE in CcuGateway.sendScriptByName but in line 194 in release-version "binding-homematic - 2.2.0" after setting up my CCU2 while discovering the devices.

**Comment by gerrieg** [comment]
Is this issue still valid for OH 2.3 release?

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5781
