### ISSUE TITLE
RFXCOM NPE when not even connected

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#2298]
While the bridge is not connected, it is not even plugged in... it's still trying to send out the message and fails because there is OutputStream available that exception not caught because it's an NPE so finally we get a real error in the log.

```
2017-05-25 19:36:27.743 [ERROR] [.c.thing.internal.ThingManager:363  ] - Exception occured while calling handler: java.lang.NullPointerExceptionjava.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:352)
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Caused by: java.lang.NullPointerException: null
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector.sendMessage(RFXComSerialConnector.java:126)
	at org.openhab.binding.rfxcom.handler.RFXComBridgeHandler.sendMessage(RFXComBridgeHandler.java:215)
	at org.openhab.binding.rfxcom.handler.RFXComHandler.handleCommand(RFXComHandler.java:83)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:355)
	at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:1)
	... 5 common frames omitted
```

If the serial connector sees that it has no correct OutputStream it should maybe throw an IOException which is properly handled in the bridge handler and it will keep/mark the item offline with a correct message.

**Comment by martinvw** [comment]
Working on it :-)
