### ISSUE TITLE
[Synop] Error starting Synop binding

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab2-addons#2341]
I am trying the Synop binding to retrieve the octa value, to replace a direct call in a rule with some string manipulation.
I cannot get it to work. When the binding starts or is restarted (through the console), I get the following error:
```
2017-06-07 10:33:41.472 [ERROR] [ore.internal.events.OSGiEventManager] - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: java.lang.NoSuchMethodError: org.apache.http.client.utils.URIBuilder.setParameters(Ljava/util/List;)Lorg/apache/http/client/utils/URIBuilder;
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.http.client.utils.URIBuilder.setParameters(Ljava/util/List;)Lorg/apache/http/client/utils/URIBuilder;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_121]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:194)[101:org.eclipse.smarthome.core:0.9.0.201706012026]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)[101:org.eclipse.smarthome.core:0.9.0.201706012026]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)[101:org.eclipse.smarthome.core:0.9.0.201706012026]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.dispatchESHEvent(OSGiEventManager.java:188)[101:org.eclipse.smarthome.core:0.9.0.201706012026]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:163)[101:org.eclipse.smarthome.core:0.9.0.201706012026]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:146)[101:org.eclipse.smarthome.core:0.9.0.201706012026]
	at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415)[6:org.apache.karaf.services.eventadmin:4.0.8]
	at org.apache.felix.eventadmin.impl.tasks.HandlerTask.run(HandlerTask.java:90)[6:org.apache.karaf.services.eventadmin:4.0.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.apache.http.client.utils.URIBuilder.setParameters(Ljava/util/List;)Lorg/apache/http/client/utils/URIBuilder;
	at org.openhab.binding.synopanalyzer.handler.SynopAnalyzerHandler.forgeURL(SynopAnalyzerHandler.java:218)
	at org.openhab.binding.synopanalyzer.handler.SynopAnalyzerHandler.getLastAvailableSynop(SynopAnalyzerHandler.java:93)
	at org.openhab.binding.synopanalyzer.handler.SynopAnalyzerHandler.updateSynop(SynopAnalyzerHandler.java:122)
	at org.openhab.binding.synopanalyzer.handler.SynopAnalyzerHandler.handleCommand(SynopAnalyzerHandler.java:234)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)
	... 4 more
```
I am running snapshot build #938.

**Comment by martinvw** [comment]
@clinique can you take a look at this?

**Comment by clinique** [comment]
@martinvw , @mherwege : yes, I'll take care of this

**Comment by clinique** [comment]
@mherwege : I do not reproduce this problem with an updated development environment. Can you try to update your openhab instance and tell me if you still got it ?

**Comment by mherwege** [comment]
@clinique I updated openHAB to the latest snapshot and still run into the same error in my main environment, running on a raspberryPi. I also tried running your code through the Eclipse IDE. I don't have the error there. So I don't have a clue what the cause could be.

**Comment by clinique** [comment]
@mherwege : the PR has just been merged. Let see if it solves the problem...

**Comment by mherwege** [comment]
@clinique I did an update and the issue is gone. Many thanks.
