### ISSUE TITLE
some openHab bundles doesn't active on Eclipse Smart Home

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab2-addons#2438]
Hello,
I am trying to use openhab1 -bundles and openhab2-bundles into eclipse smart home.
This is smart home repo,   https://github.com/maggu2810/smarthome-packaging-sample-karaf
Here I just clone repo and call   `mvn clean install`, then start the  server.
When I put the jar file of bundle into deploy folder. It showing always bundle status Installed.
see here is my log file:

```
2017-07-05 18:50:19,610 | ERROR | lixDispatchQueue | wemo                             | 204 - org.eclipse.smarthome.binding.wemo - 0.9.0.201707051748 | FrameworkEvent ERROR - org.eclipse.smarthome.binding.wemo
org.osgi.framework.BundleException: Unable to resolve org.eclipse.smarthome.binding.wemo [204](R 204.0): missing requirement [org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp) Unresolved requirements: [[org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4132) [?:?]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) [?:?]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) [?:?]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
2017-07-05 18:50:19,614 | ERROR | FelixStartLevel  | Felix                            |  -  -  | Bundle org.eclipse.smarthome.binding.wemo [204] Error starting file:/E:/SmartHome/smarthome-packaging-sample-karaf/target/assembly/deploy/org.eclipse.smarthome.binding.wemo_0.9.0.201707051748.jar (org.osgi.framework.BundleException: Unable to resolve org.eclipse.smarthome.binding.wemo [204](R 204.0): missing requirement [org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp) Unresolved requirements: [[org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp)])
org.osgi.framework.BundleException: Unable to resolve org.eclipse.smarthome.binding.wemo [204](R 204.0): missing requirement [org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp) Unresolved requirements: [[org.eclipse.smarthome.binding.wemo [204](R 204.0)] osgi.wiring.package; (osgi.wiring.package=org.eclipse.smarthome.io.transport.upnp)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4132) [?:?]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) [?:?]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371) [?:?]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]

```
Bundle list:

```
173 | Active    |  80 | 2.9.2.v20160428-1452  | Xbase Model
174 | Active    |  80 | 2.9.2                 | Xbase Runtime Library
191 | Active    |  80 | 2.2.0                 | JUPnP Library
192 | Active    |  80 | 1.9.6                 | MIME streaming extension
193 | Active    |  80 | 1.0.9                 | mapdb
194 | Active    |  80 | 5.0.2                 | Require-Bundle Fix :: org.objectweb.asm
200 | Active    |  80 | 3.1.4                 | Stax2 API
204 | Installed |  80 | 0.9.0.201707051748    | Eclipse SmartHome Wemo Binding
```

Even some eclipse smart home bundles also doesn't work for me. I am trying multiple bundles deployed into my repo, some bundle working fine and some bundle showing status Installed. How I could resolve this issue.
 Is there any stuff add to my pom.xml file?

Thanks ,
Amar.

**Comment by kaikreuzer** [comment]
This does not seem to be a bug report about any openhab 2 add-on - it does not even seem to be related to openHAB itself as you use your own custom runtime.

If you do that, better first get familiar with OSGi and Karaf itself, so that their log messages make sense to you and you can find your way through building a correct package.
Alternatively, either use openHAB or the eclipse smarthome (non-karaf) sample packaging.

**Comment by amarpulli544** [comment]
@kaikreuzer , As you said correct , this is not openhab2  add-on bug. 
 I need to use some openhab2 - addons .
I did some work on eclipse smart home features . It will be work fine for me and also it will be active state.
Simillarly when I could try to use openhab2 features through pom file, but unable to use openhab2 features.
how i could  use openhab2 features through pom.file.
This is my pom.file
```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <prerequisites>
    <maven>3.0</maven>
  </prerequisites>
  <groupId>de.maggu2810.tmp.org.eclipse.smarthome.packaging.sample</groupId>
  <artifactId>karaf</artifactId>
  <version>0.9.0-SNAPSHOT</version>
  <packaging>karaf-assembly</packaging>

  <name>Eclipse SmartHome :: Packaging Sample :: Karaf</name>
   
  <description>A packaging example for Eclipse SmartHome using Karaf</description>   
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

    <esh.version>${project.version}</esh.version>
    <karaf.version>4.1.1</karaf.version>
  </properties>

  <licenses>
    <license>
      <name>Eclipse Public License</name>
      <url>http://www.eclipse.org/legal/epl-v10.html</url>
    </license>
  </licenses>

  <dependencies>
    <dependency>
      <groupId>org.apache.karaf.features</groupId>
      <artifactId>framework</artifactId>
      <version>${karaf.version}</version>
      <type>kar</type>
    </dependency>
    <dependency>
      <groupId>org.apache.karaf.features</groupId>
      <artifactId>standard</artifactId>
      <version>${karaf.version}</version>
      <classifier>features</classifier>
      <type>xml</type>
    </dependency>
    <dependency>
      <groupId>org.apache.karaf.features</groupId>
      <artifactId>framework</artifactId>
      <classifier>features</classifier>
      <type>xml</type>
      <version>${karaf.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.smarthome</groupId>
      <artifactId>karaf</artifactId>
      <version>${esh.version}</version>
      <classifier>features</classifier>
      <type>xml</type>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.smarthome</groupId>
      <artifactId>karaf-tp</artifactId>
      <version>${esh.version}</version>
      <classifier>features</classifier>
      <type>xml</type>
      <scope>runtime</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.karaf.tooling</groupId>
          <artifactId>karaf-maven-plugin</artifactId>
          <version>${karaf.version}</version>
          <extensions>true</extensions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>2.6</version>
          <executions>
            <execution>
              <id>process-resources</id>
              <goals>
                <goal>resources</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
    <resources>
      <resource>
        <directory>${project.basedir}/src/main/resources</directory>
        <filtering>false</filtering>
        <includes>
          <include>**/*</include>
        </includes>
      </resource>
      <resource>
        <directory>${project.basedir}/src/main/filtered-resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>**/*</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.karaf.tooling</groupId>
        <artifactId>karaf-maven-plugin</artifactId>
        <configuration>
          <installedFeatures>
            <feature>wrapper</feature>
          </installedFeatures>
          <startupFeatures>
            <feature>eventadmin</feature>
          </startupFeatures>
          <bootFeatures>
            <feature>jaas</feature>
            <feature>shell</feature>
            <feature>shell-compat</feature>
            <feature>ssh</feature>
            <feature>management</feature>
            <feature>bundle</feature>
            <feature>config</feature>
            <feature>deployer</feature>
            <feature>diagnostic</feature>
            <feature>instance</feature>
            <feature>kar</feature>
            <feature>log</feature>
            <feature>package</feature>
            <feature>service</feature>
            <feature>system</feature>
            <feature>feature</feature>
            <feature>webconsole</feature>
            <feature>esh-base</feature>
            <feature>esh-io-console-karaf</feature>
            <feature>esh-io-rest-sitemap</feature>
            <feature>esh-model-item-runtime</feature>
            <feature>esh-model-persistence-runtime</feature>
            <feature>esh-model-rule-runtime</feature>
            <feature>esh-model-script-runtime</feature>
            <feature>esh-model-sitemap-runtime</feature>
            <feature>esh-model-thing-runtime</feature>
            <feature>esh-storage-mapdb</feature>
            <feature>esh-ui-iconset-classic</feature>
            <feature>esh-ui-paper</feature>
         
            <feature>esh-binding-wemo</feature>
            <feature>esh-binding-ntp</feature>
            <feature>esh-io-webaudio</feature>
            <feature>esh-ui-classic</feature>
            <feature>esh-binding-yahooweather</feature>
            <feature>esh-binding-hue</feature>
            <feature>esh-binding-digitalstrom</feature>
            <feature>esh-binding-sonos</feature>
            <feature>esh-io-javasound</feature>
            <feature>esh-tp-jmdns</feature>
            <feature>esh-io-transport-mdns</feature>
            <feature>esh-binding-fsinternetradio</feature>
       
            <feature>esh-automation-api</feature>
            <feature>esh-automation-commands</feature>
            <feature>esh-automation-core</feature>
            <feature>esh-automation-module-core</feature>
            <feature>esh-automation-module-script</feature>
            <feature>esh-automation-module-script-defaultscope</feature>
            <feature>esh-automation-module-timer</feature>
            <feature>esh-automation-parser-gson</feature>
            <feature>esh-automation-providers</feature>
            <feature>esh-automation-rest</feature>
          </bootFeatures>
          <archiveZip>false</archiveZip>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <repositories>
    <!-- Maven Central -->
    <!-- Use this first, so we prefer Central all the time -->
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Maven Repository Switchboard</name>
      <url>https://repo1.maven.org/maven2</url>
    </repository>

    <repository>
      <id>jCenter</id>
      <url>https://jcenter.bintray.com/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>

    <!-- maggu2810's private repository -->
    <repository>
      <id>bintray-maggu2810-maven</id>
      <url>https://dl.bintray.com/maggu2810/maven/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>

    <!-- jUPnP -->
    <repository>
      <id>jupnp-bintray</id>
      <url>https://dl.bintray.com/jupnp/mvn/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>

    <!-- Eclipse Release Repository -->
    <repository>
      <id>eclipse-releases</id>
      <name>Eclipse Release Repository</name>
      <layout>default</layout>
      <url>https://repo.eclipse.org/content/repositories/releases/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>

    <!-- Eclipse Snapshot Repository -->
    <repository>
      <id>eclipse-snapshots</id>
      <name>Eclipse Snapshot Repository</name>
      <layout>default</layout>
      <url>https://repo.eclipse.org/content/repositories/snapshots/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

</project>
```
Thanks,
Amar.
