### ISSUE TITLE
hdpowerview binding fails on 2.1 with type conversion error

### ISSUE THREAD

**Issue by beowulfe** [openhab/openhab2-addons#2520]
15:34:27.427 [DEBUG] [.smarthome.config.core.Configuration] - Setting value (int) 5257 to field ‘id’ in configuration class org.openhab.binding.hdpowerview.config.HDPowerViewShadeConfiguration
15:34:27.429 [WARN ] [.smarthome.config.core.Configuration] - Could not set field value for field ‘id’: Can not set int field org.openhab.binding.hdpowerview.config.HDPowerViewShadeConfiguration.id to java.lang.String
java.lang.IllegalArgumentException: Can not set int field org.openhab.binding.hdpowerview.config.HDPowerViewShadeConfiguration.id to java.lang.String
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)[:1.8.0_65]
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)[:1.8.0_65]
at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(UnsafeIntegerFieldAccessorImpl.java:98)[:1.8.0_65]
at java.lang.reflect.Field.set(Field.java:764)[:1.8.0_65]
at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:523)[30:org.apache.commons.lang:2.6.0]
at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:500)[30:org.apache.commons.lang:2.6.0]
at org.apache.commons.lang.reflect.FieldUtils.writeField(FieldUtils.java:560)[30:org.apache.commons.lang:2.6.0]
at org.eclipse.smarthome.config.core.Configuration.as(Configuration.java:96)[94:org.eclipse.smarthome.config.core:0.9.0.b5]
at org.openhab.binding.hdpowerview.handler.HDPowerViewHubHandler.getThingsByShadeId(HDPowerViewHubHandler.java:213)[234:org.openhab.binding.hdpowerview:2.1.0]
at org.openhab.binding.hdpowerview.handler.HDPowerViewHubHandler.pollShades(HDPowerViewHubHandler.java:154)[234:org.openhab.binding.hdpowerview:2.1.0]
at org.openhab.binding.hdpowerview.handler.HDPowerViewHubHandler.poll(HDPowerViewHubHandler.java:139)[234:org.openhab.binding.hdpowerview:2.1.0]
at org.openhab.binding.hdpowerview.handler.HDPowerViewHubHandler.access$0(HDPowerViewHubHandler.java:136)[234:org.openhab.binding.hdpowerview:2.1.0]
at org.openhab.binding.hdpowerview.handler.HDPowerViewHubHandler$1.run(HDPowerViewHubHandler.java:235)[234:org.openhab.binding.hdpowerview:2.1.0]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_65]

**Comment by beowulfe** [comment]
Fix incoming
