### ISSUE TITLE
[HarmonyHub] Timeout-Exceptions

### ISSUE THREAD

**Issue by JoeRu** [openhab/openhab2-addons#2573]
Many Timeout-Exceptions - the reason is quite unclear.

## Expected Behavior
Better explanations where and why the timeout occure. 
Much better - not timeout exception at all.

## Current Behavior

22:07:19.216 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'harmonyhub.things'
22:07:24.226 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while calling thing updated at ThingHandler 'org.openhab.binding.harmonyhub.handler.HarmonyHubHandler@62cfd6cd': null
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)[:1.8.0_144]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:194)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:524)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:221)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:144)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:177)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.lambda$18(GenericThingProvider.java:978)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
	at java.util.ArrayList.forEach(ArrayList.java:1249)[:1.8.0_144]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModelForThingHandlerFactory(GenericThingProvider.java:987)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$1(GenericThingProvider.java:950)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.lambda$0(GenericThingProvider.java:234)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)[:1.8.0_144]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:236)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:1)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
	at org.eclipse.smarthome.config.core.BundleProcessorVetoManager.applyActionFor(BundleProcessorVetoManager.java:124)
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.lambda$3(GenericThingProvider.java:304)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
	at java.lang.Iterable.forEach(Iterable.java:75)[:1.8.0_144]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModel(GenericThingProvider.java:306)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
	at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.modelChanged(GenericThingProvider.java:820)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:286)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:120)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)[122:org.eclipse.smarthome.model.core:0.9.0.b5]
	at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:206)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]

## Possible Solution
increase default Timeout - but - my tests suggest no impact on this error. 

## Steps to Reproduce (for Bugs)
Just use HarmonyHub-Binding. No special preparations needed.

## Context
The issue is minor. The effect on functionality is not given. It just explodes the logs

## Your Environment
* Version used: (e.g., openhab and addon versions)
openhab 2.1

* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
➜  services git:(master) ✗ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by JoeRu** [comment]
Sorry : this is the Forum-link to the issue:
https://community.openhab.org/t/error-harmony-binding/21488/9
