### ISSUE TITLE
[network] failing tests

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#2577]
On Mac Os the new network tests are failing:

```
Tests run: 4, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.13 sec <<< FAILURE! - in org.openhab.binding.network.internal.PresenceDetectionTest
partialAndFinalCallbackTests(org.openhab.binding.network.internal.PresenceDetectionTest)  Time elapsed: 0.042 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <SYSTEM_PING>
     but: was <JAVA_PING>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:865)
        at org.junit.Assert.assertThat(Assert.java:832)
        at org.openhab.binding.network.internal.PresenceDetectionTest.setUp(PresenceDetectionTest.java:78)

cacheTest(org.openhab.binding.network.internal.PresenceDetectionTest)  Time elapsed: 0.025 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <SYSTEM_PING>
     but: was <JAVA_PING>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:865)
        at org.junit.Assert.assertThat(Assert.java:832)
        at org.openhab.binding.network.internal.PresenceDetectionTest.setUp(PresenceDetectionTest.java:78)

reuseValueTests(org.openhab.binding.network.internal.PresenceDetectionTest)  Time elapsed: 0.022 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <SYSTEM_PING>
     but: was <JAVA_PING>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:865)
        at org.junit.Assert.assertThat(Assert.java:832)
        at org.openhab.binding.network.internal.PresenceDetectionTest.setUp(PresenceDetectionTest.java:78)

threadCountTest(org.openhab.binding.network.internal.PresenceDetectionTest)  Time elapsed: 0.024 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <SYSTEM_PING>
     but: was <JAVA_PING>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:865)
        at org.junit.Assert.assertThat(Assert.java:832)
        at org.openhab.binding.network.internal.PresenceDetectionTest.setUp(PresenceDetectionTest.java:78)

Running org.openhab.binding.network.internal.PresenceDetectionValuesTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in org.openhab.binding.network.internal.PresenceDetectionValuesTest
updateLatencyTests(org.openhab.binding.network.internal.PresenceDetectionValuesTest)  Time elapsed: 0 sec
pingTests(org.openhab.binding.network.internal.PresenceDetectionValuesTest)  Time elapsed: 0.006 sec
isFinishedTests(org.openhab.binding.network.internal.PresenceDetectionValuesTest)  Time elapsed: 0 sec
tcpTests(org.openhab.binding.network.internal.PresenceDetectionValuesTest)  Time elapsed: 0.001 sec
Running org.openhab.binding.network.internal.utils.NetworkUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in org.openhab.binding.network.internal.utils.NetworkUtilsTest
testInterfaceIPS(org.openhab.binding.network.internal.utils.NetworkUtilsTest)  Time elapsed: 0.003 sec
testConvertMethods(org.openhab.binding.network.internal.utils.NetworkUtilsTest)  Time elapsed: 0 sec
Running org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.129 sec - in org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest
testConstructorWrongCacheTime(org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest)  Time elapsed: 0.001 sec
testExpiring(org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest)  Time elapsed: 0.11 sec
testConstructorNoRefrehCommand(org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest)  Time elapsed: 0 sec
testFetchValue(org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest)  Time elapsed: 0.012 sec
testFetchExpiredValue(org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest)  Time elapsed: 0.003 sec

Results :

Failed tests: 
  PresenceDetectionTest.setUp:78 
Expected: is <SYSTEM_PING>
     but: was <JAVA_PING>
  PresenceDetectionTest.setUp:78 
Expected: is <SYSTEM_PING>
     but: was <JAVA_PING>
  PresenceDetectionTest.setUp:78 
Expected: is <SYSTEM_PING>
     but: was <JAVA_PING>
  PresenceDetectionTest.setUp:78 
Expected: is <SYSTEM_PING>
     but: was <JAVA_PING>

Tests run: 24, Failures: 4, Errors: 0, Skipped: 0
```

Which is not completely surprising given the code:

```java
public void setPingMethod(PresenceDetection.PingMethod pingMethod) {
    if (pingMethod == PresenceDetection.PingMethod.SYSTEM_PING && !this.networkUtils.isNativePingWorking()) {
        pingMethod = PresenceDetection.PingMethod.JAVA_PING;
    }

    this.pingMethod = pingMethod;
}
```

@davidgraeff can you please look into this

**Comment by martinvw** [comment]
Some more information:

```
guest192:tmp mvanwinger$ ping -w
ping: invalid option -- w
usage: ping [-AaDdfnoQqRrv] [-c count] [-G sweepmaxsize]
            [-g sweepminsize] [-h sweepincrsize] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern]
            [-S src_addr] [-s packetsize] [-t timeout][-W waittime]
            [-z tos] host
       ping [-AaDdfLnoQqRrv] [-c count] [-I iface] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern] [-S src_addr]
            [-s packetsize] [-T ttl] [-t timeout] [-W waittime]
            [-z tos] mcast-group
Apple specific options (to be specified before mcast-group or host like all options)
            -b boundif           # bind the socket to the interface
            -k traffic_class     # set traffic class socket option
            -K net_service_type  # set traffic class socket options
            -apple-connect       # call connect(2) in the socket
            -apple-time          # display current time
```

**Comment by martinvw** [comment]
Looks correct:

```
guest192:tmp mvanwinger$ ping -W 1 -c 1 localhost
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.038 ms

--- localhost ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.038/0.038/0.038/0.000 ms
```

**Comment by davidgraeff** [comment]
@martinvw Could you try to find the correct argument in the man pages? Apparently "-w" and "-W" have different semantics on linux:

        -w deadline
              Specify a timeout, in seconds, before ping exits  regardless  of
              how  many  packets have been sent or received. In this case ping
              does not stop after count packet are sent, it waits  either  for
              deadline  expire  or until count probes are answered or for some
              error notification from network.

       -W timeout
              Time to wait for a response, in seconds. The option affects only
              timeout  in  absence  of any responses, otherwise ping waits for
              two RTTs.

**Comment by martinvw** [comment]
Then maybe you want this one:

```
     -t timeout
             Specify a timeout, in seconds, before ping exits regardless of how many packets have been received.
```

**Comment by davidgraeff** [comment]
Haha they make it extra hard then. Linux has:

       -t ttl ping only.  Set the IP Time to Live.

So we can't do a reliable feature test. What happens, if someone installs the bsd/gnu ping on MacOS (which is possible via brew I guess), the Operating System special case is not the best option, sigh.

**Comment by martinvw** [comment]
```
-T ttl  Set the IP Time To Live for multicasted packets.  This flag only applies if the ping destination is a multicast address.
```

😢

**Comment by martinvw** [comment]
I would go for an os check and:

```
ping -t 1 -c 1 localhost
```

**Comment by svilenvul** [comment]
I have also a test failure:
```
testExpiring(org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest)  Time elapsed: 0.109 sec  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked:
Wanted but not invoked:
expiringCacheUpdate.requestCacheUpdate();
-> at org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest.testExpiring(ExpiringCacheAsyncTest.java:81)
Actually, there were zero interactions with this mock.

        at org.openhab.binding.network.toberemoved.cache.ExpiringCacheAsyncTest.testExpiring(ExpiringCacheAsyncTest.java:81)

```
