### ISSUE TITLE
Freebox: box orientation (IllegalFormatConversionException)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#2684]
It looks like the way the API provides the box orientation has changed. It looks like it is now a text rather than a numeric value in degrees.
```
2017-09-09 13:17:37.394 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value 'Horizontal' of item Freebox_lcd_orientation with format '%d °': {}
java.util.IllegalFormatConversionException: d != java.lang.String
        at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302) [?:?]
        at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793) [?:?]
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747) [?:?]
        at java.util.Formatter.format(Formatter.java:2520) [?:?]
        at java.util.Formatter.format(Formatter.java:2455) [?:?]
        at java.lang.String.format(String.java:2940) [?:?]
        at org.eclipse.smarthome.core.library.types.StringType.format(StringType.java:50) [98:org.eclipse.smarthome.core:0.9.0.201709071501]
        at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getLabel(ItemUIRegistryImpl.java:344) [137:org.eclipse.smarthome.ui:0.9.0.201709071501]
        at org.eclipse.smarthome.ui.basic.internal.render.AbstractWidgetRenderer.preprocessSnippet(AbstractWidgetRenderer.java:87) [187:org.eclipse.smarthome.ui.basic:0.9.0.201709071501]
        at org.eclipse.smarthome.ui.basic.internal.render.TextRenderer.renderWidget(TextRenderer.java:37) [187:org.eclipse.smarthome.ui.basic:0.9.0.201709071501]
        at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.renderWidget(PageRenderer.java:164) [187:org.eclipse.smarthome.ui.basic:0.9.0.201709071501]
        at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.processChildren(PageRenderer.java:129) [187:org.eclipse.smarthome.ui.basic:0.9.0.201709071501]
        at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.processPage(PageRenderer.java:92) [187:org.eclipse.smarthome.ui.basic:0.9.0.201709071501]
        at org.eclipse.smarthome.ui.basic.internal.servlet.WebAppServlet.service(WebAppServlet.java:172) [187:org.eclipse.smarthome.ui.basic:0.9.0.201709071501]
...
```

**Comment by lolodomo** [comment]
Finally it looks like a bad pattern in the channel definition that uses options:
```
	<channel-type id="lcd_orientation">
		<item-type>Number</item-type>
		<label>Screen Orientation</label>
		<description>Screen Orientation in degrees</description>
		<state pattern="%d °">
			<options>
				<option value="0">Horizontal</option>
				<option value="90">Turned left</option>
				<option value="180">Turned right</option>
				<option value="270">Reversed</option>
			</options>
		</state>
</channel-type>
```
In this case, the pattern should be `%s` and the item type should be `String` ?

**Comment by lolodomo** [comment]
The problem is in the framework. I opened an issue in the right repo: https://github.com/eclipse/smarthome/issues/4248
