### ISSUE TITLE
[HomeKit] Exception "Bad Client Credentials" when adding Openhab as a device in iOS Home app 

### ISSUE THREAD

**Issue by isigmund** [openhab/openhab2-addons#2798]
All of a sudden my items stopped being recognised in the iOS Home app. I did remove the entrie configuration from the Home app and added OpenHab again (I did a ClearPairings OSGi-Console before)
Home app does find openHab and asks for the pairing code. After entering the code it tries to identify items but it does not find any despite the fact that they are correctly tagged.

I did find the following exception in the log while the Home app tries to identify the items:
```
2017-10-23 20:31:37.092 [ERROR] [ulfe.hap.impl.pairing.PairingManager] - Exception encountered while processing pairing request
com.nimbusds.srp6.SRP6Exception: Bad client credentials
        at com.beowulfe.hap.impl.pairing.HomekitSRP6ServerSession.step2(HomekitSRP6ServerSession.java:331) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at com.beowulfe.hap.impl.pairing.SrpHandler.step2(SrpHandler.java:76) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at com.beowulfe.hap.impl.pairing.SrpHandler.handle(SrpHandler.java:47) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at com.beowulfe.hap.impl.pairing.PairingManager.handle(PairingManager.java:44) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at com.beowulfe.hap.impl.connections.HttpSession.handlePairSetup(HttpSession.java:107) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at com.beowulfe.hap.impl.connections.HttpSession.handleRequest(HttpSession.java:51) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [227:org.openhab.io.homekit:2.2.0.201710181101]
        at java.lang.Thread.run(Thread.java:745) [?:?]
```

I am on the current OpenHab2 snapshot just updated today via apt. Any help to resolve this issue is appreciated.

Take care
    Ingo

**Comment by isigmund** [comment]
Never mind - with the newest snapshot this problem seems to be gone.

**Comment by kduytsch** [comment]
Well, got the issue now 

`11:03:39.632 [ERROR] [wulfe.hap.impl.pairing.PairingManager] - Exception encountered while processing pairing request
com.nimbusds.srp6.SRP6Exception: Bad client credentials
        at com.beowulfe.hap.impl.pairing.HomekitSRP6ServerSession.step2(HomekitSRP6ServerSession.java:331) [224:org.openhab.io.homekit:2.2.0]
        at com.beowulfe.hap.impl.pairing.SrpHandler.step2(SrpHandler.java:76) [224:org.openhab.io.homekit:2.2.0]
        at com.beowulfe.hap.impl.pairing.SrpHandler.handle(SrpHandler.java:47) [224:org.openhab.io.homekit:2.2.0]
        at com.beowulfe.hap.impl.pairing.PairingManager.handle(PairingManager.java:44) [224:org.openhab.io.homekit:2.2.0]
        at com.beowulfe.hap.impl.connections.HttpSession.handlePairSetup(HttpSession.java:107) [224:org.openhab.io.homekit:2.2.0]
        at com.beowulfe.hap.impl.connections.HttpSession.handleRequest(HttpSession.java:51) [224:org.openhab.io.homekit:2.2.0]
        at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51) [224:org.openhab.io.homekit:2.2.0]
        at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46) [224:org.openhab.io.homekit:2.2.0]
        at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47) [224:org.openhab.io.homekit:2.2.0]
        at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15) [224:org.openhab.io.homekit:2.2.0]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [224:org.openhab.io.homekit:2.2.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [224:org.openhab.io.homekit:2.2.0]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [224:org.openhab.io.homekit:2.2.0]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299) [224:org.openhab.io.homekit:2.2.0]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [224:org.openhab.io.homekit:2.2.0]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [224:org.openhab.io.homekit:2.2.0]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [224:org.openhab.io.homekit:2.2.0]
        at java.lang.Thread.run(Thread.java:745) [?:?]
`
