### ISSUE TITLE
Homematic: HM-Dis-EP-WM55 display problem UNREACH

### ISSUE THREAD

**Issue by lopez1de** [openhab/openhab2-addons#2803]
I can't  figure it out. After some submits to the HM-Dis-EP-WM55 the device gets unreach for a short time. It looks like it has a general problem when a button on the HM-Dis-EP-WM55 was pressed and a submit gets received to fast after this button press. But even if I don't press any button and send submits by rule, the device gets UNREACH after some submits. 
UNREACH is set to false after a short time, but openhab still has the value true. It never updates the communication status.
`[hingStatusInfoChangedEvent] - 'homematic:HG-HM-Dis-EP-WM55:82cf380a:NEQXXXXXXX' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR)`
The device seems still functioning normally in most cases. Sometimes I have to restart openhab service, because some other homematic device aren't working too.

```
2017-10-24 14:07:27.796 [ERROR] [ematic.handler.HomematicThingHandler] - -100 No answer from device. (sending setValue()
NEQXXXXXXX:3
SUBMIT
0x02,0x0a,0x12,0x41,0x6e,0x77,0x65,0x73,0x65,0x6e,0x64,0x13,0x84,0x0a,0x12,0x46,0x65,0x6e,0x73,0x74,0x65,0x72,0x13,0x84,0x0a,0x12,0x20,0x0a,0x14,0xc0,0x1c,0xd0,0x1D,0xe0,0x16,0xf0,0x03
)
java.io.IOException: -100 No answer from device. (sending setValue()
NEQXXXXXXX:3
SUBMIT
0x02,0x0a,0x12,0x41,0x6e,0x77,0x65,0x73,0x65,0x6e,0x64,0x13,0x84,0x0a,0x12,0x46,0x65,0x6e,0x73,0x74,0x65,0x72,0x13,0x84,0x0a,0x12,0x20,0x0a,0x14,0xc0,0x1c,0xd0,0x1D,0xe0,0x16,0xf0,0x03
)
	at org.openhab.binding.homematic.internal.communicator.parser.RpcResponseParser.parse(RpcResponseParser.java:50)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:90)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:102)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:78)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.client.RpcClient.setDatapointValue(RpcClient.java:281)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:614)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:61)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:593)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:572)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.virtual.DisplayTextVirtualDatapoint.handleCommand(DisplayTextVirtualDatapoint.java:382)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:601)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:61)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:593)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:572)[203:org.openhab.binding.homematic:2.1.0]
	at org.openhab.binding.homematic.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:177)[203:org.openhab.binding.homematic:2.1.0]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:377)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.executeDirectly(SafeMethodCaller.java:218)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:189)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:374)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:47)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2017-10-24 14:07:32.873 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@1f611db' takes more than 5000ms.

```

**Comment by gerrieg** [comment]
Is this still valid with OH 2.3 release?

**Comment by mdicke2s** [comment]
This issue was moved to eclipse/smarthome#5785
