### ISSUE TITLE
[Tellstick]: Telldus live gateway fails when no devices are found

### ISSUE THREAD

**Issue by pikkukoo** [openhab/openhab2-addons#2809]
## Expected Behavior
When connecting Telldus live gateway, the binding should not fail even if no devices are found. When there are sensors but no devices, sensor values should be fetched.

## Current Behavior
When the configured Telldus live account has no devices and the bridge tries to connect, it fails with a null pointer exception:

`
2017-10-26 18:56:51.788 [ERROR] [andler.live.TelldusLiveBridgeHandler] - Failed to update
java.lang.NullPointerException
	at org.openhab.binding.tellstick.handler.live.TelldusLiveBridgeHandler.updateDevices(TelldusLiveBridgeHandler.java:137)[203:org.openhab.binding.tellstick:2.1.0]
	at org.openhab.binding.tellstick.handler.live.TelldusLiveBridgeHandler.refreshDeviceList(TelldusLiveBridgeHandler.java:119)[203:org.openhab.binding.tellstick:2.1.0]
	at org.openhab.binding.tellstick.handler.live.TelldusLiveBridgeHandler$1.run(TelldusLiveBridgeHandler.java:70)[203:org.openhab.binding.tellstick:2.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
`
## Possible Solution
Handle an empty list of devices returned from Telldus Live API and look for existing sensors even if devices are not available.

## Steps to Reproduce (for Bugs)
1. Have a Telldus Live account with only sensors existing (no devices)
2. Try integrating with OpenHAB2 Tellstick binding and Telldus live gateway

## Context
I was trying to only fetch temperature sensor values from my old Tellstick NET via Telldus API. All switches have been deleted and I only have a couple of sensors. The sensor values were not updated to OpenHAB2 because of this null pointer exception. As a workaround (and proof of bug origin) you can create an empty device group to Telldus Live and see that the sync does work after that.

## Your Environment
OpenHAB2 (2.1) on RPi3

**Comment by jakobstenfeldt** [comment]
https://github.com/openhab/openhab2-addons/pull/2910

This should be solved now. 

/J
