### ISSUE TITLE
[astro] Events stopped working coincides with Daylight Savings change

### ISSUE THREAD

**Issue by BillBaird** [openhab/openhab2-addons#2830]
astro sun set#event and sun rise#event stopped firing coinciding with the daylight savings time change.  The event log supports this and in addition, "java.lang.IllegalStateException: Queue full" exceptions were logged starting at midnight on the day that daylight savings began (UTC).  See below for details.

## Expected Behavior
astro events should be unaffected by daylight savings time changes.

## Current Behavior
astro events stopped firing 

## Possible Solution
Events started firing again upon restarting astro

## Steps to Reproduce (for Bugs)
1.  Configure astro sun set#event and rise#events.
2.  Transition across a change to DayLight savings time

## Context
This was simply puzzling until I realized that the failure exactly occurred with that change to DST.

## Your Environment
Running OpenHab2.1 on a raspberry pi.  

Thing configuration (**Arizona, which does not observe Daylight Savings Time**):
```
astro:sun:home   [ geolocation="33.587222,-111.778889", altitude=1700, interval=60 ] {
    Channels:
        Type start : set#start [offset=15]
        Type end : set#end [offset=15]
}
```
Relevant rule:
```
rule PatioLightsSunsetOnEvening
  when
    Channel 'astro:sun:home:set#event' triggered START
  then
    sendCommand(Pool_Circuit9, ON)
end
```
## Logs
Excerpt prior to DST (which transitioned between Saturday 11-04 and Sunday 11-05)
```
2017-11-03 17:32:00.016 [ChannelTriggeredEvent     ] - astro:sun:home:set#event triggered START
2017-11-03 17:35:00.008 [ChannelTriggeredEvent     ] - astro:sun:home:set#event triggered END
2017-11-04 17:31:00.016 [ChannelTriggeredEvent     ] - astro:sun:home:set#event triggered START
2017-11-04 17:34:00.026 [ChannelTriggeredEvent     ] - astro:sun:home:set#event triggered END
    Events stopped after the above
    Restarted OpenHab on 11-07 ... events resume
2017-11-07 17:29:00.006 [ChannelTriggeredEvent     ] - astro:sun:home:set#event triggered START
2017-11-07 17:31:00.008 [ChannelTriggeredEvent     ] - astro:sun:home:set#event triggered END
2017-11-08 17:28:00.021 [ChannelTriggeredEvent     ] - astro:sun:home:set#event triggered START
2017-11-08 17:30:00.007 [ChannelTriggeredEvent     ] - astro:sun:home:set#event triggered END
```
Starting at 00:00:00 on 11-04 (the day prior to DST change, although the day of since Arizona is UTC-07)
```
2017-11-03 23:58:44.350 [INFO ] [onplm.internal.device.MessageHandler] - DimmerRequestReplyHandler: set device 2F.BD.CF to level 0
2017-11-04 00:00:00.092 [INFO ] [thome.binding.astro.internal.job.Job] - Scheduled Astro event-jobs for thing astro:moon:home
2017-11-04 00:00:00.121 [WARN ] [jdbc.internal.JdbcPersistenceService] - JDBC::store: ignore Item 'applianceLinc20B939lhf' because it is UnDefType
2017-11-04 00:00:00.130 [INFO ] [thome.binding.astro.internal.job.Job] - Scheduled Astro event-jobs for thing astro:sun:home
2017-11-04 00:00:00.186 [INFO ] [Manager$ExpressionThreadPoolExecutor] - Expression '0 0 0 4 11 ? 2017' has no future executions anymore
2017-11-04 00:00:00.199 [ERROR] [thome.binding.astro.internal.job.Job] - Queue full
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)[:1.8.0_65]
	at org.eclipse.smarthome.binding.astro.handler.AstroThingHandler.addJobToQueue(AstroThingHandler.java:314)[214:org.eclipse.smarthome.binding.astro:0.9.0.b5]
	at org.eclipse.smarthome.binding.astro.internal.job.Job.schedule(Job.java:58)[214:org.eclipse.smarthome.binding.astro:0.9.0.b5]
	at org.eclipse.smarthome.binding.astro.internal.job.Job.scheduleEvent(Job.java:94)[214:org.eclipse.smarthome.binding.astro:0.9.0.b5]
	at org.eclipse.smarthome.binding.astro.internal.job.Job.scheduleRange(Job.java:114)[214:org.eclipse.smarthome.binding.astro:0.9.0.b5]
	at org.eclipse.smarthome.binding.astro.internal.job.DailyJobSun.run(DailyJobSun.java:63)[214:org.eclipse.smarthome.binding.astro:0.9.0.b5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2017-11-04 00:00:00.210 [ERROR] [thome.binding.astro.internal.job.Job] - Queue full
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)[:1.8.0_65]
```
Starting at midnight on 11-04, there were 22 of these (identical), while prior to that the log was clean.  On 11-05, 11-06, and 11-07 there were 35 of these immediately at midnight.  Since restarting OpenHab, there have not been any.

**Comment by martinvw** [comment]
I fear that it might not be related to dst, see also https://github.com/openhab/openhab2-addons/issues/2668 and others. It's a bug in the 2.1 version of the Astro binding, you can upgrade to the snapshot version of the module or of openHAB or periodically restart your instance.
