### ISSUE TITLE
OH2.2.0-1 KNXnet/IP Tunneling response timeout waiting for confirmation

### ISSUE THREAD

**Issue by starranger3** [openhab/openhab2-addons#3052]
**OH2.2.0-1 KNXnet/IP Tunneling response timeout waiting for confirmation**
I have installed openHAB 2.2.0-1 on my raspberry pi 3 and activated the knx binding. The installation was so far successfull and i can control lights and shutter via the basic ui over the knx bus. However, the reaction is very slow and it takes almost 2-3 seconds till a light is activated or deactivated. I get a lot of warnings on the console, see attached trace dump for the knx address 3/1/1.
I am using a MDT KNX IP Interace in TUNNEL mode, since the IP interface does not support ROUTER mode.

**Trace:**
2017-12-30 11:50:53.369 [vent.ItemStateChangedEvent] - TIstEGWohnen changed from 19.52 to 19.45

==> /var/log/openhab2/openhab.log <==
2017-12-30 11:50:56.371 [WARN ] [.binding.knx.internal.bus.KNXBinding] - Value '19.45' could not be sent to the KNX bus using datapoint 'command DP 3/1/1 TIstEGWohnen, DPT main 0 id 9.001, low priority' - retrying one time: no confirmation reply received for L-Data.req from 1.1.240 to 3/1/1, low priority hop count 6 repeat tpdu 00 80 07 99
2017-12-30 11:50:56.371 [WARN ] [tuwien.auto.calimero                ] - KNXnet/IP Tunneling 192.168.2.100:3671: response timeout waiting for confirmation
tuwien.auto.calimero.exception.KNXTimeoutException: no confirmation reply received for L-Data.req from 1.1.240 to 3/1/1, low priority hop count 6 repeat tpdu 00 80 07 99
        at tuwien.auto.calimero.knxnetip.ClientConnection.doExtraBlockingModes(ClientConnection.java:236) [206:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:269) [206:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:149) [206:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:263) [206:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:304) [206:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.sendRequestWait(KNXNetworkLinkIP.java:240) [206:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:466) [206:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:438) [206:org.openhab.binding.knx:1.11.0]
        at org.openhab.binding.knx.internal.bus.KNXBinding.writeToKNX(KNXBinding.java:149) [206:org.openhab.binding.knx:1.11.0]
        at org.openhab.binding.knx.internal.bus.KNXBinding.internalReceiveUpdate(KNXBinding.java:126) [206:org.openhab.binding.knx:1.11.0]
        at org.openhab.core.binding.AbstractBinding.receiveUpdate(AbstractBinding.java:113) [207:org.openhab.core.compat1x:2.2.0]
        at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:39) [207:org.openhab.core.compat1x:2.2.0]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:82) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:166) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2017-12-30 11:50:59.383 [ERROR] [.binding.knx.internal.bus.KNXBinding] - Value '19.45' could not be sent to the KNX bus using datapoint 'command DP 3/1/1 TIstEGWohnen, DPT main 0 id 9.001, low priority' - giving up after second try: no confirmation reply received for L-Data.req from 1.1.240 to 3/1/1, low priority hop count 6 repeat tpdu 00 80 07 99

**The corresponding entry in the items file:**

//--> Heizung [3/x/x]
//================================================================
//--> EG Wohnen [3/1/x]
Number TIstEGWohnen "EG Wohnen Temperatur Ist [%.1f °C]" 	(gWohnenEG, gTemp)		{knx = "<3/1/1"}

**Comment by kaikreuzer** [comment]
Please note that KNX is a 1.x binding, thus issues should be reported at https://github.com/openhab/openhab1-addons/issues.
