### ISSUE TITLE
[squeezebox] NumberFormatException when processing mixer volume message

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#3080]
@pgfeller  and @phil2fer More info on the NFE

SqueezeboxServerHandler gets NumberFormatException when processing `mixer volume` message.

It appears that a URL encoded `+` sign is occasionally received in the mixer volume message (e.g. %2B2).  Because it is URL encoded, the parseInt call [here](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxServerHandler.java#L593) throws a NumberFormatException.

There probably are two changes required:
- wrap the parseInt call with try/catch
- replace `value` with `decode(value)` in call to parseInt

```
2018-01-04 18:00:09.903 [WARN ] [ebox.handler.SqueezeBoxServerHandler] - Listener received unexpected exception: For input string: "%2B2"
java.lang.NumberFormatException: For input string: "%2B2"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:569) [?:?]
        at java.lang.Integer.parseInt(Integer.java:615) [?:?]
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener$3.updateListener(SqueezeBoxServerHandler.java:595) [242:org.openhab.binding.squeezebox:2.3.0.201801042031]
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler.updatePlayer(SqueezeBoxServerHandler.java:849) [242:org.openhab.binding.squeezebox:2.3.0.201801042031]
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler.access$8(SqueezeBoxServerHandler.java:846) [242:org.openhab.binding.squeezebox:2.3.0.201801042031]
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.handleMixerMessage(SqueezeBoxServerHandler.java:592) [242:org.openhab.binding.squeezebox:2.3.0.201801042031]
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.handlePlayerUpdate(SqueezeBoxServerHandler.java:544) [242:org.openhab.binding.squeezebox:2.3.0.201801042031]
        at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.run(SqueezeBoxServerHandler.java:411) [242:org.openhab.binding.squeezebox:2.3.0.201801042031]
```

**Comment by pgfeller** [comment]
@mhilbush 

Hi Mark, can you verify that the patch did solve the issue? Then we could close this - or, if necessary I would follow up.

with kind regards,
Patrik

**Comment by mhilbush** [comment]
I literally just finished testing it in build 1191.  Looks good.  Thanks for implementing these changes/fixes!
