### ISSUE TITLE
[homematic] Can't convert BOOL value '0' with OnOffTypeConverter

### ISSUE THREAD

**Issue by tbail** [openhab/openhab2-addons#3115]
Since Build 1177 of OH 2.3 i get the above error in the log. Following is a snippet from the log.

```
2018-01-11 09:36:25.224 [ERROR] [ematic.handler.HomematicThingHandler] - Can't convert BOOL value '0' with OnOffTypeConverter for 'LEQxxxxx:0#LOWBAT'
org.openhab.binding.homematic.internal.converter.ConverterTypeException: Can't convert BOOL value '0' with OnOffTypeConverter for 'LEQxxxxx:0#LOWBAT'
        at org.openhab.binding.homematic.internal.converter.type.AbstractTypeConverter.convertFromBinding(AbstractTypeConverter.java:114) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.handler.HomematicThingHandler.updateChannelState(HomematicThingHandler.java:250) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.handler.HomematicThingHandler.updateDatapointState(HomematicThingHandler.java:226) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.onStateUpdated(HomematicBridgeHandler.java:233) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.lambda$0(AbstractHomematicGateway.java:615) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:61) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.eventReceived(AbstractHomematicGateway.java:612) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleEvent(RpcResponseHandler.java:94) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:47) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:64) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.server.BinRpcResponseHandler.run(BinRpcResponseHandler.java:46) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```
The error is confirmed by two other users in the forum and is in build 1182 still available

**Comment by Andirs55** [comment]
I found out that it is not because auf OH but the newest homegear version 0.7.13-1548

**Comment by tbail** [comment]
I am using the nightly and have that problem with build 1958 and 1967. I will check that with homegear and ask if they changed something

**Comment by tbail** [comment]
The problem arises with other homegear versions as well, but the is currently no feedback from the homegear team if they changed something

**Comment by MHerbst** [comment]
I have tested it with a CCU2 and here everything works fine. The CCU sends "true" resp. "false" (tested with the latest CCU firmware). So I'm assuming it is caused by Homegear.

**Comment by tbail** [comment]
We are currently in Diskussion with Sathya (Homegear) He has changed something and is checking if and why that has changed something

**Comment by tbail** [comment]
The problem is fixed it was a problem with homegear. If you have this error update to latest nightly 0.8.0-1979 or latest release version 0.7.xxxx
