### ISSUE TITLE
[YamahaReceiver] Main_Zone thing fails to INITIALIZE

### ISSUE THREAD

**Issue by WizBangCrash** [openhab/openhab2-addons#3138]
I’ve had to rebuild my system and decided to use the latest 2.3.0-SNAPHOT (Build #1188) and I cannot add the Yamaha Receiver binding zones. I always get the error shown below.
I am able to add the bridge, but whenever I add a zone it is always showing as UNINITIALIZED

I am using the PaperUI to add the binding and then select the items from the Inbox. They are discovered with no problems.

## Expected Behaviour
I would expect the Zone to initialise correctly after adding.

## Current Behaviour
Here is a snippet of the openhab.log showing the whole process of installing the binding, adding the bridge and then adding the Main_Zone.

```
2018-01-18 23:36:05.461 [INFO ] [internal.service.FeaturesServiceImpl] - Adding features: openhab-binding-yamahareceiver/[2.3.0.SNAPSHOT,2.3.0.SNAPSHOT]
2018-01-18 23:36:15.782 [INFO ] [internal.service.FeaturesServiceImpl] - Changes to perform:
2018-01-18 23:36:15.784 [INFO ] [internal.service.FeaturesServiceImpl] -   Region: root
2018-01-18 23:36:15.785 [INFO ] [internal.service.FeaturesServiceImpl] -     Bundles to install:
2018-01-18 23:36:15.786 [INFO ] [internal.service.FeaturesServiceImpl] -       mvn:org.eclipse.smarthome.config/org.eclipse.smarthome.config.discovery.upnp/0.10.0-SNAPSHOT
2018-01-18 23:36:15.787 [INFO ] [internal.service.FeaturesServiceImpl] -       mvn:org.eclipse.smarthome.io/org.eclipse.smarthome.io.transport.upnp/0.10.0-SNAPSHOT
2018-01-18 23:36:15.788 [INFO ] [internal.service.FeaturesServiceImpl] -       mvn:org.openhab.binding/org.openhab.binding.yamahareceiver/2.3.0-SNAPSHOT
2018-01-18 23:36:15.797 [INFO ] [internal.service.FeaturesServiceImpl] - Installing bundles:
2018-01-18 23:36:15.798 [INFO ] [internal.service.FeaturesServiceImpl] -   mvn:org.eclipse.smarthome.config/org.eclipse.smarthome.config.discovery.upnp/0.10.0-SNAPSHOT
2018-01-18 23:36:15.812 [INFO ] [internal.service.FeaturesServiceImpl] -   mvn:org.eclipse.smarthome.io/org.eclipse.smarthome.io.transport.upnp/0.10.0-SNAPSHOT
2018-01-18 23:36:15.833 [INFO ] [internal.service.FeaturesServiceImpl] -   mvn:org.openhab.binding/org.openhab.binding.yamahareceiver/2.3.0-SNAPSHOT
2018-01-18 23:36:15.843 [DEBUG] [org.openhab.binding.yamahareceiver  ] - BundleEvent INSTALLED - org.openhab.binding.yamahareceiver
2018-01-18 23:36:15.916 [DEBUG] [org.openhab.binding.yamahareceiver  ] - BundleEvent RESOLVED - org.openhab.binding.yamahareceiver
2018-01-18 23:36:15.938 [DEBUG] [org.openhab.binding.yamahareceiver  ] - BundleEvent STARTING - org.openhab.binding.yamahareceiver
2018-01-18 23:36:15.940 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - Bundle Considered for SPI providers: org.openhab.binding.yamahareceiver
2018-01-18 23:36:15.942 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - No 'SPI-Provider' Manifest header. Skipping bundle: org.openhab.binding.yamahareceiver
2018-01-18 23:36:15.949 [DEBUG] [org.openhab.binding.yamahareceiver  ] - BundleEvent STARTED - org.openhab.binding.yamahareceiver
2018-01-18 23:36:15.953 [DEBUG] [org.openhab.binding.yamahareceiver  ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.UpnpDiscoveryParticipant}={component.name=org.openhab.binding.yamahareceiver.internal.discovery.YamahaDiscoveryParticipant, component.id=187, service.id=315, service.bundleid=210, service.scope=bundle} - org.openhab.binding.yamahareceiver
2018-01-18 23:36:15.961 [DEBUG] [org.openhab.binding.yamahareceiver  ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={component.name=org.openhab.binding.yamahareceiver.internal.YamahaReceiverHandlerFactory, component.id=188, service.id=316, service.bundleid=210, service.scope=bundle} - org.openhab.binding.yamahareceiver
2018-01-18 23:36:15.966 [DEBUG] [org.openhab.binding.yamahareceiver  ] - BundleEvent [unknown:512] - org.openhab.binding.yamahareceiver
2018-01-18 23:36:15.968 [INFO ] [internal.service.FeaturesServiceImpl] - Starting bundles:
2018-01-18 23:36:15.972 [INFO ] [internal.service.FeaturesServiceImpl] -   org.eclipse.smarthome.config.discovery.upnp/0.10.0.201801152239
2018-01-18 23:36:15.975 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - Bundle Considered for SPI providers: org.eclipse.smarthome.config.discovery.upnp
2018-01-18 23:36:15.976 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - No 'SPI-Provider' Manifest header. Skipping bundle: org.eclipse.smarthome.config.discovery.upnp
2018-01-18 23:36:15.990 [DEBUG] [discovery.YamahaDiscoveryParticipant] - Discovered a Yamaha Receiver 'RX-A3070 FE28B5' model 'RX-A3070' thing with UDN '9ab0c000-f668-11de-9976-00a0defe28b5'
2018-01-18 23:36:15.992 [DEBUG] [discovery.YamahaDiscoveryParticipant] - Discovered a Yamaha Receiver 'RX-A3070 FE28B5' model 'RX-A3070' thing with UDN '9ab0c000-f668-11de-9976-00a0defe28b5'
2018-01-18 23:36:16.003 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'yamahareceiver:yamahaAV:9ab0c000_f668_11de_9976_00a0defe28b5' to inbox.
2018-01-18 23:36:16.015 [INFO ] [internal.service.FeaturesServiceImpl] -   org.eclipse.smarthome.io.transport.upnp/0.10.0.201801152239
2018-01-18 23:36:16.016 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - Bundle Considered for SPI providers: org.eclipse.smarthome.io.transport.upnp
2018-01-18 23:36:16.019 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - No 'SPI-Provider' Manifest header. Skipping bundle: org.eclipse.smarthome.io.transport.upnp
2018-01-18 23:36:16.067 [INFO ] [internal.service.FeaturesServiceImpl] - Done.
2018-01-18 23:36:55.900 [DEBUG] [org.openhab.binding.yamahareceiver  ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=319, service.bundleid=210, service.scope=singleton} - org.openhab.binding.yamahareceiver
2018-01-18 23:36:55.935 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'yamahareceiver:zone:9ab0c000_f668_11de_9976_00a0defe28b5:Main_Zone' to inbox.
2018-01-18 23:36:55.938 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'yamahareceiver:zone:9ab0c000_f668_11de_9976_00a0defe28b5:Zone_2' to inbox.
2018-01-18 23:36:55.941 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'yamahareceiver:zone:9ab0c000_f668_11de_9976_00a0defe28b5:Zone_3' to inbox.
2018-01-18 23:36:55.944 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'yamahareceiver:zone:9ab0c000_f668_11de_9976_00a0defe28b5:Zone_4' to inbox.
2018-01-18 23:36:56.053 [DEBUG] [discovery.YamahaDiscoveryParticipant] - Discovered a Yamaha Receiver 'RX-A3070 FE28B5' model 'RX-A3070' thing with UDN '9ab0c000-f668-11de-9976-00a0defe28b5'
2018-01-18 23:37:02.932 [INFO ] [org.quartz.core.QuartzScheduler     ] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED started.
2018-01-18 23:37:16.585 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.yamahareceiver.handler.YamahaZoneThingHandler@402a36b5': org/eclipse/smarthome/core/thing/type/TypeResolver
java.lang.NoClassDefFoundError: org/eclipse/smarthome/core/thing/type/TypeResolver
	at org.openhab.binding.yamahareceiver.internal.ChannelsTypeProviderPreset.<init>(ChannelsTypeProviderPreset.java:80) ~[?:?]
	at org.openhab.binding.yamahareceiver.handler.YamahaZoneThingHandler.initialize(YamahaZoneThingHandler.java:132) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.201801152239]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.201801152239]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.ClassNotFoundException: org.eclipse.smarthome.core.thing.type.TypeResolver cannot be found by org.openhab.binding.yamahareceiver_2.3.0.201801141430
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:410) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
	... 12 more
2018-01-18 23:37:16.595 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while initializing handler of thing 'yamahareceiver:zone:9ab0c000_f668_11de_9976_00a0defe28b5:Main_Zone': org/eclipse/smarthome/core/thing/type/TypeResolver
java.lang.NoClassDefFoundError: org/eclipse/smarthome/core/thing/type/TypeResolver
	at org.openhab.binding.yamahareceiver.internal.ChannelsTypeProviderPreset.<init>(ChannelsTypeProviderPreset.java:80) ~[?:?]
	at org.openhab.binding.yamahareceiver.handler.YamahaZoneThingHandler.initialize(YamahaZoneThingHandler.java:132) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.201801152239]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.201801152239]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.ClassNotFoundException: org.eclipse.smarthome.core.thing.type.TypeResolver cannot be found by org.openhab.binding.yamahareceiver_2.3.0.201801141430
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:410) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
	... 12 more
2018-01-18 23:37:23.616 [INFO ] [org.quartz.core.QuartzScheduler     ] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED started.
```

## Possible Solution
N/A

## Steps to Reproduce (for Bugs)
1. User PaperUI
2. Add the YamahaReceiver Binding
3. Wait for the receiver to appear in the Inbox
4. Add the bridge thing
5. Wait for the Zones to appear in the Inbox
6. Add the Main_Zone

Default settings are used for all steps above.

## Your Environment

* Version used: openHAB 2.3.0-SNAPSHOT (Build #1188)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): DSM Synology 6.1, Java 8.151
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): DSM 6.1

**Comment by WizBangCrash** [comment]
Re-tested on openHAB 2.3.0-SNAPSHOT (Build #1189) and still getting the same error with this binding.
Is anyone else experiencing this?
I have now reinstalled openHAB from scratch 4 times, but get the issue everytime.
I've also tried adding the thing manually and get a similar problem.
I have also downloaded the hot fix fro here: https://www.dropbox.com/sh/8y8gg6b4rnb7iuo/AADaIORB107VG9sgNNjF4ZjWa?dl=0&lst= but have exactly the same issue.
Is there anyone out there using the binding on an RX-A3070?

**Comment by WizBangCrash** [comment]
So I've just reverted back to the openHAB-2.2.0 release and attempted to add the an RX-A3070 Yamaha Receiver and all went well. The receiver and it's zone were added with no problems and INITIALIZED 👍 
Looks like I am stuck with 2.2.0 for now until this issue is fixed in the 2.3.0 branch.
@martinvw  or @kaikreuzer are you aware of this one?

**Comment by martinvw** [comment]
That is most likely related to the PR of @sjka were I was stilling waiting for this answer...

**Comment by kaikreuzer** [comment]
@martinvw Can you post a link to the PR you are referring to?

**Comment by martinvw** [comment]
Yes i can

https://github.com/openhab/openhab2-addons/pull/2997

**Comment by kaikreuzer** [comment]
Thanks. And can you now explain me why you closed this issue (sorry, if I am a bit stupid...)?
What I read is that 2.2 worked and currently in 2.3 it does not work. Or do you claim that it works in 2.3 since #2997 (which was right after the release)?

**Comment by martinvw** [comment]
But I only merged that PR today, since I asked a question which I did not yet receive an answer for.

![image](https://user-images.githubusercontent.com/2625279/35196186-0687d9f4-fecf-11e7-9fe5-c421569b965e.png)

**Comment by kaikreuzer** [comment]
Oh, sorry, I only noticed now that #2977 has been merged today, not in December already. So please forget my question :-)
