### ISSUE TITLE
[avmfritz] NullPointerException in ThingHandler.handleCommand()

### ISSUE THREAD

**Issue by Marmo** [openhab/openhab2-addons#3141]
Binding version: 2.2.0
OpenHAB Package version: 2.2.0-1

# Expected behaviour
Power outlet is switched on OpenHAB  command.
# Actual behaviour
Upon switching the switch (Basic UI or HABPanel) nothing happens and the following Error is logged:

```
[ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.avmfritz.handler.DeviceHandler@113317': null
java.lang.NullPointerException: null
	at org.openhab.binding.avmfritz.handler.DeviceHandler.handleCommand(DeviceHandler.java:162) [250:org.openhab.binding.avmfritz:2.2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at com.sun.proxy.$Proxy163.handleCommand(Unknown Source) [250:org.openhab.binding.avmfritz:2.2.0]
	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:72) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]
```

According to Paper UI the FRITZ!Powerline 546E-Thing is correctly configured and the Switch Item is linked to its power outlet channel via text based configuration.

Here are some debug log entries from the avmfritz binding, which, as far as I can tell, show that the Thing is correctly cconfigured:

```
2018-01-19 13:06:06.712 [DEBUG] [nding.avmfritz.handler.DeviceHandler] - polling FRITZ!Box avmfritz:FRITZ_Powerline_546E_Solo:192_168_2_103
2018-01-19 13:06:06.760 [DEBUG] [ternal.hardware.FritzahaWebInterface] - GETting URL http://192.168.2.103:80/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=381e2190d275d1c1
2018-01-19 13:06:06.955 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 200
2018-01-19 13:06:06.981 [DEBUG] [nal.hardware.FritzahaContentExchange] - HTTP response 200
2018-01-19 13:06:07.002 [DEBUG] [nal.hardware.FritzahaContentExchange] - response complete: <devicelist version="1"><device identifier="*:*:*:*:*:*" id="1000" functionbitmask="640" fwversion="06.50" manufacturer="AVM" productname="FRITZ!Powerline 546E"><present>1</present><name>FRITZ!Powerline 546E</name><switch><state>0</state><mode>auto</mode><lock>0</lock></switch><powermeter><power>0</power><energy>42139</energy></powermeter></device></devicelist>

2018-01-19 13:06:07.108 [DEBUG] [nding.avmfritz.handler.DeviceHandler] - set device model: org.openhab.binding.avmfritz.internal.ahamodel.DeviceModel@a26bdb[ain=*:*:*:*:*:*,bitmask=640,isDectRepeater=false,isPowermeter=true,isTempSensor=false,isSwitchableOutlet=true,isHeatingThermostat=false,id=1000,manufacturer=AVM,productname=FRITZ!Powerline 546E,fwversion=06.50,present=1,name=FRITZ!Powerline 546E,org.openhab.binding.avmfritz.internal.ahamodel.SwitchModel@809f41[state=0,mode=AUTOMATIC,lock=0,devicelock=<null>],org.openhab.binding.avmfritz.internal.ahamodel.PowerMeterModel@180bc0d[power=0.000,energy=42.139],<null>,<null>]
```

Completely removing Item, Thing and Binding and re-adding them did not change anything.

**Comment by cweitkamp** [comment]
I will look into this. One question: Which FRITZ!OS Version do you run on the Powerline device?

@martinvw Please assign me to this issue. Thanks.

**Comment by Marmo** [comment]
@cweitkamp FritzOS version is 06.50, added this to the opening post.

**Comment by cweitkamp** [comment]
Thank you.

Can you try this version here: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.avmfritz/2.3.0-SNAPSHOT/. Uninstall the original binding first and then put the new .jar file into your addons folder. After that remove the Thing and re-add it again. Happy to hear feedback.

**Comment by Marmo** [comment]
Tried it. The error persists. In the following log included an error that was raised when adding the thing (I guess this was there also with the 2.2.0 version of the binding) and might be the root cause of the second error.

```
2018-01-20 16:35:12.728 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'avmfritz:FRITZ_Powerline_546E_Solo:192_168_2_103' to inbox.
2018-01-20 16:39:01.010 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null
java.lang.NullPointerException: null
	at org.openhab.binding.avmfritz.handler.DeviceHandler.handleCommand(DeviceHandler.java:162) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:243) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:290) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]
2018-01-20 16:39:51.599 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.avmfritz.handler.DeviceHandler@b254b0': null
java.lang.NullPointerException: null
	at org.openhab.binding.avmfritz.handler.DeviceHandler.handleCommand(DeviceHandler.java:162) [265:org.openhab.binding.avmfritz:2.3.0.201801201309]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at com.sun.proxy.$Proxy155.handleCommand(Unknown Source) [265:org.openhab.binding.avmfritz:2.3.0.201801201309]
	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:72) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:?]

```

**Comment by cweitkamp** [comment]
Uff, that's nearly impossible because the code line DeviceHandler.java:162 doesn't exist anymore in the version I which had been linked. Just to be sure the linked version is the correct one, I attached another .jar file. Sometimes jfrog doesn't provide the version to be expected. Please give it another try. Thanks.

[org.openhab.binding.avmfritz-2.3.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/1649085/org.openhab.binding.avmfritz-2.3.0-SNAPSHOT.jar.zip)

**Comment by Marmo** [comment]
Success! After, exchanging the jar, restarting OpenHAB and removing&re-adding the Thing there is no more error in the log and the power outlet switches on and off :smiley: Thank you! :+1:

**Comment by Marmo** [comment]
Strangely, now two Things are added to the inbox:
```
2018-01-21 07:54:19.087 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'avmfritz:FRITZ_Powerline_546E_Solo:192_168_2_103' to inbox.
2018-01-21 07:57:46.677 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'avmfritz:FRITZ_Powerline_546E:192_168_2_103:**_**_**_**_**_**' to inbox.
```
The one I added and reported to work was the first one, without ain/MAC in the identifier.

**Comment by cweitkamp** [comment]
Sounds good. I'm glad that it's working. We now have to wait for PR #3022 to be merged.

> now two Things are added to the inbox.

That's the way it works for now. The FRITZ!Powerline can be used in stand-alone mode like you do. It acts like a Bridge on its own. You are able to operate other DECT devices attached to it.

**Comment by thucke** [comment]
After upgrade to 2.3.0 the issue still occurs in my installation.
I've removed Items, Things and Binding and reinstalled all after restart - nothing helped.
Did this bugfix really find its way into the recent version?

**Comment by cweitkamp** [comment]
> Did this bugfix really find its way into the recent version?

Yes, it has been merged. Please append your current exception at thus issue. I will look into it.

**Comment by thucke** [comment]
Hi @cweitkamp ,
thank you for this quick response.
Maybe I was a bit too eager in in posting.
I stuggled a bit around with my Fritz! configuration with the result that all is working now.
I had to change the access method to "Powerline bridge" to include the adapter into my Fritz!Home setup.

**Comment by cweitkamp** [comment]
@thucke I am glad you got it working.
