### ISSUE TITLE
Squeezebox Binding 2.2 Problems with playSound

### ISSUE THREAD

**Issue by frost80** [openhab/openhab2-addons#3175]
Hi there,
since 2 weeks i try to get playSound in a rule get to work with openhab 2.2 stable. 
I work with the Logitech Media Server Version: 7.7.5 on the same device Openhab is running. 
The sinks are 2 x Squeezebox + 1x Squeezebox touch.
When i restart the Server playSound often works, not ever. But after a few hours it stops working.
Then the music is getting loud (60 notification Sound Volume) and on the Squeezebox there is the file listed in the display that should play but it doesn't. After a while the sounds goes off (Volume 0) and later on (25)
Openhab is installed on Linux Mint 17.1.
 

Things are installed with Paper UI.
Logitech Media Server [server] - squeezebox:squeezeboxserver:9A9BF401-7BA5-4561-80B1-D33726583417
Mac Adress 00:04:20:2d:43:e5

IP Adresse Server 10.1.2.150
Web Port: 9000
Cli Port:9090

I can see every Squeezebox and the Server under Things

Items in File:
Dimmer kueche_Ansage	"LautstÃ¤rke Durchsage" (SB_Kueche)      {channel="squeezebox:squeezeboxplayer:9A9BF401-7BA5-4561-80B1-D33726583417:0004202d43e5:notificationSoundVolume"}
String kueche_stream	"Stream"               (SB_Kueche)      {channel="squeezebox:squeezeboxplayer:9A9BF401-7BA5-4561-80B1-D33726583417:0004202d43e5:stream"}

rule:
rule "Klingel Squeezebox Küche"
	when
		Item Klingel_Haustuer changed to OFF
	then
                 var String sinkKitchen = "squeezebox:squeezeboxplayer:9A9BF401-7BA5-4561-80B1-D33726583417:0004202d43e5"

playSound(sinkKitchen, "BigBen.mp3")

end

openhab log:
2018-01-26 17:43:59.770 [DEBUG] [eezebox.internal.SqueezeBoxAudioSink] - Processing audioStream http://10.1.2.150:8080/audio/6d289f2b-070a-468d-be1f-e7780f19ec24.mp3 of format AudioFormat [codec=MP3, container=NONE, ]
2018-01-26 17:43:59.770 [DEBUG] [ebox.handler.SqueezeBoxPlayerHandler] - Play notification sound on player 00:04:20:2d:43:e5 at URI http://10.1.2.150:8080/audio/6d289f2b-070a-468d-be1f-e7780f19ec24.mp3
2018-01-26 17:43:59.770 [DEBUG] [ebox.handler.SqueezeBoxPlayerHandler] - Cur State: vol=25, mut=NOT MUTED, pwr=ON, stp=NOT STOPPED, ctl=PLAYING, shf=OFF, rpt=OFF, tix=0, tnm=1, tim=691
2018-01-26 17:43:59.770 [DEBUG] [ebox.handler.SqueezeBoxPlayerHandler] - Setting up player for notification
2018-01-26 17:43:59.771 [DEBUG] [ebox.handler.SqueezeBoxServerHandler] - Sending command: 00:04:20:2d:43:e5 stop
2018-01-26 17:43:59.776 [DEBUG] [ebox.handler.SqueezeBoxServerHandler] - Sending command: 00:04:20:2d:43:e5 mixer volume 60
2018-01-26 17:44:03.781 [WARN ] [ebox.handler.SqueezeBoxPlayerHandler] - TIMEOUT after 4000 waiting for volume to update!
2018-01-26 17:44:03.782 [DEBUG] [ebox.handler.SqueezeBoxPlayerHandler] - Playing notification
2018-01-26 17:44:03.782 [DEBUG] [ebox.handler.SqueezeBoxServerHandler] - Sending command: 00:04:20:2d:43:e5 playlist add http://10.1.2.150:8080/audio/6d289f2b-070a-468d-be1f-e7780f19ec24.mp3
2018-01-26 17:44:05.172 [INFO ] [lipse.smarthome.io.net.exec.ExecUtil] - executed commandLine 'wget http://admin:flower112@10.1.2.205/Streaming/channels/101/picture -O  /var/lib/openhab2/tmp/Türklingel2.jpg'
2018-01-26 17:44:08.786 [WARN ] [ebox.handler.SqueezeBoxPlayerHandler] - TIMEOUT after 5000 waiting for playlist to update!
2018-01-26 17:44:08.786 [DEBUG] [ebox.handler.SqueezeBoxServerHandler] - Sending command: 00:04:20:2d:43:e5 mixer volume 25
2018-01-26 17:44:12.790 [WARN ] [ebox.handler.SqueezeBoxPlayerHandler] - TIMEOUT after 4000 waiting for volume to update!
2018-01-26 17:44:18.195 [DEBUG] [ebox.handler.SqueezeBoxServerHandler] - Sending command: players 0

Sometimes in the log is
2018-01-26 17:43:43.000 [DEBUG] [ebox.handler.SqueezeBoxPlayerHandler] - Could not get album art data
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851) [?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) [?:?]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848) [?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) [?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) [?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) [?:?]
	at org.openhab.binding.squeezebox.internal.utils.HttpUtils.getData(HttpUtils.java:89) [240:org.openhab.binding.squeezebox:2.2.0]
	at org.openhab.binding.squeezebox.handler.SqueezeBoxPlayerHandler.coverArtChangeEvent(SqueezeBoxPlayerHandler.java:370) [240:org.openhab.binding.squeezebox:2.2.0]
	at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener$13.updateListener(SqueezeBoxServerHandler.java:728) [240:org.openhab.binding.squeezebox:2.2.0]
	at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler.updatePlayer(SqueezeBoxServerHandler.java:831) [240:org.openhab.binding.squeezebox:2.2.0]
	at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler.access$8(SqueezeBoxServerHandler.java:815) [240:org.openhab.binding.squeezebox:2.2.0]
	at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.handleStatusMessage(SqueezeBoxServerHandler.java:725) [240:org.openhab.binding.squeezebox:2.2.0]
	at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.handlePlayerUpdate(SqueezeBoxServerHandler.java:532) [240:org.openhab.binding.squeezebox:2.2.0]
	at org.openhab.binding.squeezebox.handler.SqueezeBoxServerHandler$SqueezeServerListener.run(SqueezeBoxServerHandler.java:410) [240:org.openhab.binding.squeezebox:2.2.0]

Has anybody an idea?

Thanks very much

**Comment by frost80** [comment]
There is another thing: The LMS in PaperUI /Things has to set up the IP-Adress to 10.1.2.150 after every reboot. After reboot there is the IP "re"set to 127.0.0.1
2018-01-26 18:15:04.117 [DEBUG] [ebox.handler.SqueezeBoxServerHandler] - listener connection started to server 127.0.0.1:9090

But with 127.0.0.1 the control of the Squeezebox works also well as with 10.1.2.150.

**Comment by mhilbush** [comment]
@frost80 I responded to your forum post on this topic.  We can try to sort out the issue over there.

**Comment by frost80** [comment]
Moved to:
https://community.openhab.org/t/playsound-mit-squeezebox/39282

**Comment by mhilbush** [comment]
For future reference, the 7.7.5 version of LMS was causing the issue.  After upgrading to LMS version 7.9.*, the problem went away.

At the next binding update, I will add this known issue to the README.
