### ISSUE TITLE
[homekit] Bad client credentials

### ISSUE THREAD

**Issue by kduytsch** [openhab/openhab2-addons#3339]
This is to re-open : https://github.com/openhab/openhab2-addons/issues/2798

```
11:03:39.632 [ERROR] [wulfe.hap.impl.pairing.PairingManager] - Exception encountered while processing pairing request com.nimbusds.srp6.SRP6Exception: Bad client credentials 
	at com.beowulfe.hap.impl.pairing.HomekitSRP6ServerSession.step2(HomekitSRP6ServerSession.java:331) [224:org.openhab.io.homekit:2.2.0] 
	at com.beowulfe.hap.impl.pairing.SrpHandler.step2(SrpHandler.java:76) [224:org.openhab.io.homekit:2.2.0] 
	at com.beowulfe.hap.impl.pairing.SrpHandler.handle(SrpHandler.java:47) [224:org.openhab.io.homekit:2.2.0] 
	at com.beowulfe.hap.impl.pairing.PairingManager.handle(PairingManager.java:44) [224:org.openhab.io.homekit:2.2.0] 
	at com.beowulfe.hap.impl.connections.HttpSession.handlePairSetup(HttpSession.java:107) [224:org.openhab.io.homekit:2.2.0] 
	at com.beowulfe.hap.impl.connections.HttpSession.handleRequest(HttpSession.java:51) [224:org.openhab.io.homekit:2.2.0] 
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51) [224:org.openhab.io.homekit:2.2.0] 
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46) [224:org.openhab.io.homekit:2.2.0] 
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47) [224:org.openhab.io.homekit:2.2.0] 
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15) [224:org.openhab.io.homekit:2.2.0] 
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [224:org.openhab.io.homekit:2.2.0] 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [224:org.openhab.io.homekit:2.2.0] 
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [224:org.openhab.io.homekit:2.2.0] 
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299) [224:org.openhab.io.homekit:2.2.0] 
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [224:org.openhab.io.homekit:2.2.0] 
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [224:org.openhab.io.homekit:2.2.0] 
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [224:org.openhab.io.homekit:2.2.0] 
	at java.lang.Thread.run(Thread.java:745) [?:?]
```

**Comment by raaahbin** [comment]
And... it just happened to me. Added a couple of devices and now I'm getting the bad client credentials message. Have followed the steps here (https://github.com/openhab/openhab2-addons/issues/1822#issuecomment-297860690) as I was also getting the MAC address error, but having done that apparently successfully, I still can't pair to any iOS device.

It had been working perfectly up until today, at which point I added a new ZWave device to the system. The device is working perfectly with OpenHAB, but it seems along the way, OpenHAB's HomeKit is now dead.

**Comment by raaahbin** [comment]
Right - I'm not sure how I've done it, but I've got rid of that error. I followed all the steps in the comment above, and then after shutting down and re-launching OH2, I issued the  `smarthome:homekit clearPairings` command _again_, before attempting to pair the iOS device. I've now got everything up and running, although I'm worried that it might not survive a restart of OH2... that will be the next test.

**Comment by raaahbin** [comment]
OK - it seems the only bug I now have is the "losing HomeKit when you restart OpenHAB" bug - my behaviour (using the command above) is exactly the same as described in that thread.

**Comment by J-N-K** [comment]
Please check if this is still the case with a recent version of OH (i.e. 2.5 SNAPSHOT >= 1601).

**Comment by EjvindHald** [comment]
I keep getting the same error.

Please note these messages below which might be interesting for debugging purposes:
Entering second stage of pair for openHAB
Bad client credentials
... and something with Unauthorized connection keep alive, which I do not know what is.

Here is a subset of my trace log:

2019-06-05 22:18:03.274 [INFO ] [.hap.impl.http.impl.AccessoryHandler] - Terminated homekit connection from /192.168.1.242:49705

2019-06-05 22:18:03.206 [DEBUG] [ulfe.hap.impl.pairing.PairingManager] - Entering second stage of pair for openHAB
2019-06-05 22:18:03.256 [ERROR] [ulfe.hap.impl.pairing.PairingManager] - Exception encountered while processing pairing request
com.nimbusds.srp6.SRP6Exception: Bad client credentials
        at com.beowulfe.hap.impl.pairing.HomekitSRP6ServerSession.step2(HomekitSRP6ServerSession.java:270) ~[191:org.openhab.io.homekit:2.5.0.201902270358]
        at com.beowulfe.hap.impl.pairing.SrpHandler.step2(SrpHandler.java:76) ~[191:org.openhab.io.homekit:2.5.0.201902270358]
        at com.beowulfe.hap.impl.pairing.SrpHandler.handle(SrpHandler.java:47) ~[191:org.openhab.io.homekit:2.5.0.201902270358]
        at com.beowulfe.hap.impl.pairing.PairingManager.handle(PairingManager.java:44) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at com.beowulfe.hap.impl.connections.HttpSession.handlePairSetup(HttpSession.java:109) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at com.beowulfe.hap.impl.connections.HttpSession.handleRequest(HttpSession.java:53) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:54) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:47) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:52) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:17) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [191:org.openhab.io.homekit:2.5.0.201902270358]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-06-05 22:18:03.258 [INFO ] [ap.impl.http.HomekitClientConnection] - 401 /pair-setup
2019-06-05 22:18:03.259 [TRACE] [pl.http.impl.NettyHomekitHttpService] - WRITE UnpooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 256) [/192.168.1.242:49705]:
00000000 48 54 54 50 2F 31 2E 31 20 34 30 31 20 55 6E 61 HTTP/1.1 401 Una
00000010 75 74 68 6F 72 69 7A 65 64 0D 0A 43 6F 6E 74 65 uthorized..Conte
00000020 6E 74 2D 4C 65 6E 67 74 68 3A 20 30 0D 0A 43 6F nt-Length: 0..Co
00000030 6E 6E 65 63 74 69 6F 6E 3A 20 6B 65 65 70 2D 61 nnection: keep-a
00000040 6C 69 76 65 0D 0A 0D 0A                         live....

**Comment by J-N-K** [comment]
Did you try uninstalling homekit, deleting homekit.json, re-installing?

**Comment by EjvindHald** [comment]
Yes, I have tried that. 
But the very same OH version and Homekit build has working fine previously. I have tried many things, but not been able to finde root cause.

**Comment by EjvindHald** [comment]
This is solved now. I have entered the correct Homekit code in my config file, but on Iphone itself, I made a type error with this 8 digit number when trying to pair. This obviously result in an error. However, a more precise error message would have saved many hours for me.

**Comment by J-N-K** [comment]
Thanks for your feedback. I‘ll add a note to the documentation that „Bad Client Credentials“ might be caused by incorrect pairing pin.
