### ISSUE TITLE
[Mi Home] NPE while sending command

### ISSUE THREAD

**Issue by C4ET4uK** [openhab/openhab2-addons#3384]
## Expected Behavior

Command to items should be processed without errors.

## Current Behavior

When I try to send command to xiaomi item via gateway I get NPE.

## Possible Solution

As I see for sending command to Xiomi item used cipher of two values
1.Developer key
2. Gateway token.
As I see in the code gateway token should be recieved from the heartbeat messages but, when I debugging it I didn't recieve any heartbeat message. So the gatewayToken field is null and I get NPE while trying to encode a key.

```
21:57:05.152 [ERROR] [rnal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.mihome.handler.XiaomiAqaraActorSwitch2Handler@6a0d5e6a': null
java.lang.NullPointerException: null
        at org.openhab.binding.mihome.internal.EncryptionHelper.encrypt(EncryptionHelper.java:69) [202:org.openhab.binding.mihome:2.2.0]
        at org.openhab.binding.mihome.internal.EncryptionHelper.encrypt(EncryptionHelper.java:42) [202:org.openhab.binding.mihome:2.2.0]
        at org.openhab.binding.mihome.handler.XiaomiBridgeHandler.getEncryptedKey(XiaomiBridgeHandler.java:291) [202:org.openhab.binding.mihome:2.2.0]
        at org.openhab.binding.mihome.handler.XiaomiBridgeHandler.createDataJsonString(XiaomiBridgeHandler.java:277) [202:org.openhab.binding.mihome:2.2.0]
        at org.openhab.binding.mihome.handler.XiaomiBridgeHandler.writeToDevice(XiaomiBridgeHandler.java:268) [202:org.openhab.binding.mihome:2.2.0]
        at org.openhab.binding.mihome.handler.XiaomiAqaraActorSwitch2Handler.execute(XiaomiAqaraActorSwitch2Handler.java:48) [202:org.openhab.binding.mihome:2.2.0]
        at org.openhab.binding.mihome.handler.XiaomiDeviceBaseHandler.handleCommand(XiaomiDeviceBaseHandler.java:104) [202:org.openhab.binding.mihome:2.2.0]
        at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at com.sun.proxy.$Proxy138.handleCommand(Unknown Source) [202:org.openhab.binding.mihome:2.2.0]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:72) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
        at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
```
But I see the token field in the get_id_list_ack message. But if I try to just put it into gatewayToken I get "invalid key" message so probably the encoding mechanism is also changed.

## Steps to Reproduce (for Bugs)

1. Start openhab 2.2
2. Add Mi Home addon
3. Discover gateway
4. Specify developer key
5. Add any thing.
6. Add item for thing.
7. Try to send command

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
OpenHab 2.2
java version "1.8.0_111"
Windows 10

**Comment by dimalo** [comment]
Hi @C4ET4uK 
Thanks for your nice and detailed report!
You are right, the missing information should be catched and a proper message displayed.
I will get to it in the near future...
Cheers!

**Comment by C4ET4uK** [comment]
I tried to fix it myself and provide pull request, but I didn't find how exactly this key should be encoded. :-(

**Comment by dimalo** [comment]
When the gateway is set to dev. mode, it sends a new token every 10sec. so even having the first of them via the response in the get_id_list_ack message won't make things run.
The best solution would be to fix the missing heartbeat messages, which probably are missing because your OH instance doesn't receive multicast traffic in your network.
