### ISSUE TITLE
[yamahareceiver binding] Party mode and Scenes for Yamaha receivers

### ISSUE THREAD

**Issue by teqnet** [openhab/openhab2-addons#3393]
## Expected Behavior
It would be nice to be able to enable Party mode and Scenes for all the zones on the yamaha receiver.
I made a post to this thread:
https://community.openhab.org/t/yamahareceiver-binding-has-issue-with-zone-2/19731/45
I think that this has been done before for other automation systems:
https://www.npmjs.com/package/yamaha-nodejs
It would be great to have it in OpenHab as well.

## Current Behavior
It's not possible to enable party mode (should be a switch)
It's not possible to change the scene for a zone (should be a string like the input(?).

## Possible Solution
Add support for Partymode and Scenes

## Steps to Reproduce (for Bugs)
N/A

## Context
I use the amplifier with google home using openHab every day. By adding this feature, openHab would give me a much greater value.

## Your Environment
I run OpenHab as Docker on a Ubuntu server. It's connected to the same internal network as my Yamaha receiver.

**Comment by wborn** [comment]
We already have https://github.com/openhab/openhab2-addons/issues/3176 for adding scenes but it does not cover party mode. :smiley: :balloon:

**Comment by zarusz** [comment]
Hi @teqnet, could you please send me your device descriptor XML?
It is usually located under `http://<your_yamaha_ip>/YamahaRemoteControl/desc.xml` (or `http://<your_yamaha_ip>/YamahaRemoteControl/UnitDesc.xml` for older devices).

**Comment by zarusz** [comment]
@teqnet and @wborn  I made the changes to add scene and party mode support. Can you please test if this works for your AVR?

[Here](https://www.dropbox.com/sh/pa069i3bnbsptzj/AABqgJSrQ0lISfDNkUCbwWUma?dl=0) is the addon. Just remove the stock addon and add this one to the addons folder.

[Here](https://github.com/zarusz/openhab2-addons/tree/feature/yamaha_2.3.0_improvements/addons/binding/org.openhab.binding.yamahareceiver#for-manually-linking) is how to use scenes and party mode.

**Comment by wborn** [comment]
Thanks for picking this up @zarusz. I don't have a Yamaha AVR so it's difficult to test for me. It's nice to see you've also added some unit tests! :+1:

**Comment by dastrix80** [comment]
I have a Yamaha RX 3070, we will enable this add on and test SCENE/Party mode

**Comment by lauron** [comment]
Is the Party mode feature included in the 2.3 release?
I have an RX-A2000 and would like to know how I need to follow your above steps along with the 2.3 upgrade.

**Comment by seesemichaelj** [comment]
@lauron doesn't seem like it's in the 2.3 release; https://github.com/zarusz/openhab2-addons/commit/02e6fa2d48b8c820316cd943fe88059fad83240c and https://github.com/zarusz/openhab2-addons/commit/f9606ddfdf020f33db9f44b5516f3dd9b09d4fa8 doesn't seem to be pushed to the master repo.

Looks like if we can test the jar @zarusz provided, we can verify his fix works and it can get pushed upstream

**Comment by zarusz** [comment]
Correct, the party mode and scenes are not yet released. More Yamaha users need to test it first before I prepare a pull request that will make it's way into the next OH 2.4.0 release. I tested this on RX-S601D.

Although the JAR I have linked is 2.3.0-SNAPSHOT, I found it also works in openHAB 2.3.0 stable runtime.
Essentially, to test my build:
* uninstall the stock YamahaReceiver addon (via PaperUI)
* add my JAR into `addons` folder of your OH
* preferably use OH2.3.0 (stable)
* if any issues, try to remove the `kar`, `tmp`, `cache` folders (inside `userdata`) on your OH installation and reboot
* check the notes from my earlier post

**Comment by zarusz** [comment]
@lauron your models should be compatible according to the documentation [here](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.yamahareceiver#yamaha-receiver-binding). 

Not sure where would these folders be exactly on Pi. Maybe check these locations from the [install manuals](https://www.openhab.org/docs/installation/linux.html#installation).

Yes, I meant the uninstall like this PaperUI>Addons>Bindings.
I did not removed the `-SNAPSHOT` and it worked for me.
Removal of THINGS should not be necessary. Try without removing them first, but please bear in mind that the [settings names changed between 2.2.0 and 2.3.0](https://github.com/openhab/openhab-distro/wiki/%5BDRAFT%5D-openHAB-2.3-Release-Notes#add-ons) - you would need to reset the mandatory settings again in PaperUI (Configuration >Things > Edit > Yamaha Receiver > host, Configuration > Things > Edit > Yamaha Main Zone > zone).

**Comment by lauron** [comment]
@zarusz <https://github.com/zarusz>  party mode does work on the RX-A830, but does not work on the RX-A2000. The channels show up and configure the same for both devices, it’s just that the RX-A2000 just does not execute. The RX-A2000 is also a much older device. If I use the Yamaha AV Controller app, the command does execute. Is there something that I can do to help debug this?

**Comment by McFly3025** [comment]
Hi all,
today I tried to install the binding provided by zarusz following the instructions above. I'm running Openhabian 2.3.0 Stable on a Raspberry Pi.
After uninstalling the Binding from PaperUI I copied the jar-file to the folder /usr/share/openhab2/addons.
After rebooting the device the binding did not show under Configuration -> Bindings.
So I removed the folders cache and tmp (kar was not there) from /var/lib/openhab2/ and rebooted the device again.
Unfortunately, I'm no longer able to reach PaperUI (Chromium browser states that the connection is refused). Connecting via putty works flawlessly.

Here is an extract from the openhab.log file

`2018-06-19 21:51:05.046 [WARN ] [org.apache.karaf.main.Main          ] - Lock lost. Setting startlevel to 1
2018-06-19 21:51:28.816 [WARN ] [org.apache.karaf.main.Main          ] - Lock lost. Setting startlevel to 1
2018-06-19 21:51:29.055 [ERROR] [org.eclipse.smarthome.config.xml    ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:29.066 [ERROR] [org.eclipse.smarthome.core.thing.xml] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:29.121 [ERROR] [org.openhab.ui.homebuilder          ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:29.271 [ERROR] [org.eclipse.smarthome.config.core   ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:29.375 [ERROR] [ipse.smarthome.config.discovery.mdns] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:29.381 [ERROR] [rg.eclipse.smarthome.config.dispatch] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.193 [ERROR] [org.eclipse.smarthome.io.console    ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.273 [ERROR] [rg.eclipse.smarthome.core.autoupdate] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.280 [ERROR] [g.eclipse.smarthome.core.binding.xml] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.286 [ERROR] [org.eclipse.smarthome.core.id       ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.854 [ERROR] [g.eclipse.smarthome.io.console.karaf] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.862 [ERROR] [org.eclipse.smarthome.io.javasound  ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.868 [ERROR] [org.eclipse.smarthome.io.monitor    ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.873 [ERROR] [org.eclipse.smarthome.io.net        ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.881 [ERROR] [org.eclipse.smarthome.io.rest       ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.889 [ERROR] [org.eclipse.smarthome.io.rest.core  ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.895 [ERROR] [org.eclipse.smarthome.io.rest.mdns  ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.906 [ERROR] [rg.eclipse.smarthome.io.rest.sitemap] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.916 [ERROR] [org.eclipse.smarthome.io.rest.sse   ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.922 [ERROR] [org.eclipse.smarthome.io.rest.voice ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.928 [ERROR] [.eclipse.smarthome.io.transport.mdns] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.934 [ERROR] [org.eclipse.smarthome.io.webaudio   ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.939 [ERROR] [org.eclipse.smarthome.model.core    ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.946 [ERROR] [org.eclipse.smarthome.model.item    ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.953 [ERROR] [eclipse.smarthome.model.item.runtime] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.971 [ERROR] [.eclipse.smarthome.model.persistence] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.978 [ERROR] [.smarthome.model.persistence.runtime] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.983 [ERROR] [org.eclipse.smarthome.model.rule    ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:30.990 [ERROR] [eclipse.smarthome.model.rule.runtime] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:31.161 [ERROR] [lipse.smarthome.model.script.runtime] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:31.181 [ERROR] [ipse.smarthome.model.sitemap.runtime] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:31.186 [ERROR] [org.eclipse.smarthome.model.thing   ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:31.193 [ERROR] [clipse.smarthome.model.thing.runtime] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:31.665 [ERROR] [org.eclipse.smarthome.ui.icon       ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:31.671 [ERROR] [eclipse.smarthome.ui.iconset.classic] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:31.689 [ERROR] [org.jupnp                           ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:32.043 [ERROR] [org.eclipse.smarthome.ui.paper      ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:32.118 [ERROR] [ipse.smarthome.config.discovery.upnp] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:32.124 [ERROR] [.eclipse.smarthome.io.transport.upnp] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:32.131 [ERROR] [smarthome.config.discovery.usbserial] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:32.136 [ERROR] [onfig.discovery.usbserial.linuxsysfs] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:32.142 [ERROR] [org.eclipse.smarthome.config.serial ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:32.149 [ERROR] [e.smarthome.io.transport.serial.rxtx] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:51:32.204 [ERROR] [org.openhab.core                    ] - Component descriptor entry 'OSGI-INF/*.xml' not found
2018-06-19 21:52:32.004 [WARN ] [raf.features.internal.osgi.Activator] - Error starting activator
java.io.IOException: Unexpected end of input at 1:1
	at org.apache.karaf.features.internal.util.JsonReader.error(JsonReader.java:337) [10:org.apache.karaf.features.core:4.1.5]
	at org.apache.karaf.features.internal.util.JsonReader.expected(JsonReader.java:331) [10:org.apache.karaf.features.core:4.1.5]
	at org.apache.karaf.features.internal.util.JsonReader.readValue(JsonReader.java:93) [10:org.apache.karaf.features.core:4.1.5]
	at org.apache.karaf.features.internal.util.JsonReader.parse(JsonReader.java:58) [10:org.apache.karaf.features.core:4.1.5]
	at org.apache.karaf.features.internal.util.JsonReader.read(JsonReader.java:52) [10:org.apache.karaf.features.core:4.1.5]
	at org.apache.karaf.features.internal.region.DigraphHelper.readDigraph(DigraphHelper.java:90) [10:org.apache.karaf.features.core:4.1.5]
	at org.apache.karaf.features.internal.region.DigraphHelper.loadDigraph(DigraphHelper.java:70) [10:org.apache.karaf.features.core:4.1.5]
	at org.apache.karaf.features.internal.osgi.Activator.doStart(Activator.java:131) [10:org.apache.karaf.features.core:4.1.5]
	at org.apache.karaf.util.tracker.BaseActivator.run(BaseActivator.java:242) [10:org.apache.karaf.features.core:4.1.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`

Does anybody have a clue, how to solve that issue?

Best regards

McFly

**Comment by zarusz** [comment]
@lauron 
When saying it does not work on the RX-A2000, you mean the scenes don't work or the entire binding does not seem to work with this model?

Please send me the XML descriptor file for your model. You can simply download it using a web browser. [Here are two possible locations](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.yamahareceiver/docs#xml-descriptor) to obtain it for your model. This will help me and other developers understand what is so different on this older model. 

If the entire addon does not work for RX-A2000, then it will need a separate issue to fix the compatibility since it will most likely require more work.

@McFly3025 
I am not using openhabian myself. Try these things:
1. Ensure you have UIs installed/enabled in your `conf\services\addons.cfg` file, e.g. this entry should be there:
```
package = standard
```
or the list of UIs to install:
```
ui = basic,paper,habpanel
```

2. Before removing `kar` and `cache`, I suggest to stop the OH service. Also, you can try deleting them once more - when delete was done without stopping the OH service some partial/corrupt files could have been created.

**Comment by lauron** [comment]
@zarusz <https://github.com/zarusz> 

Everything seems to work for the RX-A2000 EXCEPT for party mode. All features, at least what I use, along with scenes DO work. So it is just the party mode which does not work. Attached is the .xml file from the unit.

Let me know what I can do next..

Thanks.

**Comment by dastrix80** [comment]
Hi Guys, please see attached my XML file for the Yamaha RX-A3070

[RX3070.txt](https://github.com/openhab/openhab2-addons/files/2117249/RX3070.txt)

**Comment by lauron** [comment]
Thanks for your file,

I see that my RX-A2000 .xml file does not have a ‘Party_Mode’ declaration in the System Unit section. Though if I use the Yamaha AV Controller app to enable party mode, the receiver does respond with PARTY MODE on the display, thus enabling zone 2 speakers. Does the binding require the .xml declaration? I am wondering if  the‘RX-A2000’ was the initial/early release for the YNCA protocol and may not of had a complete .xml file declaration and the Yamaha app had to walk around this case?

**Comment by lauron** [comment]
@zarusz <https://github.com/zarusz>  we made a modification to your code to get party mode to work on the RX-A2000 (see below) This forces the command to execute and works for me in the interim (thanks @seesemichaelj), but would require me to re-patch on future releases. Not sure what the best method of dealing with this, as we would have to make an assumption of when this exemption needs to occur, so I defer to your judgment, but we are willing to help if you like.

 

I do wonder if the version in the .xml file could help:

 <file:///D:/Users/Ron/Documents/owncloud/Projects/openhab/yamaha%20desc%20files/a2000-desc.xml> <Unit_Description Unit_Name="RX-A2000" Version="1.0">

 

Thanks!

 

    /**

     * Apply command changes to ensure compatibility with all supported models

     */

    protected void applyModelVariations() {

        if (systemDescriptor == null) {

            logger.trace("System descriptor not available");

            return;

        }

 

        logger.trace("Compatibility detection");

 

        /*partyModeSupported = systemDescriptor.hasCommandEnding("System,Party_Mode,Mode",

                () -> logger.info("The {} channel is not supported on your model", CHANNEL_PARTY_MODE));

 

        partyModeMuteSupported = systemDescriptor.hasCommandEnding("System,Party_Mode,Volume,Mute",

                () -> logger.info("The {} channel is not supported on your model", CHANNEL_PARTY_MODE_MUTE));

 

        partyModeVolumeSupported = systemDescriptor.hasCommandEnding("System,Party_Mode,Volume,Lvl",

                () -> logger.info("The {} channel is not supported on your model", CHANNEL_PARTY_MODE_VOLUME));*/

        systemDescriptor.hasCommandEnding("System,Party_Mode,Mode",

                () -> logger.info("The {} channel is not supported on your model SEESE EDIT", CHANNEL_PARTY_MODE));

        partyModeSupported = true;

        partyModeMuteSupported = true;

        partyModeVolumeSupported = true;

    }

 

 

From: Ron Seese <ronseese@seese.net> 
Sent: Tuesday, June 19, 2018 7:21 PM
To: 'openhab/openhab2-addons' <reply@reply.github.com>; 'openhab/openhab2-addons' <openhab2-addons@noreply.github.com>
Cc: 'Ron Seese' <ron@seese.net>; 'Mention' <mention@noreply.github.com>
Subject: RE: [openhab/openhab2-addons] [yamahareceiver binding] Party mode and Scenes for Yamaha receivers (#3393)

 

@zarusz <https://github.com/zarusz> 

Everything seems to work for the RX-A2000 EXCEPT for party mode. All features, at least what I use, along with scenes DO work. So it is just the party mode which does not work. Attached is the .xml file from the unit.

Let me know what I can do next..

Thanks.

**Comment by lauron** [comment]
@dastrix80

@seesemichaelj

@zarusz

 

A couple of declarations from devices that work with the unmodified code:

 

<Unit_Description Unit_Name="RX-A3070" Version="10">

 <file:///D:/Users/Ron/Documents/owncloud/Projects/openhab/yamaha%20desc%20files/a830-desc.xml> <Unit_Description Unit_Name="RX-A830" Version="1.2">

 

 

From: Ron Seese <ronseese@seese.net> 
Sent: Tuesday, June 19, 2018 10:43 PM
To: 'openhab/openhab2-addons' <reply@reply.github.com>; 'openhab/openhab2-addons' <openhab2-addons@noreply.github.com>
Cc: 'Ron Seese' <ron@seese.net>; 'Mention' <mention@noreply.github.com>; Mike <seesemichaelj@gmail.com>
Subject: RE: [openhab/openhab2-addons] [yamahareceiver binding] Party mode and Scenes for Yamaha receivers (#3393)

 

@zarusz <https://github.com/zarusz>  we made a modification to your code to get party mode to work on the RX-A2000 (see below) This forces the command to execute and works for me in the interim (thanks @seesemichaelj), but would require me to re-patch on future releases. Not sure what the best method of dealing with this, as we would have to make an assumption of when this exemption needs to occur, so I defer to your judgment, but we are willing to help if you like.

 

I do wonder if the version in the .xml file could help:

 <file:///D:/Users/Ron/Documents/owncloud/Projects/openhab/yamaha%20desc%20files/a2000-desc.xml> <Unit_Description Unit_Name="RX-A2000" Version="1.0">

 

Thanks!

 

    /**

     * Apply command changes to ensure compatibility with all supported models

     */

    protected void applyModelVariations() {

        if (systemDescriptor == null) {

            logger.trace("System descriptor not available");

            return;

        }

 

        logger.trace("Compatibility detection");

 

        /*partyModeSupported = systemDescriptor.hasCommandEnding("System,Party_Mode,Mode",

                () -> logger.info("The {} channel is not supported on your model", CHANNEL_PARTY_MODE));

 

        partyModeMuteSupported = systemDescriptor.hasCommandEnding("System,Party_Mode,Volume,Mute",

                () -> logger.info("The {} channel is not supported on your model", CHANNEL_PARTY_MODE_MUTE));

 

        partyModeVolumeSupported = systemDescriptor.hasCommandEnding("System,Party_Mode,Volume,Lvl",

                () -> logger.info("The {} channel is not supported on your model", CHANNEL_PARTY_MODE_VOLUME));*/

        systemDescriptor.hasCommandEnding("System,Party_Mode,Mode",

                () -> logger.info("The {} channel is not supported on your model SEESE EDIT", CHANNEL_PARTY_MODE));

        partyModeSupported = true;

        partyModeMuteSupported = true;

        partyModeVolumeSupported = true;

    }

 

 

From: Ron Seese <ronseese@seese.net <mailto:ronseese@seese.net> > 
Sent: Tuesday, June 19, 2018 7:21 PM
To: 'openhab/openhab2-addons' <reply@reply.github.com>; 'openhab/openhab2-addons' <openhab2-addons@noreply.github.com <mailto:openhab2-addons@noreply.github.com> >
Cc: 'Ron Seese' <ron@seese.net <mailto:ron@seese.net> >; 'Mention' <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Subject: RE: [openhab/openhab2-addons] [yamahareceiver binding] Party mode and Scenes for Yamaha receivers (#3393)

 

@zarusz <https://github.com/zarusz> 

Everything seems to work for the RX-A2000 EXCEPT for party mode. All features, at least what I use, along with scenes DO work. So it is just the party mode which does not work. Attached is the .xml file from the unit.

Let me know what I can do next..

Thanks.

**Comment by McFly3025** [comment]
Hello,

> 2. Before removing kar and cache, I suggest to stop the OH service. Also, you can try deleting them once more - when delete was done without stopping the OH service some partial/corrupt files could have been created.
<
I managend to reestablish a connection with PaperUI, fianlly. After that the Yamaha Receiver binding occurred under >Configuration>Bindings.

With the original items and things it did not work any more. So I removed all items and things related to the yamaha receiver and recreated all things and items. After that scenes were working fine.

Btw: I tested it with an RX-V583.

I didn't test party mode, because I don't need it. The openhab.log file says that my model is not supporting party mode. 

Best regards

**Comment by zarusz** [comment]
@McFly3025 cool that this started to work for you on RX-V583.

@lauron I have the XML for your RX-A2000 and the findings you provided with @seesemichaelj. I made further changes to my version and incorporated the fact that RX-A2000 descriptor does not declare party mode. Please grab my latest JAR and check if party feature works.

@dastrix80 thanks for the XML file. Did you manage to test scene/party mode on RX-A3070?
They should work according to the descriptor.



I will be away for few days, but will get back when I can ;)

**Comment by zarusz** [comment]
@lauron the typo is now fixed, please recheck.

**Comment by teqnet** [comment]
Hi!
I don't get it in the paper UI. I think I got the improved binding, since I now have four things on my amplifier.
Should it show up in the Paper UI under any of these things?
I cleared the tmp, cache and kar folders.

**Comment by lauron** [comment]
@zarusz looks like the latest is working perfectly for me. Thanks.

**Comment by teqnet** [comment]
Be careful in removing the cache folder. I can't get OH to start again...
https://github.com/openhab/openhab-distro/issues/263
Any suggestions on how to get it to work again?

**Comment by teqnet** [comment]
Got it working by removing the folders again and restart.

**Comment by zarusz** [comment]
@teqnet for me the custom addon does not show under PaperUI > Addons > Bindings, and instead the stock version displays as to be installed (with the install button next to it). Remember to uninstall the stock binding prior putting my custom JAR into `addons` folder.

As soon as you add the Yamaha Thing via PaperUI > Things > (+) you should notice new channels `party_mode` and `scene` for the main thing and zones respectively. 
The config examples [are here](https://github.com/zarusz/openhab2-addons/blob/feature/yamaha_2.3.0_improvements/addons/binding/org.openhab.binding.yamahareceiver/README.md#basic-setup). 

I am waiting for your feedback.

**Comment by teqnet** [comment]
Hello!
Yes, the addon is stated as not installed, but the binding is available.

I cant se party_mode in any channel in the yamaha things in paper ui. Cant get the lines of code to activate it either. Took a bunch of screenshots, but github doesnt support pictures.

**Comment by teqnet** [comment]
![capture _2018-06-26-07-36-02](https://user-images.githubusercontent.com/7504536/41891608-78a66526-7915-11e8-84e5-21f64a688dbd.png)
![capture _2018-06-26-07-35-31](https://user-images.githubusercontent.com/7504536/41891609-78d554a8-7915-11e8-8f11-df4e12eff743.png)
![capture _2018-06-26-07-26-36](https://user-images.githubusercontent.com/7504536/41891610-78f67eee-7915-11e8-8f80-adf869818749.png)
![Uploading Capture+_2018-06-26-07-25-37.png…]()
![Uploading Capture+_2018-06-26-07-24-03.png…]()
![Uploading Capture+_2018-06-26-07-23-12.png…]()
![Uploading Capture+_2018-06-26-07-19-52.png…]()

**Comment by teqnet** [comment]
Desktop mode allowed my phone to attach pictures. ☺

**Comment by zarusz** [comment]
Hi @teqnet,
Thanks for the screen grabs.
it looks like the old stock binding was somehow cached by osgi / OH. 

Can you stop your OH, remove folders cache, kar, tmp from userdata folder and start OH?

You may need to repeat some of the manual config setup done in paperUI.

**Comment by teqnet** [comment]
Hello!
I tried that again. I even rebuilt the docker after deliting the three folders.
Isnt it strange that I get four things? Earlier the binding only generated 3 things.
In what thing should I find party mode?

**Comment by teqnet** [comment]
I removed all the things. Then I removed the binding, cleared the folders and restarted OH. Then I added the .jar file from this thread to the adsons folder again. 
But no things appears in the Inbox. Shouldnt the things with their channels appear automatically? I can assign them manually.

**Comment by teqnet** [comment]
Added the things manually. Now the Partymode works!! Hurra!!

**Comment by teqnet** [comment]
Scenes is also working!

**Comment by zarusz** [comment]
@teqnet glad to hear that! :)

Regarding the auto discovery, are you starting the docker container with the `--net=host`?

**Comment by dastrix80** [comment]
Hi Guys,

The binding is working great so far. Ive just encountered an issue, not sure if its HabPanel, OH2 or the binding.

In Habpanel I have some code to toggle the Party Mode switch, today I started to see this error for no reason:

20:36:06.108 [WARN ] [.rest.core.internal.item.ItemResource] - Received HTTP POST request at 'items/Yamaha_PartyMode_Toggle' with an invalid status value ''.

Using this as a switch in a Basic UI sitemap works fine though turning it on and off.

Thoughts?

Thanks!

**Comment by zarusz** [comment]
Hi @dastrix80 nothing rings a bell why you would get this warning. Perhaps you could post your setup and the code/rule you mentioned?
