### ISSUE TITLE
[fronius] NullPointerException (no new values until openhab restart)

### ISSUE THREAD

**Issue by cybermanat** [openhab/openhab2-addons#3556]
When running a while, sometimes the binding stops working (not refreshing any value) and a _java.lang.NullPointerException: null_ occurs.

Logfile Output:
```
java.lang.NullPointerException: null
	at org.openhab.binding.fronius.handler.FroniusBaseThingHandler.updateChannel(FroniusBaseThingHandler.java:110) ~[?:?]
	at org.openhab.binding.fronius.handler.FroniusBaseThingHandler.updateChannels(FroniusBaseThingHandler.java:85) ~[?:?]
	at org.openhab.binding.fronius.handler.FroniusSymoInverterHandler.refresh(FroniusSymoInverterHandler.java:58) ~[?:?]
	at org.openhab.binding.fronius.handler.FroniusBridgeHandler.lambda$0(FroniusBridgeHandler.java:109) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?] 
```

After enabling debug mode for the binding I got the following response data:

working response part from GetPowerFlowRealtimeData.fcgi:
```
"Site" : {
            "E_Day" : 26300,
            "E_Total" : 82703.0078125,
            "E_Year" : 82703.5,
            "Meter_Location" : "grid",
            "Mode" : "meter",
            "P_Akku" : null,
            "P_Grid" : 1645.7999632135034,
            "P_Load" : -1675.7999632135034,
            "P_PV" : 30,
            "rel_Autonomy" : 1.7901897994121083,
            "rel_SelfConsumption" : 100
         }
```

non working response with NullPointerException: 
```
"Site" : {
            "E_Day" : 26300,
            "E_Total" : 82703.0078125,
            "E_Year" : 82703.5,
            "Meter_Location" : "grid",
            "Mode" : "meter",
            "P_Akku" : null,
            "P_Grid" : 1612.0499639678746,
            "P_Load" : -1612.0499639678746,
            "P_PV" : null,
            "rel_Autonomy" : 0,
            "rel_SelfConsumption" : null
         }
```

## Expected Behavior
Setting the value and continue to update the values instead of crashing and ignoring the "null" value.

## Current Behavior
NullPointerException appears and after that, the binding don't update values and seems to be crashed (openhab needs to be restarted)

## Possible Solution
Ignore "null" values or translate them to "0"

## Steps to Reproduce (for Bugs)
1. Run for a while (didn't run for a whole day)
2. Maybe it is needed, that P_PV gets null, if no sun is shining and PV production stops

## Your Environment
* Version used: 2.3.0-SNAPSHOT (#1272)
* Environment name and version: tried with Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76) and java-8
* Operating System and version: Raspbian

**Comment by cybermanat** [comment]
Problem occurs, if Body and Data is empty (Transfer timeout) 
Request: `solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData`
api Respone: `   "Body" : {
      "Data" : {}
   },
   "Head" : {
      "RequestArguments" : {
         "DataCollection" : "CommonInverterData",
         "DeviceClass" : "Inverter",
         "DeviceId" : "1",
         "Scope" : "Device"
      },
      "Status" : {
         "Code" : 8,
         "Reason" : "Transfer timeout.",
         "UserMessage" : ""
      },
      "Timestamp" : "2018-05-11T10:51:16+02:00"
   }
}`

**Comment by dsemprich** [comment]
My fronius binding also not updating the values and showing minus data for grid and load power

**Comment by 9037568** [comment]
Anyone care to try out a [test jar](https://drive.google.com/open?id=15IVwMl-QPSjitPCoCEUtaa86SI7v2FLp)?

**Comment by aMU5Ed** [comment]
Hi,
I just updated to 2.4.0 Snapshot of this Jar and experience some more nullpointer exceptions.

2018-10-25 08:52:26.468 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.NullPointerException: null
	at org.openhab.binding.fronius.handler.FroniusSymoInverterHandler.getValue(FroniusSymoInverterHandler.java:86) ~[?:?]
	at org.openhab.binding.fronius.handler.FroniusBaseThingHandler.updateChannel(FroniusBaseThingHandler.java:99) ~[?:?]
	at org.openhab.binding.fronius.handler.FroniusBaseThingHandler.updateChannels(FroniusBaseThingHandler.java:85) ~[?:?]
	at org.openhab.binding.fronius.handler.FroniusSymoInverterHandler.refresh(FroniusSymoInverterHandler.java:58) ~[?:?]
	at org.openhab.binding.fronius.handler.FroniusBridgeHandler.lambda$0(FroniusBridgeHandler.java:109) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]

Please give me some suggestions if this would be only a configuration issue.

KR, Thomas
