### ISSUE TITLE
[onewire] TCP connection does not reset/release

### ISSUE THREAD

**Issue by ggzengel** [openhab/openhab2-addons#3603]
I'm using OH2 2.2

After restarting the raspberry with owserver the onewire binding does not reconnect.

Even stop and start of this binding does not work.
```
openhab> list | grep -i wire
293 │ Active   │  80 │ 1.11.0                 │ openHAB OneWire Binding
openhab> stop 293
openhab> start 293                                                                                                                                                                               
openhab> restart 293
```

netstat shows an old connection to the owserver. In the meanwhile I rebooted the raspberry twice.

```
$ netstat -anopt | grep 4304
tcp6       0      0 192.168.180.111:55776   192.168.180.132:4304    ESTABLISHED 373/java             off (0.00/0/0)
```

After 1h the onewire binding didn't reconnect. 
```
2018-05-28 19:30:24.716 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'mower.items'
2018-05-28 21:25:08.464 [ERROR] [nternal.connection.OneWireConnection] - couldn't establish network connection while read attempt 1 '/statistics/errors/DS2480_read_read' ip:port=192.168.180.132:4304
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210) [?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) [?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:224) [?:?]
        at java.io.DataInputStream.readInt(DataInputStream.java:387) [?:?]
        at org.owfs.jowfsclient.internal.OwfsConnectionImpl.readPacket(OwfsConnectionImpl.java:234) [293:org.openhab.binding.onewire:1.11.0]
        at org.owfs.jowfsclient.internal.OwfsConnectionImpl.read(OwfsConnectionImpl.java:133) [293:org.openhab.binding.onewire:1.11.0]
        at org.openhab.binding.onewire.internal.connection.OneWireConnection.readFromOneWire(OneWireConnection.java:291) [293:org.openhab.binding.onewire:1.11.0]
        at org.openhab.binding.onewire.internal.OneWireBinding.updateItemFromOneWire(OneWireBinding.java:304) [293:org.openhab.binding.onewire:1.11.0]
        at org.openhab.binding.onewire.internal.OneWireBinding.devicePropertyWantsUpdate(OneWireBinding.java:258) [293:org.openhab.binding.onewire:1.11.0]
        at org.openhab.binding.onewire.internal.scheduler.OneWireUpdateTask.run(OneWireUpdateTask.java:61) [293:org.openhab.binding.onewire:1.11.0]
2018-05-28 21:25:08.466 [INFO ] [nternal.connection.OneWireConnection] - Trying to reconnect to owserver...
2018-05-28 21:25:12.487 [INFO ] [nternal.connection.OneWireConnection] - Connected to owserver [IP '192.168.180.132' Port '4304']
```
The 2nd reboot of the raspberry was after 21:25, the connection is still open and the binding did not reconnect even after stop/start.
Normally TCP connections will be closed if the host on the other side comes up and sends an reset to a not existing connection. It looks like the binding didn't send data anymore and the host on the other side does not have a chance to reset the connection.
Perhaps this binding is completely frozen.

After restarting of the whole OH2 the binding will reconnect.

Perhaps this is a solution for this problem:
https://dimovelev.blogspot.de/2015/03/java-socket-timeout.html

@kaikreuzer Is this a problem from a single binding or is this a problem in the OH2-core?

**Comment by wborn** [comment]
> 293 │ Active   │  80 │ 1.11.0                 │ openHAB OneWire Binding

Please create an issue for this in the [openhab1-addons issue tracker](https://github.com/openhab/openhab1-addons/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+onewire) if you are still having this issue with the OH 1.x OneWire Binding.

You could also test if it is fixed in the new [OneWire Binding](https://www.openhab.org/addons/bindings/onewire) which is available in the openHAB 2.4.0 SNAPSHOT builds.
