### ISSUE TITLE
Nikobus binding in OH2, automatic refresh (module status query) is not working

### ISSUE THREAD

**Issue by DaanDW** [openhab/openhab2-addons#3659]
The automatic refresh (module status query) of the Nikobus binding (1.x binding) is not working in OH2.

My Nikobus binding is working fine but the scheduled refreshed don’t work.

- When I press a Nikobus button, the light reacts and the matching switch Item in Openhab changes -> OK
- When I press a Openhab (nikobus) Item (on my phone app or webinterface), the lights react (Nikobus output reacts) -> OK
- NO automatic refreshes of the Nikobus modules -> NOK

I see this same issue in the community but is seems not yet reported as a bug.
[https://community.openhab.org/t/nikobus-compativbility-oh2/7096/73](url)
[https://community.openhab.org/t/nikobus-binding-not-updating-status-in-oh2/15761/12](url)

Some people uninstall and reinstall the binding and claims that is works from that on but this don't work for me.

I ported my config from openhab 1.8.3 to 2.3.0, in the 1.8.3 version the automatic module status query works fine but in the 2.3.0 version it don't.

These automatic module status query is a needed function to keep openhab synchronised with the Nikobus installation. Now I have wrong item states in openhab when Nikobus perform automatic functions like a "automatic delayed off" function or "presence simulation" function.
When Openhab and Nikobus are not synchronised, openhab will unwanted change Nikobus output states. Openhab pushes 6 output states at once to the Nikobus installation and forces these outputs to the openhab state, even if this openhab state is not equal to the Nikobus output state. This give unwanted status changes on the Nikobus installation.

I got this out of my LOG:

```
2018-06-05 21:16:01.798 [ERROR] [ding.nikobus.internal.NikobusBinding] - Error occurred during scheduled status refresh.
java.util.concurrent.TimeoutException: No ACK received within timeout and retry count.
	at org.openhab.binding.nikobus.internal.core.NikobusAckMonitor.waitForAck(NikobusAckMonitor.java:92) [232:org.openhab.binding.nikobus:1.12.0]
	at org.openhab.binding.nikobus.internal.NikobusBinding.sendCommand(NikobusBinding.java:155) [232:org.openhab.binding.nikobus:1.12.0]
	at org.openhab.binding.nikobus.internal.NikobusBinding$2.run(NikobusBinding.java:288) [232:org.openhab.binding.nikobus:1.12.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

My openhab 2.3.0 installation is running on a raspberry pi 3 model B, with raspbian lite (stretch).

**Comment by kaikreuzer** [comment]
As this is about code from https://github.com/openhab/openhab1-addons (even when being used on a 2.x runtime), please report the issue at https://github.com/openhab/openhab1-addons/issues - thanks!
