### ISSUE TITLE
[homekit] Exception crash homekit 2.3.0 with IOS 11.4

### ISSUE THREAD

**Issue by temuccio** [openhab/openhab2-addons#3682]
After the last update of IOS, the integration from openhab and IOS with homekit didn't works.
I have upgrade openhab from version 2.2.0 to 2.3.0, delete the key pair and reassociate the Iphone.
It's works few time but  random I have a disassociation with this error:
```
2018-06-16 09:46:44.855 [ERROR] [lfe.hap.impl.http.impl.BinaryHandler] - Exception in binary handler
java.io.IOException: Connessione scaduta
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) [?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) [?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) [?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) [?:?]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:880) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [211:org.openhab.io.homekit:2.3.0]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-06-16 09:46:44.875 [TRACE] [ons.LengthPrefixedByteArrayProcessor] - Returning 0 results
2018-06-16 09:46:44.880 [INFO ] [.hap.impl.http.impl.AccessoryHandler] - Terminated homekit connection from /192.168.1.20:54476
2018-06-16 11:35:22.635 [ERROR] [lfe.hap.impl.http.impl.BinaryHandler] - Exception in binary handler
java.io.IOException: Connessione interrotta dal corrispondente
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) [?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) [?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) [?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) [?:?]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:880) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [211:org.openhab.io.homekit:2.3.0]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-06-16 11:35:22.650 [TRACE] [ons.LengthPrefixedByteArrayProcessor] - Received message of length 0. Existing buffer is 0
2018-06-16 11:35:22.644 [ERROR] [.hap.impl.http.impl.AccessoryHandler] - Exception caught in web handler
java.io.IOException: Connessione interrotta dal corrispondente
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) [?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) [?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) [?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) [?:?]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:880) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [211:org.openhab.io.homekit:2.3.0]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-06-16 11:35:22.657 [TRACE] [ons.LengthPrefixedByteArrayProcessor] - Returning 0 results
java.io.IOException: Connessione interrotta dal corrispondente
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) [?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) [?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) [?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) [?:?]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:880) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [211:org.openhab.io.homekit:2.3.0]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [211:org.openhab.io.homekit:2.3.0]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-06-16 11:35:22.657 [TRACE] [ons.LengthPrefixedByteArrayProcessor] - Returning 0 results
2018-06-16 11:35:22.662 [INFO ] [.hap.impl.http.impl.AccessoryHandler] - Terminated homekit connection from /192.168.1.20:54548
2018-06-16 11:40:25.900 [INFO ] [.hap.impl.http.impl.AccessoryHandler] - New homekit connection from /192.168.1.20:54683
```
Do you know a solution? With previous version of openhab and IOS I'm very happy for the works.

**Comment by jj74** [comment]
Same here with all iOS devices. Can`t pair anymore :-(

**Comment by Lovingyourwork** [comment]
I had similar issues, finally resolved by deleting all of my existing HomeKit 'houses' / configuration on all devices. Was it a massive pain in the b*tt? - yes, but once re-added, everything now works perfectly again.

**Comment by jj74** [comment]
I found the reason (in my case!), why it crashes all the time with the error above. I`using several temp/humidity sensors (BME280) with Wemos D1 or Sonoff devices (all with Tasmota firmware).  Everytime a temp device has a failure and crashes, it shows strange values on the Web-frontend like -139 degrees. If that happens, Homekit binding crashes as well! An issue with the I2C connection was the reason for that. This was the solution for me: [https://github.com/arendst/Sonoff-Tasmota/issues/3431]

**Comment by raelli** [comment]
> I found the reason (in my case!), why it crashes all the time with the error above. I`m using several temp/humidity sensors (BME280) with Wemos D1 or Sonoff devices (all with Tasmota firmware). Everytime a temp device has a failure and crashes, it shows strange values on the Web-frontend like -139 degrees. If that happens, Homekit binding crashes as well! An issue with the I2C connection was the reason for that. This was the solution for me: [arendst/Sonoff-Tasmota#3431](https://github.com/arendst/Sonoff-Tasmota/issues/3431)

I dom‘t think that this is really the issue. In my network are only zwave switches and dimmers from qubino. These devices seema to work properly all together.

I can observe this issue only when my iPhone gets disconneted. After 30-60 minutes this exception occurs.
If my iPhone is connected all the time or never connected this issue never happens.

**Comment by J-N-K** [comment]
Is this still the case in latest snapshots?

**Comment by J-N-K** [comment]
no response, old version, probably fixed
