### ISSUE TITLE
[chromecast] Chromecast binding freezes openHAB

### ISSUE THREAD

**Issue by radokristof** [openhab/openhab2-addons#3693]
Dear Community and binding Maintainers/Developers!

I have an issue with the Chromecast binding and I found similar issues with this binding. However for me this happens "automatically" I don't have to press anything on Chromecast it happens randomly and freezes the whole openHab.
Currently  I'm on 2.3.0 stable.

Here is the message I get:

```
2018-06-15 06:39:33.504 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while reading
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Broken pipe (Write failed)
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1551) [?:?]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:95) [?:?]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:71) [?:?]
	at su.litvak.chromecast.api.v2.Channel.read(Channel.java:411) [217:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel.access$200(Channel.java:50) [217:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:132) [217:org.openhab.binding.chromecast:2.3.0]
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Broken pipe (Write failed)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1880) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1825) ~[?:?]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:128) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:75) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel.write(Channel.java:401) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel.write(Channel.java:397) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel.write(Channel.java:384) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel.access$000(Channel.java:50) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:191) ~[?:?]
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:?]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:?]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[?:?]
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431) ~[?:?]
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:886) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:857) ~[?:?]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:75) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel.write(Channel.java:401) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel.write(Channel.java:397) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel.write(Channel.java:384) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel.access$000(Channel.java:50) ~[?:?]
	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:191) ~[?:?]
2018-06-15 06:39:33.929 [WARN ] [su.litvak.chromecast.api.v2.Channel ] -  <--  null payload in message 
2018-06-15 06:40:09.570 [WARN ] [me.core.internal.events.EventHandler] - Dispatching event to subscriber 'org.eclipse.smarthome.model.rule.runtime.internal.engine.RuleEngineImpl@136110e' takes more than 5000ms.
2018-06-15 06:40:11.517 [INFO ] [e.smarthome.model.script.radio.rules] - Received command: classHit
2018-06-15 06:40:17.748 [INFO ] [e.smarthome.model.script.radio.rules] - Received command: classHit
2018-06-15 06:40:40.697 [WARN ] [me.core.internal.events.EventHandler] - Dispatching event to subscriber 'org.openhab.io.openhabcloud.internal.CloudService@16167e6' takes more than 5000ms.
```

I know it seems that something else has a problem, but I had this error so many times, right after this Chromecast exception. So I think Chromecast binding has some bug.

Thanks!

**Comment by wborn** [comment]
The library used by openHAB has some additional fixes that haven't been released yet. Maybe it is already fixed by https://github.com/vitalidze/chromecast-java-api-v2/pull/88 .

**Comment by radokristof** [comment]
@wborn Yes this seems the issue which I always have. You mean that haven't been released that these fixes included in daily snapshots or the binding haven't been updated at all to the newest chromecast-java-api?

**Comment by wborn** [comment]
There is no chromecast-java-api release with that fix. We could build the jar ourself though if want to include it.

**Comment by radokristof** [comment]
Yes, sorry I missed that the last release was in November... Anyway is that normal that this exception freezes openHab?

**Comment by wborn** [comment]
I haven't seen my openHAB freezing due to it. So I don't know if that makes normal or abnormal. ;-)

**Comment by radokristof** [comment]
@wborn Interesting, no one reported on the community as well that has this problem or they solved it by pinging the Chromecast to not to close the connection. However this doesn't seem to work for me as well. I have less freezes like this, but not solved it completely... I think I will try to remove this binding now, and see how it works after...

**Comment by wborn** [comment]
I created a [branch](https://github.com/wborn/openhab2-addons/commit/4f5b89847e0ba84b4d6f847d6a90c15f12ad45de) for creating a [org.openhab.binding.chromecast-2.4.0-SNAPSHOT.jar](http://www.maindrain.net/iot-marketplace/org.openhab.binding.chromecast-2.4.0-SNAPSHOT.jar) which uses the latest version of the library. Maybe you can test it @radokristof? :smile:

**Comment by radokristof** [comment]
Sure :D I have never tried an external addon, how should I do it? Delete the installed version, copy this jar to the addons folder and then install it from the bindings page? Or it will automatically be there at my bindings after I place it in the folder?

**Comment by wborn** [comment]
Yes first uninstall the original binding from Paper UI and then copy the .jar to the addons folder. It should automatically be installed by that. 

To use the original binding again. Remove the .jar from the addons folder and install the original binding from Paper UI again.

**Comment by radokristof** [comment]
Thanks, I have installed this version (hope so, I haven't found anywhere in PaperUI the version, but when I see the addons page, the Chromecast binding is not installed there) I will test it and see if I get any freezes now :) Thanks for help!

**Comment by radokristof** [comment]
Now I get different type of error :(

`2018-06-28 06:43:00.333 [ERROR] [io.openhabcloud.internal.CloudClient] - Socket.IO error: {}
io.socket.engineio.client.EngineIOException: websocket error
        at io.socket.engineio.client.Transport.onError(Transport.java:71) [232:org.openhab.io.openhabcloud:2.3.0]
        at io.socket.engineio.client.transports.WebSocket.access$500(WebSocket.java:28) [232:org.openhab.io.openhabcloud:2.3.0]
        at io.socket.engineio.client.transports.WebSocket$2$5.run(WebSocket.java:150) [232:org.openhab.io.openhabcloud:2.3.0]
        at io.socket.thread.EventThread$2.run(EventThread.java:80) [232:org.openhab.io.openhabcloud:2.3.0]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.java:59) ~[?:?]
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:72) ~[?:?]
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:115) ~[?:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:104) ~[?:?]
        at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97) ~[?:?]
        at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152) ~[?:?]
        at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41) ~[?:?]
        at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97) ~[?:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126) ~[?:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[?:?]
        ... 3 more
2018-06-28 06:41:53.324 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:?]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) [?:?]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155) [?:?]
        at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431) [?:?]
        at sun.security.ssl.OutputRecord.write(OutputRecord.java:417) [?:?]
        at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:886) [?:?]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:857) [?:?]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) [?:?]
        at java.io.OutputStream.write(OutputStream.java:75) [?:?]
        at su.litvak.chromecast.api.v2.Channel.write(Channel.java:405) [245:org.openhab.binding.chromecast:2.4.0.201806241822]
        at su.litvak.chromecast.api.v2.Channel.write(Channel.java:401) [245:org.openhab.binding.chromecast:2.4.0.201806241822]
        at su.litvak.chromecast.api.v2.Channel.write(Channel.java:388) [245:org.openhab.binding.chromecast:2.4.0.201806241822]
        at su.litvak.chromecast.api.v2.Channel.access$000(Channel.java:50) [245:org.openhab.binding.chromecast:2.4.0.201806241822]
        at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:195) [245:org.openhab.binding.chromecast:2.4.0.201806241822]`

**Comment by wborn** [comment]
The EngineIOException seems unrelated to the Chromecast binding since it has openhabcloud in the stack trace.

The SocketException is related to the Chromecast binding but does it still cause openHAB to lock up or result in loss of functionality? 

The log levels in the library could be tuned better so it is less verbose when it handles common exceptions that can be properly handled.

I already put in https://github.com/vitalidze/chromecast-java-api-v2/pull/101 for stack traces that are printed whenever the openHAB runtime is stopped.

**Comment by radokristof** [comment]
Yes, sorry the first error doesn’t seem related to this problem, I just somehow copied that out. Yes after these lines the whole openhab locked up again, I needed to restart the whole openhab. However I will continue testing it, see when this error happens, because it happened only once since I installednthis version and I haven’t restarted the system since then. 

Thanks for your help!

**Comment by wborn** [comment]
Perhaps you can get and add a thread dump when openHAB locks up, so we can see what the threads are doing.

There are several ways to get one, e.g.:

* `jstack pid`
 See: https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jstack.html
 Where `pid` is the process identifier of openhab.
* `kill -3 pid`
 The stack trace should will be printed to stdout
* `threads --locks --monitors`
 On the openHAB [console](https://www.openhab.org/docs/administration/console.html)

---

You could also enable debug logging in the [console](https://www.openhab.org/docs/administration/console.html) so we can see more details of what the binding and library are doing:

```
log:set debug org.openhab.binding.chromecast
log:set debug su.litvak.chromecast.api.v2
```

--- 

Or perhaps uninstall the binding and see if openHAB still locks up. Maybe the Chromecast exceptions are the result of openHAB locking up. 

---

It could also be your own rules that may be causing openHAB to lock up. So you could also try disabling some of them for a while.

**Comment by radokristof** [comment]
Since then, I haven't received an error like this and openHab haven't locked up because of this error. :) However I will keep testing it, because my whole setup is only a few months old and I change a lot of configuration from day to day and that's because I can't really track stability.
Thanks for help anyway! Closing this issue for now.

**Comment by radokristof** [comment]
`2018-07-20 00:45:24.585 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while reading
su.litvak.chromecast.api.v2.ChromeCastException: Remote socket closed
	at su.litvak.chromecast.api.v2.Channel.read(Channel.java:417) [245:org.openhab.binding.chromecast:2.4.0.201806241822]
	at su.litvak.chromecast.api.v2.Channel.access$200(Channel.java:50) [245:org.openhab.binding.chromecast:2.4.0.201806241822]
	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:132) [245:org.openhab.binding.chromecast:2.4.0.201806241822]
2018-07-20 00:45:25.290 [WARN ] [su.litvak.chromecast.api.v2.Channel ] -  <--  null payload in message 
2018-07-20 00:45:30.904 [WARN ] [me.core.internal.events.EventHandler] - Dispatching event to subscriber 'org.eclipse.smarthome.core.internal.items.ItemUpdater@a12047' takes more than 5000ms.
2018-07-20 00:46:48.568 [WARN ] [me.core.internal.events.EventHandler] - Dispatching event to subscriber 'org.openhab.io.openhabcloud.internal.CloudService@e14b3' takes more than 5000ms.
`

Today I got that error again and I don't know what to do with it... should I try thread dump?

**Comment by wborn** [comment]
I see the error too sometimes but my openHAB doesn't lock up due to it.
Please try to create a thread dump when it locks up so we can see what the threads are doing.

**Comment by wborn** [comment]
The updated Chromecast library should be part of the next 2.4.0-SNAPSHOT build (i.e. build 1316 or newer, see also https://github.com/openhab/openhab2-addons/pull/3759). So you no longer need to use the JAR from https://github.com/openhab/openhab2-addons/issues/3693#issuecomment-399777267 to get these changes.
