### ISSUE TITLE
[yamahareceiver] Doesn't connect reliably

### ISSUE THREAD

**Issue by staehler** [openhab/openhab2-addons#3711]
I've a Yamaha RX-V437 and wanted to bind it with openhab into my home automation. openhab recognizes the receiver, but not reliably. When I leave the house, I switch every consumer to OFF, my Yamahe receiver as well.
After coming back, the binding might be online, but somtimes it stays offline. Even after a openhab restart, the binding can stay offline (as today, see log below).

## Expected Behavior
I would expect, that the binding tries to reconnect to the thing as long as it is successfully connected.

## Current Behavior
This log shows the behavior. I restarted openhab and the thing stayed offline since I restarted the Yamaha binding at 10:57 oclock. The Yamaha Receiver was switched on and played music during the openhab restart. But as you can see in the openhab.log, openhab2 wasn't be able to reach the device.
Before the openhab restart, the binding was online and the binding worked a expected.
```
openhab> bundle:list | grep -i yamah
241 │ Active   │  80 │ 2.4.0.201807010828     │ YamahaReceiver Binding
openhab> bundle:restart 241
```
events.log
```
2018-07-07 10:01:06.034 [hingStatusInfoChangedEvent] - 'yamahareceiver:yamahaAV:receiverWZ' changed from UNINITIALIZED to INITIALIZING
2018-07-07 10:01:06.158 [hingStatusInfoChangedEvent] - 'yamahareceiver:yamahaAV:receiverWZ' changed from INITIALIZING to OFFLINE (CONFIGURATION_PENDING): Waiting for data
2018-07-07 10:01:09.290 [hingStatusInfoChangedEvent] - 'yamahareceiver:yamahaAV:receiverWZ' changed from OFFLINE (CONFIGURATION_PENDING): Waiting for data to OFFLINE (COMMUNICATION_ERROR): Keine Route zum Zielrechner (Host unreachable)
2018-07-07 10:01:11.121 [hingStatusInfoChangedEvent] - 'yamahareceiver:zone:receiverWZ:Main_Zone' changed from UNINITIALIZED to INITIALIZING
2018-07-07 10:01:11.172 [hingStatusInfoChangedEvent] - 'yamahareceiver:zone:receiverWZ:Main_Zone' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)
2018-07-07 10:01:12.486 [hingStatusInfoChangedEvent] - 'yamahareceiver:yamahaAV:receiverWZ' changed from OFFLINE (COMMUNICATION_ERROR): Keine Route zum Zielrechner (Host unreachable) to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): Could not communicate with the device
2018-07-07 10:11:30.512 [vent.ItemStateChangedEvent] - yamaha changed from OFF to ON
2018-07-07 10:57:02.375 [hingStatusInfoChangedEvent] - 'yamahareceiver:zone:receiverWZ:Main_Zone' changed from OFFLINE (BRIDGE_OFFLINE) to UNINITIALIZED
2018-07-07 10:57:02.498 [hingStatusInfoChangedEvent] - 'yamahareceiver:zone:receiverWZ:Main_Zone' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2018-07-07 10:57:02.509 [hingStatusInfoChangedEvent] - 'yamahareceiver:yamahaAV:receiverWZ' changed from UNINITIALIZED (HANDLER_INITIALIZING_ERROR): Could not communicate with the device to UNINITIALIZED
2018-07-07 10:57:02.524 [hingStatusInfoChangedEvent] - 'yamahareceiver:yamahaAV:receiverWZ' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2018-07-07 10:57:02.901 [hingStatusInfoChangedEvent] - 'yamahareceiver:yamahaAV:receiverWZ' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
2018-07-07 10:57:02.909 [hingStatusInfoChangedEvent] - 'yamahareceiver:yamahaAV:receiverWZ' changed from INITIALIZING to OFFLINE (CONFIGURATION_PENDING): Waiting for data
2018-07-07 10:57:02.932 [hingStatusInfoChangedEvent] - 'yamahareceiver:zone:receiverWZ:Main_Zone' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
2018-07-07 10:57:02.957 [hingStatusInfoChangedEvent] - 'yamahareceiver:zone:receiverWZ:Main_Zone' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)
2018-07-07 10:57:03.326 [me.event.ThingUpdatedEvent] - Thing 'yamahareceiver:yamahaAV:receiverWZ' has been updated.
2018-07-07 10:57:03.335 [me.event.ThingUpdatedEvent] - Thing 'yamahareceiver:yamahaAV:receiverWZ' has been updated.
2018-07-07 10:57:03.389 [hingStatusInfoChangedEvent] - 'yamahareceiver:yamahaAV:receiverWZ' changed from OFFLINE (CONFIGURATION_PENDING): Waiting for data to ONLINE
2018-07-07 10:57:03.453 [hingStatusInfoChangedEvent] - 'yamahareceiver:zone:receiverWZ:Main_Zone' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
```
openhab.log
```
2018-07-07 10:01:09.218 [WARN ] [receiver.handler.YamahaBridgeHandler] - Communication error. Please review your Yamaha thing configuration.
java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) [?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) [?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) [?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) [?:?]
	at java.net.Socket.connect(Socket.java:589) [?:?]
	at java.net.Socket.connect(Socket.java:538) [?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) [?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) [?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) [?:?]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) [?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) [?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) [?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) [?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) [?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) [?:?]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) [?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) [?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) [?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.postMessage(XMLConnection.java:77) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.sendReceive(XMLConnection.java:115) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getResponse(XMLProtocolService.java:80) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.DeviceInformationXML.update(DeviceInformationXML.java:83) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.handler.YamahaBridgeHandler.updateDeviceInformation(YamahaBridgeHandler.java:187) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.handler.YamahaBridgeHandler.connectionEstablished(YamahaBridgeHandler.java:274) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.internal.protocol.ProtocolFactory.createConnection(ProtocolFactory.java:39) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.handler.YamahaBridgeHandler.initialize(YamahaBridgeHandler.java:254) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [94:org.eclipse.smarthome.core:0.10.0.201806271317]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [94:org.eclipse.smarthome.core:0.10.0.201806271317]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2018-07-07 10:01:11.072 [WARN ] [ome.core.thing.internal.ThingManager] - Initializing handler for thing 'yamahareceiver:yamahaAV:receiverWZ' takes more than 5000ms.
2018-07-07 10:01:12.218 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.yamahareceiver.handler.YamahaBridgeHandler@74be38e1': Could not communicate with the device
java.lang.RuntimeException: Could not communicate with the device
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.InputConverterXML.<init>(InputConverterXML.java:58) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.internal.protocol.ProtocolFactory.InputConverter(ProtocolFactory.java:131) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.handler.YamahaBridgeHandler.initialize(YamahaBridgeHandler.java:255) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [94:org.eclipse.smarthome.core:0.10.0.201806271317]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [94:org.eclipse.smarthome.core:0.10.0.201806271317]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
	at java.net.Socket.connect(Socket.java:589) ~[?:?]
	at java.net.Socket.connect(Socket.java:538) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:?]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.postMessage(XMLConnection.java:77) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.sendReceive(XMLConnection.java:115) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getResponse(XMLProtocolService.java:80) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getZoneResponse(XMLProtocolService.java:68) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getInputs(XMLProtocolService.java:100) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.InputConverterXML.createInputsWithoutMapping(InputConverterXML.java:96) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.InputConverterXML.<init>(InputConverterXML.java:55) ~[?:?]
	... 11 more
2018-07-07 10:01:12.484 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while initializing handler of thing 'yamahareceiver:yamahaAV:receiverWZ': Could not communicate with the device
java.lang.RuntimeException: Could not communicate with the device
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.InputConverterXML.<init>(InputConverterXML.java:58) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.internal.protocol.ProtocolFactory.InputConverter(ProtocolFactory.java:131) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at org.openhab.binding.yamahareceiver.handler.YamahaBridgeHandler.initialize(YamahaBridgeHandler.java:255) [241:org.openhab.binding.yamahareceiver:2.4.0.201807010828]
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [94:org.eclipse.smarthome.core:0.10.0.201806271317]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [94:org.eclipse.smarthome.core:0.10.0.201806271317]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
	at java.net.Socket.connect(Socket.java:589) ~[?:?]
	at java.net.Socket.connect(Socket.java:538) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:?]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.postMessage(XMLConnection.java:77) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.sendReceive(XMLConnection.java:115) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getResponse(XMLProtocolService.java:80) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getZoneResponse(XMLProtocolService.java:68) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getInputs(XMLProtocolService.java:100) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.InputConverterXML.createInputsWithoutMapping(InputConverterXML.java:96) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.InputConverterXML.<init>(InputConverterXML.java:55) ~[?:?]
	... 11 more
```
My yamaha.things file
```
Bridge yamahareceiver:yamahaAV:receiverWZ "Yamaha Receiver RX-V473" [host="192.168.x.yyy"] {
	Thing zone Main_Zone "Main Zone" @ "Wohnzimmer" [zone="Main_Zone", volumeDbMin=-81, volumeDbMax=12]
}
```
## Possible Solution
Workaround: manually restart the yamaha binding.

## Steps to Reproduce (for Bugs)
I cannot reproduce it, as it happens not every time. Sometimes it works as expexted, sometime the thing stays offline.

## Your Environment
- Debian 8.11 in a VM
- java-common 0.52
- oracle-java8-installer 8u171-1~webupd8~0
- oracle-java8-set-default 8u171-1~webupd8~0
- openhab2 2.4.0~20180701105417-1
- binding-yamahareceiver - 2.4.0.SNAPSHOT

**Comment by davidgraeff** [comment]
> NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)

This is an operating system / vm problem and cannot be solved from within the binding. The binding does not establish a continuous connection, but polls for the state (re-connect) every 60 seconds via TCP.
