### ISSUE TITLE
[chromecast] volume channel: Could not resolve type id 'DEVICE_UPDATED'

### ISSUE THREAD

**Issue by Stefan300381** [openhab/openhab2-addons#3729]
## Expected Behavior
I want to set the volume for my Google Home device.

## Current Behavior
In my google home app I've created group of google home devices. This group has been added as a thing to OH 2.3 stable. The item GoogleHomeGroup uses the volume channel of the thing.
When a rule fires GoogleHomeGroup.sendCommand(xxx) to set the volume level I see the following entry (and much much more) in the events.log and openhab.log

```
2018-07-12 15:30:56.168 [vent.ItemStateChangedEvent] - GoogleHomeGroup changed from 100 to 42

==> /var/log/openhab2/openhab.log <==

2018-07-12 15:30:56.203 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling
org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'DEVICE_UPDATED' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]
 at [Source: N/A; line: -1, column: -1]
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[207:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownTypeException(StdDeserializationContext.java:273) [207:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:117) [207:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:74) [207:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) [207:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.StdDeserializerProvider$WrappedDeserializer.deserialize(StdDeserializerProvider.java:494) [207:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695) [207:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1990) [207:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.EventListenerHolder.deliverEvent(EventListenerHolder.java:56) [207:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel.notifyListenersOfSpontaneousEvent(Channel.java:440) [207:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel.access$600(Channel.java:50) [207:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:186) [207:org.openhab.binding.chromecast:2.3.0]
```

## Possible Solution
no clue

## Your Environment
orange Pi 
openHAB 2.3 stable

**Comment by wborn** [comment]
The same stack trace was reported in https://github.com/openhab/openhab2-addons/issues/3719. But you seem to have a reproduction scenario. :+1:

**Comment by Stefan300381** [comment]
:-)

**Comment by wborn** [comment]
I see the error is a bit different! Your error message is about DEVICE_UPDATED whereas #3719 is about DEVICE_ADDED. :upside_down_face:

**Comment by ChristianKrausse** [comment]
Same Problem on raspibian

`20:46:27.291 [WARN ] [su.litvak.chromecast.api.v2.Channel  ] - Error while handling
org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'DEVICE_UPDATED' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]
 at [Source: N/A; line: -1, column: -1]
        at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[208:org.openhab.binding.chromecast:2.3.0]
        at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownTypeException(StdDeserializationContext.java:273) [208:org.openhab.binding.chromecast:2.3.0]
        at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:117) [208:org.openhab.binding.chromecast:2.3.0]
        at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:74) [208:org.openhab.binding.chromecast:2.3.0]
        at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) [208:org.openhab.binding.chromecast:2.3.0]
        at org.codehaus.jackson.map.deser.StdDeserializerProvider$WrappedDeserializer.deserialize(StdDeserializerProvider.java:494) [208:org.openhab.binding.chromecast:2.3.0]
        at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695) [208:org.openhab.binding.chromecast:2.3.0]
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1990) [208:org.openhab.binding.chromecast:2.3.0]
        at su.litvak.chromecast.api.v2.EventListenerHolder.deliverEvent(EventListenerHolder.java:56) [208:org.openhab.binding.chromecast:2.3.0]
        at su.litvak.chromecast.api.v2.Channel.notifyListenersOfSpontaneousEvent(Channel.java:440) [208:org.openhab.binding.chromecast:2.3.0]
        at su.litvak.chromecast.api.v2.Channel.access$600(Channel.java:50) [208:org.openhab.binding.chromecast:2.3.0]
        at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:186) [208:org.openhab.binding.chromecast:2.3.0]
`
