### ISSUE TITLE
iCloud Binding stopped updating

### ISSUE THREAD

**Issue by broyuken** [openhab/openhab2-addons#3762]
iCloud Binding

## Expected Behavior
iCloud binding updates with current device information

## Current Behavior
iCloud binding does not update. PaperUI shows the following error:

Status: OFFLINE - COMMUNICATION_ERROR sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

## Possible Solution
It looks like this is an issue with the certificate being presented? This was working 2 days ago and just randomly stopped working. I don't believe I made any changes related to iCloud that would have broken this.

## Steps to Reproduce (for Bugs)
Install iCloud binding and attempt to link it to your account by logging in.

## Context
I can't use iCloud locations in rules/items any more

Logs:
```
15:43:08.635 [WARN ] [ud.handler.ICloudAccountBridgeHandler] - Unable to refresh device data
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: u
nable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964) ~[?:?]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328) ~[?:?]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322) ~[?:?]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614) ~[?:?]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:?]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259) ~[?:?]
        at org.openhab.binding.icloud.internal.Connection.postRequest(Connection.java:95) ~[?:?]
        at org.openhab.binding.icloud.internal.Connection.requestDeviceStatusJSON(Connection.java:55) ~[?:?]
        at org.openhab.binding.icloud.handler.ICloudAccountBridgeHandler.lambda$0(ICloudAccountBridgeHandler.java:81) ~[?:?]
        at org.eclipse.smarthome.core.cache.ExpiringCache.refreshValue(ExpiringCache.java:81) ~[?:?]
        at org.eclipse.smarthome.core.cache.ExpiringCache.getValue(ExpiringCache.java:61) ~[?:?]
        at org.openhab.binding.icloud.handler.ICloudAccountBridgeHandler.refreshData(ICloudAccountBridgeHandler.java:132) ~[?:?]
        at org.openhab.binding.icloud.handler.ICloudAccountBridgeHandler.lambda$1(ICloudAccountBridgeHandler.java:123) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

##Environment:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

openjdk version "1.8.0_172"
OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)
OpenJDK 64-Bit Server VM (Zulu 8.30.0.1-linux64) (build 25.172-b01, mixed mode)

openHAB 2.3.0 Release Build

**Comment by Dan1001** [comment]
I have exactly the same issue.

**Comment by miklosandras** [comment]
Same issue :(

**Comment by martinvw** [comment]
Did you see the community topic, there is a workaround there, somehow Apple decided to switch to a certificate which is not accepted (yet) using the default trusted certificate authorities.

See https://community.openhab.org/t/icloud-binding-general-sslengine-problem/48314/18

**Comment by Dan1001** [comment]
Yes - this does indeed provide a temporary fix.

**Comment by kaikreuzer** [comment]
Manually importing the certificated into the Java keystore is a pretty cumbersome workaround that many users probably won't be able to apply.

So how should the issue be solved?
@martinvw suggested in the forum to deactivate the validation, which would be one quick way.
Another would be to implement a [TrustManagerProvider](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/TrustManagerProvider.java) and register this for the iCloud endpoint - when using the shared HttpClient, this should then be automatically taken into account.

@pgfeller Is this something you could try out? I'll happily support you if there are any questions.

**Comment by martinvw** [comment]
@pgfeller did you already start on this? I can make some time tonight but if you are already half way than that would be wasted so stop me if needed :-D

**Comment by hpetersen** [comment]
> Please find an attached test binding which should resolve the problems
> 
> [org.openhab.binding.icloud-2.4.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/2376911/org.openhab.binding.icloud-2.4.0-SNAPSHOT.jar.zip)

Hi @martinvw ,
I tested out your new binding snapshot and it works perfect for me. It do however start new threads and never quits then. This is resulting in very high CPU usage when it's enabled.
Please see attached screenshot or reference.

https://cl.ly/bb9ec208871f

**Comment by martinvw** [comment]
You are right, I did not recompile the one where I shut down the connection properly :-)

However there is still some ongoing debate about the actual implementation, I will keep you posted

**Comment by martinvw** [comment]
[org.openhab.binding.icloud-2.4.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/2398510/org.openhab.binding.icloud-2.4.0-SNAPSHOT.jar.zip)

As a start a new version which should not suffer from the same problem.

**Comment by martinvw** [comment]
@hpetersen could you check whether the version we merged now suffers from the same problems, it should be present in the current snapshot.
