### ISSUE TITLE
[groheondus] Thing intialization error with NPE

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab2-addons#3899]
Copied from original pull request: https://github.com/openhab/openhab2-addons/pull/3696#issuecomment-419673125

> Is this binding available in the snapshot yet?
> I saw it was merged but not available on paper UI
> There is nothing in the add-ons docs either
> I got my hand on a bargain Grohe sense and after downloading the jar binding I was able to create the bridge thing but the sense thing created errors when I added it and it remains uninitialized.

> Errors:
```
==> /var/log/openhab2/openhab.log <==
2018-09-08 18:20:37.871 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.groheondus.internal.handler.GroheOndusApplianceHandler@42f78543': null
java.lang.NullPointerException: null
	at org.openhab.binding.groheondus.internal.handler.GroheOndusApplianceHandler.getPollingInterval(GroheOndusApplianceHandler.java:120) [253:org.openhab.binding.groheondus:2.4.0.201809071759]
	at org.openhab.binding.groheondus.internal.handler.GroheOndusApplianceHandler.initialize(GroheOndusApplianceHandler.java:75) [253:org.openhab.binding.groheondus:2.4.0.201809071759]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [94:org.eclipse.smarthome.core:0.10.0.oh240M2]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [94:org.eclipse.smarthome.core:0.10.0.oh240M2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
==> /var/log/openhab2/events.log <==
2018-09-08 18:20:37.880 [hingStatusInfoChangedEvent] - 'groheondus:appliance:c4a2ccb4-0906-4470-b021-c8ee0ace85e7' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR)
==> /var/log/openhab2/openhab.log <==
2018-09-08 18:20:37.881 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while initializing handler of thing 'groheondus:appliance:c4a2ccb4-0906-4470-b021-c8ee0ace85e7': null
java.lang.NullPointerException: null
	at org.openhab.binding.groheondus.internal.handler.GroheOndusApplianceHandler.getPollingInterval(GroheOndusApplianceHandler.java:120) [253:org.openhab.binding.groheondus:2.4.0.201809071759]
	at org.openhab.binding.groheondus.internal.handler.GroheOndusApplianceHandler.initialize(GroheOndusApplianceHandler.java:75) [253:org.openhab.binding.groheondus:2.4.0.201809071759]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [94:org.eclipse.smarthome.core:0.10.0.oh240M2]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [94:org.eclipse.smarthome.core:0.10.0.oh240M2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by FlorianSW** [comment]
@vzorglub What exactly do you mean with "downgraded" the binding (from https://github.com/openhab/openhab2-addons/pull/3696#issuecomment-419699637). I've never tested the SENSE device, at I don't have such device in the account I used to develop this binding with, so it could be, that the device model for the SENSE is completely different from what it is for the SENSE Guard.

Reference to openHAB community thread: https://community.openhab.org/t/grohe-sense-ondus-binding/33814/8

**Comment by FlorianSW** [comment]
Closing as I can't reproduce the issue. Please re-open if it occurs again or open a new issue :)
