### ISSUE TITLE
[groheondus] Temperature channel for SENSE device throwing NPE

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab2-addons#3900]
Copied over from: https://github.com/openhab/openhab2-addons/issues/3898#issuecomment-419700208

```
2018-09-09 09:39:54.468 [.ItemChannelLinkAddedEvent] - Link 'Toilet_ThermostatAmbientTemp-groheondus:appliance:c4a2ccb4-0906-4470-b021-c8ee0ace85e7:temperature' has been added.
==> /var/log/openhab2/openhab.log <==
2018-09-09 09:39:55.146 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null

java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.library.types.QuantityType.<init>(QuantityType.java:104) ~[?:?]
	at org.openhab.binding.groheondus.internal.handler.GroheOndusApplianceHandler.updateChannel(GroheOndusApplianceHandler.java:134) ~[?:?]
	at org.openhab.binding.groheondus.internal.handler.GroheOndusApplianceHandler.channelLinked(GroheOndusApplianceHandler.java:95) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:300) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by FlorianSW** [comment]
Please reopen, if it still occurs :)
