### ISSUE TITLE
[LG webOS] Null Pointer Exception

### ISSUE THREAD

**Issue by UdoWeberJR** [openhab/openhab2-addons#3903]
If I turn of my LG OLED65B7 with the remote of the TV, I see a Null Pointer Exception in the log files, no problem for me, everything works as expected. But it should not be happening.

binding-lgwebos - 2.3.0
openhab 2.3.0-1

If I can help with other information, let me know. 

Greets Udo

```
2018-09-09 23:08:38.523 [hingStatusInfoChangedEvent] - 'lgwebos:WebOSTV:305838ee-1bfe-49b3-901f-ef5e2f5d46bc' changed from ONLINE: Connected to OFFLINE: TV is off
2018-09-09 23:08:38.559 [vent.ItemStateChangedEvent] - TV_LG_OLED65B7D_Power changed from ON to OFF

2018-09-09 23:08:38.479 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.NullPointerException: null
	at org.openhab.binding.lgwebos.internal.BaseChannelHandler.refreshSubscription(BaseChannelHandler.java:59) ~[?:?]
	at org.openhab.binding.lgwebos.handler.LGWebOSHandler.lambda$4(LGWebOSHandler.java:210) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1289) [?:?]
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) [?:?]
	at org.openhab.binding.lgwebos.handler.LGWebOSHandler.refreshAllChannelSubscriptions(LGWebOSHandler.java:210) [206:org.openhab.binding.lgwebos:2.3.0]
	at org.openhab.binding.lgwebos.handler.LGWebOSHandler.onCapabilityUpdated(LGWebOSHandler.java:156) [206:org.openhab.binding.lgwebos:2.3.0]
	at com.connectsdk.device.ConnectableDevice$2.run(ConnectableDevice.java:217) [206:org.openhab.binding.lgwebos:2.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by Alpoy** [comment]
I've been seeing this in my log as well and like you said everything works fine.

**Comment by thovoigt** [comment]
Same thing here with:

openhab2-2.3.0-1.noarch
binding-lgwebos - 2.3.0
openSUSE Leap 42.3
LG TV 42LB650V-ZN, Software Version 05.05.55, webOS 1.4.0-2529

**Comment by Hilbrand** [comment]
I've just started using this binding and saw this too. I've created a fix (https://github.com/Hilbrand/openhab2-addons/commit/8a77bd4781077a3c6d94aa67c47466c73c8d637a) and I'm going to do some extra testing tomorrow. If that looks fine, I'm going to make a PR of it.
