### ISSUE TITLE
[modbus] Test failure

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab2-addons#3910]
In a recent build there was a test failure in Modbus. I've not looked at this in detail, but I assume this test is not stable / deterministic...

https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/405/

```
Stacktrace
java.lang.AssertionError: 198.75
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.openhab.io.transport.modbus.test.SmokeTest.testRegularReadEvery50msWithCoil(SmokeTest.java:644)
Standard Output
21:58:22.194 [main] INFO  o.o.i.t.m.internal.ModbusManagerImpl - Modbus manager activated
21:58:22.195 [Thread-10] DEBUG n.wimpi.modbus.net.ModbusTCPListener - Listenening to ServerSocket[addr=/127.0.0.1,localport=59145] (Port 0)
21:58:22.200 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Executing scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00]. Current millis: 1536695902200
21:58:22.201 [ESH-modbusManagerPollerThreadPool-3] DEBUG n.w.modbus.net.TCPMasterConnection - connect()
21:58:22.201 [Thread-10] DEBUG n.wimpi.modbus.net.ModbusTCPListener - Making new connection Socket[addr=/127.0.0.1,port=47362,localport=59145]
21:58:22.202 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Request (transaction id 3): 00 03 00 00 00 06 01 01 00 01 00 0f 
21:58:22.202 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Response (transaction id 3): 00 03 00 00 00 05 01 01 02 aa 2a 
21:58:22.203 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Execution of scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00] finished at 1536695902203. Was started at millis: 1536695902200 (=duration of 3 millis)
21:58:22.254 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Executing scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00]. Current millis: 1536695902254
21:58:22.806 [ESH-modbusManagerPollerThreadPool-3] DEBUG n.w.modbus.net.TCPMasterConnection - connect()
21:58:22.807 [Thread-10] DEBUG n.wimpi.modbus.net.ModbusTCPListener - Making new connection Socket[addr=/127.0.0.1,port=47363,localport=59145]
21:58:22.812 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Request (transaction id 4): 00 04 00 00 00 06 01 01 00 01 00 0f 
21:58:22.812 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Response (transaction id 4): 00 04 00 00 00 05 01 01 02 aa 2a 
21:58:22.813 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Execution of scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00] finished at 1536695902813. Was started at millis: 1536695902254 (=duration of 559 millis)
21:58:22.864 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Executing scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00]. Current millis: 1536695902863
21:58:22.867 [ESH-modbusManagerPollerThreadPool-3] DEBUG n.w.modbus.net.TCPMasterConnection - connect()
21:58:22.867 [Thread-10] DEBUG n.wimpi.modbus.net.ModbusTCPListener - Making new connection Socket[addr=/127.0.0.1,port=47364,localport=59145]
21:58:22.873 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Request (transaction id 5): 00 05 00 00 00 06 01 01 00 01 00 0f 
21:58:22.873 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Response (transaction id 5): 00 05 00 00 00 05 01 01 02 aa 2a 
21:58:22.873 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Execution of scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00] finished at 1536695902873. Was started at millis: 1536695902863 (=duration of 10 millis)
21:58:22.924 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Executing scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00]. Current millis: 1536695902924
21:58:22.927 [ESH-modbusManagerPollerThreadPool-3] DEBUG n.w.modbus.net.TCPMasterConnection - connect()
21:58:22.927 [Thread-10] DEBUG n.wimpi.modbus.net.ModbusTCPListener - Making new connection Socket[addr=/127.0.0.1,port=47365,localport=59145]
21:58:22.934 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Request (transaction id 6): 00 06 00 00 00 06 01 01 00 01 00 0f 
21:58:22.934 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Response (transaction id 6): 00 06 00 00 00 05 01 01 02 aa 2a 
21:58:22.934 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Execution of scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00] finished at 1536695902934. Was started at millis: 1536695902924 (=duration of 10 millis)
21:58:22.985 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Executing scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00]. Current millis: 1536695902985
21:58:22.987 [ESH-modbusManagerPollerThreadPool-3] DEBUG n.w.modbus.net.TCPMasterConnection - connect()
21:58:22.987 [Thread-10] DEBUG n.wimpi.modbus.net.ModbusTCPListener - Making new connection Socket[addr=/127.0.0.1,port=47366,localport=59145]
21:58:22.995 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Request (transaction id 7): 00 07 00 00 00 06 01 01 00 01 00 0f 
21:58:22.995 [Thread-9] DEBUG n.w.modbus.net.TCPConnectionHandler - Response (transaction id 7): 00 07 00 00 00 05 01 01 02 aa 2a 
21:58:22.996 [ESH-modbusManagerPollerThreadPool-3] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Execution of scheduled (50ms) poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00] finished at 1536695902995. Was started at millis: 1536695902985 (=duration of 10 millis)
21:58:22.996 [main] INFO  o.o.i.t.m.internal.ModbusManagerImpl - Unregistering regular poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00] (interrupting if necessary)
21:58:22.997 [main] INFO  o.o.i.t.m.internal.ModbusManagerImpl - Poll task BasicPollTaskImpl@6673ac52[request=BasicModbusReadRequestBlueprint@68b45eec[slaveId=1,functionCode=READ_COILS,start=1,length=15,maxTries=1],endpoint=ModbusTCPSlaveEndpoint@6c8bc722[address=127.0.0.1,port=59145],callback=org.openhab.io.transport.modbus.test.SmokeTest$12@3670f00] canceled
21:58:22.997 [main] DEBUG o.o.i.t.m.internal.ModbusManagerImpl - Modbus manager deactivated
```

**Comment by cdjackson** [comment]
This happened again two days ago, and it's periodically preventing the OH2 build completing.

@ssalonen since you seem to have authored the tests are you able to take a look?
