### ISSUE TITLE
[CHROMECAST] Errors in Karaf as well as OpenHab log

### ISSUE THREAD

**Issue by KidSquid1** [openhab/openhab2-addons#3950]
I am receiving frequent error messages from the Chromecast binding in both the KAraf console as well as in the OH log.

Operation does not seem to be affected but I am only using the Chromcast binding at this point to use a Google Home device as an audio sink.

I have posted about this in the OH Community at:
[https://community.openhab.org/t/chromecast-binding-errors/48333](url) with no replys

I am happy to assist in providing additional information as needed.

Many thanks,

Squid

Latest Error in the Karaf console

`java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at su.litvak.chromecast.api.v2.Channel$ResultProcessor.get(Channel.java:239)
        at su.litvak.chromecast.api.v2.Channel.send(Channel.java:367)
        at su.litvak.chromecast.api.v2.Channel.sendStandard(Channel.java:336)
        at su.litvak.chromecast.api.v2.Channel.getStatus(Channel.java:451)
        at su.litvak.chromecast.api.v2.ChromeCast.getStatus(ChromeCast.java:179)
        at org.openhab.binding.chromecast.internal.ChromecastCommander.handleRefresh(ChromecastComma
nder.java:87)
        at org.openhab.binding.chromecast.handler.ChromecastHandler$Coordinator$1.run(ChromecastHand
ler.java:231)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Scheduled
ThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadP
oolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "Timer-1630" java.lang.NullPointerException
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at su.litvak.chromecast.api.v2.Channel$ResultProcessor.get(Channel.java:239)
        at su.litvak.chromecast.api.v2.Channel.send(Channel.java:367)
        at su.litvak.chromecast.api.v2.Channel.sendStandard(Channel.java:336)
        at su.litvak.chromecast.api.v2.Channel.getStatus(Channel.java:451)
        at su.litvak.chromecast.api.v2.ChromeCast.getStatus(ChromeCast.java:179)
        at org.openhab.binding.chromecast.internal.ChromecastCommander.handleRefresh(ChromecastComma
nder.java:87)
        at org.openhab.binding.chromecast.handler.ChromecastHandler$Coordinator$1.run(ChromecastHand
ler.java:231)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Scheduled
ThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadP
oolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
######### this is control command response, don't need to notify status change!
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at su.litvak.chromecast.api.v2.Channel$ResultProcessor.get(Channel.java:239)
        at su.litvak.chromecast.api.v2.Channel.send(Channel.java:367)
        at su.litvak.chromecast.api.v2.Channel.sendStandard(Channel.java:336)
        at su.litvak.chromecast.api.v2.Channel.getStatus(Channel.java:451)
        at su.litvak.chromecast.api.v2.ChromeCast.getStatus(ChromeCast.java:179)
        at org.openhab.binding.chromecast.internal.ChromecastCommander.handleRefresh(ChromecastComma
nder.java:87)
        at org.openhab.binding.chromecast.handler.ChromecastHandler$Coordinator$1.run(ChromecastHand
ler.java:231)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Scheduled
ThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadP
oolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by meingraham** [comment]
Same boat. Hopefully someone can shed some light.

I just created a new topic on the OH Community as well.

https://community.openhab.org/t/chromecast-binding-log-errors/51652

**Comment by wborn** [comment]
The InterruptedException was already solved in 2.4.0-SNAPSHOT with #3759.

We have [open issues](https://github.com/openhab/openhab2-addons/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+chromecast) for each and every other Chromecast warning/error already.
I recognize them since I'm a Chromecast user myself. :wink:
