### ISSUE TITLE
[dsmr] serial over TCP

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab2-addons#4011]
Hello @Hilbrand,

Given DSMR was the only who would support it and some serial problems in my upgraded Ubuntu environment, I thought to give it a try, however I ended up with this state:

```
2018-09-22 21:15:07.432 [DEBUG] [internal.device.DSMRSerialAutoDevice] - Stop discovery of port settings.
2018-09-22 21:15:07.432 [DEBUG] [internal.device.DSMRSerialAutoDevice] - Stop discovery of port settings.
2018-09-22 21:15:07.434 [DEBUG] [device.connector.DSMRSerialConnector] - Port does not support requested port settings (invalid dsmr:portsettings parameter?): //192.168.1.191:10003
org.eclipse.smarthome.io.transport.serial.UnsupportedCommOperationException: gnu.io.UnsupportedCommOperationException
	at org.eclipse.smarthome.io.transport.serial.rxtx.RxTxSerialPort.enableReceiveThreshold(RxTxSerialPort.java:157) ~[?:?]
	at org.openhab.binding.dsmr.internal.device.connector.DSMRSerialConnector.open(DSMRSerialConnector.java:154) [266:org.openhab.binding.dsmr:2.4.0.201809182206]
	at org.openhab.binding.dsmr.internal.device.connector.DSMRSerialConnector.open(DSMRSerialConnector.java:115) [266:org.openhab.binding.dsmr:2.4.0.201809182206]
	at org.openhab.binding.dsmr.internal.device.DSMRSerialAutoDevice.start(DSMRSerialAutoDevice.java:145) [266:org.openhab.binding.dsmr:2.4.0.201809182206]
	at org.openhab.binding.dsmr.internal.device.DSMRSerialAutoDevice.restart(DSMRSerialAutoDevice.java:155) [266:org.openhab.binding.dsmr:2.4.0.201809182206]
	at org.openhab.binding.dsmr.internal.device.DSMRDeviceRunnable.run(DSMRDeviceRunnable.java:78) [266:org.openhab.binding.dsmr:2.4.0.201809182206]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: gnu.io.UnsupportedCommOperationException
	at gnu.io.rfc2217.TelnetSerialPort.enableReceiveThreshold(TelnetSerialPort.java:900) ~[?:?]
	at org.eclipse.smarthome.io.transport.serial.rxtx.RxTxSerialPort.enableReceiveThreshold(RxTxSerialPort.java:155) ~[?:?]
	... 6 more
```

<img width="1243" alt="screen shot 2018-09-22 at 21 17 12" src="https://user-images.githubusercontent.com/2625279/45920980-ee82c500-beac-11e8-9f79-65ed340bbe5f.png">

Do you have idea what is going on?

**Comment by Hilbrand** [comment]
That looks like a problem that should be handled by the smart home implemented wrapper. Not something that every using library should make exceptions or handle these cases. So you might want to file this problem there (too).

If you want to get it to work in a remote way you could try using socat. There were some forum posts about how to use it.

**Comment by kaikreuzer** [comment]
I agree that this should be handled in the framework (assuming that such calls simply do not make sense for a remote call). Want to open an issue in ESH (or maybe directly a PR)?

**Comment by martinvw** [comment]
Okay, I did the sanity check commenting these two out, makes it work :-)

I'm still doubting what would be correct, maybe we should aim on fixing TelnetSerialPort.java#L900 but let's discuss that in ESH https://github.com/eclipse/smarthome/issues/6280
