### ISSUE TITLE
[boschindego] Unable to connect due to missing root certificate on Raspberry Pi with Java 1.8.0_65-b17

### ISSUE THREAD

**Issue by timtimsson** [openhab/openhab2-addons#4142]
Hello,
i use openhab2.3.0 with the indego binding2.3.0.
Errorcode /var/log/openhab2/openhab.log:
What could be wrong?
```
[schindego.handler.BoschIndegoHandler] - An error occurred
de.zazaz.iot.bosch.indego.IndegoException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at de.zazaz.iot.bosch.indego.IndegoController.doAuthenticate(IndegoController.java:250) ~[?:?]
        at de.zazaz.iot.bosch.indego.IndegoController.connect(IndegoController.java:117) ~[?:?]
        at org.openhab.binding.boschindego.handler.BoschIndegoHandler.poll(BoschIndegoHandler.java:106) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[?:?]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[?:?]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[?:?]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509) ~[?:?]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:?]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[?:?]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[?:?]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[?:?]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[?:?]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[?:?]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[?:?]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[?:?]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[?:?]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[?:?]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[?:?]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[?:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[?:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[?:?]
        at de.zazaz.iot.bosch.indego.IndegoController.doAuthenticate(IndegoController.java:232) ~[?:?]
        ... 9 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[?:?]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[?:?]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:?]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491) ~[?:?]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:?]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:?]
```

**Comment by jofleck** [comment]
Which OS and which Java version are you using? Do you use a custom Truststore?

**Comment by timtimsson** [comment]
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Raspberry 4.9.50-v7+
I use the default installation. I created with openssl a cert/pem and use this with lighttpd - it works..
How can i check the ssl in openhab2? 
With openssl s_client -connect localhost:8443 it looks like good....
The binding has no connection to the mover - if i call https://api.indego.iot.bosch-si.com/api/v1/ with a webinterface directly - it works with lighttpd (no problem with the external connection)
Any ideas for me???

**Comment by timtimsson** [comment]
... i restore a old backup - and i 've got the same new error with the old working backup-file...????
I'm alone?

**Comment by wborn** [comment]
> Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

Looks like the server running the API started using a new certificate that is signed by a root certificate that was not trusted by the more than 3 year old 1.8.0_65-b17 Java version.

```
$ openssl s_client -showcerts -connect api.indego.iot.bosch-si.com:443 | openssl x509 -noout -dates
depth=2 C = BM, O = QuoVadis Limited, CN = QuoVadis Root CA 2 G3
verify return:1
depth=1 C = BM, O = QuoVadis Limited, CN = QuoVadis Global SSL ICA G3
verify return:1
depth=0 C = DE, ST = Berlin, L = Berlin (Charlottenburg), O = Bosch Software Innovations GmbH, CN = api.indego.iot.bosch-si.com
verify return:1
notBefore=Jun 28 09:28:07 2018 GMT
notAfter=Jun 28 09:38:00 2020 GMT
```

Oracle added it in Java 8u91, see the [release notes](https://www.oracle.com/technetwork/java/javase/8u91-relnotes-2949462.html).

They'll need to renew the certificate again before June 28, 2020. So you may have a similar issue if the certificate is again signed by a new CA root certificate. ;-)
