### ISSUE TITLE
[Network Binding] Stops working after some pings

### ISSUE THREAD

**Issue by UdoWeberJR** [openhab/openhab2-addons#4200]
Hi,

I use the Network Binding for presence detection. It works fine, but only sometimes.
Often it stops working after some pings, over the time of timeout and retries in sum (165 seconds for Smartphone Udo).

I then tried the new 2.4 Version, same result.
I also restarted the raspberry w/o success
Also stopped openHAB, cleared cache and started it again, same problem. 

Sometime it works some hours, sometimes only some minutes. 

Here an example log, I let out unnecessary entries from my point of view, if you need more, let me know. That IP´s and names are visible is no problem for me.
After the last entry no logs for _g.network.internal.PresenceDetection_ in more then 40 minutes. So it seems to be that it stops working, I set log level to trace and can't identify the problem.

All I can see, that last ping was for Smartphone Udo with IP *.35 this time and that the last _presence_dection_type_ for it is already empty.

Everything else is working just fine. 

What can we do? Is their an option with more debugging information? 

Log
```
2018-11-05 00:19:26.314 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.187 on interface: eth0

2018-11-05 00:19:27.662 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.54 on interface: eth0

2018-11-05 00:19:27.668 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.54

2018-11-05 00:19:32.675 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35

2018-11-05 00:19:32.675 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0

2018-11-05 00:20:43.461 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0

2018-11-05 00:20:43.461 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35

2018-11-05 00:21:18.995 [vent.ItemStateChangedEvent] - Astro_SunData_PositionAzimuth changed from 4.72 to 4.99

2018-11-05 00:21:19.005 [vent.ItemStateChangedEvent] - Astro_SunData_PositionElevation changed from -55.55 to -55.54

2018-11-05 00:21:19.077 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.187

2018-11-05 00:21:19.077 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.187 on interface: eth0

2018-11-05 00:21:19.398 [vent.ItemStateChangedEvent] - Network_Smartphone_Julia_Latency changed from 225.0 to 309.0

2018-11-05 00:21:20.411 [vent.ItemStateChangedEvent] - Network_Smartphone_Julia_Lastseen changed from 2018-11-05T00:19:27.625+0100 to 2018-11-05T00:21:19.389+0100

2018-11-05 00:21:20.419 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.54 on interface: eth0

2018-11-05 00:21:20.419 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.54

2018-11-05 00:21:20.428 [me.event.ThingUpdatedEvent] - Thing 'network:pingdevice:xperia' has been updated.

2018-11-05 00:21:20.452 [vent.ItemStateChangedEvent] - Network_Desktop_Udo_Latency changed from 16.0 to 15.0

2018-11-05 00:21:21.781 [vent.ItemStateChangedEvent] - Network_Desktop_Udo_Lastseen changed from 2018-11-05T00:19:27.689+0100 to 2018-11-05T00:21:20.437+0100

2018-11-05 00:21:22.175 [vent.ItemStateChangedEvent] - Time_Date_DateTime changed from 2018-11-05T00:19:29.446+0100 to 2018-11-05T00:21:22.177+0100

2018-11-05 00:21:22.178 [vent.ItemStateChangedEvent] - Time_Date_String changed from 2018-11-05 00:19:29 CET to 2018-11-05 00:21:22 CET

2018-11-05 00:21:55.460 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0

2018-11-05 00:21:55.461 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35
```

Items
```
Switch     Network_Desktop_Udo_Online     "Online"                           {channel="network:pingdevice:desktop:online"} // (gPresentUdo) no presence detection for desktop
Number     Network_Desktop_Udo_Latency    "Pingzeit"                         {channel="network:pingdevice:desktop:latency"}
DateTime   Network_Desktop_Udo_Lastseen   "Zuletzt gesehen"                  {channel="network:pingdevice:desktop:lastseen"}

Switch     Network_Smartphone_Julia_Online                  "Online"            (gPresentJulia)     {channel="network:pingdevice:xperia:online"}
Number     Network_Smartphone_Julia_Latency                 "Pingzeit"                              {channel="network:pingdevice:xperia:latency"}
DateTime   Network_Smartphone_Julia_Lastseen                "Zuletzt gesehen"                       {channel="network:pingdevice:xperia:lastseen"}

Switch     Network_Smartphone_Udo_Online     "Online"           (gPresentUdo)   {channel="network:pingdevice:galaxy:online"}
Number     Network_Smartphone_Udo_Latency    "Pingzeit"                         {channel="network:pingdevice:galaxy:latency"}
DateTime   Network_Smartphone_Udo_Lastseen   "Zuletzt gesehen"                  {channel="network:pingdevice:galaxy:lastseen"}
```
Item Properties

Udo
```
uses_dhcp_listen | no
dhcp_state | Running normally
presence_detection_type |  
arp_state | THOMAS_HABERT_ARPING_WITHOUT_TIMEOUT
uses_ios_wakeup | On
icmp_state | IPUTILS_LINUX_PING
uses_arp_pings | no
```
Julia

```
uses_dhcp_listen | no
dhcp_state | Running normally
presence_detection_type | ICMP_PING
arp_state | THOMAS_HABERT_ARPING_WITHOUT_TIMEOUT
uses_ios_wakeup | On
icmp_state | IPUTILS_LINUX_PING
uses_arp_pings | no
```

Dektop

```
uses_dhcp_listen | no
dhcp_state | Running normally
presence_detection_type | ICMP_PING
arp_state | THOMAS_HABERT_ARPING_WITHOUT_TIMEOUT
uses_ios_wakeup | On
icmp_state | IPUTILS_LINUX_PING
uses_arp_pings | no
```

Thing
```
Thing network:pingdevice:xperia  "Network Smartphone Julia"  @ "Flat" [ hostname="192.168.178.187", retry=3, timeout=5000, refreshInterval=60000 ]
Thing network:pingdevice:galaxy  "Network Smartphone Udo"    @ "Flat" [ hostname="192.168.178.35", retry=15, timeout=5000, refreshInterval=6000 ]
Thing network:pingdevice:desktop  "Network Desktop Udo"    @ "Office" [ hostname="192.168.178.54", retry=3, timeout=5000, refreshInterval=60000 ]
```

cfg
```
binding.network:allowSystemPings=true
binding.network:allowDHCPlisten=true
binding.network:arpPingToolPath=arping
binding.network:cacheDeviceStateTimeInMS=2000
```

ARPing 2.19, by Thomas Habets

System and Binding
Raspbian GNU/Linux 9 (stretch)
Kernel = Linux 4.14.71-v7+
Platform = Raspberry Pi 3 Model B Rev 1.2
Binding = Network Binding 2.4.0.201810160926
OepnHAB = openhab 2.3.0-1

**Comment by swildner** [comment]
Are these all smartphones? If so, my guess is that they simply stop responding to pings at some point when in standby, as many of them do.

Sascha

**Comment by UdoWeberJR** [comment]
> Are these all smartphones? If so, my guess is that they simply stop responding to pings at some point when in standby, as many of them do.
> 
> Sascha

Thanks for your response. 

One is a desktop and for sure it is possible that they stop responding. But that is not the scope of this problem. 

In the case the device is not reachable, the binding should set status of _network:pingdevice:desktop:online_ to offline, that it´s not the case.
Also the binding should not stop to send ping`s at all, it should keep going in the defined interval until the device comes back online, that's not the case too. 

Greets Udo

**Comment by UdoWeberJR** [comment]
@davidgraeff 
Is their an option with more debugging information?

**Comment by davidgraeff** [comment]
No, trace is the most you get. The network binding is using the framework scheduler for getting new threads to perform the pings. I do not think that the network binding itself is leaking any thread resources, because it just calls the external "ping" utility and finishes afterwards.

But if you use scripting and create timers etc, your scripts might light thread resources and the network binding is not getting any new threads anymore at some point. Just a guess.

**Comment by UdoWeberJR** [comment]
> No, trace is the most you get. The network binding is using the framework scheduler for getting new threads to perform the pings. I do not think that the network binding itself is leaking any thread resources, because it just calls the external "ping" utility and finishes afterwards.
> 
> But if you use scripting and create timers etc, your scripts might light thread resources and the network binding is not getting any new threads anymore at some point. Just a guess.

Uhh thanks for your fast response. 👍 

Got your point, do you know if their is something like "Out of Threads Exception" in some gramework package were I can set the log level for to see if this happens?

Because I have only one timer and have a logInfo in this rule before and it`s not fired, only once.

**Comment by UdoWeberJR** [comment]
> Have a look at the openhab.cfg file and increase the thread pool size. Default is 5 or 10 or so and observe the network binding. That would be one way to determine if this is a problem.
> It's not only scripting, every add-on can ask for threads and might leak resources.

Ok, for everyone who has the same problem or is interested, here is what I found out so far:

Found the file, in my case it's
`/etc/openhab2/services/runtime.cfg`

From [this post](https://github.com/eclipse/smarthome/issues/5040) I found out, that you can add the following values to your file and that the thingHandler threadpool size is responsable:

```
# Configuration of thread pool sizes, found in some forum
# default 5, added 5 more
org.eclipse.smarthome.threadpool:thingHandler=10

# default 5
# org.eclipse.smarthome.threadpool:discovery=5

# default 10
# org.eclipse.smarthome.threadpool:safeCall=10

# default unknown
#org.eclipse.smarthome.threadpool:RuleEngine=5
```

I got the default values via karaf console:

` config:list "(service.pid=org.eclipse.smarthome.threadpool)"`

After saving the file the pool size is adapted to the values with out the need to restart openhab! Only when you are decreasing the values you have to wait until the open threads got a timeout.

Directly after saving the file w/o restart, I saw that it started again to ping:
`2018-11-07 01:26:27.084 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection...`

So @davidgraeff was right, thanks for this!
Some things blocked all 5 available threads

But the big question is now:

Why I'm running out of threads? Should the things not release the thread to the pool if they are not using it? Or should the framework not adapt the pool size to the installed things?

Via karaf console you can create a dump file, I did it while everything stopped. In this dump file their is an _threads.txt_ file with information about the running threads, but I'm unable to get out of it anything. 

`dev:dump-create`

or for just output you can do also:

`shell:threads`

I'm at the end with my knowledge, next would be to remove all thing and adding it one by one to see which caused the block, but I have some, so that would be a stupid way to do it, any idea? 
Thanks for any help.

Greets Udo

**Comment by UdoWeberJR** [comment]
@davidgraeff 
Mmm, was thinking a bit, when I have 3 network ping devices and you are doing the ping and arping at the same time, do you then need in worst case 6 threads out of the pool of 5? Or 2 at most, because you are pining the devices after each other? The log suggest me the last version.

**Comment by davidgraeff** [comment]
Threads in the network binding are named. Names start with "presenceDetectionTCP_" and "presenceDetectionARP_" and "presenceDetectionICMP_".

Your arping tool is also recognised wrong as a version below 2.18 which doesn't support a timeout. Could you please check your running applications with "ps -aux" or similar and check if there are many "arping" applications still running?

I have improved the detection of newer versions: #4206

**Comment by UdoWeberJR** [comment]
> Mmm, was thinking a bit, when I have 3 network ping devices and you are doing the ping and arping at the same time, do you then need in worst case 6 threads out of the pool of 5 and waiting forever because you block them all by yourself?
> 
> Or 2 at most, because you are pining the devices after each other? The log suggest me the last version.
> 
> But the long timeout and interval could lead to the case you have to do some all at once and then you need 6 threads. Could this be a problem? Or are you using you own pool and just one thread from the framework?


@davidgraeff Did you read this post? Because since raising the count of threads no problem, but could also other things/addons that blocked the pool.


> Threads in the network binding are named. Names start with "presenceDetectionTCP_" and "presenceDetectionARP_" and "presenceDetectionICMP_".

In the dump I created when the pining stopped completely, their is no thread with this name.
Also tried other names. Only one I found with something related to it, is this one, because of the word _PING_, but I think it is not the network binding. 

```
sender-1kfcjfl1vh PING" Id=515 TIMED_WAITING on java.util.TaskQueue@1ea197d
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@1ea197d
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)
```

> Your arping tool is also recognised wrong as a version below 2.18 which doesn't support a timeout. Could you please check your running applications with "ps -aux" or similar and check if there are many "arping" applications still running?

At the moment the pings are running since tonight, all I see is here and their a thread with _ping_ and _[arping]_ disappearing quickly, so seems to be fine. Will the change already be in the snapshot tonight, so I can test it?

Thanks, Udo

**Comment by davidgraeff** [comment]
If there are no threads with the mentioned names in the dump,
it is not the network binding that cloaks the thread pool.

@martinvw Can be closed

**Comment by UdoWeberJR** [comment]
@davidgraeff 
Removed all bindings, except for network binding, let it run for one day and this is the result:

```
[A LOT OF HOURS DOING ONLY PINGS... NOTHING ELSE ... THEN]
2018-11-24 14:28:32.440 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0
2018-11-24 14:28:32.849 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.187 on interface: eth0
2018-11-24 14:28:32.847 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.187
2018-11-24 14:28:40.584 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35
2018-11-24 14:28:40.583 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0
2018-11-24 14:28:40.986 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.187 on interface: eth0
2018-11-24 14:28:40.988 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.187
2018-11-24 14:28:48.764 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35
2018-11-24 14:28:48.764 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0
2018-11-24 14:28:49.211 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.187
2018-11-24 14:28:49.211 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.187 on interface: eth0
2018-11-24 14:28:50.367 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) ~[?:?]
	at java.lang.Thread.start(Thread.java:717) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1603) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.reExecutePeriodic(ScheduledThreadPoolExecutor.java:350) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:296) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2018-11-24 14:28:56.903 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0
2018-11-24 14:28:56.904 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35
2018-11-24 14:28:57.386 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.187 on interface: eth0
2018-11-24 14:28:57.386 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.187
2018-11-24 14:29:05.084 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35
2018-11-24 14:29:05.084 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0
2018-11-24 14:29:05.558 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.187 on interface: eth0
2018-11-24 14:29:05.565 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.187
2018-11-24 14:29:13.253 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0
2018-11-24 14:29:13.254 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35
2018-11-24 14:29:13.500 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.54 on interface: eth0
2018-11-24 14:29:13.500 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.54
2018-11-24 14:29:13.709 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) ~[?:?]
	at java.lang.Thread.start(Thread.java:717) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367) ~[?:?]
	at org.openhab.binding.network.internal.PresenceDetection.performPresenceDetection(PresenceDetection.java:276) ~[?:?]
	at org.openhab.binding.network.internal.PresenceDetection.lambda$4(PresenceDetection.java:479) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2018-11-24 14:29:13.716 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.187 on interface: eth0
2018-11-24 14:29:21.383 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35
2018-11-24 14:29:21.383 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0
2018-11-24 14:29:29.542 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35
2018-11-24 14:29:29.542 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0
2018-11-24 14:29:37.707 [TRACE] [g.network.internal.PresenceDetection] - Perform ARP ping presence detection for 192.168.178.35 on interface: eth0
2018-11-24 14:29:37.708 [TRACE] [g.network.internal.PresenceDetection] - Perform native ping presence detection for 192.168.178.35
2018-11-24 14:29:37.754 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'EventSubscriber.receive()' on 'org.eclipse.smarthome.core.internal.items.ItemUpdater@e78be5': unable to create new native thread
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) ~[?:?]
	at java.lang.Thread.start(Thread.java:717) ~[?:?]
	at org.eclipse.smarthome.core.common.QueueingThreadPoolExecutor.addToQueue(QueueingThreadPoolExecutor.java:129) ~[101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.common.QueueingThreadPoolExecutor.execute(QueueingThreadPoolExecutor.java:176) ~[101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.items.GenericItem.notifyListeners(GenericItem.java:246) ~[101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.items.GenericItem.applyState(GenericItem.java:224) ~[101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.items.GenericItem.setState(GenericItem.java:210) ~[101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.library.items.StringItem.setState(StringItem.java:86) ~[101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.internal.items.ItemUpdater.receiveUpdate(ItemUpdater.java:78) ~[101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:50) ~[101:org.eclipse.smarthome.core:0.10.0.oh230]
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [101:org.eclipse.smarthome.core:0.10.0.oh230]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [101:org.eclipse.smarthome.core:0.10.0.oh230]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]

```

Ok, I do heavy pinging, but never the less "out of memory" seems to to be the problem, don't know if its related to out of threads. But something crashes definitiv.

**Comment by davidgraeff** [comment]
You can reopen it as the original poster :)

Because of this issue I have performed a review on the code.
Personally I think this is not the network binding, but the internal core that leaks memory when executing external processes. 

It's the same outcome for the user of course with the network binding as the biggest consumer of that API.

**Comment by UdoWeberJR** [comment]
> You can reopen it as the original poster :)

Ah didn't know this. :)

Does it make sense to reopen or should it addressed to different category?
What can I do to help and identify the problem a bit more?

Greets Udo
