### ISSUE TITLE
[homeatic] binding always offline: Jetty start failed

### ISSUE THREAD

**Issue by pahofmann** [openhab/openhab2-addons#4247]
## Expected Behavior
Homematic CCU (Raspberrymatic) Thing should come online after manually adding it.

## Current Behavior
Homematic CCU Thing is in offline state. From whats in the logs I can say its a problem with Jetty:
```
2018-11-18 21:24:01.980 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'WIRED' on gateway 'd5a1bfa5' not available, disabling support
2018-11-18 21:24:01.991 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'CUXD' on gateway 'd5a1bfa5' not available, disabling support
2018-11-18 21:24:02.005 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=3.37.8.20181026,address=PEQ0628654,wired=false,hmip=true,cuxd=false,group=t
rue]
2018-11-18 21:24:02.024 [ERROR] [matic.handler.HomematicBridgeHandler] - Homematic bridge was set to OFFLINE-COMMUNICATION_ERROR due to the following exception: Jetty start failed
java.io.IOException: Jetty start failed
        at org.openhab.binding.homematic.internal.communicator.server.XmlRpcServer.start(XmlRpcServer.java:86) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.startServers(AbstractHomematicGateway.java:245) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.initialize(AbstractHomematicGateway.java:183) ~[?:?]
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.lambda$0(HomematicBridgeHandler.java:87) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.IllegalArgumentException: port out of range:-3
        at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) ~[?:?]
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:188) ~[?:?]
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:166) ~[?:?]
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[?:?]
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319) ~[?:?]
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[?:?]
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[?:?]
        at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.server.XmlRpcServer.start(XmlRpcServer.java:81) ~[?:?]
        ... 10 more

```

## Steps to Reproduce (for Bugs)
1. Run latest OpenHab via docker (--net=host)
2. Try to add Raspberrymatic CCU via Homeatic Binding

## Your Environment

* openHAB 2.3.0 (Via Docker)
* binding-homematic - 2.3.0
* Raspberrymatic 3.37.8.20181026 (On Pi3)

Can't explain why it is `port out of range:**-3**`.   
None of the Ports used by the binding are used by other applications:
```
patrick ~ $ ss -tulpn | grep LISTEN
tcp    LISTEN   0        50                0.0.0.0:445            0.0.0.0:*     
tcp    LISTEN   0        128               0.0.0.0:9090           0.0.0.0:*     
tcp    LISTEN   0        128               0.0.0.0:8899           0.0.0.0:*     
tcp    LISTEN   0        128          192.168.2.10:8100           0.0.0.0:*     
tcp    LISTEN   0        50              127.0.0.1:8101           0.0.0.0:*     
tcp    LISTEN   0        128               0.0.0.0:5000           0.0.0.0:*     
tcp    LISTEN   0        50                0.0.0.0:8200           0.0.0.0:*     
tcp    LISTEN   0        80                0.0.0.0:3306           0.0.0.0:*     
tcp    LISTEN   0        50                0.0.0.0:139            0.0.0.0:*     
tcp    LISTEN   0        128               0.0.0.0:5355           0.0.0.0:*     
tcp    LISTEN   0        128          192.168.2.10:2222           0.0.0.0:*     
tcp    LISTEN   0        50                0.0.0.0:5007           0.0.0.0:*     
tcp    LISTEN   0        50                0.0.0.0:8080           0.0.0.0:*     
tcp    LISTEN   0        128               0.0.0.0:80             0.0.0.0:*     
tcp    LISTEN   0        1                 0.0.0.0:1234           0.0.0.0:*     
tcp    LISTEN   0        1               127.0.0.1:46835          0.0.0.0:*     
tcp    LISTEN   0        128               0.0.0.0:22             0.0.0.0:*     
tcp    LISTEN   0        128             127.0.0.1:5432           0.0.0.0:*     
tcp    LISTEN   0        50                0.0.0.0:13337          0.0.0.0:*     
tcp    LISTEN   0        50           192.168.2.10:8090           0.0.0.0:*     
tcp    LISTEN   0        50                0.0.0.0:8443           0.0.0.0:*     
tcp    LISTEN   0        128               0.0.0.0:443            0.0.0.0:* 
```

**Comment by kaikreuzer** [comment]
This is likely to be fixed in the latest 2.4 snapshots already.
If not, feel free to enter an issue at https://github.com/eclipse/smarthome/issues (as this is where the Homematic binding lives now).
