### ISSUE TITLE
[squeezebox] ConcurrentModificationException causes listener thread to exit

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab2-addons#4253]
User reports that every 1-3 days the squeezebox binding stops responding to commands. Further investigation determined the following exception is being thrown.

I'm working with the user to find root cause and develop a fix.

```
2018-11-14 19:58:24.626 [DEBUG] [rnal.handler.SqueezeBoxServerHandler] - **SqueezeServerListener got unexpected exception: null
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:?]
	at org.openhab.binding.squeezebox.internal.handler.SqueezeBoxServerHandler.updatePlayer(SqueezeBoxServerHandler.java:1010) ~[167:org.openhab.binding.squeezebox:2.4.0.201811121430]
	at org.openhab.binding.squeezebox.internal.handler.SqueezeBoxServerHandler.access$8(SqueezeBoxServerHandler.java:1008) ~[167:org.openhab.binding.squeezebox:2.4.0.201811121430]
	at org.openhab.binding.squeezebox.internal.handler.SqueezeBoxServerHandler$SqueezeServerListener.handleStatusMessage(SqueezeBoxServerHandler.java:794) ~[167:org.openhab.binding.squeezebox:2.4.0.201811121430]
	at org.openhab.binding.squeezebox.internal.handler.SqueezeBoxServerHandler$SqueezeServerListener.handlePlayerUpdate(SqueezeBoxServerHandler.java:574) ~[167:org.openhab.binding.squeezebox:2.4.0.201811121430]
	at org.openhab.binding.squeezebox.internal.handler.SqueezeBoxServerHandler$SqueezeServerListener.run(SqueezeBoxServerHandler.java:444) [167:org.openhab.binding.squeezebox:2.4.0.201811121430]
```

**Comment by mhilbush** [comment]
It seems that the iteration on `squeezeBoxPlayerListeners` here
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java#L990

is not synchronized as required here
https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#synchronizedList-java.util.List-

Currently testing a fix with the user.
