### ISSUE TITLE
[chromecast] Constant "TIME_TICK" exceptions/warnings while streaming Pandora

### ISSUE THREAD

**Issue by bkpsu** [openhab/openhab2-addons#4429]
## Expected Behavior
Streaming Pandora through Chromecast Audio, executed from a Google Home (no interaction with openHAB).

## Current Behavior
While stream is active (Playing), openHAB logs show a constant "TIME_TICK" exception, with a period of 1 second. Sample exception text:

`
2018-12-23 07:29:27.112 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling

org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'TIME_TICK' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]

 at [Source: N/A; line: -1, column: -1]

	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownTypeException(StdDeserializationContext.java:273) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:117) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:74) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.deser.StdDeserializerProvider$WrappedDeserializer.deserialize(StdDeserializerProvider.java:494) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1990) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at su.litvak.chromecast.api.v2.EventListenerHolder.deliverEvent(EventListenerHolder.java:56) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at su.litvak.chromecast.api.v2.Channel.notifyListenersOfSpontaneousEvent(Channel.java:452) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at su.litvak.chromecast.api.v2.Channel.access$600(Channel.java:51) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:195) [239:org.openhab.binding.chromecast:2.5.0.201812170851]
`

## Steps to Reproduce (for Bugs)
1. Use Google Home to start Pandora stream on a Chromecast Audio
2. Observe OH logs for 1-second TIME_TICK exceptions
3. Pause Chromecast stream
4. Observe OH logs no longer show exception
5. Restart Chromecast stream
6. Observe OH logs show exception again.

## Context
Logs are over-filling and become unreadable - some system slowdown witnessed by others here:
https://community.openhab.org/t/chromecast-time-tick-errors/47979/5

## Your Environment
* Version used: OH 2.4.0 Stable, Chromecast binding 2.5.0.201812170851
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): RPI 3B
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): openHABian

**Comment by wborn** [comment]
To get it fixed it needs to be properly handled by the [chromecast-java-api-v2](https://github.com/vitalidze/chromecast-java-api-v2) library used in the binding. 

Can you also create an issue for it in the library issue tracker? Also add the received messages that show when enabling debug logging on: `su.litvak.chromecast.api.v2` 

We had similar issues fixed like that, e.g. https://github.com/vitalidze/chromecast-java-api-v2/issues/103

**Comment by bkpsu** [comment]
@wborn - Done! Added https://github.com/vitalidze/chromecast-java-api-v2/issues/106

I will get the debug log added when I have a chance.
