### ISSUE TITLE
[network] binding throws exception if host is not available

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab2-addons#4562]
I'm using network binding for presence detection. When restarting openhab or changing the network binding configuration while one device is out of home, it throws an Exception. I'm not sure if it's only an aesthetic problem or if the device isn't detected while online again. But in no case it should throw an exception. 

```
2019-01-10 20:07:01.665 [ERROR] [work.internal.handler.NetworkHandler] - Configuration for hostname is faulty
java.net.UnknownHostException: Lisas-iPhone: unknown error
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1255) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1171) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1105) ~[?:?]
	at java.net.InetAddress.getByName(InetAddress.java:1055) ~[?:?]
	at org.openhab.binding.network.internal.PresenceDetection.setHostname(PresenceDetection.java:101) ~[218:org.openhab.binding.network:2.4.0]
	at org.openhab.binding.network.internal.handler.NetworkHandler.initialize(NetworkHandler.java:160) [218:org.openhab.binding.network:2.4.0]
	at org.openhab.binding.network.internal.handler.NetworkHandler.initialize(NetworkHandler.java:211) [218:org.openhab.binding.network:2.4.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.10.0.oh240]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:744) [?:?]
```

**Comment by PascalTurbo** [comment]
@davidgraeff I've had a briefer look on the problem. The devices that leads to the exception was never detected again after this message. So it's not only an ugly message, it's a bug.

**Comment by J-N-K** [comment]
I don't think the problem is that the device is out-of-home. The error mesage (which could be better, agreed, it just spits the exception to the log) indicates a problem with the setting of the hostname. i.e. an FQDN could not be resolved to an IP address, an IP address has invalid format or something like that. Could you describe a little bit more when exactly that happens and what you configured foe the thing?

**Comment by J-N-K** [comment]
A more important question is, if we need to log that message at all. Since the thing status is updated with the important information, it shpuld be removed or at least reduced to DEBUG (also five lines below with the port error message).

**Comment by davidgraeff** [comment]
I agree to remove the log altogether, if a meaningful message is presented to the user via the Thing-Offline status.

**Comment by PascalTurbo** [comment]
@J-N-K , @davidgraeff maybe I should explain the use case:

I've added multiple iPhones to the configuration. They don't have a static DNS configuration so they are only resolvable, when they are connected to the network.
If you now start openhab and one of the iPhones isn't available to the network it is impossible to resolve the IP address of the device because there is no DNS entry for it. 
At the moment the binding stops search for this device. But it should try it again and again until it's reachable. 

As far as I can see this only happens on binding startup. It doesn't happen when the devices leaves the network for a longer time and then come back again.

**Comment by J-N-K** [comment]
Mhm. You‘ll run into issues then anyway if the up changes, since the resolution is only done once during intialization.

**Comment by PascalTurbo** [comment]
> Mhm. You‘ll run into issues then anyway if the up changes, since the resolution is only done once during intialization. So just retrying until you are successful will not solve your problem.

Mhm, isn't this a design problem? How about IPv6 only setups with changing IPs? Is it really necessary to cache the result of the DNS resolution?

**Comment by J-N-K** [comment]
Maybe. I'll have a look if that can be improved.

**Comment by J-N-K** [comment]
@davidgraeff I had a quick look at the original problem. We could either create a new `InetAddress` on each call to `performPresenceDetection` or use the cached one and try to resolve it again when the detection fails. WDYT?

**Comment by davidgraeff** [comment]
Why probably need a new object.

Looking at the documentation (https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html) the failed resolve attempt should only be cached around 10 seconds without a security manager. That doesn't work for us (and is implementation dependant anyway).

For everyone who does not want a DNS resolution every period can still just enter an IP, I guess.
