### ISSUE TITLE
[max] Sending action rebootCube causes StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by cubistico** [openhab/openhab2-addons#4618]
Rebooting the cube from either paperUI, Habpanel or via REST API will work, but cause a StringIndexOutOfBoundsException. 

## Expected Behavior
Exception should not happen.

## Current Behavior
Cube will be rebooted, but an exception is logged:
```
[ERROR] [st.core.internal.thing.ThingResource] - Exception during HTTP PUT request for update config at 'things/max:bridge:NEQ1442746/config'
java.lang.StringIndexOutOfBoundsException: String index out of range: -3
	at java.lang.String.substring(String.java:1931) [?:?]
	at org.openhab.binding.max.internal.command.UdpCubeCommand.receiveUdpCommandResponse(UdpCubeCommand.java:139) [205:org.openhab.binding.max:2.3.0]
[...]
```

## Possible Solution
The exception is caused by a wrong substring offset in org.openhab.binding.max.internal.command.UdpCubeCommand

The offset for should be 20, not 24. Since the string is only 21 chars long, an exception is thrown.

## Steps to Reproduce (for Bugs)
Reboot cube via PaperUI, Habpanel, or REST API

## Context
Not a big deal really.

## Your Environment
openHABian, openHAB 2.4

**Comment by cubistico** [comment]
See also https://community.openhab.org/t/max-cube-can-i-restart-the-cube-from-the-rule/41254/10
