### ISSUE TITLE
[SOLVED] [innogysmarthome] Binding authorization problem, authcode not accepted

### ISSUE THREAD

**Issue by profigriller** [openhab/openhab2-addons#4643]
Problem with accepting new Authcode after innogy password change

## Expected Behavior
Bridge shall accept new authcode

## Current Behavior
I changed my innogy password yesterday afternoon. at 21:43 the bridge went offline with permission problems.
I tried to create a new Authcode using the URL from here https://www.openhab.org/addons/bindings/innogysmarthome/
The authcode is created but not accepted by the binding. See Error log below.
I already tried to remove the bridge in the PaperUI and add it again. Same error message appears in log file.

The URLs contained in the PaperUI always lead to message "Wrong provider. Please use correct client login"

```
2019-01-21 16:58:25.788 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Initializing innogy SmartHome BridgeHandler...
2019-01-21 16:58:25.807 [DEBUG] [marthome.handler.InnogyBridgeHandler] - innogy config: Config [clientId=12345678, clientSecret=no secret, redirectUrl=https://www.ollie.in/innogy-smarthome-token/, authCode=XXXXXXXXXXXXXXXXXX, accessToken=, refreshToken=]
2019-01-21 16:58:25.811 [INFO ] [marthome.handler.InnogyBridgeHandler] - Initializing innogy SmartHome client...
2019-01-21 16:58:25.814 [DEBUG] [arthome.internal.client.InnogyClient] - Trying to get access and refresh tokens
2019-01-21 16:58:26.250 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Error fetching access tokens. Invalid authcode! Please generate a new one. Detail: Error fetching access token: {"errorcode":2002,"description":"Invalid token request","messages":["Reason: invalid_request"]}
2019-01-21 16:58:26.306 [DEBUG] [marthome.handler.InnogyBridgeHandler] - Disposing innogy SmartHome bridge handler 'SMARTHOME09'
2019-01-21 16:58:26.308 [DEBUG] [arthome.internal.client.InnogyClient] - Uninitializing innogy SmartHome Session...
2019-01-21 16:58:26.344 [DEBUG] [arthome.internal.client.InnogyClient] - [1] Statuscode is NOT OK: 403
2019-01-21 16:58:26.347 [TRACE] [arthome.internal.client.InnogyClient] - Response error content: null
2019-01-21 16:58:26.351 [DEBUG] [arthome.internal.client.InnogyClient] - Error without JSON message, code: 403 / message: Forbidden
2019-01-21 16:58:26.353 [DEBUG] [arthome.internal.client.InnogyClient] - Error disposing resources: Error code: 403
2019-01-21 16:58:26.354 [TRACE] [arthome.internal.client.InnogyClient] - Trace:
org.openhab.binding.innogysmarthome.internal.client.exception.ApiException: Error code: 403
        at org.openhab.binding.innogysmarthome.internal.client.InnogyClient.handleResponseErrors(InnogyClient.java:356) ~[158:org.openhab.binding.innogysmarthome:2.3.0.201802091047]
        at org.openhab.binding.innogysmarthome.internal.client.InnogyClient.uninitializeSession(InnogyClient.java:206) ~[158:org.openhab.binding.innogysmarthome:2.3.0.201802091047]
        at org.openhab.binding.innogysmarthome.internal.client.InnogyClient.dispose(InnogyClient.java:529) [158:org.openhab.binding.innogysmarthome:2.3.0.201802091047]
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.dispose(InnogyBridgeHandler.java:336) [158:org.openhab.binding.innogysmarthome:2.3.0.201802091047]
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.handleClientException(InnogyBridgeHandler.java:832) [158:org.openhab.binding.innogysmarthome:2.3.0.201802091047]
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler.access$4(InnogyBridgeHandler.java:790) [158:org.openhab.binding.innogysmarthome:2.3.0.201802091047]
        at org.openhab.binding.innogysmarthome.handler.InnogyBridgeHandler$Initializer.run(InnogyBridgeHandler.java:109) [158:org.openhab.binding.innogysmarthome:2.3.0.201802091047]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-01-21 16:58:26.358 [DEBUG] [marthome.handler.InnogyBridgeHandler] - innogy SmartHome bridge handler shut down.
2019-01-21 16:58:26.359 [ERROR] [marthome.handler.InnogyBridgeHandler] - Error initializing innogy SmartHome client.
```

## Possible Solution
none so far

## Steps to Reproduce (for Bugs)
well it currently occurs all the time

## Context
I can't access data anymore

## Your Environment
Openhab 2.4.0 Release build

**Comment by profigriller** [comment]
I decided to clear the cache which caused all other kinds of error messages in the log after starting openhab but the innogy bridge now accepted the new authcode.
So I decided to clear the cache again, did a couple of restarts and finally it is working again since 23hrs.
Strange but successful in the end.

**Comment by wborn** [comment]
Perhaps @ollie-dev knows if this is an issue in the binding?

**Comment by ollie-dev** [comment]
What I see is the old oauth redirect URL in the logs. I assume this is the stable version of the binding from OH 2.4 release. Seems like the URL did not get overwritten with the new binding. Maybe changing/selecting the brand in again in the bridge settings in PaperUI would help.

**Comment by profigriller** [comment]
I tried to change the password again and ran into the same issue again. After some hours the connection to the innogy bridge is lost.

In PaperUI I can't use the hyperlinks to get an authcode. They always lead to "Wrong Provider. Please use correct client to login"

https://api.services-smarthome.de/AUTH/authorize?response_type=code&client_id=XXXXXXXX&redirect_uri=https%3A%2F%2Fwww.ollie.in%2Fstart-smarthome-token%2F&scope&lang=de-DE

The only URL I can login are the ones from here https://www.openhab.org/addons/bindings/innogysmarthome/

Version is 
openhab> feature:list | grep innogy
openhab-binding-innogysmarthome             │ 2.4.0            │          │ Uninstalled │ openhab-addons-2.4.0        │ innogy Smarthome Binding

I find the "uninstalled" strange. When trying to install I get the following


openhab> feature:install openhab-binding-innogysmarthome
Error executing command: Error restarting bundles:
        Could not resolve module: org.openhab.binding.innogysmarthome [243]
  Another singleton bundle selected: osgi.identity; osgi.identity="org.openhab.binding.innogysmarthome"; type="osgi.bundle"; version:Version="2.3.0.201802091047"; singleton:="true"

**Comment by profigriller** [comment]
Found it and solved it
Under /usr/share/openhab2/addons there was a 2.3 snapsshot which I was not aware of. I removed the snapshot and then it came up again.

**Comment by ollie-dev** [comment]
Did you edit the Controller in Paper UI to make sure the redirect URL is fixed if cached from an old version?

**Comment by ollie-dev** [comment]
Okay, perfect.

**Comment by wborn** [comment]
Can we close this issue since it's solved @profigriller?

**Comment by ollie-dev** [comment]
Yes close it.
