### ISSUE TITLE
[chromecast] JsonMappingException on Chromecast Audio

### ISSUE THREAD

**Issue by OzZyHH** [openhab/openhab2-addons#4800]
Sometimes I have the following exception in my openhab.log file

```
2019-02-04 22:30:09.598 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling
org.codehaus.jackson.map.JsonMappingException: Can not construct instance of su.litvak.chromecast.api.v2.MediaStatus$PlayerState from String value 'LOADING': value not one of declared Enum instance names
 at [Source: N/A; line: -1, column: -1]
        at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.StdDeserializationContext.weirdStringException(StdDeserializationContext.java:243) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:74) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:23) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:899) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObjectUsingNonDefault(BeanDeserializer.java:733) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:683) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:104) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:899) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObjectUsingNonDefault(BeanDeserializer.java:733) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:683) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:600) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.deser.StdDeserializerProvider$WrappedDeserializer.deserialize(StdDeserializerProvider.java:494) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695) ~[214:org.openhab.binding.chromecast:2.4.0]
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1990) ~[214:org.openhab.binding.chromecast:2.4.0]
        at su.litvak.chromecast.api.v2.EventListenerHolder.deliverEvent(EventListenerHolder.java:56) ~[214:org.openhab.binding.chromecast:2.4.0]
        at su.litvak.chromecast.api.v2.Channel.notifyListenersOfSpontaneousEvent(Channel.java:452) ~[214:org.openhab.binding.chromecast:2.4.0]
        at su.litvak.chromecast.api.v2.Channel.access$600(Channel.java:51) ~[214:org.openhab.binding.chromecast:2.4.0]
        at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:195) [214:org.openhab.binding.chromecast:2.4.0]
```

I'm using a Chromecast Audio and openHAB 2.4 on RPI3 with Raspbian Stretch using docker

**Comment by cweitkamp** [comment]
I moved the issue to the issue tracker of the library.

https://github.com/vitalidze/chromecast-java-api-v2/issues/107

**Comment by cweitkamp** [comment]
@OzZyHH Can you add the received messages that show when enabling debug logging on: `su.litvak.chromecast.api.v2`. Thanks.

**Comment by OzZyHH** [comment]
@cweitkamp I've enabled debug logging for this class and wait for next occurence
