### ISSUE TITLE
[mqtt][mqtt.homeassistant] Compatibility with zigbee2mqtt

### ISSUE THREAD

**Issue by yozik04** [openhab/openhab2-addons#5632]
I am trying to integrate zigbee2mqtt sensors via homeassistant autodiscovery.

MQTT 2.4 documentation is not existent! =(

## Expected Behavior
zigbee2mqtt devices should appear in autodiscovery

## Current Behavior
```
2019-05-23 14:37:25.257 [DEBUG] [g.openhab.binding.mqtt.homeassistant] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=461, service.bundleid=231, service.scope=bundle, component.name=org.openhab.binding.mqtt.homeassistant.internal.discovery.HomeAssistantDiscovery, component.id=299} - org.openhab.binding.mqtt.homeassistant
2019-05-23 14:37:25.305 [ERROR] [ansport.mqtt.internal.ClientCallback] - MQTT message received. MqttMessageSubscriber#processMessage() implementation failure
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 457 path $.device.identifiers
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.ChannelConfigurationTypeAdapterFactory$2.read(ChannelConfigurationTypeAdapterFactory.java:101) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.ChannelConfigurationTypeAdapterFactory$1.read(ChannelConfigurationTypeAdapterFactory.java:77) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:888) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:853) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:802) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:774) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.BaseChannelConfiguration.fromString(BaseChannelConfiguration.java:55) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.BaseChannelConfiguration.fromString(BaseChannelConfiguration.java:66) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.discovery.HomeAssistantDiscovery.receivedMessage(HomeAssistantDiscovery.java:161) ~[?:?]
	at org.openhab.binding.mqtt.discovery.TopicSubscribe.processMessage(TopicSubscribe.java:53) ~[?:?]
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.lambda$3(ClientCallback.java:90) ~[237:org.openhab.core.io.transport.mqtt:2.5.0.201905191703]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:?]
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:90) [237:org.openhab.core.io.transport.mqtt:2.5.0.201905191703]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:513) [221:org.eclipse.paho.client.mqttv3:1.2.1]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:416) [221:org.eclipse.paho.client.mqttv3:1.2.1]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:213) [221:org.eclipse.paho.client.mqttv3:1.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 457 path $.device.identifiers
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350) ~[?:?]
	at org.openhab.binding.mqtt.generic.tools.JsonReaderDelegate.beginArray(JsonReaderDelegate.java:58) ~[?:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[?:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[?:?]
	... 19 more
2019-05-23 14:37:25.361 [TRACE] [nal.discovery.HomeAssistantDiscovery] - Discovered an already known component cover
2019-05-23 14:37:25.363 [ERROR] [ansport.mqtt.internal.ClientCallback] - MQTT message received. MqttMessageSubscriber#processMessage() implementation failure
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 345 path $.device.identifiers
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.ChannelConfigurationTypeAdapterFactory$2.read(ChannelConfigurationTypeAdapterFactory.java:101) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.ChannelConfigurationTypeAdapterFactory$1.read(ChannelConfigurationTypeAdapterFactory.java:77) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:888) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:853) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:802) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:774) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.BaseChannelConfiguration.fromString(BaseChannelConfiguration.java:55) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.BaseChannelConfiguration.fromString(BaseChannelConfiguration.java:66) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.discovery.HomeAssistantDiscovery.receivedMessage(HomeAssistantDiscovery.java:161) ~[?:?]
	at org.openhab.binding.mqtt.discovery.TopicSubscribe.processMessage(TopicSubscribe.java:53) ~[?:?]
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.lambda$3(ClientCallback.java:90) ~[237:org.openhab.core.io.transport.mqtt:2.5.0.201905191703]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:?]
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:90) [237:org.openhab.core.io.transport.mqtt:2.5.0.201905191703]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:513) [221:org.eclipse.paho.client.mqttv3:1.2.1]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:416) [221:org.eclipse.paho.client.mqttv3:1.2.1]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:213) [221:org.eclipse.paho.client.mqttv3:1.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 345 path $.device.identifiers
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350) ~[?:?]
	at org.openhab.binding.mqtt.generic.tools.JsonReaderDelegate.beginArray(JsonReaderDelegate.java:58) ~[?:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[?:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[?:?]
	... 19 more
2019-05-23 14:37:25.376 [ERROR] [ansport.mqtt.internal.ClientCallback] - MQTT message received. MqttMessageSubscriber#processMessage() implementation failure
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 362 path $.device.identifiers
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.ChannelConfigurationTypeAdapterFactory$2.read(ChannelConfigurationTypeAdapterFactory.java:101) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.ChannelConfigurationTypeAdapterFactory$1.read(ChannelConfigurationTypeAdapterFactory.java:77) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:888) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:853) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:802) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:774) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.BaseChannelConfiguration.fromString(BaseChannelConfiguration.java:55) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.BaseChannelConfiguration.fromString(BaseChannelConfiguration.java:66) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.discovery.HomeAssistantDiscovery.receivedMessage(HomeAssistantDiscovery.java:161) ~[?:?]
	at org.openhab.binding.mqtt.discovery.TopicSubscribe.processMessage(TopicSubscribe.java:53) ~[?:?]
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.lambda$3(ClientCallback.java:90) ~[237:org.openhab.core.io.transport.mqtt:2.5.0.201905191703]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:?]
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:90) [237:org.openhab.core.io.transport.mqtt:2.5.0.201905191703]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:513) [221:org.eclipse.paho.client.mqttv3:1.2.1]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:416) [221:org.eclipse.paho.client.mqttv3:1.2.1]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:213) [221:org.eclipse.paho.client.mqttv3:1.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 362 path $.device.identifiers
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350) ~[?:?]
	at org.openhab.binding.mqtt.generic.tools.JsonReaderDelegate.beginArray(JsonReaderDelegate.java:58) ~[?:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[?:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[?:?]
	... 19 more
```
## Possible Solution
- More debug logging
- Better documentation

## Context
I am trying to integrate zigbee2mqtt sensors via homeassistant autodiscovery.

```
homeassistant/cover/0x00158d999hf7dsdc/cover/config

{
  "command_topic": "/my_home/zigbee/living_room_left_curtain/set",
  "position_topic": "/my_home/zigbee/living_room_left_curtain",
  "set_position_topic": "/my_home/zigbee/living_room_left_curtain/set",
  "set_position_template": "{ \"position\": {{ position }} }",
  "value_template": "{{ value_json.position }}",
  "name": "living_room_left_curtain_cover",
  "unique_id": "0x00158d999hf7dsdc_cover_/my_home/zigbee",
  "device": {
    "identifiers": "zigbee2mqtt_0x00158d999hf7dsdc",
    "name": "living_room_left_curtain",
    "sw_version": "Zigbee2mqtt 1.4.0",
    "model": "Aqara curtain motor (ZNCLDJ11LM)",
    "manufacturer": "Xiaomi"
  },
  "availability_topic": "/my_home/zigbee/living_room_left_curtain/availability"
}

-----
homeassistant/sensor/0x00158d999hf7dsdc/cover/config

{
  "value_template": "{{ value_json.position }}",
  "icon": "mdi:view-array",
  "state_topic": "/my_home/zigbee/living_room_left_curtain",
  "json_attributes_topic": "/my_home/zigbee/living_room_left_curtain",
  "name": "living_room_left_curtain_cover",
  "unique_id": "0x00158d999hf7dsdc_cover_/my_home/zigbee",
  "device": {
    "identifiers": "zigbee2mqtt_0x00158d999hf7dsdc",
    "name": "living_room_left_curtain",
    "sw_version": "Zigbee2mqtt 1.4.0",
    "model": "Aqara curtain motor (ZNCLDJ11LM)",
    "manufacturer": "Xiaomi"
  },
  "availability_topic": "/my_home/zigbee/living_room_left_curtain/availability"
}

-----
homeassistant/sensor/0x00158d999hf7dsdc/linkquality/config

{
  "unit_of_measurement": "-",
  "value_template": "{{ value_json.linkquality }}",
  "state_topic": "/my_home/zigbee/living_room_left_curtain",
  "json_attributes_topic": "/my_home/zigbee/living_room_left_curtain",
  "name": "living_room_left_curtain_linkquality",
  "unique_id": "0x00158d999hf7dsdc_linkquality_/my_home/zigbee",
  "device": {
    "identifiers": "zigbee2mqtt_0x00158d999hf7dsdc",
    "name": "living_room_left_curtain",
    "sw_version": "Zigbee2mqtt 1.4.0",
    "model": "Aqara curtain motor (ZNCLDJ11LM)",
    "manufacturer": "Xiaomi"
  },
  "availability_topic": "/my_home/zigbee/living_room_left_curtain/availability"
}

```
I am trying to integrate zigbee2mqtt sensors via homeassistant autodiscovery.
Currently tried adding manually to PaperUI. Failed as well...

## Your Environment
* Version used: Openhab 2.5 snapshot, org.openhab.binding.mqtt.homeassistant@2.5.0.201905191805
* Environment name and version: Java 8
* Operating System and version: Docker Alpine

**Comment by davidgraeff** [comment]
> "identifiers": "zigbee2mqtt_0x00158d999hf7dsdc",

That should be an array. zigbee2mqtt is exposing wrong / non specified values here. The current HA components implementation is very strict on data types.

**Comment by yozik04** [comment]
https://www.home-assistant.io/components/binary_sensor.mqtt/

```
identifiers
(list | string)(Optional)A list of IDs that uniquely identify the device. For example a serial number.
```

**Comment by davidgraeff** [comment]
Json does not allow to express "either". It must be an array or a string.

**Comment by yozik04** [comment]
This is limitation of parsing with Gson. How can we support the current spec?

**Comment by davidgraeff** [comment]
Gson is just following the json specification. As I said there is no "union" type. HA is violating the json format by allowing both and HA need to be fixed.

**Comment by yozik04** [comment]
I have changed "identifiers" to array in a **zigbee2mqtt** fork. Discovery now works but only for one item from the type. I have 3 curtain motors. Only first is detected. I have 2 led light controllers, only first is detected. I have 2 buttons, only first one is detected.

I have added one detected device via PaperUI. But it's state is always "OFFLINE - GONE". What needs to happen so device would go out of this state. I have tried updating state and restarting mqtt so all homeassistant/+ mqtt messages got republished. Nothing changed.
Also tried adding via things file. Same result. But broker locks up and whole openhab needs a restart to fix it.

**Comment by davidgraeff** [comment]
The recent changes to the HA code is not mine tbh. I can't answer those questions without looking into the code.

> But broker locks up and whole openhab needs a restart to fix it.

That one is interesting and should not happen. Could you specify which part exactly looks up? the "embedded" (moquette) broker?

**Comment by yozik04** [comment]
I am using mosquitto. When I save a .things file that has a MQTT thing in it, all MQTT things stop receiving updates (like they were unsubscribed). Paper UI shows that all is fine with all the things. But in reality they do not work. Posting to MQTT also does not work. Openhab restart or restarting main broker client in Paper UI helps.

**Comment by davidgraeff** [comment]
In theory that would also happen if you create an MQTT Broker Thing (or Generic Thing) via PaperUI and edit the configuration, I guess? Could you try that out?

It would be interesting to know if it happens when the MQTT Broker Thing is edited or a Generic Thing is edited. Because you probably have both in a .thing file at the moment, we only know for sure if you recreate this scenario via PaperUI. That'd be sweet. (Personally I do not use .thing files, I have even removed that part from my OH, so can't debug)

**Comment by yozik04** [comment]
Just did an extended test.

My MQTT broker sits in a separate .things file:

mqtt_broker.things
-----
```
Bridge mqtt:broker:main "MQTT Broker" [ host="192.168.1.2", username="myuser", password="mypass" ] {}
```
If I edit that then all generic MQTT things do not receive updates anymore. Only Homie MQTT thing keeps working. 😱 No idea about _homeassistant_ as I could not get it fully working yet.

After each test I am restaring openhab.

generic.things
-----
```
Thing mqtt:topic:hall_curtain "Hall curtain" (mqtt:broker:main) @ "Hall" {
    Channels:
        Type dimmer:  position    "Position" [
            stateTopic="zigbee/hall_curtain", transformationPattern="JSONPATH:$.position",
            commandTopic="zigbee/hall_curtain/set", min=0, max=100, step=1, formatBeforePublish="{\"position\":%s}"
        ]
        Type switch: running      "Running" [ stateTopic="zigbee/hall_curtain", transformationPattern="JS:zigbee_curtain_running.js" ]
        Type number: linkquality  "Signal"  [ stateTopic="zigbee/hall_curtain", transformationPattern="JSONPATH:$.linkquality" ]

        Type switch: availability "Online"  [ stateTopic="zigbee/hall_curtain/availability", on="online", off="offline" ]
}
```
If I edit that then no problems occur. All keeps working.
Restarting openhab.

homie.things
-----
```
Thing mqtt:homie300:main:7a21f1ddb729 "Hygrothermograph" (mqtt:broker:main) @ "Sauna" [deviceid="7a21f1ddb729"]
```
If I edit that (For example: commenting whole Thing out and saving and back and save. Just adding a space does not trigger this problem) I get all things locked. Homie and Generic.

homeassistant.things
-----
I could not get it to work yet. Editing a config (commenting) does not trigger lock up.
```
Thing mqtt:homeassistant:main:hall_curtain "Hall curtain" (mqtt:broker:main) @ "Hall" [objectid="0x00239f1233f63320/cover"]
```
Thing is in OFFLINE - GONE state. Maybe zigbee2mqtt is not compatible... Will try to fix it.

**Comment by yozik04** [comment]
UPDATE: Adding **homeassistant** thing from Inbox in Paper UI also triggers lockup.

Maybe this error is related:
```
MQTT message received. MqttMessageSubscriber#processMessage() implementation failure
java.lang.IllegalArgumentException: ID segment '0x00239f1233f63320_cover_/home/zigbee' contains invalid characters. Each segment of the ID must match the pattern [A-Za-z0-9_-]*.
```
Maybe it is zigbee2mqtt problem...

**Comment by yozik04** [comment]
https://github.com/openhab/openhab2-addons/blob/231cb8efdd86a9b2665447b46b7a3adaa3b11718/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java#L136

This one is wrong for sure. It needs to be nodeId + objectId. This is why only one of a type is discovered.

**Comment by davidgraeff** [comment]
> java.lang.IllegalArgumentException: ID segment '0x00239f1233f63320_cover_/home/zigbee' contains invalid characters. Each segment of the ID must match the pattern [A-Za-z0-9_-]*.

Rats! The mqtt topic filter in core is too strict. I think I can even remove that filter. MQTT topics can be any utf8 characters afaik.

> I suggest using topicParts.getFallbackGroupId()

Makes sense. Could you make a quick github-editor PR? That'd be sweet.

**Comment by davidgraeff** [comment]
> If I edit that then all generic MQTT things do not receive updates anymore. Only Homie MQTT thing keeps working.

Makes sense. Homie is a separate binding and reacts different when the bridge disappears. That's a bridge offline/online defect in the Generic binding. HomeAssistant should act like Homie in that regard.

**Comment by yozik04** [comment]
@davidgraeff 

After latest change we have all devices successfully auto detected.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/2420038/58861873-13743c80-86b8-11e9-9d7a-5962c9c23f8b.png">
Do we want these items separately or merged into one thing?

When added they appear like that:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/2420038/58861921-343c9200-86b8-11e9-85ce-ba546f8d69ee.png">


**OFFLINE_GONE** is because **unique_id** contains invalid chars for UID. Waiting for **encoding** method in **AbstractUID**. https://github.com/maggu2810/openhab-core/commit/8feb1d0d2e7a0d22b0b2f8ab9d139bb837067f61

**Comment by davidgraeff** [comment]
> Do we want these items separately or merged into one thing?

A heuristic could be applied, if for example only the last topic segment is different, to group Things together. I don't know how HomeAssistant presents those apparently different HA components.

**Comment by yozik04** [comment]
In HomeAssistant it is one thing.

**Comment by yozik04** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/2420038/58880110-cdcb6a00-86df-11e9-8933-038db7473c47.png">

**Comment by davidgraeff** [comment]
In that case we want the same of course ^^

**Comment by TheLexus** [comment]
@yozik04 Does the zigbee2mqtt/mosquitto/oh2 combination works now for you? Do you use your modified zigbee2mqtt or the original version? Can you explain what do you changed..? Thank you!

**Comment by fmorillo** [comment]
I have tested this as well with openhab version 2.5.0-SNAPSHOT Build #1637, the zigbee2mqtt fork from yozik04 and I'm using an Innr Smart plug SP120.
Good things first, auto-discovery works and finds three things: switch, power and linkquality. The switch works but I have problems with the output from the linked items of power and linkquality.

The output of the power item is basically the payload with an added Watt:
```
{"state":"OFF","linkquality":105,"power":0,"current":0,"voltage":233} Watt
```

And the configuration looks like this:
```
{
"unit_of_measurement":"Watt",
"icon":"mdi:flash",
"value_template":"{{ value_json.power }}",
"state_topic":"zigbee2mqtt/Innr_1",
"json_attributes_topic":"zigbee2mqtt/Innr_1",
"name":"Innr_1_power",
"unique_id":"0x0000000000000000_power_zigbee2mqtt",
"device":{"identifiers":["zigbee2mqtt_0x0000000000000000"],"name":"Innr_1","sw_version":"Zigbee2mqtt 1.4.0","model":"Smart plug (SP 120)","manufacturer":"Innr"},
"availability_topic":"zigbee2mqtt/bridge/state"
}
```
So the unit_of_measurement is beeing used but not the value_template. Also I get the following error message in openhab:
```
Transformation service JINJA for pattern {{ value_json.power }} not found!
```
I have the same error message with value_json.linkquality and value_json.state. Any idea why the power value is not extracted out of the payload?

**Comment by yozik04** [comment]
As critical https://github.com/openhab/openhab-core/pull/864 part was already merged. Then it is time to continue improving `mqtt.homeassistant`. I did not had more time yet.

**Comment by yozik04** [comment]
This one should be interesting:
https://github.com/openhab/openhab2-addons/pull/4927

**Comment by J-N-K** [comment]
While looking at #5839 I did check the autodiscovery and IMO using the `fallbackGroupId` as `thingOd` is wrong, because it includes the `component` part. I think `"oid_"+objectId` or `"nid_"+nodeId` is the way to go. We can then use channels for the objectIds if a `nodeId` is present (always for zigbee2mqtt?) andd have one thing per `nodeId`.

**Comment by jochen314** [comment]
> So the unit_of_measurement is beeing used but not the value_template. Also I get the following error message in openhab:
> 
> ```
> Transformation service JINJA for pattern {{ value_json.power }} not found!
> ```
> 
> I have the same error message with value_json.linkquality and value_json.state. Any idea why the power value is not extracted out of the payload?
The franformation is done by the addon: org.openhab.transform.jinja
The addon must be installed for the tranfomations to work.

I have a problem with the addon in eclipse.

- Resolving the <code>app</code> without the bundle works fine.
- After adding <code>org.openhab.transform.jinja</code> the error is:
```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.openhab.transform.jinja)
          ⇒ [org.openhab.transform.jinja version=2.5.0.201908251051]
              ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.hubspot.jinjava)(&(version>=2.5.0)(!(version>=3.0.0))))
```
- I tried to add the dependency to <code>org.openhab.addons.bom.openhab-addons</code>:
```
   <dependency>
      <groupId>org.openhab.osgiify</groupId>
      <artifactId>com.hubspot.jinjava.jinjava</artifactId>
      <version>2.5.0</version>
   </dependency>
```
then I get the following error:
```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.eclipse.equinox.metatype)
```

Any ideas?
