### ISSUE TITLE
Jetty not starting: keystore missing

### ISSUE THREAD

**Issue by SuperOok** [openhab/openhab2-addons#577]
[Build 450](https://openhab.ci.cloudbees.com/job/openHAB2/450/) runtime fails to start the webserver out-of-the box with the warnings below. After copying the keystore from an old installation, it worked just fine. Is this a but or a feature? Was I supposed to create the keystore manually or smthg like that? 

Running on Raspberry Pi 2.0 with Raspbian.

```
2015-12-26 20:15:27.187 [WARN ] [.u.component.AbstractLifeCycle:212  ] - FAILED SslContextFactory@1c778bb(runtime/etc/keystore,runt                                                                            ime/etc/keystore): java.io.FileNotFoundException: /home/pi/openhab/distribution-2.0.0-SNAPSHOT-runtime-450/runtime/etc/keystore (Da                                                                            tei oder Verzeichnis nicht gefunden)java.io.FileNotFoundException: /home/pi/openhab/distribution-2.0.0-SNAPSHOT-runtime-450/runtime                                                                            /etc/keystore (Datei oder Verzeichnis nicht gefunden)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:131)
        at org.eclipse.jetty.util.resource.FileResource.getInputStream(FileResource.java:290)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:43)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:871)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:273)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

2015-12-26 20:15:27.195 [WARN ] [.u.component.AbstractLifeCycle:212  ] - FAILED SslConnectionFactory@1d1e97c{SSL-http/1.1}: java.io                                                                            .FileNotFoundException: /home/pi/openhab/distribution-2.0.0-SNAPSHOT-runtime-450/runtime/etc/keystore (Datei oder Verzeichnis nicht                                                                             gefunden)java.io.FileNotFoundException: /home/pi/openhab/distribution-2.0.0-SNAPSHOT-runtime-450/runtime/etc/keystore (Datei oder                                                                             Verzeichnis nicht gefunden)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:131)
        at org.eclipse.jetty.util.resource.FileResource.getInputStream(FileResource.java:290)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:43)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:871)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:273)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

2015-12-26 20:15:27.225 [WARN ] [.u.component.AbstractLifeCycle:212  ] - FAILED ServerConnector@160c442{SSL-http/1.1}{0.0.0.0:8443}                                                                            : java.io.FileNotFoundException: /home/pi/openhab/distribution-2.0.0-SNAPSHOT-runtime-450/runtime/etc/keystore (Datei oder Verzeich                                                                            nis nicht gefunden)java.io.FileNotFoundException: /home/pi/openhab/distribution-2.0.0-SNAPSHOT-runtime-450/runtime/etc/keystore (Da                                                                            tei oder Verzeichnis nicht gefunden)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:131)
        at org.eclipse.jetty.util.resource.FileResource.getInputStream(FileResource.java:290)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:43)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:871)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:273)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

2015-12-26 20:15:27.269 [WARN ] [.u.component.AbstractLifeCycle:212  ] - FAILED org.eclipse.jetty.server.Server@1d601cc: java.io.Fi                                                                            leNotFoundException: /home/pi/openhab/distribution-2.0.0-SNAPSHOT-runtime-450/runtime/etc/keystore (Datei oder Verzeichnis nicht ge                                                                            funden)java.io.FileNotFoundException: /home/pi/openhab/distribution-2.0.0-SNAPSHOT-runtime-450/runtime/etc/keystore (Datei oder Ver                                                                            zeichnis nicht gefunden)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:131)
        at org.eclipse.jetty.util.resource.FileResource.getInputStream(FileResource.java:290)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:43)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:871)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:273)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)

2015-12-26 20:15:27.326 [WARN ] [.i.s.JettyServerServiceTracker:120  ] - java.io.FileNotFoundException: /home/pi/openhab/distributi                                                                            on-2.0.0-SNAPSHOT-runtime-450/runtime/etc/keystore (Datei oder Verzeichnis nicht gefunden)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:131)
        at org.eclipse.jetty.util.resource.FileResource.getInputStream(FileResource.java:290)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:43)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:871)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:273)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
```

**Comment by kaikreuzer** [comment]
The certificate is generated at startup, see https://github.com/openhab/openhab2/issues/2.
It is possible that this process takes too long on a RaspPi and the Jetty is started up without the certificate. But on the next restart, it should be there. Could you check?

**Comment by SuperOok** [comment]
I cannot confirm yet. I restarted multiple times but no keystore got created. Even after 30 minutes nothing was created.

**Comment by kaikreuzer** [comment]
Note: I won't spend time to investigate this further, since we will hopefully switch to the Karaf-based distribution very soon (which might have the same problem, but the fix might be a different one).
If you are interested yourself, have a look at https://openhab.ci.cloudbees.com/job/openHAB2-Karaf/ and feel free to start testing it as well.

**Comment by SuperOok** [comment]
Ok, I'll give the Karaf version a try, as it is also the OSGi runtime we are switching to at work and it looks quite promising. However, I don't see the linked jenkins job. The URL above is dead and the cloudbees has no Karaf job at the moment. ´Where can I find it?

**Comment by kaikreuzer** [comment]
It is here: https://openhab.ci.cloudbees.com/job/openHAB-Distribution/
But please note that we are currently heavily working on it. So if you have some time, wait maybe 2 more days and it should be more stable!

**Comment by SuperOok** [comment]
Thanks for the info; I have no pressure; just curious. Is there a good background thread somewhere (Forum) about the Karaf ongoings? You write in your Christmas Carol about enhanced dependency management opportunities in Karaf compared to Equinox, where I don't understand how that works because both is just plain OSGi, isn't it? Is Maven the trick there? So you use Maven to install stuff at runtime?

**Comment by kaikreuzer** [comment]
Right here: https://github.com/openhab/openhab2/issues/194

**Comment by kaikreuzer** [comment]
Should work on the new distro
