### ISSUE TITLE
[astro] Unreliable test for SunCalc

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab2-addons#5834]
Seems to be related to #5720.

```
[ERROR] Tests run: 22, Failures: 9, Errors: 0, Skipped: 1, Time elapsed: 0.338 s <<< FAILURE! - in org.openhab.binding.astro.internal.calc.SunCalcTest
[ERROR] testGetSunInfoForNauticDawnAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.059 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.55124826E12> but was:<1.55124485E12>
	at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForNauticDawnAccuracy(SunCalcTest.java:109)
[ERROR] testGetSunInfoForNauticDuskAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.011 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.55129335E12> but was:<1.55128981E12>
	at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForNauticDuskAccuracy(SunCalcTest.java:169)
[ERROR] testGetSunInfoForAstronomicalDawnAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.5512459E12> but was:<1.55124236E12>
	at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForAstronomicalDawnAccuracy(SunCalcTest.java:98)
[ERROR] testGetSunInfoForAstronomicalDuskAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.011 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.55129571E12> but was:<1.55129217E12>
	at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForAstronomicalDuskAccuracy(SunCalcTest.java:180)
[ERROR] testGetSunInfoForRiseAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.55125272E12> but was:<1.55124918E12>
	at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForRiseAccuracy(SunCalcTest.java:131)
[ERROR] testGetSunInfoForCivilDawnAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.55125062E12> but was:<1.55124708E12>
	at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForCivilDawnAccuracy(SunCalcTest.java:120)
[ERROR] testGetSunInfoForCivilDuskAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.011 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.55129125E12> but was:<1.55128771E12>
	at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForCivilDuskAccuracy(SunCalcTest.java:158)
[ERROR] testGetSunInfoForSetAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.55129125E12> but was:<1.55128758E12>
	at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForSetAccuracy(SunCalcTest.java:149)
[ERROR] testGetSunInfoForSunNoonAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.55127199E12> but was:<1.55126845E12>
	at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForSunNoonAccuracy(SunCalcTest.java:140)
[INFO] Running org.openhab.binding.astro.internal.model.SunTest
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.openhab.binding.astro.internal.model.SunTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SunCalcTest.testGetSunInfoForAstronomicalDawnAccuracy:98 expected:<1.5512459E12> but was:<1.55124236E12>
[ERROR]   SunCalcTest.testGetSunInfoForAstronomicalDuskAccuracy:180 expected:<1.55129571E12> but was:<1.55129217E12>
[ERROR]   SunCalcTest.testGetSunInfoForCivilDawnAccuracy:120 expected:<1.55125062E12> but was:<1.55124708E12>
[ERROR]   SunCalcTest.testGetSunInfoForCivilDuskAccuracy:158 expected:<1.55129125E12> but was:<1.55128771E12>
[ERROR]   SunCalcTest.testGetSunInfoForNauticDawnAccuracy:109 expected:<1.55124826E12> but was:<1.55124485E12>
[ERROR]   SunCalcTest.testGetSunInfoForNauticDuskAccuracy:169 expected:<1.55129335E12> but was:<1.55128981E12>
[ERROR]   SunCalcTest.testGetSunInfoForRiseAccuracy:131 expected:<1.55125272E12> but was:<1.55124918E12>
[ERROR]   SunCalcTest.testGetSunInfoForSetAccuracy:149 expected:<1.55129125E12> but was:<1.55128758E12>
[ERROR]   SunCalcTest.testGetSunInfoForSunNoonAccuracy:140 expected:<1.55127199E12> but was:<1.55126845E12>
[INFO] 
[ERROR] Tests run: 39, Failures: 9, Errors: 0, Skipped: 1
```

**Comment by wmarkow** [comment]
@cweitkamp, indeed it is related to #5720. The unit tests pass only when the time zone on machine is set to **UTC+01:00**. To reproduce the issue just change the time zone on the computer to something like **UTC-09:00** (for example) and run the tests.

I will take a look at this issue and propose a pull request soon.
