### ISSUE TITLE
[knx] Close connection - maximum send attempts

### ISSUE THREAD

**Issue by shakalandy** [openhab/openhab2-addons#5861]
## Expected Behavior
Have a KNX2 binding connection with same stability as legacy knx1 bundle

## Current Behavior
From time to time my Openhab Installation is loosing its connection to the KNX bus.
This connection close was not happening with the legacy knx1 binding
Due to #5281  i'm using the current 2.5 nightly build - maybe related to that?

## Possible Solution
Increase reconnect functionality further.

## Steps to Reproduce (for Bugs)
Not sure how to reproduce - sometimes the connection close happens after a scheduled timer, sometimes just randomly.
What was interesting is that the connection was stable for 3 weeks as we have been away on holiday.

## Context
Migrated to the KNX2 binding some time ago and having regular disconnects.
Don't want to migrate back to KNX1 binding.
Want to help and make the connection even more stable as mentioned in #5281 .
Also would be interested in generating a better example conf including all the info from @lewie over here https://github.com/openhab/openhab2-addons/issues/5281#issuecomment-498284324

## Your Environment

* Version used: Openhab 2.5.0~S1640-1 
* KNX binding 2.5.0.201907171148
* System is operated on a raspberry v3+

Some error messages as an example:
```
2019-07-24 21:10:28.569 [WARN ] [net/IP Tunneling 192.168.188.29:3671] - response timeout waiting for confirmation
tuwien.auto.calimero.KNXTimeoutException: no confirmation reply received for 0.0.0->1.1.34 L_Data.req, low priority hop count 6 repeat, tpdu 43 00
        at tuwien.auto.calimero.knxnetip.ClientConnection.doExtraBlockingModes(ClientConnection.java:244) ~[?:?]
        at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:258) ~[?:?]
        at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:177) ~[?:?]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:264) ~[?:?]
        at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:332) ~[?:?]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.sendRequestWait(KNXNetworkLinkIP.java:243) ~[?:?]
        at tuwien.auto.calimero.mgmt.TransportLayerImpl.sendData(TransportLayerImpl.java:372) ~[?:?]
        at tuwien.auto.calimero.mgmt.ManagementClientImpl.send(ManagementClientImpl.java:797) ~[?:?]
        at tuwien.auto.calimero.mgmt.ManagementClientImpl.sendWait2(ManagementClientImpl.java:824) ~[?:?]
        at tuwien.auto.calimero.mgmt.ManagementClientImpl.readDeviceDesc(ManagementClientImpl.java:447) ~[?:?]
        at tuwien.auto.calimero.mgmt.ManagementProceduresImpl.isAddressOccupied(ManagementProceduresImpl.java:310) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.isReachable(AbstractKNXClient.java:339) ~[?:?]
        at org.openhab.binding.knx.internal.handler.AbstractKNXThingHandler.pollDeviceStatus(AbstractKNXThingHandler.java:148) ~[?:?]
        at org.openhab.binding.knx.internal.handler.AbstractKNXThingHandler.lambda$1(AbstractKNXThingHandler.java:188) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-07-24 21:10:30.609 [ERROR] [net/IP Tunneling 192.168.188.29:3671] - close connection - maximum send attempts
tuwien.auto.calimero.KNXAckTimeoutException: maximum send attempts, no service acknowledgment received
        at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:250) ~[?:?]
        at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:177) ~[?:?]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:264) ~[?:?]
        at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:332) ~[?:?]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.sendRequestWait(KNXNetworkLinkIP.java:243) ~[?:?]
        at tuwien.auto.calimero.mgmt.TransportLayerImpl.sendData(TransportLayerImpl.java:372) ~[?:?]
        at tuwien.auto.calimero.mgmt.ManagementClientImpl.send(ManagementClientImpl.java:797) ~[?:?]
        at tuwien.auto.calimero.mgmt.ManagementClientImpl.sendWait2(ManagementClientImpl.java:824) ~[?:?]
        at tuwien.auto.calimero.mgmt.ManagementClientImpl.readDeviceDesc(ManagementClientImpl.java:447) ~[?:?]
        at tuwien.auto.calimero.mgmt.ManagementProceduresImpl.isAddressOccupied(ManagementProceduresImpl.java:310) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.isReachable(AbstractKNXClient.java:339) ~[?:?]
        at org.openhab.binding.knx.internal.handler.AbstractKNXThingHandler.pollDeviceStatus(AbstractKNXThingHandler.java:148) ~[?:?]
        at org.openhab.binding.knx.internal.handler.AbstractKNXThingHandler.lambda$1(AbstractKNXThingHandler.java:188) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

in the case above 1.1.34 was the "address" of a KNX actuator - removed the "address" and a bit later:

``` 
2019-07-24 22:29:33.138 [WARN ] [net/IP Tunneling 192.168.188.29:3671] - response timeout waiting for confirmation
tuwien.auto.calimero.KNXTimeoutException: no confirmation reply received for 0.0.0->0/1/34 L_Data.req, low priority hop count 6 repeat, tpdu 00 81
        at tuwien.auto.calimero.knxnetip.ClientConnection.doExtraBlockingModes(ClientConnection.java:244) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:258) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:177) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:264) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:332) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.sendRequestWait(KNXNetworkLinkIP.java:243) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:397) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:354) ~[214:com.github.calimero.calimero-core:2.4.0]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.sendToKNX(AbstractKNXClient.java:456) ~[81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.writeToKNX(AbstractKNXClient.java:416) ~[81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$7(DeviceThingHandler.java:232) ~[81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:127) [81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:121) [81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.handleCommand(DeviceThingHandler.java:227) [81:org.openhab.binding.knx:2.5.0.201907130413]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [138:org.openhab.core:2.5.0.201907171010]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [138:org.openhab.core:2.5.0.201907171010]
        at com.sun.proxy.$Proxy272.handleCommand(Unknown Source) [?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [189:org.openhab.core.thing:2.5.0.201907171012]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [189:org.openhab.core.thing:2.5.0.201907171012]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [138:org.openhab.core:2.5.0.201907171010]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [138:org.openhab.core:2.5.0.201907171010]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-07-24 22:29:45.159 [ERROR] [net/IP Tunneling 192.168.188.29:3671] - close connection - maximum send attempts
tuwien.auto.calimero.KNXAckTimeoutException: maximum send attempts, no service acknowledgment received
        at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:250) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:177) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:264) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:332) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.sendRequestWait(KNXNetworkLinkIP.java:243) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:397) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:354) ~[214:com.github.calimero.calimero-core:2.4.0]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.sendToKNX(AbstractKNXClient.java:456) ~[81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.writeToKNX(AbstractKNXClient.java:416) ~[81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$7(DeviceThingHandler.java:232) ~[81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:127) [81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:121) [81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.handleCommand(DeviceThingHandler.java:227) [81:org.openhab.binding.knx:2.5.0.201907130413]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [138:org.openhab.core:2.5.0.201907171010]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [138:org.openhab.core:2.5.0.201907171010]
        at com.sun.proxy.$Proxy272.handleCommand(Unknown Source) [?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [189:org.openhab.core.thing:2.5.0.201907171012]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [189:org.openhab.core.thing:2.5.0.201907171012]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]``
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [138:org.openhab.core:2.5.0.201907171010]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [138:org.openhab.core:2.5.0.201907171010]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-07-24 22:29:45.205 [WARN ] [nx.internal.client.AbstractKNXClient] - Value 'ON' could not be sent to the KNX bus using datapoint 'command DP 0/1/34 'knx:ip:MDT', DPT id
1.001, low priority': maximum send attempts, no service acknowledgment received. Giving up now.
2019-07-24 22:29:45.207 [WARN ] [.internal.handler.DeviceThingHandler] - An error occurred on channel knx:device:MDT:ug_sa1:ug_sa1_n: maximum send attempts, no service acknowledgment received
tuwien.auto.calimero.KNXAckTimeoutException: maximum send attempts, no service acknowledgment received
        at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:250) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:177) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:264) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:332) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.sendRequestWait(KNXNetworkLinkIP.java:243) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:397) ~[214:com.github.calimero.calimero-core:2.4.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:354) ~[214:com.github.calimero.calimero-core:2.4.0]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.sendToKNX(AbstractKNXClient.java:456) ~[81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.writeToKNX(AbstractKNXClient.java:416) ~[81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$7(DeviceThingHandler.java:232) ~[81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:127) [81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:121) [81:org.openhab.binding.knx:2.5.0.201907130413]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.handleCommand(DeviceThingHandler.java:227) [81:org.openhab.binding.knx:2.5.0.201907130413]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [138:org.openhab.core:2.5.0.201907171010]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [138:org.openhab.core:2.5.0.201907171010]
        at com.sun.proxy.$Proxy272.handleCommand(Unknown Source) [?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [189:org.openhab.core.thing:2.5.0.201907171012]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [189:org.openhab.core.thing:2.5.0.201907171012]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [138:org.openhab.core:2.5.0.201907171010]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [138:org.openhab.core:2.5.0.201907171010]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
``` 

0.1.34 in that case is just the status of a light which is accessed via the OpenHab App

The MDT KNX Interface is currently accessed like this:
```
Bridge knx:ip:MDT "MDT KNX/IP Router" @ "KNX" [
	ipAddress="192.168.188.29",
	portNumber=3671,
	type="TUNNEL",
	readingPause=50,
	responseTimeout=10,
	readRetriesLimit=3,
        autoReconnectPeriod=120
]
```

i tried also removing all the default values without success.

Any hints or things i could try out?
bug or configuration problem?

Thanks very much!

**Comment by lewie** [comment]
@shakalandy, it should work! I run many KNX2 
> What was interesting is that the connection was stable for 3 weeks as we have been away on holiday.

Hmm, during your holidays, was also less influence from other devices on the network.

It seams there is a calimero connection problem, but I can't classify it right now.

For the moment, as I can see you have a MDT Router. Then I would prefer ROUTER type, broadcast is much more robust against the static TUNNEL connection:
https://www.openhab.org/addons/bindings/knx/#type-router-mode-configuration-template

**Comment by shakalandy** [comment]
@lewie Thanks for the comment!
In fact it is an IP Interface and not a router, the comment is misleading. Afaik i can't use that as router, right?

I read your comments in https://github.com/openhab/openhab2-addons/issues/5281#issuecomment-498284324 and have now removed all remaining "address" values before opening the bug. 
As far as i can see this happens when use the app and query the status of a light - the GA for the light should include the right value - so i hope that the bundle is not fetching this from the actuator somehow?
Should i set "fetch=false" then to make sure that there is no query happening?

Just to mention : i was running knx1 bundle with a similar config and the same hardware before without any reconnection issue.

**Comment by GeminiServer** [comment]
Same issue here with the knx2 and things. I have over 250 GA. I need a reliable knx. Unfortunalety, i switched back to knx1, which works really safe. My configuration port von knx1 to knx2 is done now and the KNX2 is really nice and cool to use, but it must to be stablelized. So, if i can help, please let me know.

**Comment by PBrou** [comment]
I have the same issue when I moved this week my openhab config from my Mac mini (running on 2.4) to a raspberry Pi 3+ (but on 2.5.0 build #1530).
This migration was not really a walk in the park but now the remaining problem is the KNX which is not working correctly. In my case I use a GIRA IP interface.
Exactly same behavior / issue. I absolutely never had this behavior on the Mac mini on 2.4. On the raspberry Pi 3+ I also encountered KNX issues but rather that my KNX things would not all become on-line - at the time it was used together with knxd & I thought knxd was rather at root cause but maybe I was wrong.

**Comment by shakalandy** [comment]
Following the Tips from @lewie and cleaning the config seems to work well for now.
Upgraded to 2.5 M2 and will test for another week or so, then this issue could indeed be closed.
But i would clearly vote to create an example config for knx2 and things/items and what the best way to structure it.

@PBrou & @GeminiServer did you try to simplify your configuration?

**Comment by GeminiServer** [comment]
@shakalandy what did you exaclty mean with simplify the configuration? Just reduce the things or?

This is my configuration:
```
Bridge knx:ip:bridge "KNX/IP Gateway to knxd-pi" @ "KNXD-PI" [
    ipAddress="11.11.0.2",
    portNumber=3671,
    localIp="11.11.0.3",
    type="TUNNEL",
    useNAT=true,
    readingPause=50,
    responseTimeout=10,
    readRetriesLimit=3,
    autoReconnectPeriod=30,
    localSourceAddr="0.0.0"
]
{
    Thing device knx_virtual "KNX Virtuelles Gerät"  {
        Type datetime-control : KNX_DATE    "KNX Datum an BUS Senden"  [ ga="11.001:10/0/0" ]
        Type datetime-control : KNX_TIME    "KNX Zeit an BUS Senden"   [ ga="10.001:10/0/1" ]
    }

    Thing device generic "KNX Gruppenadressen für OpenHab" [
        address="1.1.2",
        fetch=false,
        pingInterval=300
        //readInterval=60
    ] 
    {
        // Licht EG
        Type switch : LICHT_EG_WC "Licht WC" [ ga="<1/0/35" ]
       // !!
       // Plus: ~240 additional lines of Type switches,  numbers and contacts.
       // !!
   }
}
```

Cheers, 
GeminiServer

**Comment by udo1toni** [comment]
First, please do not set parameters to their default value. Second, if using a generic device, you won't have an individual address (physikalische Adresse in german) at all, so don't set address at all. 
When address isn't set, there is neither a parameter fetch nor pingInterval to use. So the things file should more look like this:
```
Bridge knx:ip:bridge "KNX/IP Gateway to knxd-pi" @ "KNXD-PI" [
    ipAddress="11.11.0.2",
    localIp="11.11.0.3", // this parameter should not be needed.
    type="TUNNEL",
    useNAT=true, // are you sure?
    autoReconnectPeriod=30  // please consider to set this parameter at least to 60
]
{
    Thing device knx_virtual "KNX Virtuelles Gerät"  {
        Type datetime-control : KNX_DATE    "KNX Datum an BUS Senden"  [ ga="11.001:10/0/0" ]
        Type datetime-control : KNX_TIME    "KNX Zeit an BUS Senden"   [ ga="10.001:10/0/1" ]
    }

    Thing device generic "KNX Gruppenadressen für OpenHab" [] 
    {
        // Licht EG
        Type switch : LICHT_EG_WC "Licht WC" [ ga="<1/0/35" ]
       // !!
       // Plus: ~240 additional lines of Type switches,  numbers and contacts.
       // !!
   }
}
```

**Comment by shakalandy** [comment]
after the lastest modifications suggested by @lewie and the update to OpenHab 2.5M2 with the KNX Reconnect modifications from #5281 my connection is stable and i don't have to restart the binding or even OpenHab anymore.
From my point of view this could be closed.

**Comment by PBrou** [comment]
After running all pending openhabian OS updates + the update to OpenHab 2.5M3 my KNX connection seems again stable. In my case 2.5M2 wasn't enough..

**Comment by GeminiServer** [comment]
I did a full upgrade to 2.5M3 and unfortunately i still have the same issue with this build also. So my Problem is not fixed.

Here the logs. Disconnections are every 5-10 Minutes. Auto reconnection is working. 
Everything is working, exept the Disconnections.  
```
16:48:11.914 [WARN ] [ip.KNXnet/IP Tunneling 11.11.0.2:3671] - received disconnect response status 0x21 (no active data connection with that ID)
16:48:11.917 [ERROR] [ip.KNXnet/IP Tunneling 11.11.0.2:3671] - close connection - maximum send attempts
tuwien.auto.calimero.KNXAckTimeoutException: maximum send attempts, no service acknowledgment received
	at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:250) ~[209:com.github.calimero.calimero-core:2.4.0]
	at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:177) ~[209:com.github.calimero.calimero-core:2.4.0]
	at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:264) ~[209:com.github.calimero.calimero-core:2.4.0]
	at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:332) ~[209:com.github.calimero.calimero-core:2.4.0]

...

...

16:53:42.540 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'knx:ip:bridge' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): maximum send attempts
16:53:42.545 [ERROR] [calimero.link.11.11.0.2:3671         ] - send error, closing link
tuwien.auto.calimero.knxnetip.KNXConnectionClosedException: send attempt on closed connection
	at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:215) ~[?:?]
```
Binding Version:
```
openhab> bundle:list -s |grep knx
237 │ Active  │  80 │ 1.14.0.M3             │ org.openhab.binding.knx
238 │ Active  │  80 │ 2.5.0.M3              │ org.openhab.binding.knx

```

My setting/configuration for KNX2 is: 
```
Bridge knx:ip:bridge "KNX/IP Gateway to knxd-pi" @ "KNXD-PI" [
    ipAddress="11.11.0.2",
    type="TUNNEL",
    autoReconnectPeriod=60
]
{
    Thing device knx_virtual "KNX Virtuelles Gerät"  {
        Type datetime-control : KNX_DATE    "KNX Datum an BUS Senden"  [ ga="11.001:10/0/0" ]
        Type datetime-control : KNX_TIME    "KNX Zeit an BUS Senden"   [ ga="10.001:10/0/1" ]
    }

    Thing device generic "KNX Gruppenadressen für OpenHab" [] 
    {
        // Licht EG
        Type switch : LICHT_EG_WC "Licht WC" [ ga="<1/0/35" ]
       // !!
       // Plus: ~240 additional lines of Type switches,  numbers and contacts.
       // !!
   }
}
```

I use a KNXD connected to Siemens N148 21: 
`knxd --version  --> knxd 0.14.25:4358f34
`

**Comment by lewie** [comment]
@GeminiServer, why do you use TUNNEL mode with KNXD?
Please use ROUTER mode between openHAB and KNXD and your Problem should be solved.

**Comment by PBrou** [comment]
@lewie, @GeminiServer, although there is now the auto reconnect, my KNX connection drops once and a while, at the wrong moment... when my rules need to fire some KNX actions.. which don't work. Conclusion: no stable KNX connection.
I am also going to check out the setup with the intermediate KNXD...
