### ISSUE TITLE
[mqtt] NumberFormatException while parsing/handle command

### ISSUE THREAD

**Issue by gerripeach** [openhab/openhab2-addons#6039]
## Expected Behavior
Be able to use custom on/off types for mqtt things(channels)

## Current Behavior
`java.lang.NumberFormatException` because command is not parsed as string(?)

```
2019-09-07 21:08:38.795 [ome.event.ItemCommandEvent] - Item 'Livingroom_ikea_e27_01' received command ON
2019-09-07 21:08:38.795 [nt.ItemStatePredictedEvent] - Livingroom_ikea_e27_01 predicted to become ON

==> /opt/docker-projects/openhab/openhab/userdata/logs/openhab.log <==
2019-09-07 21:08:38.797 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.eclipse.smarthome.binding.mqtt.generic.internal.handler.GenericThingHandler@7a66dcf7': null
java.lang.NumberFormatException: null
        at java.math.BigDecimal.<init>(BigDecimal.java:497) ~[?:?]
        at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[?:?]
        at java.math.BigDecimal.<init>(BigDecimal.java:809) ~[?:?]
        at org.eclipse.smarthome.core.library.types.DecimalType.<init>(DecimalType.java:57) ~[102:org.eclipse.smarthome.core:0.10.0.oh240]
        at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:47) ~[102:org.eclipse.smarthome.core:0.10.0.oh240]
        at org.eclipse.smarthome.core.library.types.PercentType.valueOf(PercentType.java:63) ~[102:org.eclipse.smarthome.core:0.10.0.oh240]
        at org.eclipse.smarthome.binding.mqtt.generic.internal.values.PercentageValue.update(PercentageValue.java:87) ~[?:?]
        at org.eclipse.smarthome.binding.mqtt.generic.internal.generic.ChannelState.publishValue(ChannelState.java:302) ~[?:?]
        at org.eclipse.smarthome.binding.mqtt.generic.internal.handler.AbstractMQTTThingHandler.handleCommand(AbstractMQTTThingHandler.java:119) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at com.sun.proxy.$Proxy125.handleCommand(Unknown Source) [227:org.eclipse.smarthome.binding.mqtt.generic:0.10.0.oh240]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

## Possible Solution
https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java#L109

The command seems to be no instance of string. When I use the on/off type it works. Maybe use the same logic to process custom on/off types like in here:
https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OnOffValue.java#L74

## Steps to Reproduce (for Bugs)
.things file:
```
Bridge mqtt:broker:brokerhome [ host="", secure=false ]{
    Thing topic kitchen {
    Channels:
        Type dimmer : kitchen_ikea_gu10_01 "Room 1"
        [
            stateTopic="zigbee2mqtt/kitchen_ikea_gu10_01/get",
            commandTopic="zigbee2mqtt/kitchen_ikea_gu10_01/set",
            formatBeforePublish="{\"brightness_percent\":\"%s\"}",
            on="ON",
            off="OFF",
            min="0",
            max="255",
            step="10"
        ]
```

.items file:
```
Dimmer Kitchen_ikea_gu10_01 "Lamp 1" <lightbulb> (Kitchen) {
        channel="mqtt:topic:brokerhome:kitchen:kitchen_ikea_gu10_01",
        alexa="Lighting"
    }
```

## Context
I want to control zigbee devices with speech, without using any proprietary bridges.

## Your Environment
- openhab 2.4 in docker enviroment
- alexa, connected via the openhab skill to my instance
- some mqtt backend so switch devices on and off

**Comment by gerripeach** [comment]
updated to openhab:2.5.0.M3. its working now.
