### ISSUE TITLE
Removing a Freebox thing leads to an exception

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#627]
While the Freebox binding is not working, I tried to remove the thing using Paper UI.
It leaded to this exception:

```
12:25:55.606 [ERROR] [ome.core.thing.internal.ThingManager] - The ItemHandler caused an exception while handling the removal of its thing
java.lang.NullPointerException
        at org.eclipse.smarthome.core.thing.internal.ThingManager$1.statusUpdated(ThingManager.java:186)
        at org.eclipse.smarthome.core.thing.internal.ThingManager.thingRemoving(ThingManager.java:388)
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:209)
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.remove(ThingRegistryImpl.java:105)
        at org.eclipse.smarthome.core.thing.setup.ThingSetupManager.removeThing(ThingSetupManager.java:434)
        at org.eclipse.smarthome.io.rest.core.thing.setup.ThingSetupManagerResource.removeThing(ThingSetupManagerResource.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0]
        at java.lang.reflect.Method.invoke(Method.java:483)[:1.8.0]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[12:com.eclipsesource.jaxrs.publisher:5.3.0.201512270850]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)[71:org.eclipse.jetty.servlet:9.2.10.v20150310]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[71:org.eclipse.jetty.servlet:9.2.10.v20150310]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[135:org.ops4j.pax.web.pax-web-jetty:4.2.3]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[69:org.eclipse.jetty.security:9.2.10.v20150310]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[135:org.ops4j.pax.web.pax-web-jetty:4.2.3]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[71:org.eclipse.jetty.servlet:9.2.10.v20150310]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[135:org.ops4j.pax.web.pax-web-jetty:4.2.3]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.Server.handle(Server.java:497)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[70:org.eclipse.jetty.server:9.2.10.v20150310]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)[62:org.eclipse.jetty.io:9.2.10.v20150310]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[73:org.eclipse.jetty.util:9.2.10.v20150310]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[73:org.eclipse.jetty.util:9.2.10.v20150310]
        at java.lang.Thread.run(Thread.java:744)[:1.8.0]
12:25:55.614 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'freebox:server:a6222edf' changed from UNINITIALIZED (HANDLER_INITIALIZING_ERROR): javax/net/ssl/HostnameVerifier to REMOVING
```
The thing remained in a status REMOVING.
I was able to remove it forcing a removal with Paper UI (second remove).

**Comment by kaikreuzer** [comment]
This does not be to be in any way related to the Freebox binding, but a general bug. I have created https://github.com/eclipse/smarthome/issues/868 for it.
