### ISSUE TITLE
[mqtt.homie] HomieThingHandlerTests.handleCommandRefresh test fails

### ISSUE THREAD

**Issue by wborn** [openhab/openhab2-addons#6408]
The `HomieThingHandlerTests.handleCommandRefresh` test has been failing for some days now:

```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.459 s <<< FAILURE! - in org.openhab.binding.mqtt.homie.internal.handler.HomieThingHandlerTests
[ERROR] handleCommandRefresh(org.openhab.binding.mqtt.homie.internal.handler.HomieThingHandlerTests)  Time elapsed: 0.013 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
callback.stateUpdated(
    <Homie thing handler tests$$ lambda$ 9 0/ 0x 0 0 0 0 0 0 0 8 0 0 2 5 6 0 4 0>,
    <Homie thing handler tests$$ lambda$ 9 1/ 0x 0 0 0 0 0 0 0 8 0 0 2 5 6 4 4 0>
);
-> at org.openhab.binding.mqtt.homie.internal.handler.HomieThingHandlerTests.handleCommandRefresh(HomieThingHandlerTests.java:235)
Actually, there were zero interactions with this mock.

	at org.openhab.binding.mqtt.homie.internal.handler.HomieThingHandlerTests.handleCommandRefresh(HomieThingHandlerTests.java:235)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   HomieThingHandlerTests.handleCommandRefresh:235 
Wanted but not invoked:
callback.stateUpdated(
    <Homie thing handler tests$$ lambda$ 9 0/ 0x 0 0 0 0 0 0 0 8 0 0 2 5 6 0 4 0>,
    <Homie thing handler tests$$ lambda$ 9 1/ 0x 0 0 0 0 0 0 0 8 0 0 2 5 6 4 4 0>
);
-> at org.openhab.binding.mqtt.homie.internal.handler.HomieThingHandlerTests.handleCommandRefresh(HomieThingHandlerTests.java:235)
Actually, there were zero interactions with this mock.
```

Do you know what might be causing this test to fail and do you have a fix for this @J-N-K, @davidgraeff? 

If there is no easy solution it might be better to ignore it for now so full builds succeed again.

**Comment by davidgraeff** [comment]
Do we keep this open here now that the test is ignore?

**Comment by wborn** [comment]
Do you or @J-N-K know what's causing the test to fail? If the test is correct there is  regression that needs to be fixed. If there isn't the test should be fixed.

**Comment by davidgraeff** [comment]
Refresh handling has changed in the mqtt binding. This test needs to be adapted, I think, but I'm not sure if anyone has time for that atm.
