### ISSUE TITLE
Crash of plugin when removing the usb plug

### ISSUE THREAD

**Issue by jrcourtois** [openhab/openhab2-addons#644]
Obviously, you could say that I don't have to unplug it, but it can happens.
I got this stacktrace
```
2016-01-26 11:06:15.212 [ERROR] [.opencean.core.EnoceanByteStreamPipe] - Error while reading from COM port. Stopping.
java.io.IOException: Device not configured in readByte
	at gnu.io.RXTXPort.readByte(Native Method)
	at gnu.io.RXTXPort$SerialInputStream.read(RXTXPort.java:1286)[167:org.openhab.io.transport.serial:2.0.0.201601211059]
	at org.opencean.core.EnoceanByteStreamPipe.run(EnoceanByteStreamPipe.java:27)[166:org.openhab.binding.enocean:1.9.0.201601220210]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

The problem is when I re plug it, it is not working, and simply restarting the binding does not work. I have to restart the whole openhab.

**Comment by kaikreuzer** [comment]
As there is no enocean binding in openhab2-addons, shouldn't this issue rather to go https://github.com/openhab/openhab/issues?
