### ISSUE TITLE
[IPP] waiting jobs always returns -NaN in OH 2.5.0.M5

### ISSUE THREAD

**Issue by TommyFive** [openhab/openhab2-addons#6471]
All channels like waiting_jobs on IPP printers return -NaN with OH 2.5.0.M5. With 2.4.0 everything works well.

## Expected Behavior
Waiting jobs should return the real printer's waiting jobs value. 

## Current Behavior

Waiting jobs always returns -NaN
![image](https://user-images.githubusercontent.com/8273791/69832603-97564e00-122f-11ea-9fa4-927c847437a1.png)

## Possible Solution

No solution found other the doing an downgrade to OH 2.4.0 release.
I have tried to delete the think / items and recreate it. But this does not help.

## Steps to Reproduce (for Bugs)

1. Add a printer thing
2. Connect an item to waiting jobs channel
3. Add a printer job and observe the waiting jobs item

## Your Environment
<!-- Include as many relevant details about the environment you experienced the bug 
OH 2.5.0.M5
Linux openHABianPi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l

**Comment by TommyFive** [comment]
After updating the thing settings, I can see the following error in the events.log

2019-11-30 11:51:48.857 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NoClassDefFoundError: org/simpleframework/xml/Serializer
	at ch.ethz.vppserver.ippclient.IppAttributeProviderFactory.createIppAttributeProvider(IppAttributeProviderFactory.java:5) ~[?:?]
	at ch.ethz.vppserver.ippclient.IppResponse.<init>(IppResponse.java:54) ~[?:?]
	at org.cups4j.operations.IppOperation.sendRequest(IppOperation.java:220) ~[?:?]
	at org.cups4j.operations.IppOperation.sendRequest(IppOperation.java:131) ~[?:?]
	at org.cups4j.operations.IppOperation.request(IppOperation.java:67) ~[?:?]
	at org.cups4j.operations.ipp.IppGetJobsOperation.getPrintJobs(IppGetJobsOperation.java:119) ~[?:?]
	at org.cups4j.CupsPrinter.getJobs(CupsPrinter.java:330) ~[?:?]
	at org.openhab.binding.ipp.internal.handler.IppPrinterHandler.onDeviceStateChanged(IppPrinterHandler.java:131) ~[?:?]
	at org.openhab.binding.ipp.internal.handler.IppPrinterHandler.lambda$0(IppPrinterHandler.java:110) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.ClassNotFoundException: org.simpleframework.xml.Serializer cannot be found by org.openhab.binding.ipp_2.5.0.M5
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[org.eclipse.osgi-3.12.100.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	... 16 more

**Comment by kaikreuzer** [comment]
@J-N-K The pom.xml contains
```
    <bnd.importpackage>!org.simpleframework.xml.*</bnd.importpackage>
```
Where is this dependency expected to be resolved from? Should https://github.com/openhab/openhab2-addons/pull/6481 fix it?

Btw, in the IDE I cannot resolve the binding as it complains about missing commons-io 1.4 - any clue why it has this version constraint on the import-package? I'm confused...
