### ISSUE TITLE
RFXCOM exception when logging out from openHAB2

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#649]
Here is the exception I get when I logout from OH2:
```
Exception in thread "ESH-thingManager-1" java.lang.IllegalAccessError: org.openhab.binding.rfxcom.handler.RFXComHandler.bridgeHandlerDisposed(Lorg/eclipse/smarthome/core/thing/binding/ThingHandler;Lorg/eclipse/smarthome/core/thing/Bridge;)V
        at org.eclipse.smarthome.core.thing.internal.ThingManager$11.run(ThingManager.java:695)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
Exception in thread "ESH-thingManager-2" java.lang.IllegalAccessError: org.openhab.binding.rfxcom.handler.RFXComHandler.bridgeHandlerDisposed(Lorg/eclipse/smarthome/core/thing/binding/ThingHandler;Lorg/eclipse/smarthome/core/thing/Bridge;)V
        at org.eclipse.smarthome.core.thing.internal.ThingManager$11.run(ThingManager.java:695)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by kaikreuzer** [comment]
JavaDoc says: "this error can only occur at run time if the definition of a class has incompatibly changed."
So it seems that the RFXCOMHandler has been compiled against an older version of ESH. This might be the case, since the last build was from Jan 23. openHAB distro 114 now contains RFXCOM build from yesterday, so I would assume this issue is resolved with it. Please re-open, if my assumption is wrong!

**Comment by lolodomo** [comment]
Confirmed. No exception with snapshot 114.

**Comment by kaikreuzer** [comment]
:+1:
