### ISSUE TITLE
[telegram] Installation via PaperUI fails with exceptions

### ISSUE THREAD

**Issue by ZzetT** [openhab/openhab2-addons#6501]
When I try to install the Telegram binding via the PaperUI, I see a lot of exceptions in the karaf console. Compiling via maven and using the JAR works however.

```
openhab> org.apache.karaf.features.internal.util.MultiException: Error:
        Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar
        Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar
        Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/logging-interceptor/3.12.3/logging-interceptor-3.12.3.jar
        Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/logging-interceptor/3.12.3/logging-interceptor-3.12.3.jar
        Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/github/pengrad/java-telegram-bot-api/4.4.0/java-telegram-bot-api-4.4.0.jar
        Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/github/pengrad/java-telegram-bot-api/4.4.0/java-telegram-bot-api-4.4.0.jar
        Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/okhttp/3.12.3/okhttp-3.12.3.jar
        Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/okhttp/3.12.3/okhttp-3.12.3.jar
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.io.IOException: Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                ... 3 more
        Caused by: java.io.IOException: Could not download [wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar]
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:92)
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
                ... 7 more
        Caused by: java.net.MalformedURLException: unknown protocol: wrap
                at java.net.URL.<init>(URL.java:600)
                at java.net.URL.<init>(URL.java:490)
                at java.net.URL.<init>(URL.java:439)
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:63)
                ... 8 more
        [CIRCULAR REFERENCE:java.io.IOException: Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar]
        Suppressed: java.io.IOException: Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/logging-interceptor/3.12.3/logging-interceptor-3.12.3.jar
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                ... 3 more
        Caused by: java.io.IOException: Could not download [wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/logging-interceptor/3.12.3/logging-interceptor-3.12.3.jar]
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:92)
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
                ... 7 more
        Caused by: java.net.MalformedURLException: unknown protocol: wrap
                at java.net.URL.<init>(URL.java:600)
                at java.net.URL.<init>(URL.java:490)
                at java.net.URL.<init>(URL.java:439)
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:63)
                ... 8 more
        [CIRCULAR REFERENCE:java.io.IOException: Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/logging-interceptor/3.12.3/logging-interceptor-3.12.3.jar]
        Suppressed: java.io.IOException: Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/github/pengrad/java-telegram-bot-api/4.4.0/java-telegram-bot-api-4.4.0.jar
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                ... 3 more
        Caused by: java.io.IOException: Could not download [wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/github/pengrad/java-telegram-bot-api/4.4.0/java-telegram-bot-api-4.4.0.jar]
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:92)
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
                ... 7 more
        Caused by: java.net.MalformedURLException: unknown protocol: wrap
                at java.net.URL.<init>(URL.java:600)
                at java.net.URL.<init>(URL.java:490)
                at java.net.URL.<init>(URL.java:439)
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:63)
                ... 8 more
        [CIRCULAR REFERENCE:java.io.IOException: Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/github/pengrad/java-telegram-bot-api/4.4.0/java-telegram-bot-api-4.4.0.jar]
        Suppressed: java.io.IOException: Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/okhttp/3.12.3/okhttp-3.12.3.jar
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                ... 3 more
        Caused by: java.io.IOException: Could not download [wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/okhttp/3.12.3/okhttp-3.12.3.jar]
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:92)
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
                ... 7 more
        Caused by: java.net.MalformedURLException: unknown protocol: wrap
                at java.net.URL.<init>(URL.java:600)
                at java.net.URL.<init>(URL.java:490)
                at java.net.URL.<init>(URL.java:439)
                at org.apache.karaf.features.internal.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:63)
                ... 8 more
        [CIRCULAR REFERENCE:java.io.IOException: Error downloading wrap:file:/C:/Users/winuser/DOWNLO~1/OPENHA~1.M6/userdata/tmp/mvn/com/squareup/okhttp3/okhttp/3.12.3/okhttp-3.12.3.jar]
```

## Steps to Reproduce (for Bugs)
1. Click the install button in PaperUI

## Your Environment

* Version used: OH 2.5.0.M6
* Environment name and version: openjdk version "1.8.0_222",OpenJDK Runtime Environment (Zulu 8.40.0.25-win64)-Microsoft-Azure-restricted (build 1.8.0_222-b10),OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-win64)-Microsoft-Azure-restricted (build 25.222-b10, mixed mode)
* Operating System and version: Windows 64 bit

**Comment by kaikreuzer** [comment]
@J-N-K Did we lose somehow the "wrap" feature? I've seen such reports more often recently...

**Comment by wborn** [comment]
It's not installed by default see also https://github.com/openhab/openhab-core/pull/676. So if it's not a feature prerequisite in feature.xml it won't work for everyone. Preferably wrap isn't used at all and non-osgi-bundle dependencies are embedded into the JAR. That way they don't give issues with itests or when debugging add-ons in the Demo App.

**Comment by J-N-K** [comment]
As far as I can see we can embed everything here since we don't use okio/okhttp3 for other bundles. We have okio 1.3.0 in our osgiify, maybe we can bum that, but that seems to be a little bit dangerous. 

Why do we need to add bundles in the feature at all? Everything should be embedded by default if it is not excluded. Or are we facing a similar issue here like `javax.mail`?

Regarding the on-the-fly-wrapping: Like @wborn said. But this surely breaks the bnd-resolver for the IDE as it can't wrap like karaf.

**Comment by wborn** [comment]
I haven't looked into the mail binding issue... but for MaryTTS (https://github.com/openhab/openhab2-addons/pull/6482) there were embedding issues because there was important configuration data in each JAR in the same marytts.config.MaryConfig file that was overwritten when all contents were merged. I fixed that by adding a merged version.

Sometimes you also get class path issues because the file order may change if you start using content from other bundles that was previously provided by JARs in your own bundle.

**Comment by kaikreuzer** [comment]
> Regarding the on-the-fly-wrapping: Like @wborn said. But this surely breaks the bnd-resolver for the IDE as it can't wrap like karaf.

As we still seem to use the wrapping at some places, it seems to be the safest to apply it here, so that it works for the release. After the 2.5 release, I agree that we should work on removing all wrapping to allow easy use within the IDE. Wdyt?

**Comment by J-N-K** [comment]
Where do we use wrappings in openhab2-addons? I thought I removed every occurence.

I did test installing the bundle alone and it works - as expected - perfectly without installing additional dependencies.

**Comment by kaikreuzer** [comment]
> I thought I removed every occurence.

Well, this issue proves your wrong then ;-) . If that was the only one, all is fine!

**Comment by wborn** [comment]
I grepped around and found that linuxinput and dlinksmarthome still have some:

```
bundles/org.openhab.binding.linuxinput/src/main/feature/feature.xml:        <feature prerequisite="true">wrap</feature>
bundles/org.openhab.binding.linuxinput/src/main/feature/feature.xml:        <bundle dependency="true">wrap:mvn:com.github.jnr/jnr-posix/3.0.47$overwrite=merge&amp;Import-Package=jnr.ffi.provider.jffi,jnr.constants,jnr.constants.platform,jnr.constants.platform.windows,jnr.ffi,jnr.ffi.annotations,jnr.ffi.byref,jnr.ffi.mapper,jnr.ffi.provider,jnr.ffi.types,com.kenai.jffi,jnr.ffi.provider.converters</bundle>
bundles/org.openhab.binding.linuxinput/src/main/feature/feature.xml:        <bundle dependency="true">wrap:mvn:com.github.jnr/jnr-a64asm/1.0.0$Bundle-Name=jnr-a64asm&amp;Bundle-SymbolicName=com.github.jnr.jnr-a64asm&amp;Bundle-Version=1.0.0</bundle>
bundles/org.openhab.binding.linuxinput/src/main/feature/feature.xml:        <bundle dependency="true">wrap:mvn:com.github.jnr/jnr-x86asm/1.0.2$Bundle-Name=jnr-x86asm&amp;Bundle-SymbolicName=com.github.jnr.jnr-x86asm&amp;Bundle-Version=1.0.2</bundle>
bundles/org.openhab.binding.dlinksmarthome/src/main/feature/feature.xml:        <feature prerequisite="true">wrap</feature>
bundles/org.openhab.binding.dlinksmarthome/src/main/feature/feature.xml:        <bundle dependency="true">wrap:mvn:com.sun.xml.ws/jaxws-rt/2.2.10$Bundle-Name=JAX%20WS%20RI%20Runtime%20Bundle&amp;Bundle-SymbolicName=com.sun.xml.ws.jaxws-rt&amp;Bundle-Version=2.3.2</bundle>
```

**Comment by wborn** [comment]
There are also a few webui features that still use wrap:
* [CometVisu Backend](https://github.com/openhab/openhab-webui/blob/6ada19c3d09d087ae8da63d556cc9e758d82fbbb/features/src/main/feature/feature.xml#L48-L49)
* [HABmin](https://github.com/openhab/openhab-webui/blob/6ada19c3d09d087ae8da63d556cc9e758d82fbbb/features/src/main/feature/feature.xml#L88-L89)

Instead they should use the jaxb feature using:

```
<feature dependency="true">openhab.tp-jaxb</feature>
```

In core there are only some commented [wrap left overs](https://github.com/openhab/openhab-core/blob/98d27b185adc46071b4adaf86d5050d751bf4109/features/karaf/openhab-tp/src/main/feature/feature.xml#L250-L251). :-)
