### ISSUE TITLE
Setup tasks fail due to namespace clash between OH1 and OH2

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2-addons#673]
Just ran into an error when importing projects as part of the "setup tasks":

  ERROR: org.eclipse.core.resources code=77 /Users/kgoderis/openhab2-beta1/git/openhab/bundles/binding/org.openhab.binding.zwave overlaps the location of another project: 'org.openhab.binding.zwave'

I guess there will many more of these as some bindings are in the process of being migrated from OH1 to OH2 as well.

**Comment by kaikreuzer** [comment]
> openhab2-beta1/git/openhab/bundles/binding/org.openhab.binding.zwave

This binding does not (yet) exist in OH2, so I guess this is your personal workspace where you have this issue...
And note that the OH1 ZWave binding has already been renamed to prevent such clashes, see https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.zwave/.project#L3.
We will do this with others as well - whereever we want to keep the OH1 version at all in the (default) workspace.

**Comment by kgoderis** [comment]
Ok - Here is the complete error log

mporting project org.openhab.binding.zwave1
ERROR: org.eclipse.oomph.resources code=0 org.eclipse.core.internal.resources.ResourceException: Invalid project description.
org.eclipse.oomph.resources.backend.BackendException: org.eclipse.core.internal.resources.ResourceException: Invalid project description.
  at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:158)
  at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl$1.run(ProjectsImportTaskImpl.java:384)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2225)
  at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl.importProjects(ProjectsImportTaskImpl.java:372)
  at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl.perform(ProjectsImportTaskImpl.java:295)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3028)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:2972)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4152)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4146)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4144)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2963)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2938)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2829)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:552)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:671)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
ERROR: org.eclipse.core.resources code=77 Invalid project description.
  at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:168)
  at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:52)
  at org.eclipse.core.internal.resources.Project.create(Project.java:268)
  at org.eclipse.core.internal.resources.Project.create(Project.java:252)
  at org.eclipse.oomph.resources.ResourcesUtil.importProject(ResourcesUtil.java:289)
  at org.eclipse.oomph.resources.backend.LocalBackendSystem.importIntoWorkspace(LocalBackendSystem.java:139)
  at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:146)
  at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl$1.run(ProjectsImportTaskImpl.java:384)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2225)
  at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl.importProjects(ProjectsImportTaskImpl.java:372)
  at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl.perform(ProjectsImportTaskImpl.java:295)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3028)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:2972)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4152)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4146)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4144)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2963)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2938)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2829)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:552)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:671)
  ... 1 more
  OK: unknown code=0 OK
  ERROR: org.eclipse.core.resources code=77 /Users/kgoderis/openhab2-beta1/git/openhab/bundles/binding/org.openhab.binding.zwave overlaps the location of another project: 'org.openhab.binding.zwave'

And I have not yet imported project manual after the "IDE beta1" setup process.

**Comment by kaikreuzer** [comment]
Will have a look later today...

**Comment by kgoderis** [comment]
Solved it by reloading completely the setup tasks. They seem to be cached
