### ISSUE TITLE
NPE when updating neighbours

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2-addons#694]
I just had this error on all my nodes during startup:
```
12:53:05.732 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE 5: Controller failed to register event handler.
12:53:05.735 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured during notification of thing 'zwave:fibaro_fgms001_00_000:ad1f4a49:node5' about bridge initialization at 'org.openhab.binding.zwave.handler.ZWaveThingHandler@c42d9d': null
java.lang.NullPointerException
	at org.openhab.binding.zwave.handler.ZWaveThingHandler.updateNeighbours(ZWaveThingHandler.java:924)[170:org.openhab.binding.zwave:2.0.0.201603010202]
	at org.openhab.binding.zwave.handler.ZWaveThingHandler.bridgeHandlerInitialized(ZWaveThingHandler.java:307)[170:org.openhab.binding.zwave:2.0.0.201603010202]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$8.run(ThingManager.java:686)[98:org.eclipse.smarthome.core.thing:0.8.0.201602251230]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

**Comment by bhuism** [comment]
grrr, I was looking into this :+1:

**Comment by cdjackson** [comment]
Sorry. ;)

This was something that I added the other night, but again, it’s caused (potentially!) by the startup race conditions when synchronising multiple ‘domains’ (i.e. the protocol stack, the controller itself, and the initialisation of things)…

**Comment by bhuism** [comment]
Indeed, good fix!

**Comment by bhuism** [comment]
still one to go (sorry for hijacking)

2016-03-02 17:36:43.473 [INFO ] [ve.internal.protocol.ZWaveController:145] - Starting ZWave controller
2016-03-02 17:36:43.477 [INFO ] [ve.internal.protocol.ZWaveController:153] - ZWave timeout is set to 5000ms. Soft reset is false.
2016-03-02 17:36:44.060 [ERROR] [ocol.ZWaveController$ZWaveSendThread:1192] - Exception during ZWave thread: Send
java.lang.NullPointerException
	at org.openhab.binding.zwave.handler.ZWaveSerialHandler.sendPacket(ZWaveSerialHandler.java:304)[152:org.openhab.binding.zwave:2.0.0.201603021603]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveSendThread.run(ZWaveController.java:1159)[152:org.openhab.binding.zwave:2.0.0.201603021603]

**Comment by cdjackson** [comment]
That's a different issue not related to this.

**Comment by bhuism** [comment]
Yes, sorry, off topic
