### ISSUE TITLE
Build failure running MAX! binding tests

### ISSUE THREAD

**Issue by llamahunter** [openhab/openhab2-addons#782]
Running org.openhab.binding.max.test.MaxBridgeHandlerOSGiTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.668 sec <<< FAILURE! - in org.openhab.binding.max.test.MaxBridgeHandlerOSGiTest
maxCubeBridgeHandlerRegisteredAndUnregister(org.openhab.binding.max.test.MaxBridgeHandlerOSGiTest)  Time elapsed: 0.287 sec  <<< ERROR!
groovy.lang.MissingMethodException: No signature of method: org.eclipse.smarthome.core.thing.ManagedThingProvider.createThing() is applicable for argument types: (org.eclipse.smarthome.core.thing.ThingTypeUID, org.eclipse.smarthome.core.thing.ThingUID, null, null, org.eclipse.smarthome.config.core.Configuration) values: [max:bridge, max:bridge:testCube, null, null, org.eclipse.smarthome.config.core.Configuration@8ed9e01e]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:56)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.openhab.binding.max.test.MaxBridgeHandlerOSGiTest.maxCubeBridgeHandlerRegisteredAndUnregister(MaxBridgeHandlerOSGiTest.groovy:64)

**Comment by llamahunter** [comment]
had to comment out the max binding tests to get the tree to build.

**Comment by kaikreuzer** [comment]
Cloudbees confirms the problem: https://openhab.ci.cloudbees.com/job/openHAB2-Addons/org.openhab.binding$org.openhab.binding.max.test/555/testReport/junit/org.openhab.binding.max.test/MaxBridgeHandlerOSGiTest/maxCubeBridgeHandlerRegisteredAndUnregister/
