### ISSUE TITLE
[Homematic] Homematic socket failure on reconnect

### ISSUE THREAD

**Issue by punkadiddle** [openhab/openhab2-addons#867]
The Homematic binding works fine until the first reconnect after idle. From then on it fails with "read timed out" messages.

The homematic build was installed through the ui from an online repository: 201605010850

Is there an option to try the XML-RPC protocol instead? It's mentioned in the homematic binding documentation but it's not visible in the paper UI configuration dialog. I also couldn't find where paper ui persists the configuration.

```
15:10:20.511 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
listBidcosInterfaces()

15:10:20.511 [TRACE] [al.communicator.client.SocketHandler] - Returning socket for port 2001
15:10:20.517 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcResponse:
[
        {
                ADDRESS=NEQ0219353
                CONNECTED=true
                DEFAULT=true
                DESCRIPTION=
                DUTY_CYCLE=0
                FIRMWARE_VERSION=1.4.1
                TYPE=CCU2
        }
]

15:10:35.249 [INFO ] [ternal.communicator.HomematicGateway] - No event since 342 seconds from gateway '7d04f0ba', restarting RPC server
15:10:35.251 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
init()
binary://192.168.1.121:9125

15:10:35.255 [TRACE] [al.communicator.client.SocketHandler] - Returning socket for port 2001
15:10:35.260 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcResponse:


15:10:35.261 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
init()
binary://192.168.1.121:9125

15:10:35.262 [TRACE] [al.communicator.client.SocketHandler] - Returning socket for port 8701
15:10:35.266 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcResponse:


15:10:35.267 [DEBUG] [nal.communicator.server.BinRpcServer] - Stopping BIN-RPC server
15:10:35.269 [DEBUG] [nal.communicator.server.BinRpcServer] - Initializing BIN-RPC server at port 9125
15:10:35.271 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
init()
binary://192.168.1.121:9125
RF-7d04f0ba

15:10:35.272 [TRACE] [al.communicator.client.SocketHandler] - Returning socket for port 2001
15:10:35.276 [WARN ] [rthome.core.common.ThreadPoolManager] - Thread pool 'homematicRpc' rejected execution of class org.openhab.binding.homematic.internal.communicator.server.BinRpcCallbackHandler
15:10:46.755 [WARN ] [rthome.core.common.ThreadPoolManager] - Thread pool 'homematicRpc' rejected execution of class org.openhab.binding.homematic.internal.communicator.server.BinRpcCallbackHandler
15:10:50.356 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcResponse:
null
15:10:50.357 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
listBidcosInterfaces()

15:10:50.358 [TRACE] [al.communicator.client.SocketHandler] - Returning socket for port 2001
15:10:50.359 [WARN ] [ternal.communicator.HomematicGateway] - Read timed out
15:10:50.360 [TRACE] [ternal.communicator.HomematicGateway] - Read timed out
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)[:1.8.0_65]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)[:1.8.0_65]
        at java.net.SocketInputStream.read(SocketInputStream.java:170)[:1.8.0_65]
        at java.net.SocketInputStream.read(SocketInputStream.java:141)[:1.8.0_65]
        at org.openhab.binding.homematic.internal.communicator.message.BinRpcMessage.<init>(BinRpcMessage.java:75)[171:org.openhab.binding.homematic:2.0.0.201605010850]
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:90)[171:org.openhab.binding.homematic:2.0.0.201605010850]
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:79)[171:org.openhab.binding.homematic:2.0.0.201605010850]
        at org.openhab.binding.homematic.internal.communicator.client.RpcClient.init(RpcClient.java:79)[171:org.openhab.binding.homematic:2.0.0.201605010850]
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.init(BinRpcClient.java:67)[171:org.openhab.binding.homematic:2.0.0.201605010850]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.startServer(AbstractHomematicGateway.java:212)[171:org.openhab.binding.homematic:2.0.0.201605010850]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.access$4(AbstractHomematicGateway.java:204)[171:org.openhab.binding.homematic:2.0.0.201605010850]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$EventTrackerThread.run(AbstractHomematicGateway.java:738)[171:org.openhab.binding.homematic:2.0.0.201605010850]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_65]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
15:11:05.370 [DEBUG] [nal.communicator.client.BinRpcClient] - BinRpcMessage socket failure, sending message again 1/1
15:11:05.371 [TRACE] [al.communicator.client.SocketHandler] - Closing Socket on port 2001
15:11:05.377 [TRACE] [al.communicator.client.SocketHandler] - Creating new socket for port 2001
15:11:20.399 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcResponse:
null
15:11:20.400 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcResponse:
null
15:11:20.401 [WARN ] [ternal.communicator.HomematicGateway] - Connection lost on gateway '7d04f0ba'
15:11:20.403 [TRACE] [al.communicator.client.SocketHandler] - Closing Socket on port 2001
15:11:20.406 [TRACE] [al.communicator.client.SocketHandler] - Closing Socket on port 8701
15:11:20.443 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'homematic:bridge:7d04f0ba' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Connection lost
15:11:20.454 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'homematic:HM-RCV-50:7d04f0ba:BidCoS-RF' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
15:11:20.456 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'homematic:HM-OU-CFM-Pl:7d04f0ba:MEQ0374314' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
15:11:20.467 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'homematic:GATEWAY-EXTRAS-7D04F0BA:7d04f0ba:GWE00000000' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
15:11:35.444 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
listBidcosInterfaces()
```

**Comment by punkadiddle** [comment]
I just reininstalled the CCU2 with the latest firmware 2.17.15 and removed/installed all homematic things in OpenHab. Now the plugin uses XmlRpc (for whatever reason) and there are no more connection problems.
