### ISSUE TITLE
[ZWave] Handler broken: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab2-addons#884]
I've got bad and good news:
1. My siren is now visible
2. The handler is broken and the serial stick can't be initialized.

Here is the log:
```
2016-05-03 15:11:24.408 [INFO ] [smarthome.event.ThingStatusInfoEvent] - 'zwave:serial_zstick:0fcf1c4f' updated: INITIALIZING
2016-05-03 15:11:24.411 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while initializing handler of thing 'zwave:serial_zstick:0fcf1c4f': java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/String;)Ljava/lang/Object;
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/String;)Ljava/lang/Object;
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_91]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:179)[93:org.eclipse.smarthome.core:0.8.0.201604261907]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:72)[93:org.eclipse.smarthome.core:0.8.0.201604261907]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:56)[93:org.eclipse.smarthome.core:0.8.0.201604261907]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$7.run(ThingManager.java:659)[99:org.eclipse.smarthome.core.thing:0.8.0.201604261907]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/String;)Ljava/lang/Object;
        at org.openhab.binding.zwave.handler.ZWaveSerialHandler.initialize(ZWaveSerialHandler.java:69)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:662)
        at org.eclipse.smarthome.core.thing.internal.ThingManager$7$1.call(ThingManager.java:1)
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:170)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_91]
        ... 3 more
2016-05-03 15:11:24.419 [INFO ] [smarthome.event.ThingStatusInfoEvent] - 'zwave:serial_zstick:0fcf1c4f' updated: UNINITIALIZED (HANDLER_INITIALIZING_ERROR): org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/String;)Ljava/lang/Object;
2016-05-03 15:11:24.433 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:0fcf1c4f' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): org.eclipse.smarthome.config.core.Configuration.get(Ljava/lang/String;)Ljava/lang/Object;
2016-05-03 15:11:24.411 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:0fcf1c4f' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
```

PS: If you need further information, I'll add there also the debug messages of course.

Thanks!

**Comment by maggu2810** [comment]
See eclipse/smarthome#1437

**Comment by cdjackson** [comment]
As I’ve posted on the forum, you need to update the OH2 runtime to the latest version.

**Comment by thopiekar** [comment]
Thanks!

2016-05-03 17:38 GMT+02:00 Chris Jackson <notifications@github.com>:

**Comment by thopiekar** [comment]
Fixed by installing latest distro
