### ISSUE TITLE
systeminfo.test failed

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#950]
When I run maven (Windows 10), it fails. Here is the content of my file org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.txt in folder openhab2-master\git\openhab2-addons\addons\binding\org.openhab.binding.systeminfo.test\target\surefire-reports:
```
-------------------------------------------------------------------------------
Test set: org.openhab.binding.systeminfo.test.SysteminfoOSGiTest
-------------------------------------------------------------------------------
Tests run: 23, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 64.622 sec <<< FAILURE! - in org.openhab.binding.systeminfo.test.SysteminfoOSGiTest
assert channel cpu#load is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 4.431 sec  <<< FAILURE!
java.lang.AssertionError: Thing status detail is {NONE} with description {null}
Expected: is <ONLINE>
     but: was <INITIALIZING>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrap.invoke(StaticMetaMethodSite.java:130)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:99)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:173)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest$_testItemState_closure2.doCall(SysteminfoOSGiTest.groovy:156)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest$_testItemState_closure2.doCall(SysteminfoOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testItemState(SysteminfoOSGiTest.groovy:153)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testItemStateIsUpdated(SysteminfoOSGiTest.groovy:145)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.this$3$testItemStateIsUpdated(SysteminfoOSGiTest.groovy)

assert channel cpu#threads is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 3.678 sec
assert channel memory#available is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 2.993 sec
test discovery with invalid hostname(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 0.32 sec
assert low priority channel is not updated on not supported command(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 6.324 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <NULL>
     but: was <81.3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:169)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testItemState(SysteminfoOSGiTest.groovy:175)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testItemStateIsNull(SysteminfoOSGiTest.groovy:149)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testItemStateOnCommand(SysteminfoOSGiTest.groovy:269)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.this$3$testItemStateOnCommand(SysteminfoOSGiTest.groovy)

assert channel memory#availablePercent is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 2.866 sec
assert channel sensors#cpuVoltage is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 2.799 sec
assert channel cpu#description is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 2.654 sec
test discovery with unresolved hostname(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 0.179 sec
assert medium priority channel is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 4.113 sec
assert channel cpu#load15 is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 2.5 sec
assert channel sensors#cpuTemp is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 3.507 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: not <NULL>
     but: was <NULL>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest$_testItemState_closure3.doCall(SysteminfoOSGiTest.groovy:179)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest$_testItemState_closure3.doCall(SysteminfoOSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
	at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testItemState(SysteminfoOSGiTest.groovy:177)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testItemStateIsUpdated(SysteminfoOSGiTest.groovy:145)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.this$3$testItemStateIsUpdated(SysteminfoOSGiTest.groovy)

assert low priority channel is updated on REFESH(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 6.208 sec
assert channel cpu#name is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 2.425 sec
assert channel cpu#uptime is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 2.499 sec
assert state of not existing device is not updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 3.532 sec
test discovery with empty hostname string(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 0.099 sec
assert channel memory#used is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 3.446 sec
assert channel memory#total is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 2.448 sec
test discovery with valid hostname(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 0.106 sec
assert channel cpu#load1 is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 3.615 sec
assert invalid thing configuration values are handled(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 1.41 sec
assert channel cpu#load5 is updated(org.openhab.binding.systeminfo.test.SysteminfoOSGiTest)  Time elapsed: 2.445 sec
```

**Comment by kaikreuzer** [comment]
@svilenvul, is it possible that these tests are platform specific and failing on Windows?

**Comment by svilenvul** [comment]
I ran the test many times on my Windows 7 machine, and see that the first test fails, because of the test set up - sometimes an item is created too early. I will fix that in a PR.
About the second one, I am not completely sure, that the problem is the same,I guess so, but I will investigate further too.
