### ISSUE TITLE
[avmfritz] Missing jackson jaxb jar?

### ISSUE THREAD

**Issue by sja** [openhab/openhab2-addons#955]
My exception stack:

```
2016-05-24 08:42:02.937 [ERROR] [org.openhab.binding.avmfritz        ] - FrameworkEvent ERROR - org.openhab.binding.avmfritz
java.io.IOException: Exception in opening zip file: /openhab/userdata/cache/org.eclipse.osgi/189/1/.cp/lib/jackson-module-jaxb-annotations-2.3.2.jar
    at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:305)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.basicOpen(ZipBundleFile.java:85)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getZipFile(ZipBundleFile.java:98)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.checkedOpen(ZipBundleFile.java:65)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.getEntry(ZipBundleFile.java:232)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.storage.bundlefile.BundleFile.getResourceURL(BundleFile.java:129)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findResourceImpl(ClasspathManager.java:420)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalResources(ClasspathManager.java:397)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalResources(ModuleClassLoader.java:320)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.loader.BundleLoader.findLocalResources(BundleLoader.java:806)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.loader.BundleLoader.findResources(BundleLoader.java:667)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.getResources(ModuleClassLoader.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.framework.ContextFinder.findResources(ContextFinder.java:165)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at java.lang.ClassLoader.getResources(ClassLoader.java:1142)[:1.8.0_91]
    at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)[:1.8.0_91]
    at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)[:1.8.0_91]
    at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)[:1.8.0_91]
    at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)[:1.8.0_91]
    at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_91]
    at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)[:1.8.0_91]
    at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)[:1.8.0_91]
    at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)[:1.8.0_91]
    at com.sun.xml.internal.bind.v2.util.XmlFactory.createParserFactory(XmlFactory.java:116)[:1.8.0_91]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.getXMLReader(UnmarshallerImpl.java:139)[:1.8.0_91]
    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)[:1.8.0_91]
    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)[:1.8.0_91]
    at org.openhab.binding.avmfritz.internal.hardware.callbacks.FritzAhaDiscoveryCallback.execute(FritzAhaDiscoveryCallback.java:59)[189:org.openhab.binding.avmfritz:2.0.0.201605240102]
    at org.openhab.binding.avmfritz.internal.hardware.FritzahaContentExchange.onComplete(FritzahaContentExchange.java:70)[189:org.openhab.binding.avmfritz:2.0.0.201605240102]
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:446)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:393)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:265)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1514)[69:org.eclipse.jetty.http:9.2.14.v20151106]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1272)[69:org.eclipse.jetty.http:9.2.14.v20151106]
    at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:156)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:117)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:89)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:122)[67:org.eclipse.jetty.client:9.2.14.v20151106]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[70:org.eclipse.jetty.io:9.2.14.v20151106]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[81:org.eclipse.jetty.util:9.2.14.v20151106]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[81:org.eclipse.jetty.util:9.2.14.v20151106]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
Caused by: java.io.FileNotFoundException: /openhab/userdata/cache/org.eclipse.osgi/189/1/.cp/lib/jackson-module-jaxb-annotations-2.3.2.jar (No such file or directory)
    at java.util.zip.ZipFile.open(Native Method)[:1.8.0_91]
    at java.util.zip.ZipFile.<init>(ZipFile.java:219)[:1.8.0_91]
    at java.util.zip.ZipFile.<init>(ZipFile.java:149)[:1.8.0_91]
    at java.util.zip.ZipFile.<init>(ZipFile.java:163)[:1.8.0_91]
    at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:288)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    ... 43 more
```

This error is repeated about every 1 or 2 minute. Have the online-version running, installed fritz binding by paperui. OH was already restarted. Any ideas?
##

**Comment by maggu2810** [comment]
The swagger support already depends on a lot jackson bundles

So IMHO the binding should drop all the bundled libraries (see https://github.com/openhab/openhab2-addons/tree/af2101b/addons/binding/org.openhab.binding.avmfritz/lib).
The Karaf feature should be changed to use the same as ones used in the karaf-tp feature repo for the swagger-jersey feature.
If the bundles are missing in the OH p2 repo I assume they could be simple added there.
